const ar = [
   {
      equation_id: "centripetal-acceleration",
      name: "التسارع المركزي",
      equation_text: "a_c = v² / r",
      summary: "يحسب التسارع المركزي (a_c = v^2 / r)",
      description:
         "يحسب التسارع الموجه نحو مركز المسار الدائري باستخدام السرعة الخطية ونصف القطر.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         a_c: "التسارع المركزي (التسارع m/s²)",
         v: "السرعة الخطية (السرعة m/s)",
         r: "نصف قطر المسار الدائري (الطول m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "التسارع المركزي (زاوي)",
      equation_text: "a_c = ω²r",
      summary: "يحسب التسارع المركزي (a_c = -ω^2 * r) باستخدام السرعة الزاوية",
      description:
         "يحسب مكون متجه التسارع المركزي باستخدام السرعة الزاوية ونصف القطر. الإشارة السالبة تشير إلى الاتجاه نحو المركز.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         a_c: "التسارع المركزي (التسارع m/s²)",
         ω: "السرعة الزاوية (السرعة الزاوية rad/s)",
         r: "نصف قطر المسار الدائري (الطول m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "قانون كولوم (القوة)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "يحسب القوة الكهربائية باستخدام قانون كولوم (F = k * q1*q2 / r^2)",
      description:
         "يحسب القوة الكهربائية بين شحنتين نقطيتين. يعيد القوة بإشارة (موجبة للتنافر، سالبة للتجاذب).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F: "القوة الكهربائية (القوة N)",
         k: "ثابت كولوم (ثابت N·m²/C²)",
         q1: "الشحنة 1 (الشحنة C)",
         q2: "الشحنة 2 (الشحنة C)",
         r: "المسافة بين الشحنات (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "المجال الكهربائي",
      equation_text: "E = kq / r² (شحنة نقطية)",
      summary: "يحسب المجال الكهربائي من القوة (E = F_E/q)",
      description: "يحسب شدة المجال الكهربائي بناءً على القوة المؤثرة على شحنة اختبار.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "مقدار المجال الكهربائي (المجال الكهربائي N/C)",
         k: "ثابت كولوم (ثابت N·m²/C²)",
         q: "شحنة المصدر (الشحنة C)",
         r: "المسافة من شحنة المصدر (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "الجهد الكهربائي",
      equation_text: "V = kq / r (شحنة نقطية)",
      summary: "يحسب الجهد الكهربائي من تغير الطاقة الكامنة (V = ΔU_E/q)",
      description:
         "يحسب الجهد الكهربائي (الفولتية) بناءً على التغير في الطاقة الكامنة الكهربائية لكل وحدة شحنة. ملاحظة - اسم الدالة `calculateElectricPotential` صحيح، لكن المعلمة `deltaUE` تشير إلى التغير، بينما المعادلة عادة ما تكون V=U_E/q أو ΔV=ΔU_E/q. يتم توثيقه بناءً على المعادلة ΔV = ΔU_E/q ويُرجع ΔV.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         V: "الجهد الكهربائي (الفولتية V)",
         k: "ثابت كولوم (ثابت N·m²/C²)",
         q: "شحنة المصدر (الشحنة C)",
         r: "المسافة من شحنة المصدر (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "العلاقة بين المجال الكهربائي والجهد",
      equation_text: "E_x = -dV/dx",
      summary: "يحسب المجال الكهربائي من فرق الجهد (E = ΔV/d)",
      description:
         'يحسب مقدار المجال الكهربائي المنتظم بناءً على فرق الجهد عبر مسافة. ملاحظة - اسم الدالة "المجال والجهد" مضلل؛ إنها تحسب المجال الكهربائي E.',
      language_code: "ar",
      subject: "Physics",
      variables: {
         E_x: "مكون المجال الكهربائي (المجال الكهربائي V/m)",
         V: "الجهد الكهربائي (الفولتية V)",
         x: "الموضع (الطول m)",
         ΔV: "فرق الجهد (الفولتية V)",
         d: "المسافة (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "السعة الكهربائية",
      equation_text: "C = Q / V",
      summary: "يحسب السعة الكهربائية (C = Q/V)",
      description: "يحسب السعة الكهربائية بناءً على الشحنة المخزنة والجهد عبر مكثف.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C: "السعة الكهربائية (السعة F)",
         Q: "الشحنة (الشحنة C)",
         V: "الجهد (الفولتية V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "سعة المكثف اللوحي",
      equation_text: "C = ε₀A / d",
      summary: "يحسب سعة مكثف اللوح المتوازي (C = (kε₀A)/d)",
      description:
         "يحسب سعة مكثف اللوح المتوازي باستخدام مادة عازلة. ملاحظة - الدالة تستخدم k * ε₀ كمدخل واحد (`kEpsilon`).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C: "السعة الكهربائية (السعة F)",
         ε0: "سماحية الفراغ (ثابت F/m)",
         k: "ثابت العزل (بدون أبعاد)",
         A: "مساحة الألواح (المساحة m²)",
         d: "المسافة بين الألواح (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "سعة المكثف الأسطواني",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "يحسب سعة المكثف الأسطواني (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "يحسب سعة المكثف الأسطواني باستخدام مادة عازلة. ملاحظة - الدالة تستخدم k * ε₀ كمدخل واحد (`kEpsilon`).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C: "السعة الكهربائية (السعة F)",
         π: "باي (ثابت بدون أبعاد)",
         ε0: "سماحية الفراغ (ثابت F/m)",
         k: "ثابت العزل (بدون أبعاد)",
         L: "طول الأسطوانات (الطول m)",
         b: "نصف القطر الخارجي (الطول m)",
         a: "نصف القطر الداخلي (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "سعة المكثف الكروي",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "يحسب سعة المكثف الكروي (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "يحسب سعة المكثف الكروي باستخدام مادة عازلة. ملاحظة - الدالة تستخدم k * ε₀ كمدخل واحد (`kEpsilon`).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C: "السعة الكهربائية (السعة F)",
         π: "باي (ثابت بدون أبعاد)",
         ε0: "سماحية الفراغ (ثابت F/m)",
         k: "ثابت العزل (بدون أبعاد)",
         a: "نصف القطر الداخلي (الطول m)",
         b: "نصف القطر الخارجي (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "الطاقة الكامنة للمكثف",
      equation_text: "U_C = ½CV²",
      summary: "يتحقق من صحة معادلات الطاقة الكامنة للمكثف (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "يتحقق مما إذا كانت المعادلات الثلاث الشائعة للطاقة الكامنة المخزنة في مكثف مكافئة لقيم Q وV وC المعطاة. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         U_C: "الطاقة الكامنة للمكثف (الطاقة J)",
         Q: "الشحنة (الشحنة C)",
         V: "الجهد (الفولتية V)",
         C: "السعة الكهربائية (السعة F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "التيار الكهربائي",
      equation_text: "I = ΔQ / Δt",
      summary: "يحسب التيار الكهربائي (I = ΔQ/Δt)",
      description: "يحسب التيار الكهربائي بناءً على كمية الشحنة التي تمر عبر نقطة في وحدة الزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         I: "التيار الكهربائي (التيار A)",
         ΔQ: "التغير في الشحنة (الشحنة C)",
         Δt: "التغير في الزمن (الزمن s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "كثافة الشحنة",
      equation_text: "ρ = Q / V (الحجم)",
      summary: "يحسب كثافة الشحنة (ρ = Q/V)",
      description: "يحسب متوسط كثافة الشحنة (الشحنة لكل وحدة حجم).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ρ: "كثافة الشحنة الحجمية (كثافة الشحنة C/m³)",
         Q: "الشحنة الكلية (الشحنة C)",
         V: "الحجم (الحجم m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "كثافة التيار",
      equation_text: "J = I / A",
      summary: "يحسب كثافة التيار (J = I/A)",
      description: "يحسب كثافة التيار الكهربائي (التيار لكل وحدة مساحة مقطعية).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         J: "كثافة التيار (كثافة التيار A/m²)",
         I: "التيار الكهربائي (التيار A)",
         A: "المساحة (المساحة m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "قانون أوم",
      equation_text: "V = IR",
      summary: "يحسب المقاومة باستخدام قانون أوم (R = V/I)",
      description:
         "يحسب المقاومة بناءً على الجهد والتيار. ملاحظة - الدالة تحسب المقاومة R من V وI.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         V: "الجهد (الفولتية V)",
         I: "التيار (التيار A)",
         R: "المقاومة (المقاومة Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "المقاومية والموصلية",
      equation_text: "ρ = RA / L",
      summary: "يحسب الموصلية من المقاومية (σ = 1/ρ)",
      description: "يحسب الموصلية (σ) من المقاومية (ρ).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         σ: "الموصلية (الموصلية S/m)",
         ρ: "المقاومية (المقاومية Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "المقاومة الكهربائية",
      equation_text: "R = ρL / A",
      summary: "يحسب المقاومة الكهربائية (R = ρ(l/A))",
      description:
         "يحسب مقاومة الموصل بناءً على مقاوميته، طوله، ومساحة مقطعه العرضي. ملاحظة - يستخدم `rhoValue` للمقاومية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         R: "المقاومة (المقاومة Ω)",
         ρ: "المقاومية (المقاومية Ω·m)",
         L: "الطول (الطول m)",
         A: "مساحة المقطع العرضي (المساحة m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "القدرة الكهربائية",
      equation_text: "P = IV",
      summary: "يتحقق من صحة معادلات القدرة الكهربائية (P = VI = I^2R = V^2/R)",
      description:
         "يتحقق مما إذا كانت المعادلات الثلاث الشائعة للقدرة الكهربائية مكافئة لقيم V وI وR المعطاة. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "القدرة الكهربائية (القدرة W)",
         V: "الجهد (الفولتية V)",
         I: "التيار (التيار A)",
         R: "المقاومة (المقاومة Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "المقاومات على التوالي",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "يحسب المقاومة الكلية للمقاومات على التوالي (R_total = R1 + R2 + ...)",
      description: "يحسب المقاومة المكافئة الكلية لعدة مقاومات موصلة على التوالي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         R_total: "المقاومة الكلية (المقاومة Ω)",
         R: "المقاومة الفردية (المقاومة Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "المقاومات على التوازي",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "يحسب المقاومة الكلية للمقاومات على التوازي (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "يحسب المقاومة المكافئة الكلية لعدة مقاومات موصلة على التوازي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         R_total: "المقاومة الكلية (المقاومة Ω)",
         R: "المقاومة الفردية (المقاومة Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "المكثفات على التوالي",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "يحسب السعة الكلية للمكثفات على التوالي (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "يحسب السعة المكافئة الكلية لعدة مكثفات موصلة على التوالي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C_total: "السعة الكلية (السعة F)",
         C: "السعة الفردية (السعة F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "المكثفات على التوازي",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "يحسب السعة الكلية للمكثفات على التوازي (C_total = C1 + C2 + ...)",
      description: "يحسب السعة المكافئة الكلية لعدة مكثفات موصلة على التوازي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         C_total: "السعة الكلية (السعة F)",
         C: "السعة الفردية (السعة F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "القوة المغناطيسية على شحنة",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "يحسب القوة المغناطيسية على جسيم مشحون (F = qvB sin(θ))",
      description:
         "يحسب مقدار القوة المغناطيسية المؤثرة على جسيم مشحون متحرك. يجب أن تكون الزاوية بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F_B: "مقدار القوة المغناطيسية (القوة N)",
         q: "مقدار الشحنة (الشحنة C)",
         v: "مقدار السرعة (السرعة m/s)",
         B: "مقدار المجال المغناطيسي (المجال المغناطيسي T)",
         θ: "الزاوية بين السرعة والمجال المغناطيسي (الزاوية rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "القوة المغناطيسية على تيار",
      equation_text: "F_B = ILBsin(θ)",
      summary: "يحسب القوة المغناطيسية على موصل يحمل تياراً (F = I l B sin(θ))",
      description:
         "يحسب مقدار القوة المغناطيسية المؤثرة على موصل مستقيم يحمل تياراً في مجال مغناطيسي. يجب أن تكون الزاوية بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F_B: "مقدار القوة المغناطيسية (القوة N)",
         I: "التيار (التيار A)",
         L: "طول الموصل (الطول m)",
         B: "مقدار المجال المغناطيسي (المجال المغناطيسي T)",
         θ: "الزاوية بين التيار والمجال المغناطيسي (الزاوية rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "قانون بيو-سافار",
      equation_text: "B = μ₀I / (2πr) (سلك مستقيم لا نهائي)",
      summary: "يحسب المجال المغناطيسي من عنصر تيار (dB = (μ₀I ds) / (4πr^2))",
      description:
         "يحسب مقدار مساهمة المجال المغناطيسي من عنصر تيار تفاضلي عمودي على متجه نصف القطر. ملاحظة - الدالة تطبق `(μ₀ * I * ds) / (4 * π * r^2)`، مع حذف الحد sin(θ) الذي غالبًا ما يكون موجودًا في الصيغة التفاضلية، مما يفترض فعليًا أن θ = 90 درجة أو يحسب فقط المكون العمودي على متجه نصف القطر في ذلك المستوى المحدد. يتم توثيق المعادلة المطبقة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         dB: "مقدار مساهمة المجال المغناطيسي (المجال المغناطيسي T)",
         μ0: "نفاذية الفراغ (ثابت T·m/A)",
         I: "التيار (التيار A)",
         ds: "طول تفاضلي لعنصر التيار (الطول m)",
         r: "المسافة من عنصر التيار (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "المجال المغناطيسي لملف لولبي",
      equation_text: "B = μ₀nI (بالداخل، مثالي)",
      summary: "يحسب المجال المغناطيسي داخل ملف لولبي طويل (B = μ₀nI)",
      description: "يحسب مقدار المجال المغناطيسي داخل ملف لولبي طويل مثالي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         B: "شدة المجال المغناطيسي داخل الملف اللولبي (المجال المغناطيسي T)",
         μ0: "نفاذية الفراغ (ثابت T·m/A)",
         n: "عدد اللفات لكل وحدة طول (عدد لكل طول m⁻¹)",
         I: "التيار (التيار A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "المجال المغناطيسي لسلك مستقيم",
      equation_text: "B = μ₀I / (2πr) (سلك لا نهائي)",
      summary: "يحسب المجال المغناطيسي من سلك مستقيم لا نهائي (B = (μ₀I)/(2πr))",
      description:
         "يحسب مقدار المجال المغناطيسي على مسافة من موصل طويل ومستقيم يحمل تياراً.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         B: "شدة المجال المغناطيسي من سلك مستقيم (المجال المغناطيسي T)",
         μ0: "نفاذية الفراغ (ثابت T·m/A)",
         I: "التيار (التيار A)",
         π: "باي (ثابت بدون أبعاد)",
         r: "المسافة من السلك (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "القوة بين الأسلاك المتوازية",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "يحسب القوة لوحدة الطول بين الأسلاك المتوازية (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "يحسب مقدار القوة لوحدة الطول بين موصلين طويلين ومتوازيين يحملان تيارات.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         "F/L": "القوة لوحدة الطول (القوة لكل طول N/m)",
         μ0: "نفاذية الفراغ (ثابت T·m/A)",
         I1: "التيار في السلك 1 (التيار A)",
         I2: "التيار في السلك 2 (التيار A)",
         π: "باي (ثابت بدون أبعاد)",
         d: "المسافة بين الأسلاك (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "التدفق الكهربائي",
      equation_text: "Φ_E = EAcos(θ) (E منتظم)",
      summary: "يحسب التدفق الكهربائي (Φ_E = E * A * cos(θ))",
      description:
         "يحسب التدفق الكهربائي عبر سطح مستوٍ في مجال كهربائي منتظم. يجب أن تكون الزاوية بين متجه المجال الكهربائي ومتجه المساحة، بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Φ_E: "التدفق الكهربائي (التدفق الكهربائي N·m²/C)",
         E: "مقدار المجال الكهربائي (المجال الكهربائي N/C)",
         A: "المساحة (المساحة m²)",
         θ: "الزاوية بين E ومتجه المساحة (الزاوية rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "التدفق المغناطيسي",
      equation_text: "Φ_B = BAcos(θ) (B منتظم)",
      summary: "يحسب التدفق المغناطيسي (Φ_B = B * A * cos(θ))",
      description:
         "يحسب التدفق المغناطيسي عبر سطح مستوٍ في مجال مغناطيسي منتظم. يجب أن تكون الزاوية بين متجه المجال المغناطيسي ومتجه المساحة، بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Φ_B: "التدفق المغناطيسي (التدفق المغناطيسي Wb)",
         B: "مقدار المجال المغناطيسي (المجال المغناطيسي T)",
         A: "المساحة (المساحة m²)",
         θ: "الزاوية بين B ومتجه المساحة (الزاوية rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "القوة الدافعة الكهربائية الحركية",
      equation_text: "ε = vBL (موصل مستقيم)",
      summary: "يحسب القوة الدافعة الكهربائية الحركية (emf = Blv)",
      description:
         "يحسب مقدار القوة الدافعة الكهربائية (EMF) المستحثة في موصل يتحرك عموديًا على مجال مغناطيسي. ملاحظة - تحسب الدالة مقدار Blv، مع حذف الإشارة السالبة التي تستخدم أحيانًا للاتجاه (قانون لينز).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ε: "مقدار القوة الدافعة الكهربائية الحركية (الفولتية V)",
         v: "سرعة الموصل (السرعة m/s)",
         B: "مقدار المجال المغناطيسي (المجال المغناطيسي T)",
         L: "طول الموصل (الطول m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "القوة الدافعة الكهربائية المستحثة (قانون فاراداي)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "يحسب القوة الدافعة الكهربائية المستحثة من التغير في التدفق (emf = -ΔΦ_B / Δt)",
      description: "يحسب القوة الدافعة الكهربائية المستحثة بواسطة تدفق مغناطيسي متغير وفقًا لقانون فاراداي للحث.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ε: "القوة الدافعة الكهربائية المستحثة (الفولتية V)",
         ΔΦ_B: "التغير في التدفق المغناطيسي (التدفق المغناطيسي Wb)",
         Δt: "التغير في الزمن (الزمن s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "القوة الدافعة الكهربائية المستحثة من الحث",
      equation_text: "ε_L = -L dI / dt",
      summary: "يحسب القوة الدافعة الكهربائية المستحثة من تيار متغير في محث (emf = -L * ΔI / Δt)",
      description:
         "يحسب القوة الدافعة الكهربائية المستحثة ذاتيًا في محث بسبب تيار متغير. ملاحظة - تسمى الدالة `calculateInductance` لكنها تُرجع EMF باستخدام هذه المعادلة. يتم توثيق ما تُرجعه.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ε_L: "القوة الدافعة الكهربائية المستحثة في محث (الفولتية V)",
         L: "الحث (الحث H)",
         ΔI: "التغير في التيار (التيار A)",
         Δt: "التغير في الزمن (الزمن s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "المفاعلة السعوية",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "يحسب المفاعلة السعوية (X_C = 1/(2πfC))",
      description: "يحسب مقاومة المكثف للتيار المتردد.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         X_C: "المفاعلة السعوية (المفاعلة Ω)",
         π: "باي (ثابت بدون أبعاد)",
         f: "التردد (التردد Hz)",
         C: "السعة الكهربائية (السعة F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "المفاعلة الحثية",
      equation_text: "X_L = 2πfL",
      summary: "يحسب المفاعلة الحثية (X_L = 2πfL))",
      description: "يحسب مقاومة المحث للتيار المتردد.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         X_L: "المفاعلة الحثية (المفاعلة Ω)",
         π: "باي (ثابت بدون أبعاد)",
         f: "التردد (التردد Hz)",
         L: "الحث (الحث H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "المعاوقة",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "يحسب المعاوقة (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "يحسب المقاومة الكلية لتدفق التيار في دائرة تيار متردد تحتوي على مقاومة، مفاعلة حثية، ومفاعلة سعوية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Z: "المعاوقة (المعاوقة Ω)",
         R: "المقاومة (المقاومة Ω)",
         X_L: "المفاعلة الحثية (المفاعلة Ω)",
         X_C: "المفاعلة السعوية (المفاعلة Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "الكثافة",
      equation_text: "ρ = m / V",
      summary: "يحسب الكثافة (ρ = m/V)",
      description: "يحسب الكثافة بناءً على الكتلة والحجم.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ρ: "الكثافة (الكثافة kg/m³)",
         m: "الكتلة (الكتلة kg)",
         V: "الحجم (الحجم m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "الضغط",
      equation_text: "P = F / A",
      summary: "يحسب الضغط (P = F/A)",
      description: "يحسب الضغط بناءً على القوة المطبقة على مساحة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "الضغط (الضغط Pa)",
         F: "القوة (القوة N)",
         A: "المساحة (المساحة m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "الضغط في مائع",
      equation_text: "P = P₀ + ρgh",
      summary: "يحسب الضغط في مائع (P = P0 + ρgh)",
      description: "يحسب الضغط المطلق عند عمق معين في مائع.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "الضغط المطلق (الضغط Pa)",
         P0: "الضغط الجوي أو السطحي (الضغط Pa)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
         g: "تسارع الجاذبية (التسارع m/s²)",
         h: "العمق (الطول m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "الطفو",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "يحسب قوة الطفو (F_b = ρgV_displaced)",
      description:
         "يحسب قوة الطفو التي يمارسها مائع على جسم مغمور كليًا أو جزئيًا (مبدأ أرخميدس).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F_B: "قوة الطفو (القوة N)",
         ρ_fluid: "كثافة المائع (الكثافة kg/m³)",
         V_submerged: "الحجم المغمور (الحجم m³)",
         g: "تسارع الجاذبية (التسارع m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "معدل تدفق الكتلة",
      equation_text: "ṁ = ρAv",
      summary: "يحسب معدل تدفق الكتلة (ṁ = Δm/Δt)",
      description: "يحسب المعدل الذي تمر به الكتلة عبر نقطة في وحدة الزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ṁ: "معدل تدفق الكتلة (معدل تدفق الكتلة kg/s)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
         A: "المساحة (المساحة m²)",
         v: "سرعة المائع (السرعة m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "معدل التدفق الحجمي",
      equation_text: "Q = Av",
      summary: "يحسب معدل التدفق الحجمي (Q = ΔV/Δt)",
      description: "يحسب المعدل الذي يمر به الحجم عبر نقطة في وحدة الزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Q: "معدل التدفق الحجمي (معدل التدفق الحجمي m³/s)",
         A: "المساحة (المساحة m²)",
         v: "سرعة المائع (السرعة m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "معادلة برنولي",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "يتحقق من صحة معادلة برنولي (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "يتحقق مما إذا كانت معادلة برنولي صحيحة لخواص وظروف المائع المعطاة في نقطتين. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "الضغط (الضغط Pa)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
         v: "سرعة المائع (السرعة m/s)",
         g: "تسارع الجاذبية (التسارع m/s²)",
         y: "الارتفاع (الطول m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "اللزوجة الديناميكية",
      equation_text: "τ = μ * (dv/dy)",
      summary: "يحسب اللزوجة الديناميكية (η = F * Δy / (A * Δvx))",
      description:
         "يحسب اللزوجة الديناميكية بناءً على القوة، تدرج السرعة، والمساحة. هذه المعادلة مشتقة من إجهاد القص/معدل التشوه.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         μ: "اللزوجة الديناميكية (اللزوجة الديناميكية Pa·s)",
         F: "القوة (القوة N)",
         Δy: "المسافة العمودية على التدفق (الطول m)",
         A: "المساحة (المساحة m²)",
         Δvx: "التغير في السرعة (السرعة m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "اللزوجة الحركية",
      equation_text: "ν = μ / ρ",
      summary: "يحسب اللزوجة الحركية (ν = η / ρ)",
      description: "يحسب اللزوجة الحركية من اللزوجة الديناميكية والكثافة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ν: "اللزوجة الحركية (اللزوجة الحركية m²/s)",
         μ: "اللزوجة الديناميكية (اللزوجة الديناميكية Pa·s)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "قوة السحب",
      equation_text: "F_D = ½ρv²CdA",
      summary: "يحسب قوة السحب (F_d = 0.5 * ρ * C_A * v^2)",
      description: "يحسب قوة السحب المؤثرة على جسم يتحرك عبر مائع.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F_D: "قوة السحب (القوة N)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
         v: "السرعة (السرعة m/s)",
         Cd: "معامل السحب (بدون أبعاد)",
         A: "مساحة الإشارة (المساحة m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "عدد ماخ",
      equation_text: "M = v / c_sound",
      summary: "يحسب عدد ماخ (M = v/c)",
      description: "يحسب عدد ماخ، وهو نسبة سرعة جسم إلى سرعة الصوت في الوسط.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         M: "عدد ماخ (بدون أبعاد)",
         v: "سرعة الجسم (السرعة m/s)",
         c_sound: "سرعة الصوت في الوسط (السرعة m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "عدد رينولدز",
      equation_text: "Re = ρvd / μ",
      summary: "يحسب عدد رينولدز (Re = (ρ * v * D) / η)",
      description:
         "يحسب عدد رينولدز، وهو كمية بدون أبعاد تستخدم للتنبؤ بأنماط التدفق في حالات تدفق الموائع المختلفة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Re: "عدد رينولدز (بدون أبعاد)",
         ρ: "كثافة المائع (الكثافة kg/m³)",
         v: "السرعة (السرعة m/s)",
         d: "الطول المميز (الطول m)",
         μ: "اللزوجة الديناميكية (اللزوجة الديناميكية Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "عدد فرود",
      equation_text: "Fr = v / √(gL)",
      summary: "يحسب عدد فرود (Fr = v / √(g * l))",
      description:
         "يحسب عدد فرود، وهو كمية بدون أبعاد تستخدم للإشارة إلى تأثير الجاذبية على حركة الموائع.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Fr: "عدد فرود (بدون أبعاد)",
         v: "السرعة (السرعة m/s)",
         g: "تسارع الجاذبية (التسارع m/s²)",
         L: "الطول المميز (الطول m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "التوتر السطحي",
      equation_text: "γ = F / L",
      summary: "يحسب التوتر السطحي (γ = F / l)",
      description: "يحسب التوتر السطحي لسائل بناءً على القوة والطول.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         γ: "التوتر السطحي (التوتر السطحي N/m)",
         F: "القوة (القوة N)",
         L: "الطول (الطول m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "الجاذبية الكونية (القوة)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "يحسب قوة الجاذبية (F = -Gm1m2/r^2)",
      description:
         "يحسب قوة الجاذبية الجاذبة بين كتلتين نقطيتين. ملاحظة - يعيد قيمة سالبة تشير إلى الجذب.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F: "قوة الجاذبية (القوة N)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         m1: "الكتلة 1 (الكتلة kg)",
         m2: "الكتلة 2 (الكتلة kg)",
         r: "المسافة بين الكتل (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "مجال الجاذبية",
      equation_text: "g = GM / r² (مقدار)",
      summary: "يحسب مجال الجاذبية (g = -Gm/r^2)",
      description:
         "يحسب شدة مجال الجاذبية على مسافة من كتلة نقطية. ملاحظة - يعيد قيمة سالبة تشير إلى الاتجاه نحو الكتلة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         g: "مقدار شدة مجال الجاذبية (مجال الجاذبية N/kg)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         M: "كتلة المصدر (الكتلة kg)",
         r: "المسافة من كتلة المصدر (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "الطاقة الكامنة الجاذبية",
      equation_text: "U_g = -G m₁m₂ / r (عام)",
      summary: "يحسب الطاقة الكامنة الجاذبية بين كتلتين (PE = -Gm1m2/r)",
      description: "يحسب الطاقة الكامنة الجاذبية لنظام من كتلتين نقطيتين.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         U_g: "الطاقة الكامنة الجاذبية (الطاقة J)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         m1: "الكتلة 1 (الكتلة kg)",
         m2: "الكتلة 2 (الكتلة kg)",
         r: "المسافة بين الكتل (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "الجهد الجاذبي",
      equation_text: "V_g = -GM / r",
      summary: "يحسب الجهد الجاذبي (V_g = -Gm/r)",
      description: "يحسب الجهد الجاذبي على مسافة من كتلة نقطية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         V_g: "الجهد الجاذبي (الجهد الجاذبي J/kg)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         M: "كتلة المصدر (الكتلة kg)",
         r: "المسافة من كتلة المصدر (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "سرعة المدار",
      equation_text: "v_orbit = √(GM / r) (دائري)",
      summary: "يحسب سرعة المدار (v = sqrt(Gm/r))",
      description: "يحسب سرعة جسم في مدار دائري حول كتلة أكبر.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_orbit: "سرعة المدار (السرعة m/s)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         M: "كتلة الجسم المركزي (الكتلة kg)",
         r: "نصف قطر المدار (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "سرعة الإفلات",
      equation_text: "v_escape = √(2GM / r)",
      summary: "يحسب سرعة الإفلات (v = sqrt(2Gm/r))",
      description:
         "يحسب السرعة الدنيا المطلوبة للهروب من جذب الجاذبية لكتلة من مسافة معينة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_escape: "سرعة الإفلات (السرعة m/s)",
         G: "ثابت الجاذبية (ثابت N·m²/kg²)",
         M: "كتلة الجسم المركزي (الكتلة kg)",
         r: "المسافة من المركز (الطول m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "التوصيل الحراري",
      equation_text: "Q/t = kAΔT/d",
      summary: "يحسب معدل التوصيل الحراري (Q/t = (kAΔT) / L)",
      description:
         "يحسب معدل انتقال الحرارة بالتوصيل عبر مادة. ملاحظة - تحسب الدالة Q، بافتراض أن الفترة الزمنية مفهومة من الاستخدام المعتاد للمعادلة للمعدل. التوثيق يذكر Q، لكن المعادلة عادة تكون لـ Q/t. يتم توضيح هذا الاختلاف. تُرجع الدالة نتيجة الطرف الأيمن من معادلة المعدل.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         "Q/t": "معدل انتقال الحرارة (القدرة W)",
         k: "الموصلية الحرارية (الموصلية الحرارية W/(m·K))",
         A: "المساحة (المساحة m²)",
         ΔT: "فرق درجة الحرارة (فرق درجة الحرارة K)",
         d: "السُمك (الطول m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "قانون ستيفان-بولتزمان",
      equation_text: "P = εσAT⁴",
      summary: "يحسب قدرة الإشعاع الحراري (P = εσA(T^4 - T0^4))",
      description: "يحسب المعدل الصافي للطاقة التي يشعها جسم، مع الأخذ في الاعتبار محيطه.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "القدرة الصافية المشعة (القدرة W)",
         ε: "الانبعاثية (بدون أبعاد)",
         σ: "ثابت ستيفان-بولتزمان (ثابت W/(m²·K⁴))",
         A: "مساحة السطح (المساحة m²)",
         T: "درجة حرارة الجسم (درجة الحرارة K)",
         T0: "درجة حرارة المحيط (درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "قانون فيين للإزاحة (أقصى طول موجي)",
      equation_text: "λ_max = b/T",
      summary: "يحسب أقصى طول موجي باستخدام قانون فيين (λ_max = b/T)",
      description: "يحسب طول الموجة التي يكون عندها طيف الانبعاث للجسم الأسود أعظم ما يمكن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         λ_max: "طول موجة الانبعاث الأقصى (الطول m)",
         b: "ثابت إزاحة فيين (ثابت m·K)",
         T: "درجة الحرارة (درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "قانون فيين للإزاحة (أقصى تردد)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "يحسب أقصى تردد باستخدام قانون فيين (f_max = b' * T)",
      description:
         "يحسب التردد الذي يكون عنده طيف الانبعاث للجسم الأسود أعظم ما يمكن. ملاحظة - هذا الإصدار يستخدم ثابت فيين معدّل b'.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f_max: "تردد الانبعاث الأقصى (التردد Hz)",
         "b'": "ثابت فيين المعدّل (ثابت Hz/K)",
         T: "درجة الحرارة (درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "معلومات المعادلة (خاصة)",
      equation_text: "غير متاح (يسترد معلومات، لا يحسب)",
      summary: "الحصول على معلومات المعادلة حسب المعرف واللغة",
      description:
         "يسترد تفاصيل لمعادلة محددة بناءً على معرفها الفريد واللغة المطلوبة. ملاحظة - يتم استخلاص اللغة من معلمة المسار 'language_code'. المنطق الداخلي الموضح في مقتطف الشفرة يبحث أيضًا عن معلمة استعلام 'lang'، لكن تعريف Swagger هذا يوثق معلمات المسار الأساسية.",
      language_code: "ar",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "الحصول على جميع نقاط نهاية المعادلات في واجهة برمجة التطبيقات.",
      description: "يسترد معلومات موجزة عن جميع نقاط النهاية في واجهة برمجة التطبيقات.",
      language_code: "ar",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "السرعة",
      equation_text: "v = Δx / Δt",
      summary: "يحسب السرعة",
      description: "يحسب السرعة بناءً على الإزاحة والزمن (v = Δs / Δt).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v: "السرعة (السرعة m/s)",
         Δx: "الإزاحة (الطول m)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "التسارع",
      equation_text: "a = Δv / Δt",
      summary: "يحسب التسارع",
      description: "يحسب التسارع بناءً على التغير في السرعة والزمن (a = Δv / Δt).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         a: "التسارع (التسارع m/s²)",
         Δv: "التغير في السرعة (السرعة m/s)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "معادلة الحركة (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "يحسب السرعة النهائية (v = v0 + at)",
      description: "يحسب السرعة النهائية باستخدام معادلة الحركة الأولى.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v: "السرعة النهائية (السرعة m/s)",
         v0: "السرعة الابتدائية (السرعة m/s)",
         a: "التسارع (التسارع m/s²)",
         t: "الزمن (الزمن s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "معادلة الحركة (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "يحسب الموضع النهائي (s = s0 + v0t + 0.5at^2)",
      description: "يحسب الموضع النهائي باستخدام معادلة الحركة الثانية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         s: "الموضع النهائي (الطول m)",
         s0: "الموضع الابتدائي (الطول m)",
         v0: "السرعة الابتدائية (السرعة m/s)",
         t: "الزمن (الزمن s)",
         a: "التسارع (التسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "معادلة الحركة (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "يحسب مربع السرعة النهائية (v^2 = v0^2 + 2a(s - s0))",
      description: "يحسب مربع السرعة النهائية باستخدام معادلة الحركة الثالثة. ملاحظة - يعيد v^2، وليس v.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v: "السرعة النهائية (السرعة m/s)",
         v0: "السرعة الابتدائية (السرعة m/s)",
         a: "التسارع (التسارع m/s²)",
         Δs: "الإزاحة (الطول m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "السرعة المتوسطة",
      equation_text: "v_avg = Δx / Δt",
      summary: "يحسب السرعة المتوسطة (v_avg = 0.5 * (v + v0))",
      description: "يحسب السرعة المتوسطة بافتراض تسارع ثابت.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_avg: "السرعة المتوسطة (السرعة m/s)",
         v: "السرعة النهائية (السرعة m/s)",
         v0: "السرعة الابتدائية (السرعة m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "القوة (قانون نيوتن الثاني)",
      equation_text: "F_net = ma",
      summary: "يحسب القوة (F = ma)",
      description: "يحسب القوة باستخدام قانون نيوتن الثاني.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F_net: "صافي القوة (القوة N)",
         m: "الكتلة (الكتلة kg)",
         a: "التسارع (التسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "الوزن",
      equation_text: "W = mg",
      summary: "يحسب الوزن (W = mg)",
      description: "يحسب قوة الجاذبية على جسم.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         W: "الوزن (القوة N)",
         m: "الكتلة (الكتلة kg)",
         g: "تسارع الجاذبية (التسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "أقصى قوة احتكاك سكوني",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "يحسب أقصى قوة احتكاك سكوني (F_s = μ_s * N)",
      description: "يحسب أكبر قوة احتكاك سكوني ممكنة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f_s_max: "أقصى قوة احتكاك سكوني (القوة N)",
         μ_s: "معامل الاحتكاك السكوني (بدون أبعاد)",
         F_N: "القوة العمودية (القوة N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "الاحتكاك الحركي",
      equation_text: "f_k = μ_k * F_N",
      summary: "يحسب الاحتكاك الحركي (F_k = μ_k * N)",
      description: "يحسب قوة الاحتكاك الحركي المؤثرة على جسم متحرك.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f_k: "قوة الاحتكاك الحركي (القوة N)",
         μ_k: "معامل الاحتكاك الحركي (بدون أبعاد)",
         F_N: "القوة العمودية (القوة N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "الزخم",
      equation_text: "p = mv",
      summary: "يحسب الزخم (p = mv)",
      description: "يحسب الزخم الخطي لجسم.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         p: "الزخم (الزخم kg·m/s)",
         m: "الكتلة (الكتلة kg)",
         v: "السرعة (السرعة m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "الاندفاع",
      equation_text: "J = F_avg * Δt",
      summary: "يحسب الاندفاع (J = F * Δt)",
      description: "يحسب الاندفاع من القوة والفترة الزمنية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         J: "الاندفاع (الاندفاع N·s)",
         F_avg: "متوسط القوة (القوة N)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "نظرية الاندفاع والزخم",
      equation_text: "J = Δp",
      summary: "يتحقق من صحة نظرية الاندفاع والزخم (F * Δt = m * Δv)",
      description: "يتحقق مما إذا كان الاندفاع مساوياً للتغير في الزخم للقيم المعطاة. تُرجع قيمة منطقية (boolean).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         J: "الاندفاع (الاندفاع N·s)",
         Δp: "التغير في الزخم (الزخم kg·m/s)",
         F: "القوة (القوة N)",
         Δt: "الفترة الزمنية (الزمن s)",
         m: "الكتلة (الكتلة kg)",
         Δv: "التغير في السرعة (السرعة m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "النشاط الإشعاعي",
      equation_text: "A = λN",
      summary: "يحسب النشاط المتوسط في الاضمحلال الإشعاعي (A_avg = ΔN/Δt)",
      description:
         "يحسب متوسط النشاط (معدل الاضمحلال) لعينة مشعة خلال فترة زمنية. ملاحظة - تستخدم الدالة `nValue` لعدد النواة ΔN وتستخدم `tValue` للزمن Δt. هذا متوسط مبسط على Δt، والنشاط اللحظي هو dN/dt = -λN.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         A_avg: "متوسط النشاط الإشعاعي (النشاط Bq)",
         ΔN: "عدد الاضمحلالات (عدد بدون أبعاد)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "نصف العمر",
      equation_text: "T_½ = ln(2) / λ",
      summary: "يحسب الكمية المتبقية بعد الاضمحلال (N = N0 * (1/2)^(t/T_half))",
      description:
         "يحسب الكمية المتبقية من مادة بعد فترة زمنية بناءً على نصف عمرها. ملاحظة - يستخدم `tValue` للزمن ويستخدم `Thalf` لنصف العمر.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         N: "الكمية/النواة المتبقية (عدد)",
         N0: "الكمية/النواة الأولية (عدد)",
         t: "الزمن المنقضي (الزمن s)",
         T_half: "نصف العمر (الزمن s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "الجرعة الإشعاعية الممتصة",
      equation_text: "D = dE / dm",
      summary: "يحسب الجرعة الإشعاعية الممتصة (D = E/m)",
      description:
         "يحسب الجرعة الممتصة من الإشعاع بناءً على الطاقة التي تمتصها كتلة. ملاحظة - يستخدم `EValue` للطاقة ويستخدم `mValue` للكتلة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         D: "الجرعة الممتصة (الجرعة الممتصة Gy)",
         E: "الطاقة الممتصة (الطاقة J)",
         m: "الكتلة (الكتلة kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "الجرعة الإشعاعية المكافئة",
      equation_text: "H = D * W_R",
      summary: "يحسب الجرعة الإشعاعية المكافئة (H = wR * D)",
      description:
         "يحسب الجرعة المكافئة، مع الأخذ في الاعتبار الفعالية البيولوجية لأنواع مختلفة من الإشعاع. ملاحظة - يستخدم `DValue` للجرعة الممتصة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         H: "الجرعة المكافئة (الجرعة المكافئة Sv)",
         D: "الجرعة الممتصة (الجرعة الممتصة Gy)",
         W_R: "عامل وزن الإشعاع (بدون أبعاد)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "الجرعة الإشعاعية الفعالة",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "يحسب الجرعة الإشعاعية الفعالة (E = wT * H)",
      description:
         "يحسب الجرعة الفعالة، مع الأخذ في الاعتبار حساسية الأنسجة/الأعضاء المختلفة للإشعاع. ملاحظة - يستخدم `HValue` للجرعة المكافئة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "الجرعة الفعالة (الجرعة الفعالة Sv)",
         H_T: "الجرعة المكافئة للأنسجة/العضو T (الجرعة المكافئة Sv)",
         W_T: "عامل وزن الأنسجة للأنسجة/العضو T (بدون أبعاد)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "زاوية تشيرنكوف",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "يحسب زاوية تشيرنكوف (θ_C = arccos(c/nv_p))",
      description:
         "يحسب زاوية مخروط تشيرنكوف الذي يتكون من جسيم مشحون يتحرك أسرع من سرعة الضوء في وسط. تُرجع الزاوية بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         θ_C: "زاوية تشيرنكوف (الزاوية rad)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
         n: "معامل انكسار الوسط (بدون أبعاد)",
         v: "سرعة الجسيم (السرعة m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "هدب التداخل (مثل الموقع، التباعد)",
      equation_text: "Δy = λL / d (تباعد الشق المزدوج)",
      summary: "يحسب موقع هدب التداخل (y_n = (nλL)/d)",
      description: "يحسب موقع الهدب المضيء رقم n في نمط تداخل شقي يونج.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         y_n: "موقع الهدب المضيء رقم n (الطول m)",
         n: "رتبة الهدب (عدد صحيح بدون أبعاد)",
         λ: "الطول الموجي (الطول m)",
         L: "المسافة إلى الشاشة (الطول m)",
         d: "المسافة بين الشقوق (الطول m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "معامل الانكسار",
      equation_text: "n = c / v",
      summary: "يحسب معامل الانكسار (n = c/v)",
      description:
         "يحسب معامل انكسار وسط بناءً على سرعة الضوء في الفراغ وفي الوسط.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         n: "معامل الانكسار (بدون أبعاد)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
         v: "سرعة الضوء في الوسط (السرعة m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "قانون سنل",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "يتحقق من صحة قانون سنل (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "يتحقق مما إذا كان قانون سنل صحيحًا لمرور الضوء بين وسطين بمعاملات انكسار وزوايا معينة. تُرجع قيمة منطقية (boolean). يجب أن تكون الزوايا بالراديان. ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         n1: "معامل انكسار الوسط 1 (بدون أبعاد)",
         θ1: "الزاوية في الوسط 1 (الزاوية rad)",
         n2: "معامل انكسار الوسط 2 (بدون أبعاد)",
         θ2: "الزاوية في الوسط 2 (الزاوية rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "الزاوية الحرجة",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "يحسب الزاوية الحرجة (θ_c = arcsin(n2/n1))",
      description:
         "يحسب الزاوية الحرجة للانعكاس الكلي الداخلي عندما ينتقل الضوء من وسط بمعامل انكسار n1 إلى n2 (حيث n1 > n2). تُرجع الزاوية بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         θ_c: "الزاوية الحرجة (الزاوية rad)",
         n1: "معامل انكسار الوسط 1 (بدون أبعاد)",
         n2: "معامل انكسار الوسط 2 (بدون أبعاد)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "موقع الصورة (بصريات)",
      equation_text: "1/f = 1/d_o + 1/d_i (عدسة رقيقة/مرآة)",
      summary: "يتحقق من صحة معادلة العدسة الرقيقة/المرآة (1/f = 1/do + 1/di)",
      description:
         "يتحقق مما إذا كانت العلاقة بين البعد البؤري، مسافة الجسم، ومسافة الصورة صحيحة. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f: "البعد البؤري (الطول m)",
         d_o: "مسافة الجسم (الطول m)",
         d_i: "مسافة الصورة (الطول m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "حجم الصورة (التكبير - بصريات)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "يتحقق من صحة معادلة التكبير (h'/h = di/do) (الدالة تستخدم h'/h = di/do)",
      description:
         "يتحقق مما إذا كانت العلاقة بين ارتفاعات وأبعاد الجسم/الصورة صحيحة. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة. الدالة تستخدم علاقة المقدار `h'/h = di/do` بدلاً من معادلة التكبير ذات الإشارة. يتم توثيقه بناءً على تطبيق الدالة. يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         M: "التكبير (بدون أبعاد)",
         h_i: "ارتفاع الصورة (الطول m)",
         h_o: "ارتفاع الجسم (الطول m)",
         d_i: "مسافة الصورة (الطول m)",
         d_o: "مسافة الجسم (الطول m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "معادلة المرآة الكروية",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "يحسب البعد البؤري لمرآة كروية (f = r/2)",
      description: "يحسب البعد البؤري لمرآة كروية بناءً على نصف قطر انحنائها.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f: "البعد البؤري (الطول m)",
         r: "نصف قطر الانحناء (الطول m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "الطاقة الكامنة المرونية",
      equation_text: "U_s = ½kx²",
      summary: "يحسب الطاقة الكامنة في نابض (PE = 0.5 * k * Δx^2)",
      description: "يحسب الطاقة الكامنة المرونية المخزنة في نابض مثالي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         U_s: "الطاقة الكامنة المرونية (الطاقة J)",
         k: "ثابت النابض (ثابت النابض N/m)",
         x: "الإزاحة عن موضع الاتزان (الطول m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "دورة المتذبذب التوافقي البسيط (SHO)",
      equation_text: "T = 2π√(m/k)",
      summary: "يحسب دورة المتذبذب التوافقي البسيط (SHO) لكتلة-نابض (T = 2π√(m/k))",
      description:
         "يحسب فترة الاهتزاز لمتذبذب توافقي بسيط يتكون من كتلة على نابض.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         T: "الدورة (الزمن s)",
         π: "باي (ثابت بدون أبعاد)",
         m: "الكتلة (الكتلة kg)",
         k: "ثابت النابض (ثابت النابض N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "دورة البندول البسيط",
      equation_text: "T = 2π√(L/g)",
      summary: "يحسب دورة البندول البسيط (T = 2π√(l/g))",
      description: "يحسب فترة الاهتزاز لبندول بسيط للزوايا الصغيرة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         T: "الدورة (الزمن s)",
         π: "باي (ثابت بدون أبعاد)",
         L: "طول البندول (الطول m)",
         g: "تسارع الجاذبية (التسارع m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "التردد",
      equation_text: "f = 1 / T",
      summary: "يحسب التردد (f = 1/T)",
      description: "يحسب التردد من فترة الاهتزاز.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f: "التردد (التردد Hz)",
         T: "الدورة (الزمن s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "التردد الزاوي",
      equation_text: "ω = 2πf",
      summary: "يحسب التردد الزاوي (ω = 2πf)",
      description: "يحسب التردد الزاوي من التردد.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ω: "التردد الزاوي (السرعة الزاوية rad/s)",
         π: "باي (ثابت بدون أبعاد)",
         f: "التردد (التردد Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "عامل لورنتز",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "يحسب عامل لورنتز (γ)",
      description: "يحسب عامل لورنتز باستخدام γ = 1/√(1 - (v²/c²)). يتطلب v < c.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         γ: "عامل لورنتز (بدون أبعاد)",
         v: "السرعة (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "تمدد الزمن",
      equation_text: "Δt' = γ * Δt₀",
      summary: "يحسب تمدد الزمن (t' = γ * t₀)",
      description:
         "يحسب الزمن المنقضي (t') لمراقب في إطار مرجعي قصوري S، مع العلم بالزمن الخاص (t₀) الذي تم قياسه في إطار متحرك S' وبالسرعة النسبية (v) بين S وS'. يستخدم المعادلة t' = t₀ / √(1 - (v²/c²)). يتطلب t₀ ≥ 0 و |v| ≤ c. وحدات t' ستكون هي نفسها وحدات t₀، ويجب أن تكون وحدات v وc متناسقة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Δt: "الزمن المتمدد (الزمن s)",
         Δt0: "الزمن الخاص (الزمن s)",
         v: "السرعة النسبية (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "انكماش الطول",
      equation_text: "L' = L₀ / γ",
      summary: "يحسب انكماش الطول (L' = L₀ / γ)",
      description:
         "يحسب طول (L') جسم يتم رصده من إطار متحرك S'، مع العلم بطوله الخاص (L₀) الذي تم قياسه في إطار سكونه S وبالسرعة النسبية (v) بين S وS'. يستخدم المعادلة L' = L₀ * √(1 - (v²/c²)). يتطلب L₀ ≥ 0 و |v| ≤ c. وحدات L' ستكون هي نفسها وحدات L₀، ويجب أن تكون وحدات v وc متناسقة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         L: "الطول المنكمش (الطول m)",
         L0: "الطول الخاص (الطول m)",
         v: "السرعة النسبية (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "جمع السرعات النسبية",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "يحسب جمع السرعات النسبية",
      description:
         "يحسب سرعة (u') جسم بالنسبة لإطار S'، بمعلومية سرعته (u) بالنسبة لإطار S، وسرعة (v) الإطار S بالنسبة لإطار S'. يستخدم المعادلة u' = (u + v) / (1 + uv/c²). يفترض الحركة على نفس الخط. يتطلب c ≠ 0. وحدات u، v، وc يجب أن تكون متناسقة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         u: "سرعة الجسم في الإطار S (السرعة m/s)",
         v: "سرعة الإطار S بالنسبة لـ S' (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
         "u'": "سرعة الجسم بالنسبة لإطار S' (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "الطاقة الكلية النسبية",
      equation_text: "E = γmc²",
      summary: "يحسب الطاقة الكلية النسبية (E)",
      description:
         "يحسب الطاقة النسبية الكلية لجسيم ذي كتلة ساكنة (m) يتحرك بسرعة (v). يستخدم المعادلة E = γmc² = mc² / √(1 - (v²/c²)). بشكل أساسي للجسيمات ذات الكتلة الساكنة (m > 0). يتطلب m ≥ 0 و |v| ≤ c. يجب أن تكون وحدات m وv وc متناسقة للحصول على الطاقة بالوحدات المناسبة (على سبيل المثال، m بوحدة kg، v/c بوحدة m/s تعطي E بوحدة الجول).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "الطاقة الكلية النسبية (الطاقة J)",
         m: "الكتلة الساكنة (الكتلة kg)",
         v: "السرعة (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "الزخم النسبي",
      equation_text: "p = γmv",
      summary: "يحسب الزخم النسبي (p = γmv)",
      description:
         "يحسب الزخم النسبي لجسيم ذي كتلة ساكنة (m) يتحرك بسرعة (v). يستخدم المعادلة p = γmv = mv / √(1 - (v²/c²)). بشكل أساسي للجسيمات ذات الكتلة الساكنة (m > 0). يتطلب m ≥ 0 و |v| ≤ c. يجب أن تكون وحدات m وv وc متناسقة للحصول على الزخم بالوحدات المناسبة (على سبيل المثال، m بوحدة kg، v بوحدة m/s، c بوحدة m/s تعطي p بوحدة kg·m/s).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         p: "الزخم النسبي (الزخم kg·m/s)",
         m: "الكتلة الساكنة (الكتلة kg)",
         v: "السرعة (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "علاقة الطاقة بالزخم",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "يحسب الطاقة الكلية من الزخم والكتلة الساكنة (E)",
      description:
         "يحسب الطاقة النسبية الكلية لجسيم من زخمه النسبي (p) وكتلته الساكنة (m). يستخدم علاقة الطاقة-الزخم: E² = (pc)² + (mc²)². هذه المعادلة صالحة لكل من الجسيمات ذات الكتلة (m > 0) والجسيمات عديمة الكتلة (m = 0). تتطلب p ≥ 0، m ≥ 0، و c > 0. يجب أن تكون وحدات p وm وc متناسقة.\n",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "الطاقة الكلية النسبية (الطاقة J)",
         p: "الزخم النسبي (الزخم kg·m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
         m: "الكتلة الساكنة (الكتلة kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "تكافؤ الكتلة والطاقة (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "يحسب تكافؤ الكتلة والطاقة (E₀ = mc²)",
      description:
         "يحسب طاقة السكون (E₀) المكافئة لكتلة ساكنة معينة (m) باستخدام معادلة أينشتاين الشهيرة E₀ = mc². تتطلب m ≥ 0 وc > 0. يجب أن تكون وحدات m وc متناسقة (على سبيل المثال، m بالكيلوجرام، c بالمتر في الثانية يعطي E₀ بالجول). تستخدم نقطة النهاية هذه قيمة قياسية لـ c (حوالي 299792458 م/ث) ما لم يتم توفير 'c' بشكل صريح.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E0: "طاقة السكون (الطاقة J)",
         m: "الكتلة الساكنة (الكتلة kg)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "الطاقة الحركية النسبية",
      equation_text: "KE = (γ - 1)mc²",
      summary: "يحسب الطاقة الحركية النسبية (KE)",
      description:
         "يحسب الطاقة الحركية النسبية لجسيم ذي كتلة ساكنة (m) يتحرك بسرعة (v). يستخدم المعادلة KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc². بشكل أساسي للجسيمات ذات الكتلة الساكنة (m > 0). يتطلب m ≥ 0 و |v| < c. يجب أن تكون وحدات m وv وc متناسقة للحصول على الطاقة بالوحدات المناسبة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE: "الطاقة الحركية النسبية (الطاقة J)",
         m: "الكتلة الساكنة (الكتلة kg)",
         v: "السرعة (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "تأثير دوبلر النسبي (الطول الموجي)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "يحسب تأثير دوبلر الطولي النسبي للطول الموجي",
      description:
         "يحسب الطول الموجي المرصود (λ') للضوء المنبعث بطول موجي خاص (λ₀) من مصدر يتحرك بسرعة نسبية (v_rel) مباشرة بعيدًا عن المراقب أو نحوه. يستخدم المعادلة λ' = λ₀√((1 + β)/(1 - β))، حيث β = v_rel/c. v_rel > 0 للإبتعاد (انزياح نحو الأحمر)، v_rel < 0 للإقتراب (انزياح نحو الأزرق). يتطلب λ₀ > 0 و |v_rel| < c. وحدات λ' ستكون هي نفسها وحدات λ₀، ويجب أن تكون وحدات v_rel وc متناسقة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         "λ'": "الطول الموجي المرصود (الطول m)",
         λ0: "الطول الموجي الخاص (الطول m)",
         v: "السرعة النسبية (السرعة m/s)",
         c: "سرعة الضوء في الفراغ (السرعة m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "طاقة الفوتون (من التردد)",
      equation_text: "E = hf",
      summary: "يحسب طاقة الفوتون من التردد (E = hf)",
      description:
         "يحسب طاقة (E) فوتون بناءً على تردده (f). يستخدم علاقة بلانك E = hf. يتطلب f ≥ 0 وh > 0. يجب أن تكون وحدات h وf متناسقة للحصول على الطاقة بالوحدات المناسبة (على سبيل المثال، h بوحدة J·s، f بوحدة Hz (s⁻¹) تعطي E بوحدة الجول). تستخدم نقطة النهاية هذه قيمة قياسية لـ h (حوالي 6.626e-34 J·s) ما لم يتم توفير 'h' بشكل صريح.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "طاقة الفوتون (الطاقة J)",
         h: "ثابت بلانك (ثابت J·s)",
         f: "التردد (التردد Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "زخم الفوتون (من الطول الموجي)",
      equation_text: "p = h / λ",
      summary: "يحسب زخم الفوتون من الطول الموجي (p = h/λ)",
      description:
         "يحسب زخم (p) فوتون بناءً على طوله الموجي (λ). يستخدم العلاقة p = h/λ. يتطلب λ > 0 وh > 0. يجب أن تكون وحدات h وλ متناسقة للحصول على الزخم بالوحدات المناسبة (على سبيل المثال، h بوحدة J·s، λ بوحدة المتر تعطي p بوحدة kg·m/s). تستخدم نقطة النهاية هذه قيمة قياسية لـ h (حوالي 6.626e-34 J·s) ما لم يتم توفير 'h' بشكل صريح.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         p: "زخم الفوتون (الزخم kg·m/s)",
         h: "ثابت بلانك (ثابت J·s)",
         λ: "الطول الموجي (الطول m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "التأثير الكهروضوئي (الحد الأقصى للطاقة الحركية)",
      equation_text: "KE_max = E_photon - φ",
      summary: "يحسب الحد الأقصى للطاقة الحركية في التأثير الكهروضوئي (KE_max)",
      description:
         "يحسب الحد الأقصى للطاقة الحركية (KE_max) للإلكترونات المنبعثة في التأثير الكهروضوئي. يستخدم المعادلة KE_max = E_photon - φ، حيث E_photon هي طاقة الفوتون الوارد وφ هي دالة الشغل للمادة. إذا كان E_photon ≤ φ، فلن يتم انبعاث أي إلكترونات، ويكون KE_max هو 0. يتطلب E_photon ≥ 0 وφ ≥ 0. يجب أن تكون وحدات E_photon وφ متناسقة للحصول على KE_max بنفس الوحدات.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE_max: "الحد الأقصى للطاقة الحركية للإلكترون (الطاقة J)",
         E_photon: "طاقة الفوتون (الطاقة J)",
         φ: "دالة الشغل (الطاقة J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "معادلة ريدبرج (الانتقال الذري)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "يحسب الطاقة أو عدد الموجة للانتقالات في الذرات الشبيهة بالهيدروجين",
      description:
         "يحسب فرق الطاقة (ΔE) أو عدد الموجة (1/λ) لانتقال إلكتروني بين مستويين للطاقة في ذرة شبيهة بالهيدروجين (Z). يستخدم المعادلة النتيجة = ثابت * Z² * (1/n_initial² - 1/n_final²). إذا كان 'ثابت' هو وحدة طاقة ريدبرج (على سبيل المثال، بوحدة eV)، فإن النتيجة هي فرق الطاقة E_final - E_initial (موجب للامتصاص، سالب للانبعاث). إذا كان 'ثابت' هو ثابت ريدبرج لعدد الموجة (على سبيل المثال، بوحدة m⁻¹)، فإن النتيجة هي عدد الموجة 1/λ (موجب للانبعاث، سالب للامتصاص). يتطلب nInitial > 0، nFinal > 0، nInitial ≠ nFinal، Z > 0 (أعداد صحيحة)، وثابت > 0.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔE: "فرق الطاقة (الطاقة J)",
         R_y: "ثابت ريدبرج (ثابت J أو مقلوب الطول m⁻¹)",
         Z: "العدد الذري (عدد صحيح بدون أبعاد)",
         n1: "العدد الكمي الرئيسي الأولي (عدد صحيح بدون أبعاد)",
         n2: "العدد الكمي الرئيسي النهائي (عدد صحيح بدون أبعاد)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "السرعة الزاوية",
      equation_text: "ω = Δθ / Δt",
      summary: "يحسب السرعة الزاوية (ω = Δθ / Δt)",
      description: "يحسب السرعة الزاوية بناءً على التغير في الزاوية والزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ω: "السرعة الزاوية (السرعة الزاوية rad/s)",
         Δθ: "الإزاحة الزاوية (الزاوية rad)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "التسارع الزاوي",
      equation_text: "α = Δω / Δt",
      summary: "يحسب التسارع الزاوي (α = Δω / Δt)",
      description: "يحسب التسارع الزاوي بناءً على التغير في السرعة الزاوية والزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         α: "التسارع الزاوي (التسارع الزاوي rad/s²)",
         Δω: "التغير في السرعة الزاوية (السرعة الزاوية rad/s)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "حركة الدوران (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "يحسب السرعة الزاوية النهائية (ω = ω0 + αt)",
      description: "يحسب السرعة الزاوية النهائية باستخدام معادلة الحركة الزاوية الأولى.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ω: "السرعة الزاوية النهائية (السرعة الزاوية rad/s)",
         ω0: "السرعة الزاوية الابتدائية (السرعة الزاوية rad/s)",
         α: "التسارع الزاوي (التسارع الزاوي rad/s²)",
         t: "الزمن (الزمن s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "حركة الدوران (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "يحسب الموضع الزاوي (θ = θ0 + ω0t + 0.5αt^2)",
      description: "يحسب الموضع الزاوي النهائي باستخدام معادلة الحركة الزاوية الثانية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         θ: "الموضع الزاوي النهائي (الزاوية rad)",
         θ0: "الموضع الزاوي الابتدائي (الزاوية rad)",
         ω0: "السرعة الزاوية الابتدائية (السرعة الزاوية rad/s)",
         t: "الزمن (الزمن s)",
         α: "التسارع الزاوي (التسارع الزاوي rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "حركة الدوران (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "يحسب مربع السرعة الزاوية (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "يحسب مربع السرعة الزاوية النهائية باستخدام معادلة الحركة الزاوية الثالثة. ملاحظة - يعيد ω^2، وليس ω.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ω: "السرعة الزاوية النهائية (السرعة الزاوية rad/s)",
         ω0: "السرعة الزاوية الابتدائية (السرعة الزاوية rad/s)",
         α: "التسارع الزاوي (التسارع الزاوي rad/s²)",
         Δθ: "الإزاحة الزاوية (الزاوية rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "متوسط السرعة الزاوية",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "يحسب متوسط السرعة الزاوية (ω_avg = 0.5 * (ω + ω0))",
      description: "يحسب متوسط السرعة الزاوية بافتراض تسارع زاوي ثابت.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ω_avg: "متوسط السرعة الزاوية (السرعة الزاوية rad/s)",
         ω: "السرعة الزاوية النهائية (السرعة الزاوية rad/s)",
         ω0: "السرعة الزاوية الابتدائية (السرعة الزاوية rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "عزم الدوران",
      equation_text: "τ = rFsin(θ)",
      summary: "يحسب عزم الدوران (τ = rF sin(θ))",
      description: "يحسب عزم الدوران بناءً على نصف القطر والقوة والزاوية بينهما.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         τ: "عزم الدوران (عزم الدوران N·m)",
         r: "ذراع الرافعة (الطول m)",
         F: "القوة (القوة N)",
         θ: "الزاوية بين القوة وذراع الرافعة (الزاوية rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "قانون نيوتن الثاني (الدوران)",
      equation_text: "τ_net = Iα",
      summary: "يحسب عزم الدوران باستخدام قانون الدوران الثاني (τ = Iα)",
      description: "يحسب عزم الدوران بناءً على عزم القصور الذاتي والتسارع الزاوي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         τ_net: "صافي عزم الدوران (عزم الدوران N·m)",
         I: "عزم القصور الذاتي (عزم القصور الذاتي kg·m²)",
         α: "التسارع الزاوي (التسارع الزاوي rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "عزم القصور الذاتي",
      equation_text: "I = mr² (كتلة نقطية)",
      summary: "يحسب عزم القصور الذاتي لكتلة نقطية (I = mr^2)",
      description: "يحسب عزم القصور الذاتي لكتلة نقطية واحدة بالنسبة لمحور.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         I: "عزم القصور الذاتي (عزم القصور الذاتي kg·m²)",
         m: "الكتلة (الكتلة kg)",
         r: "المسافة من المحور (الطول m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "الشغل الدوراني",
      equation_text: "W = τΔθ (عزم دوران ثابت)",
      summary: "يحسب الشغل الدوراني (W = τΔθ)",
      description: "يحسب الشغل الذي يبذله عزم دوران ثابت على مدى إزاحة زاوية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         W: "الشغل الدوراني (الطاقة J)",
         τ: "عزم الدوران (عزم الدوران N·m)",
         Δθ: "الإزاحة الزاوية (الزاوية rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "القدرة الدورانية",
      equation_text: "P = τω",
      summary: "يحسب القدرة الدورانية (P = τω cos(θ))",
      description:
         "يحسب القدرة الدورانية اللحظية بناءً على عزم الدوران والسرعة الزاوية والزاوية بينهما.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "القدرة الدورانية (القدرة W)",
         τ: "عزم الدوران (عزم الدوران N·m)",
         ω: "السرعة الزاوية (السرعة الزاوية rad/s)",
         θ: "الزاوية بين عزم الدوران والسرعة الزاوية (الزاوية rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "الطاقة الحركية الدورانية",
      equation_text: "KE_rot = ½Iω²",
      summary: "يحسب الطاقة الحركية الدورانية (KE = 0.5Iω^2)",
      description: "يحسب الطاقة الحركية لجسم يدور.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE_rot: "الطاقة الحركية الدورانية (الطاقة J)",
         I: "عزم القصور الذاتي (عزم القصور الذاتي kg·m²)",
         ω: "السرعة الزاوية (السرعة الزاوية rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "الزخم الزاوي",
      equation_text: "L = Iω",
      summary: "يحسب الزخم الزاوي (L = mrv sin(θ))",
      description: "يحسب الزخم الزاوي لكتلة نقطية تتحرك بالنسبة لنقطة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         L: "الزخم الزاوي (الزخم الزاوي kg·m²/s)",
         m: "الكتلة (الكتلة kg)",
         r: "المسافة من المحور/النقطة (الطول m)",
         v: "السرعة (السرعة m/s)",
         θ: "الزاوية بين متجه نصف القطر والسرعة (الزاوية rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "الاندفاع الزاوي",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "يحسب الاندفاع الزاوي (J = τΔt)",
      description: "يحسب الاندفاع الزاوي من عزم الدوران والفترة الزمنية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         J_angular: "الاندفاع الزاوي (الاندفاع الزاوي N·m·s)",
         τ_avg: "متوسط عزم الدوران (عزم الدوران N·m)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "معامل يونغ",
      equation_text: "E = σ / ε",
      summary: "يحسب معامل يونغ (E = (F * L0) / (A * ΔL))",
      description: "يحسب معامل يونغ (معامل المرونة) لمادة تحت إجهاد شد أو ضغط.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         E: "معامل يونغ (الضغط Pa)",
         F: "القوة (القوة N)",
         L0: "الطول الأصلي (الطول m)",
         A: "مساحة المقطع العرضي (المساحة m²)",
         ΔL: "التغير في الطول (الطول m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "معامل القص",
      equation_text: "G = τ / γ",
      summary: "يحسب معامل القص (G = (F * y) / (A * Δx))",
      description: "يحسب معامل القص (معامل الصلابة) لمادة تحت إجهاد قص.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         G: "معامل القص (الضغط Pa)",
         F: "القوة (القوة النيوتونية N)",
         y: "المسافة العمودية على القوة (الطول m)",
         A: "المساحة (المساحة m²)",
         Δx: "الإزاحة (الطول m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "معامل الحجم",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "يحسب معامل الحجم (K = (F * V0) / (A * ΔV))",
      description: "يحسب معامل الحجم لمادة تحت ضغط موحد (إجهاد هيدروستاتيكي).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         K: "معامل الحجم (الضغط Pa)",
         ΔP: "التغير في الضغط (الضغط Pa)",
         ΔV: "التغير في الحجم (الحجم m³)",
         V0: "الحجم الأصلي (الحجم m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "قانون هوك",
      equation_text: "F = kx",
      summary: "يحسب قوة النابض (F = -k * Δx)",
      description:
         "يحسب قوة الإعادة التي يمارسها نابض مثالي وفقًا لقانون هوك. ملاحظة - يعيد قيمة سالبة تشير إلى أن القوة تعارض الإزاحة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         F: "القوة (القوة N)",
         k: "ثابت النابض (ثابت النابض N/m)",
         x: "الإزاحة عن موضع الاتزان (الطول m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "التمدد الحراري للمواد الصلبة (الطول)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "يحسب التمدد الحراري الخطي للمواد الصلبة (ΔL = αL0ΔT)",
      description: "يحسب التغير في طول مادة صلبة نتيجة لتغير في درجة الحرارة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔL: "التغير في الطول (الطول m)",
         α: "معامل التمدد الخطي (معامل لكل درجة حرارة K⁻¹)",
         L0: "الطول الأصلي (الطول m)",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "التمدد الحراري للمواد الصلبة (المساحة)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "يحسب التمدد الحراري المساحي للمواد الصلبة (ΔA = 2αA0ΔT)",
      description:
         "يحسب التغير في مساحة مادة صلبة نتيجة لتغير في درجة الحرارة، باستخدام معامل التمدد الخطي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔA: "التغير في المساحة (المساحة m²)",
         α: "معامل التمدد الخطي (معامل لكل درجة حرارة K⁻¹)",
         A0: "المساحة الأصلية (المساحة m²)",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "التمدد الحراري للمواد الصلبة (الحجم)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "يحسب التمدد الحراري الحجمي للمواد الصلبة (ΔV = 3αV0ΔT)",
      description:
         "يحسب التغير في حجم مادة صلبة نتيجة لتغير في درجة الحرارة، باستخدام معامل التمدد الخطي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔV: "التغير في الحجم (الحجم m³)",
         α: "معامل التمدد الخطي (معامل لكل درجة حرارة K⁻¹)",
         V0: "الحجم الأصلي (الحجم m³)",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "التمدد الحراري للسوائل",
      equation_text: "ΔV = βV₀ΔT",
      summary: "يحسب التمدد الحراري للسوائل (ΔV = βV0ΔT)",
      description: "يحسب التغير في حجم سائل نتيجة لتغير في درجة الحرارة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔV: "التغير في الحجم (الحجم m³)",
         β: "معامل التمدد الحجمي (معامل لكل درجة حرارة K⁻¹)",
         V0: "الحجم الأصلي (الحجم m³)",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "الحرارة المحسوسة",
      equation_text: "Q = mcΔT",
      summary: "يحسب الحرارة المحسوسة (Q = mcΔT)",
      description: "يحسب الحرارة المنتقلة التي تسبب تغيرًا في درجة حرارة مادة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Q: "الحرارة المحسوسة (الطاقة J)",
         m: "الكتلة (الكتلة kg)",
         c: "السعة الحرارية النوعية (السعة الحرارية النوعية J/(kg·K))",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "الحرارة الكامنة",
      equation_text: "Q = mL",
      summary: "يحسب الحرارة الكامنة (Q = mL)",
      description: "يحسب الحرارة المنتقلة أثناء تغير حالة المادة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Q: "الحرارة الكامنة (الطاقة J)",
         m: "الكتلة (الكتلة kg)",
         L: "الحرارة الكامنة (الطاقة النوعية J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "قانون الغاز المثالي",
      equation_text: "PV = nRT",
      summary: "يتحقق من صحة قانون الغاز المثالي (PV = nRT)",
      description:
         "يتحقق مما إذا كانت معادلة قانون الغاز المثالي صحيحة للمعلمات المعطاة. تُرجع قيمة منطقية (boolean). ملاحظة - تستخدم مساواة صارمة (===) قد تكون حساسة لدقة الفاصلة العائمة؛ يفضل النظر في السماح بتفاوت في الاختبارات الواقعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "الضغط (الضغط Pa)",
         V: "الحجم (الحجم m³)",
         n: "عدد المولات (كمية المادة mol)",
         R: "ثابت الغاز المثالي (ثابت J/(mol·K))",
         T: "درجة الحرارة (درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "الطاقة الحركية الجزيئية",
      equation_text: "KE_avg = (3/2)kT",
      summary: "يحسب متوسط الطاقة الحركية الجزيئية (KE = (3/2)kT)",
      description: "يحسب متوسط الطاقة الحركية الانتقالية لكل جزيء من غاز مثالي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE_avg: "متوسط الطاقة الحركية الجزيئية (الطاقة J)",
         k: "ثابت بولتزمان (ثابت J/K)",
         T: "درجة الحرارة (درجة الحرارة K)",
         m: "كتلة جزيء واحد (الكتلة kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "السرعة الجزيئية (الأكثر احتمالاً)",
      equation_text: "v_p = √(2kT/m)",
      summary: "يحسب السرعة الجزيئية الأكثر احتمالاً (v_p = √(2kT/m))",
      description:
         "يحسب السرعة الأكثر احتمالاً للجزيئات في غاز مثالي وفقًا لتوزيع ماكسويل-بولتزمان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_p: "السرعة الجزيئية الأكثر احتمالاً (السرعة m/s)",
         k: "ثابت بولتزمان (ثابت J/K)",
         T: "درجة الحرارة (درجة الحرارة K)",
         m: "كتلة جزيء واحد (الكتلة kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "السرعة الجزيئية (المتوسطة)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "يحسب متوسط السرعة الجزيئية (v_avg = √(8kT/(πm)))",
      description:
         "يحسب متوسط السرعة للجزيئات في غاز مثالي وفقًا لتوزيع ماكسويل-بولتزمان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_avg: "متوسط السرعة الجزيئية (السرعة m/s)",
         k: "ثابت بولتزمان (ثابت J/K)",
         T: "درجة الحرارة (درجة الحرارة K)",
         π: "باي (ثابت بدون أبعاد)",
         m: "كتلة جزيء واحد (الكتلة kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "السرعة الجزيئية (جذر متوسط المربعات)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "يحسب السرعة الجزيئية لجذر متوسط المربعات (v_rms = √(3kT/m))",
      description:
         "يحسب السرعة الجزيئية لجذر متوسط المربعات للجزيئات في غاز مثالي وفقًا لتوزيع ماكسويل-بولتزمان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v_rms: "السرعة الجزيئية لجذر متوسط المربعات (السرعة m/s)",
         k: "ثابت بولتزمان (ثابت J/K)",
         T: "درجة الحرارة (درجة الحرارة K)",
         m: "كتلة جزيء واحد (الكتلة kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "التغير في الطاقة الداخلية",
      equation_text: "ΔU = Q - W",
      summary: "يحسب التغير في الطاقة الداخلية لغاز أحادي الذرة مثالي (ΔU = (3/2)nRΔT)",
      description:
         "يحسب التغير في الطاقة الداخلية لغاز مثالي أحادي الذرة يمر بتغير في درجة الحرارة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         ΔU: "التغير في الطاقة الداخلية (الطاقة J)",
         n: "عدد المولات (كمية المادة mol)",
         R: "ثابت الغاز المثالي (ثابت J/(mol·K))",
         ΔT: "التغير في درجة الحرارة (فرق درجة الحرارة K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "الشغل الثرموديناميكي",
      equation_text: "W = PΔV (ضغط ثابت)",
      summary: "يحسب الشغل الثرموديناميكي الذي يقوم به النظام عند ضغط ثابت (W = -PΔV)",
      description:
         "يحسب الشغل الذي يبذله أو يُبذل على نظام خلال عملية ثرموديناميكية عند ضغط ثابت. ملاحظة - المعادلة تحسب الشغل الذي *يبذله* النظام، موجبة للتمدد، سالبة للانضغاط. الدالة تُرجع -P*deltaV، وهو متوافق مع الشغل الذي *يبذله* النظام وفقًا للمعادلة W = PΔV، مع إضافة علامة سالبة قد تشير إلى الشغل الذي *يُبذل على* النظام حسب الاصطلاح. توثيق مخرجات الدالة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         W: "الشغل الثرموديناميكي (الطاقة J)",
         P: "الضغط (الضغط Pa)",
         ΔV: "التغير في الحجم (الحجم m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "الكفاءة الحقيقية",
      equation_text: "η = W_out / Q_in",
      summary: "يحسب كفاءة محرك حقيقي (η_real = 1 - (Q_C / Q_H))",
      description: "يحسب الكفاءة الحرارية لمحرك حراري بناءً على الحرارة الممتصة والمرفوضة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         η: "الكفاءة (بدون أبعاد)",
         Q_H: "الحرارة الممتصة من الخزان الساخن (الطاقة J)",
         Q_C: "الحرارة المرفوضة إلى الخزان البارد (الطاقة J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "الكفاءة المثالية",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "يحسب الكفاءة المثالية (كارنو) (η_ideal = 1 - (T_C / T_H))",
      description:
         "يحسب أقصى كفاءة نظرية لمحرك حراري يعمل بين درجتي حرارة (كفاءة كارنو).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         η_ideal: "الكفاءة المثالية (بدون أبعاد)",
         T_hot: "درجة حرارة الخزان الساخن (درجة الحرارة K)",
         T_cold: "درجة حرارة الخزان البارد (درجة الحرارة K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "معامل الأداء الحقيقي (COP)",
      equation_text: "COP_ref = Q_c / W (مبرد)",
      summary: "يحسب معامل الأداء لمبرد حقيقي (COP_real = QC / (QH - QC))",
      description: "يحسب معامل الأداء لمبرد أو مضخة حرارية حقيقية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         COP_real: "معامل الأداء (بدون أبعاد)",
         Q_C: "الحرارة من الخزان البارد (الطاقة J)",
         Q_H: "الحرارة إلى الخزان الساخن (الطاقة J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "معامل الأداء المثالي (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "يحسب معامل الأداء لمبرد مثالي (COP_ideal = TC / (TH - TC))",
      description:
         "يحسب الحد الأقصى النظري لمعامل الأداء لمبرد أو مضخة حرارة تعمل بين درجتي حرارة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         COP_ideal: "معامل الأداء المثالي (بدون أبعاد)",
         T_h: "درجة حرارة الخزان الساخن (درجة الحرارة K)",
         T_c: "درجة حرارة الخزان البارد (درجة الحرارة K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "سرعة الموجة الدورية",
      equation_text: "v = fλ",
      summary: "يحسب سرعة الموجة (v = fλ)",
      description: "يحسب سرعة موجة دورية بناءً على ترددها وطول موجتها.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         v: "سرعة الموجة (السرعة m/s)",
         f: "التردد (التردد Hz)",
         λ: "الطول الموجي (الطول m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "شدة الموجة",
      equation_text: "I = P / A",
      summary: "يحسب الشدة (I = P/A)",
      description: "يحسب شدة موجة (القدرة لكل وحدة مساحة).",
      language_code: "ar",
      subject: "Physics",
      variables: {
         I: "الشدة (الشدة W/m²)",
         P: "القدرة (القدرة W)",
         A: "المساحة (المساحة m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "مستوى الشدة (ديسيبل)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "يحسب مستوى الشدة بالديسيبل (L = 10 log10(I/I0))",
      description: "يحسب مستوى الشدة (مستوى شدة الصوت) بالنسبة لشدة مرجعية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         β: "مستوى الشدة (مستوى الشدة dB)",
         I: "الشدة (الشدة W/m²)",
         I0: "شدة مرجعية (الشدة W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "مستوى الضغط (مستوى ضغط الصوت)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "يحسب مستوى ضغط الصوت بالديسيبل (L = 20 log10(ΔP/ΔP0))",
      description: "يحسب مستوى ضغط الصوت بالنسبة لتغير ضغط مرجعي.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         L_p: "مستوى ضغط الصوت (مستوى الضغط dB)",
         P_rms: "تقلب الضغط RMS (الضغط Pa)",
         P_ref: "الضغط المرجعي (الضغط Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "تأثير دوبلر (الصوت/غير نسبي)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "يحسب عامل سرعة تأثير دوبلر ((c + v_o) / (c - v_s))",
      description:
         "يحسب جزء عامل السرعة من معادلة تأثير دوبلر (f' = f * factor). سرعات موجبة للمراقب الذي يتحرك نحو المصدر، والمصدر الذي يتحرك نحو المراقب.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         f_obs: "التردد المرصود (التردد Hz)",
         f_source: "تردد المصدر (التردد Hz)",
         v_wave: "سرعة الموجة (السرعة m/s)",
         v_observer: "سرعة المراقب بالنسبة للوسط (السرعة m/s)",
         v_source: "سرعة المصدر بالنسبة للوسط (السرعة m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "زاوية ماخ",
      equation_text: "sin(μ) = 1 / M",
      summary: "يحسب زاوية ماخ (θ_M = arcsin(c/v))",
      description:
         "يحسب زاوية مخروط ماخ التي يتكون من جسم يتحرك أسرع من سرعة الصوت. تُرجع الزاوية بالراديان.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         μ: "زاوية ماخ (الزاوية rad)",
         M: "عدد ماخ (بدون أبعاد)",
         c: "سرعة الصوت (السرعة m/s)",
         v: "سرعة الجسم (السرعة m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "الشغل",
      equation_text: "W = Fdcos(θ)",
      summary: "يحسب الشغل المنجز (W = F * Δs * cos(θ))",
      description: "يحسب الشغل المنجز بناءً على القوة، الإزاحة، والزاوية بينهما.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         W: "الشغل المنجز (الطاقة J)",
         F: "مقدار القوة (القوة N)",
         d: "مقدار الإزاحة (الطول m)",
         θ: "الزاوية بين القوة والإزاحة (الزاوية rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "الطاقة الحركية",
      equation_text: "KE = ½mv²",
      summary: "يحسب الطاقة الحركية (KE = 0.5 * m * v^2)",
      description: "يحسب الطاقة الحركية بناءً على الكتلة والسرعة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE: "الطاقة الحركية (الطاقة J)",
         m: "الكتلة (الكتلة kg)",
         v: "السرعة (السرعة m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "الطاقة الحركية (من الزخم)",
      equation_text: "KE = p² / (2m)",
      summary: "يحسب الطاقة الحركية من الزخم (KE = p^2 / (2m))",
      description: "يحسب الطاقة الحركية بناءً على الزخم والكتلة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         KE: "الطاقة الحركية (الطاقة J)",
         p: "الزخم (الزخم kg·m/s)",
         m: "الكتلة (الكتلة kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "الطاقة الكامنة الجاذبية",
      equation_text: "U_g = mgh (بالقرب من السطح)",
      summary: "يحسب الطاقة الكامنة الجاذبية (PE = mgh)",
      description: "يحسب التغير في الطاقة الكامنة الجاذبية.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         U_g: "الطاقة الكامنة الجاذبية (الطاقة J)",
         m: "الكتلة (الكتلة kg)",
         g: "تسارع الجاذبية (التسارع m/s²)",
         h: "الارتفاع (الطول m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "الكفاءة",
      equation_text: "الكفاءة = الخرج / الدخل",
      summary: "يحسب الكفاءة (η = W_out / W_in)",
      description: "يحسب كفاءة عملية أو آلة.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         Efficiency: "الكفاءة (بدون أبعاد)",
         Output: "طاقة أو قدرة الخرج المفيدة (الطاقة J أو القدرة W)",
         Input: "إجمالي طاقة أو قدرة الدخل (الطاقة J أو القدرة W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "القدرة",
      equation_text: "P = W / t",
      summary: "يحسب القدرة (P = ΔW / Δt)",
      description: "يحسب متوسط القدرة بناءً على التغير في الشغل والزمن.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "القدرة (القدرة W)",
         ΔW: "التغير في الشغل (الطاقة J)",
         Δt: "الفترة الزمنية (الزمن s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "القدرة (P = Fv)",
      equation_text: "P = Fv",
      summary: "يحسب القدرة من القوة والسرعة (P = Fv cos(θ))",
      description: "يحسب القدرة اللحظية بناءً على القوة والسرعة والزاوية بينهما.",
      language_code: "ar",
      subject: "Physics",
      variables: {
         P: "القدرة (القدرة W)",
         F: "مقدار القوة (القوة N)",
         v: "مقدار السرعة (السرعة m/s)",
         θ: "الزاوية بين القوة والسرعة (الزاوية rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = ar;