const bn = [
   {
      equation_id: "centripetal-acceleration",
      name: "কেন্দ্রমুখী ত্বরণ",
      equation_text: "a_c = v² / r",
      summary: "কেন্দ্রমুখী ত্বরণ গণনা করে (a_c = v^2 / r)",
      description: "রৈখিক বেগ এবং ব্যাসার্ধ ব্যবহার করে একটি বৃত্তাকার পথের কেন্দ্রের দিকে নির্দেশিত ত্বরণ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         a_c: "কেন্দ্রমুখী ত্বরণ (ত্বরণ m/s²)",
         v: "রৈখিক বেগ (গতি m/s)",
         r: "বৃত্তাকার পথের ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "কেন্দ্রমুখী ত্বরণ (কোণীয়)",
      equation_text: "a_c = ω²r",
      summary: "কোণীয় বেগ ব্যবহার করে কেন্দ্রমুখী ত্বরণ গণনা করে (a_c = -ω^2 * r)",
      description:
         "কোণীয় বেগ এবং ব্যাসার্ধ ব্যবহার করে কেন্দ্রমুখী ত্বরণ ভেক্টর উপাদান গণনা করে। ঋণাত্মক চিহ্ন কেন্দ্রের দিকে দিক নির্দেশ করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         a_c: "কেন্দ্রমুখী ত্বরণ (ত্বরণ m/s²)",
         ω: "কোণীয় বেগ (কোণীয় বেগ rad/s)",
         r: "বৃত্তাকার পথের ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "কুলম্বের নিয়ম (বল)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "কুলম্বের নিয়ম (F = k * q1*q2 / r^2) ব্যবহার করে বৈদ্যুতিক বল গণনা করে",
      description:
         "দুইটি বিন্দু চার্জের মধ্যে বৈদ্যুতিক বল গণনা করে। চিহ্নযুক্ত বল ফেরত দেয় (বিকর্ষণের জন্য ধনাত্মক, আকর্ষণের জন্য ঋণাত্মক)।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F: "বৈদ্যুতিক বল (বল N)",
         k: "কুলম্বের ধ্রুবক (ধ্রুবক N·m²/C²)",
         q1: "চার্জ 1 (চার্জ C)",
         q2: "চার্জ 2 (চার্জ C)",
         r: "চার্জের মধ্যে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "বৈদ্যুতিক ক্ষেত্র",
      equation_text: "E = kq / r² (বিন্দু চার্জ)",
      summary: "বল থেকে বৈদ্যুতিক ক্ষেত্র গণনা করে (E = F_E/q)",
      description: "একটি পরীক্ষা চার্জে প্রয়োগ করা বলের উপর ভিত্তি করে বৈদ্যুতিক ক্ষেত্রের তীব্রতা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "বৈদ্যুতিক ক্ষেত্রের মাত্রা (বৈদ্যুতিক ক্ষেত্র N/C)",
         k: "কুলম্বের ধ্রুবক (ধ্রুবক N·m²/C²)",
         q: "উৎস চার্জ (চার্জ C)",
         r: "উৎস চার্জ থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "বৈদ্যুতিক পটেনশিয়াল",
      equation_text: "V = kq / r (বিন্দু চার্জ)",
      summary: "পটেনশিয়াল শক্তি পরিবর্তন থেকে বৈদ্যুতিক পটেনশিয়াল গণনা করে (V = ΔU_E/q)",
      description:
         "প্রতি ইউনিট চার্জের বৈদ্যুতিক পটেনশিয়াল শক্তির পরিবর্তনের উপর ভিত্তি করে বৈদ্যুতিক পটেনশিয়াল (ভোল্টেজ) গণনা করে। দ্রষ্টব্য - ফাংশন নাম `calculateElectricPotential` সঠিক, কিন্তু প্যারামিটার `deltaUE` পরিবর্তন বোঝায়, যখন সমীকরণ সাধারণত V=U_E/q বা ΔV=ΔU_E/q হয়। ΔV = ΔU_E/q সমীকরণের উপর ভিত্তি করে নথিভুক্তকরণ এবং ΔV ফেরত দেওয়া হচ্ছে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         V: "বৈদ্যুতিক পটেনশিয়াল (ভোল্টেজ V)",
         k: "কুলম্বের ধ্রুবক (ধ্রুবক N·m²/C²)",
         q: "উৎস চার্জ (চার্জ C)",
         r: "উৎস চার্জ থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "বৈদ্যুতিক ক্ষেত্র এবং পটেনশিয়ালের সম্পর্ক",
      equation_text: "E_x = -dV/dx",
      summary: "পটেনশিয়াল পার্থক্য থেকে বৈদ্যুতিক ক্ষেত্র গণনা করে (E = ΔV/d)",
      description:
         'একটি নির্দিষ্ট দূরত্বে পটেনশিয়াল পার্থক্যের উপর ভিত্তি করে একটি অভিন্ন বৈদ্যুতিক ক্ষেত্রের মাত্রা গণনা করে। দ্রষ্টব্য - "Field and Potential" ফাংশন নামটি বিভ্রান্তিকর; এটি বৈদ্যুতিক ক্ষেত্র E গণনা করে।',
      language_code: "bn",
      subject: "Physics",
      variables: {
         E_x: "বৈদ্যুতিক ক্ষেত্র উপাদান (বৈদ্যুতিক ক্ষেত্র V/m)",
         V: "বৈদ্যুতিক পটেনশিয়াল (ভোল্টেজ V)",
         x: "অবস্থান (দৈর্ঘ্য m)",
         ΔV: "পটেনশিয়াল পার্থক্য (ভোল্টেজ V)",
         d: "দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "ক্যাপাসিট্যান্স",
      equation_text: "C = Q / V",
      summary: "ক্যাপাসিট্যান্স গণনা করে (C = Q/V)",
      description: "সংরক্ষিত চার্জ এবং একটি ক্যাপাসিটরের ভোল্টেজের উপর ভিত্তি করে ক্যাপাসিট্যান্স গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         Q: "চার্জ (চার্জ C)",
         V: "ভোল্টেজ (ভোল্টেজ V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "প্লেট ক্যাপাসিটরের ক্যাপাসিট্যান্স",
      equation_text: "C = ε₀A / d",
      summary: "সমান্তরাল প্লেট ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে (C = (kε₀A)/d)",
      description:
         "একটি ডাইলেক্ট্রিক সহ সমান্তরাল প্লেট ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে। দ্রষ্টব্য - ফাংশন k * ε₀ কে একক ইনপুট (`kEpsilon`) হিসাবে ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         ε0: "মুক্ত স্থানের পারমিটিভিটি (ধ্রুবক F/m)",
         k: "ডাইলেক্ট্রিক ধ্রুবক (মাত্রাহীন)",
         A: "প্লেটের ক্ষেত্রফল (ক্ষেত্রফল m²)",
         d: "প্লেটের মধ্যে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "বেলনাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "বেলনাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "একটি ডাইলেক্ট্রিক সহ বেলনাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে। দ্রষ্টব্য - ফাংশন k * ε₀ কে একক ইনপুট (`kEpsilon`) হিসাবে ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         ε0: "মুক্ত স্থানের পারমিটিভিটি (ধ্রুবক F/m)",
         k: "ডাইলেক্ট্রিক ধ্রুবক (মাত্রাহীন)",
         L: "সিলিন্ডারের দৈর্ঘ্য (দৈর্ঘ্য m)",
         b: "বহিঃস্থ ব্যাসার্ধ (দৈর্ঘ্য m)",
         a: "অভ্যন্তরীণ ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "গোলাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "গোলাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "একটি ডাইলেক্ট্রিক সহ গোলাকার ক্যাপাসিটরের ক্যাপাসিট্যান্স গণনা করে। দ্রষ্টব্য - ফাংশন k * ε₀ কে একক ইনপুট (`kEpsilon`) হিসাবে ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         ε0: "মুক্ত স্থানের পারমিটিভিটি (ধ্রুবক F/m)",
         k: "ডাইলেক্ট্রিক ধ্রুবক (মাত্রাহীন)",
         a: "অভ্যন্তরীণ ব্যাসার্ধ (দৈর্ঘ্য m)",
         b: "বহিঃস্থ ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "ক্যাপাসিটিভ পটেনশিয়াল শক্তি",
      equation_text: "U_C = ½CV²",
      summary: "ক্যাপাসিটর পটেনশিয়াল শক্তি সমীকরণ যাচাই করে (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "প্রদত্ত Q, V, এবং C-এর জন্য একটি ক্যাপাসিটরে সঞ্চিত পটেনশিয়াল শক্তির জন্য তিনটি সাধারণ সমীকরণ সমতুল্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         U_C: "ক্যাপাসিটিভ পটেনশিয়াল শক্তি (শক্তি J)",
         Q: "চার্জ (চার্জ C)",
         V: "ভোল্টেজ (ভোল্টেজ V)",
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "বৈদ্যুতিক প্রবাহ",
      equation_text: "I = ΔQ / Δt",
      summary: "বৈদ্যুতিক প্রবাহ গণনা করে (I = ΔQ/Δt)",
      description:
         "প্রতি ইউনিট সময়ে একটি বিন্দু দিয়ে প্রবাহিত চার্জের পরিমাণের উপর ভিত্তি করে বৈদ্যুতিক প্রবাহ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         I: "বৈদ্যুতিক প্রবাহ (প্রবাহ A)",
         ΔQ: "চার্জে পরিবর্তন (চার্জ C)",
         Δt: "সময়ে পরিবর্তন (সময় s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "চার্জ ঘনত্ব",
      equation_text: "ρ = Q / V (আয়তন)",
      summary: "চার্জ ঘনত্ব গণনা করে (ρ = Q/V)",
      description: "গড় চার্জ ঘনত্ব (প্রতি ইউনিট আয়তনে চার্জ) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ρ: "আয়তন চার্জ ঘনত্ব (চার্জ ঘনত্ব C/m³)",
         Q: "মোট চার্জ (চার্জ C)",
         V: "আয়তন (আয়তন m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "প্রবাহ ঘনত্ব",
      equation_text: "J = I / A",
      summary: "প্রবাহ ঘনত্ব গণনা করে (J = I/A)",
      description: "বৈদ্যুতিক প্রবাহ ঘনত্ব (প্রতি ইউনিট প্রস্থচ্ছেদ ক্ষেত্রফল প্রবাহ) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         J: "প্রবাহ ঘনত্ব (প্রবাহ ঘনত্ব A/m²)",
         I: "বৈদ্যুতিক প্রবাহ (প্রবাহ A)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "ওহমের নিয়ম",
      equation_text: "V = IR",
      summary: "ওহমের নিয়ম ব্যবহার করে রোধ গণনা করে (R = V/I)",
      description: "ভোল্টেজ এবং প্রবাহের উপর ভিত্তি করে রোধ গণনা করে। দ্রষ্টব্য - ফাংশন V এবং I থেকে রোধ R গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         V: "ভোল্টেজ (ভোল্টেজ V)",
         I: "প্রবাহ (প্রবাহ A)",
         R: "রোধ (রোধ Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "রোধকতা এবং পরিবাহিতা",
      equation_text: "ρ = RA / L",
      summary: "রোধকতা থেকে পরিবাহিতা গণনা করে (σ = 1/ρ)",
      description: "রোধকতা (ρ) থেকে পরিবাহিতা (σ) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         σ: "পরিবাহিতা (পরিবাহিতা S/m)",
         ρ: "রোধকতা (রোধকতা Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "বৈদ্যুতিক রোধ",
      equation_text: "R = ρL / A",
      summary: "বৈদ্যুতিক রোধ গণনা করে (R = ρ(l/A))",
      description:
         "একটি পরিবাহীর রোধ গণনা করে যা তার রোধকতা, দৈর্ঘ্য এবং প্রস্থচ্ছেদ ক্ষেত্রফলের উপর ভিত্তি করে। দ্রষ্টব্য - রোধকতার জন্য `rhoValue` ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         R: "রোধ (রোধ Ω)",
         ρ: "রোধকতা (রোধকতা Ω·m)",
         L: "দৈর্ঘ্য (দৈর্ঘ্য m)",
         A: "প্রস্থচ্ছেদ ক্ষেত্রফল (ক্ষেত্রফল m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "বৈদ্যুতিক শক্তি",
      equation_text: "P = IV",
      summary: "বৈদ্যুতিক শক্তি সমীকরণ যাচাই করে (P = VI = I^2R = V^2/R)",
      description:
         "প্রদত্ত V, I, এবং R-এর জন্য বৈদ্যুতিক শক্তির জন্য তিনটি সাধারণ সমীকরণ সমতুল্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "বৈদ্যুতিক শক্তি (শক্তি W)",
         V: "ভোল্টেজ (ভোল্টেজ V)",
         I: "প্রবাহ (প্রবাহ A)",
         R: "রোধ (রোধ Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "ধারাবাহিক রোধ",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "ধারাবাহিক রোধের জন্য মোট রোধ গণনা করে (R_total = R1 + R2 + ...)",
      description: "ধারাবাহিকভাবে সংযুক্ত একাধিক রোধের জন্য মোট সমতুল্য রোধ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         R_total: "মোট রোধ (রোধ Ω)",
         R: "পৃথক রোধ (রোধ Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "সমান্তরাল রোধ",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "সমান্তরাল রোধের জন্য মোট রোধ গণনা করে (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "সমান্তরালে সংযুক্ত একাধিক রোধের জন্য মোট সমতুল্য রোধ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         R_total: "মোট রোধ (রোধ Ω)",
         R: "পৃথক রোধ (রোধ Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "ধারাবাহিক ক্যাপাসিটর",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "ধারাবাহিক ক্যাপাসিটরের জন্য মোট ক্যাপাসিট্যান্স গণনা করে (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "ধারাবাহিকভাবে সংযুক্ত একাধিক ক্যাপাসিটরের জন্য মোট সমতুল্য ক্যাপাসিট্যান্স গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C_total: "মোট ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         C: "পৃথক ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "সমান্তরাল ক্যাপাসিটর",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "সমান্তরাল ক্যাপাসিটরের জন্য মোট ক্যাপাসিট্যান্স গণনা করে (C_total = C1 + C2 + ...)",
      description: "সমান্তরালে সংযুক্ত একাধিক ক্যাপাসিটরের জন্য মোট সমতুল্য ক্যাপাসিট্যান্স গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         C_total: "মোট ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
         C: "পৃথক ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "চার্জে চৌম্বকীয় বল",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "চার্জযুক্ত কণা উপর চৌম্বকীয় বল গণনা করে (F = qvB sin(θ))",
      description: "চলমান চার্জযুক্ত কণার উপর প্রযুক্ত চৌম্বকীয় বলের মাত্রা গণনা করে। কোণ রেডিয়ানে হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F_B: "চৌম্বকীয় বলের মাত্রা (বল N)",
         q: "চার্জের মাত্রা (চার্জ C)",
         v: "বেগের মাত্রা (গতি m/s)",
         B: "চৌম্বকীয় ক্ষেত্রের মাত্রা (চৌম্বকীয় ক্ষেত্র T)",
         θ: "বেগ এবং চৌম্বকীয় ক্ষেত্রের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "প্রবাহে চৌম্বকীয় বল",
      equation_text: "F_B = ILBsin(θ)",
      summary: "প্রবাহ বহনকারী পরিবাহী উপর চৌম্বকীয় বল গণনা করে (F = I l B sin(θ))",
      description:
         "একটি চৌম্বকীয় ক্ষেত্রে স্রোত বহনকারী একটি সরল পরিবাহীর উপর প্রযুক্ত চৌম্বকীয় বলের মাত্রা গণনা করে। কোণ রেডিয়ানে হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F_B: "চৌম্বকীয় বলের মাত্রা (বল N)",
         I: "প্রবাহ (প্রবাহ A)",
         L: "পরিবাহীর দৈর্ঘ্য (দৈর্ঘ্য m)",
         B: "চৌম্বকীয় ক্ষেত্রের মাত্রা (চৌম্বকীয় ক্ষেত্র T)",
         θ: "প্রবাহ এবং চৌম্বকীয় ক্ষেত্রের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "বায়ো-সাভার্ট নিয়ম",
      equation_text: "B = μ₀I / (2πr) (অসীম সরল তার)",
      summary: "প্রবাহ উপাদান থেকে চৌম্বকীয় ক্ষেত্র গণনা করে (dB = (μ₀I ds) / (4πr^2))",
      description:
         "ব্যাসার্ধ ভেক্টরের লম্ব একটি ডিফারেনশিয়াল স্রোত উপাদান থেকে চৌম্বকীয় ক্ষেত্রে অবদানের মাত্রা গণনা করে। দ্রষ্টব্য - ফাংশন `(μ₀ * I * ds) / (4 * π * r^2)` বাস্তবায়ন করে, ডিফারেনশিয়াল ফর্মে প্রায়শই উপস্থিত sin(θ) পদ বাদ দেয়, কার্যকরভাবে θ=90 ডিগ্রি অনুমান করে বা শুধুমাত্র সেই নির্দিষ্ট প্লেনে ব্যাসার্ধ ভেক্টরের লম্ব উপাদান গণনা করে। প্রয়োগ করা সমীকরণ নথিভুক্ত করা হচ্ছে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         dB: "চৌম্বকীয় ক্ষেত্র অবদানের মাত্রা (চৌম্বকীয় ক্ষেত্র T)",
         μ0: "মুক্ত স্থানের পারমিবিলিটি (ধ্রুবক T·m/A)",
         I: "প্রবাহ (প্রবাহ A)",
         ds: "প্রবাহ উপাদানের ডিফারেনশিয়াল দৈর্ঘ্য (দৈর্ঘ্য m)",
         r: "প্রবাহ উপাদান থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "সোলেনয়েডের চৌম্বকীয় ক্ষেত্র",
      equation_text: "B = μ₀nI (ভিতরে, আদর্শ)",
      summary: "লম্বা সোলেনয়েডের ভিতরে চৌম্বকীয় ক্ষেত্র গণনা করে (B = μ₀nI)",
      description: "একটি দীর্ঘ আদর্শ সোলেনয়েডের ভিতরের চৌম্বকীয় ক্ষেত্রের মাত্রা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         B: "সোলেনয়েডের ভিতরে চৌম্বকীয় ক্ষেত্রের তীব্রতা (চৌম্বকীয় ক্ষেত্র T)",
         μ0: "মুক্ত স্থানের পারমিবিলিটি (ধ্রুবক T·m/A)",
         n: "একক দৈর্ঘ্য প্রতি পাক সংখ্যা (দৈর্ঘ্য প্রতি সংখ্যা m⁻¹)",
         I: "প্রবাহ (প্রবাহ A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "সরল তারের চৌম্বকীয় ক্ষেত্র",
      equation_text: "B = μ₀I / (2πr) (অসীম তার)",
      summary: "একটি অসীম সরল তার থেকে চৌম্বকীয় ক্ষেত্র গণনা করে (B = (μ₀I)/(2πr))",
      description:
         "কারেন্ট বহনকারী একটি দীর্ঘ, সরল পরিবাহী থেকে নির্দিষ্ট দূরত্বে চৌম্বকীয় ক্ষেত্রের মাত্রা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         B: "সরল তার থেকে চৌম্বকীয় ক্ষেত্রের তীব্রতা (চৌম্বকীয় ক্ষেত্র T)",
         μ0: "মুক্ত স্থানের পারমিবিলিটি (ধ্রুবক T·m/A)",
         I: "প্রবাহ (প্রবাহ A)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         r: "তার থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "সমান্তরাল তারের মধ্যে বল",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "সমান্তরাল তারের মধ্যে প্রতি ইউনিট দৈর্ঘ্য বল গণনা করে (F/L = (μ₀I₁I₂)/(2πd))",
      description: "স্রোত বহনকারী দুটি লম্বা, সমান্তরাল পরিবাহীর মধ্যে প্রতি ইউনিট দৈর্ঘ্যে বলের মাত্রা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         "F/L": "প্রতি ইউনিট দৈর্ঘ্যে বল (দৈর্ঘ্য প্রতি বল N/m)",
         μ0: "মুক্ত স্থানের পারমিবিলিটি (ধ্রুবক T·m/A)",
         I1: "তার 1-এ প্রবাহ (প্রবাহ A)",
         I2: "তার 2-এ প্রবাহ (প্রবাহ A)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         d: "তারের মধ্যে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "বৈদ্যুতিক ফ্লাক্স",
      equation_text: "Φ_E = EAcos(θ) (একই E)",
      summary: "বৈদ্যুতিক ফ্লাক্স গণনা করে (Φ_E = E * A * cos(θ))",
      description:
         "একটি অভিন্ন বৈদ্যুতিক ক্ষেত্রে একটি সমতল পৃষ্ঠের মধ্য দিয়ে বৈদ্যুতিক ফ্লাক্স গণনা করে। কোণটি অবশ্যই বৈদ্যুতিক ক্ষেত্র ভেক্টর এবং ক্ষেত্রফল ভেক্টরের মধ্যে, রেডিয়ানে হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Φ_E: "বৈদ্যুতিক ফ্লাক্স (বৈদ্যুতিক ফ্লাক্স N·m²/C)",
         E: "বৈদ্যুতিক ক্ষেত্রের মাত্রা (বৈদ্যুতিক ক্ষেত্র N/C)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         θ: "E এবং ক্ষেত্রফল ভেক্টরের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "চৌম্বক ফ্লাক্স",
      equation_text: "Φ_B = BAcos(θ) (একই B)",
      summary: "চৌম্বক ফ্লাক্স গণনা করে (Φ_B = B * A * cos(θ))",
      description:
         "একটি অভিন্ন চৌম্বক ক্ষেত্রে একটি সমতল পৃষ্ঠের মধ্য দিয়ে চৌম্বক ফ্লাক্স গণনা করে। কোণটি অবশ্যই চৌম্বক ক্ষেত্র ভেক্টর এবং ক্ষেত্রফল ভেক্টরের মধ্যে, রেডিয়ানে হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Φ_B: "চৌম্বক ফ্লাক্স (চৌম্বক ফ্লাক্স Wb)",
         B: "চৌম্বকীয় ক্ষেত্রের মাত্রা (চৌম্বকীয় ক্ষেত্র T)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         θ: "B এবং ক্ষেত্রফল ভেক্টরের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "গতিজনিত তড়িৎচালক বল (EMF)",
      equation_text: "ε = vBL (সরল পরিবাহী)",
      summary: "গতিজনিত EMF গণনা করে (emf = Blv)",
      description:
         "চৌম্বক ক্ষেত্রের লম্বভাবে চলমান একটি পরিবাহীতে উৎপন্ন তড়িৎচালক বল (EMF) এর মাত্রা গণনা করে। দ্রষ্টব্য - ফাংশনটি Blv মাত্রা গণনা করে, দিক নির্দেশনার জন্য কখনও কখনও ব্যবহৃত ঋণাত্মক চিহ্ন (লেন্জের সূত্র) বাদ দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ε: "গতিজনিত EMF মাত্রা (ভোল্টেজ V)",
         v: "পরিবাহীর বেগ (গতি m/s)",
         B: "চৌম্বকীয় ক্ষেত্রের মাত্রা (চৌম্বকীয় ক্ষেত্র T)",
         L: "পরিবাহীর দৈর্ঘ্য (দৈর্ঘ্য m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "আবিষ্ট EMF (ফ্যারাডে-র সূত্র)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "পরিবর্তনশীল ফ্লাক্স থেকে আবিষ্ট EMF গণনা করে (emf = -ΔΦ_B / Δt)",
      description: "ফ্যারাডে-র আবেশ সূত্র অনুযায়ী পরিবর্তিত চৌম্বকীয় ফ্লাক্স দ্বারা আবিষ্ট EMF গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ε: "আবিষ্ট EMF (ভোল্টেজ V)",
         ΔΦ_B: "চৌম্বকীয় ফ্লাক্সে পরিবর্তন (চৌম্বকীয় ফ্লাক্স Wb)",
         Δt: "সময়ে পরিবর্তন (সময় s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "আবেশ থেকে আবিষ্ট EMF",
      equation_text: "ε_L = -L dI / dt",
      summary: "একটি ইন্ডাক্টরে পরিবর্তিত প্রবাহ থেকে আবিষ্ট EMF গণনা করে (emf = -L * ΔI / Δt)",
      description:
         "পরিবর্তিত প্রবাহের কারণে একটি ইন্ডাক্টরে স্ব-আবিষ্ট EMF গণনা করে। দ্রষ্টব্য - ফাংশনের নাম `calculateInductance` কিন্তু এটি এই সমীকরণ ব্যবহার করে EMF ফেরত দেয়। যা ফেরত দেয় তা নথিভুক্ত করা হচ্ছে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ε_L: "ইন্ডাক্টরে আবিষ্ট EMF (ভোল্টেজ V)",
         L: "আবেশ (আবেশ H)",
         ΔI: "প্রবাহে পরিবর্তন (প্রবাহ A)",
         Δt: "সময়ে পরিবর্তন (সময় s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "ধারকত্বীয় রিঅ্যাকট্যান্স",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "ধারকত্বীয় রিঅ্যাকট্যান্স গণনা করে (X_C = 1/(2πfC))",
      description: "প্রত্যাবর্তনশীল প্রবাহের বিরুদ্ধে একটি ক্যাপাসিটরের প্রতিরোধের গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         X_C: "ধারকত্বীয় রিঅ্যাকট্যান্স (রিঅ্যাকট্যান্স Ω)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         C: "ক্যাপাসিট্যান্স (ক্যাপাসিট্যান্স F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "আবেশীয় রিঅ্যাকট্যান্স",
      equation_text: "X_L = 2πfL",
      summary: "আবেশীয় রিঅ্যাকট্যান্স গণনা করে (X_L = 2πfL))",
      description: "প্রত্যাবর্তনশীল প্রবাহের বিরুদ্ধে একটি ইন্ডাক্টরের প্রতিরোধের গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         X_L: "আবেশীয় রিঅ্যাকট্যান্স (রিঅ্যাকট্যান্স Ω)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         L: "আবেশ (আবেশ H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "ইম্পিড্যান্স",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "ইম্পিড্যান্স গণনা করে (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "রেজিস্ট্যান্স, আবেশীয় রিঅ্যাকট্যান্স এবং ধারকত্বীয় রিঅ্যাকট্যান্স ধারণকারী একটি AC সার্কিটে প্রবাহের বিরুদ্ধে মোট প্রতিরোধের গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Z: "ইম্পিড্যান্স (ইম্পিড্যান্স Ω)",
         R: "রোধ (রোধ Ω)",
         X_L: "আবেশীয় রিঅ্যাকট্যান্স (রিঅ্যাকট্যান্স Ω)",
         X_C: "ধারকত্বীয় রিঅ্যাকট্যান্স (রিঅ্যাকট্যান্স Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "ঘনত্ব",
      equation_text: "ρ = m / V",
      summary: "ঘনত্ব গণনা করে (ρ = m/V)",
      description: "ভর এবং আয়তনের উপর ভিত্তি করে ঘনত্ব গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ρ: "ঘনত্ব (ঘনত্ব kg/m³)",
         m: "ভর (ভর kg)",
         V: "আয়তন (আয়তন m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "চাপ",
      equation_text: "P = F / A",
      summary: "চাপ গণনা করে (P = F/A)",
      description: "একটি এলাকার উপর প্রয়োগ করা বলের উপর ভিত্তি করে চাপ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "চাপ (চাপ Pa)",
         F: "বল (বল N)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "তরলে চাপ",
      equation_text: "P = P₀ + ρgh",
      summary: "তরলে চাপ গণনা করে (P = P0 + ρgh)",
      description: "একটি তরলে নির্দিষ্ট গভীরতায় পরম চাপ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "পরম চাপ (চাপ Pa)",
         P0: "বায়ুমণ্ডলীয় বা পৃষ্ঠ চাপ (চাপ Pa)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
         h: "গভীরতা (দৈর্ঘ্য m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "প্লবতা",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "প্লবতা বল গণনা করে (F_b = ρgV_displaced)",
      description:
         "একটি তরল দ্বারা নিমজ্জিত বা আংশিকভাবে নিমজ্জিত বস্তুর উপর প্রযুক্ত প্লবতা বল (আর্কিমিডিসের নীতি) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F_B: "প্লবতা বল (বল N)",
         ρ_fluid: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         V_submerged: "নিমজ্জিত আয়তন (আয়তন m³)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "ভর প্রবাহ হার",
      equation_text: "ṁ = ρAv",
      summary: "ভর প্রবাহ হার গণনা করে (ṁ = Δm/Δt)",
      description: "প্রতি ইউনিট সময়ে একটি বিন্দু দিয়ে ভর প্রবাহের হার গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ṁ: "ভর প্রবাহ হার (ভর প্রবাহ হার kg/s)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         v: "তরল বেগ (গতি m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "আয়তন প্রবাহ হার",
      equation_text: "Q = Av",
      summary: "আয়তন প্রবাহ হার গণনা করে (Q = ΔV/Δt)",
      description: "প্রতি ইউনিট সময়ে একটি বিন্দু দিয়ে আয়তন প্রবাহের হার গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Q: "আয়তন প্রবাহ হার (আয়তন প্রবাহ হার m³/s)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         v: "তরল বেগ (গতি m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "বারনোলির সমীকরণ",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "বারনোলির সমীকরণ যাচাই করে (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "দুটি বিন্দুতে প্রদত্ত তরল বৈশিষ্ট্য এবং অবস্থার জন্য বারনোলির সমীকরণ সত্য কিনা তা যাচাই করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "চাপ (চাপ Pa)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         v: "তরল বেগ (গতি m/s)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
         y: "উচ্চতা (দৈর্ঘ্য m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "ডাইনামিক ভিসকোসিটি",
      equation_text: "τ = μ * (dv/dy)",
      summary: "ডাইনামিক ভিসকোসিটি গণনা করে (η = F * Δy / (A * Δvx))",
      description:
         "বল, বেগের ঢাল এবং ক্ষেত্রফলের উপর ভিত্তি করে ডাইনামিক ভিসকোসিটি গণনা করে। এই সমীকরণটি শিয়ার স্ট্রেস/স্ট্রেন রেট থেকে উদ্ভূত হয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         μ: "ডাইনামিক ভিসকোসিটি (ডাইনামিক ভিসকোসিটি Pa·s)",
         F: "বল (বল N)",
         Δy: "প্রবাহের লম্ব দূরত্ব (দৈর্ঘ্য m)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         Δvx: "বেগের পরিবর্তন (গতি m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "কিনেমেটিক ভিসকোসিটি",
      equation_text: "ν = μ / ρ",
      summary: "কিনেমেটিক ভিসকোসিটি গণনা করে (ν = η / ρ)",
      description: "ডাইনামিক ভিসকোসিটি এবং ঘনত্ব থেকে কিনেমেটিক ভিসকোসিটি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ν: "কিনেমেটিক ভিসকোসিটি (কিনেমেটিক ভিসকোসিটি m²/s)",
         μ: "ডাইনামিক ভিসকোসিটি (ডাইনামিক ভিসকোসিটি Pa·s)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "টান বল",
      equation_text: "F_D = ½ρv²CdA",
      summary: "টান বল গণনা করে (F_d = 0.5 * ρ * C_A * v^2)",
      description: "একটি তরলের মধ্য দিয়ে চলমান বস্তুর উপর টান বল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F_D: "টান বল (বল N)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         v: "বেগ (গতি m/s)",
         Cd: "টান সহগ (মাত্রাহীন)",
         A: "রেফারেন্স ক্ষেত্রফল (ক্ষেত্রফল m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "ম্যাক সংখ্যা",
      equation_text: "M = v / c_sound",
      summary: "ম্যাক সংখ্যা গণনা করে (M = v/c)",
      description: "ম্যাক সংখ্যা গণনা করে, যা একটি বস্তুর বেগের সাথে মাধ্যমে শব্দের বেগের অনুপাত।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         M: "ম্যাক সংখ্যা (মাত্রাহীন)",
         v: "বস্তুর বেগ (গতি m/s)",
         c_sound: "মাধ্যমে শব্দের বেগ (গতি m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "রেনল্ডস সংখ্যা",
      equation_text: "Re = ρvd / μ",
      summary: "রেনল্ডস সংখ্যা গণনা করে (Re = (ρ * v * D) / η)",
      description:
         "বিভিন্ন তরল প্রবাহ পরিস্থিতিতে প্রবাহের ধরণ অনুমান করার জন্য ব্যবহৃত একটি মাত্রাহীন পরিমাণ, রেনল্ডস সংখ্যা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Re: "রেনল্ডস সংখ্যা (মাত্রাহীন)",
         ρ: "তরল ঘনত্ব (ঘনত্ব kg/m³)",
         v: "বেগ (গতি m/s)",
         d: "বৈশিষ্ট্যগত দৈর্ঘ্য (দৈর্ঘ্য m)",
         μ: "ডাইনামিক ভিসকোসিটি (ডাইনামিক ভিসকোসিটি Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "ফ্রুড সংখ্যা",
      equation_text: "Fr = v / √(gL)",
      summary: "ফ্রুড সংখ্যা গণনা করে (Fr = v / √(g * l))",
      description:
         "তরল গতিতে মাধ্যাকর্ষণের প্রভাব নির্দেশ করার জন্য ব্যবহৃত একটি মাত্রাহীন পরিমাণ, ফ্রুড সংখ্যা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Fr: "ফ্রুড সংখ্যা (মাত্রাহীন)",
         v: "বেগ (গতি m/s)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
         L: "বৈশিষ্ট্যগত দৈর্ঘ্য (দৈর্ঘ্য m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "পৃষ্ঠটান",
      equation_text: "γ = F / L",
      summary: "পৃষ্ঠটান গণনা করে (γ = F / l)",
      description: "বল এবং দৈর্ঘ্যের উপর ভিত্তি করে একটি তরলের পৃষ্ঠটান গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         γ: "পৃষ্ঠটান (পৃষ্ঠটান N/m)",
         F: "বল (বল N)",
         L: "দৈর্ঘ্য (দৈর্ঘ্য m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "মহাবিশ্বীয় আকর্ষণ (বল)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "মহাকর্ষ বল গণনা করে (F = -Gm1m2/r^2)",
      description:
         "দুইটি বিন্দু ভরের মধ্যে আকর্ষণীয় মহাকর্ষ বল গণনা করে। দ্রষ্টব্য - আকর্ষণ নির্দেশক ঋণাত্মক মান ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F: "মহাকর্ষ বল (বল N)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         m1: "ভর 1 (ভর kg)",
         m2: "ভর 2 (ভর kg)",
         r: "ভরগুলির মধ্যে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "মহাকর্ষীয় ক্ষেত্র",
      equation_text: "g = GM / r² (মাত্রা)",
      summary: "মহাকর্ষীয় ক্ষেত্র গণনা করে (g = -Gm/r^2)",
      description:
         "একটি বিন্দু ভর থেকে একটি দূরত্বে মহাকর্ষীয় ক্ষেত্রের তীব্রতা গণনা করে। দ্রষ্টব্য - ভরের দিকে দিক নির্দেশক ঋণাত্মক মান ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         g: "মহাকর্ষীয় ক্ষেত্র তীব্রতার মাত্রা (মহাকর্ষীয় ক্ষেত্র N/kg)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         M: "উৎস ভর (ভর kg)",
         r: "উৎস ভর থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "মহাকর্ষীয় পটেনশিয়াল শক্তি",
      equation_text: "U_g = -G m₁m₂ / r (সাধারণ)",
      summary: "দুটি ভরের মধ্যে মহাকর্ষীয় পটেনশিয়াল শক্তি গণনা করে (PE = -Gm1m2/r)",
      description: "দুইটি বিন্দু ভরের সিস্টেমের মহাকর্ষীয় পটেনশিয়াল শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         U_g: "মহাকর্ষীয় পটেনশিয়াল শক্তি (শক্তি J)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         m1: "ভর 1 (ভর kg)",
         m2: "ভর 2 (ভর kg)",
         r: "ভরগুলির মধ্যে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "মহাকর্ষীয় পটেনশিয়াল",
      equation_text: "V_g = -GM / r",
      summary: "মহাকর্ষীয় পটেনশিয়াল গণনা করে (V_g = -Gm/r)",
      description: "একটি বিন্দু ভর থেকে একটি দূরত্বে মহাকর্ষীয় পটেনশিয়াল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         V_g: "মহাকর্ষীয় পটেনশিয়াল (মহাকর্ষীয় পটেনশিয়াল J/kg)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         M: "উৎস ভর (ভর kg)",
         r: "উৎস ভর থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "কক্ষপথের বেগ",
      equation_text: "v_orbit = √(GM / r) (বৃত্তাকার)",
      summary: "কক্ষপথের বেগ গণনা করে (v = sqrt(Gm/r))",
      description: "বৃহত্তর ভরের চারপাশে একটি বৃত্তাকার কক্ষপথে একটি বস্তুর বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_orbit: "কক্ষপথের বেগ (গতি m/s)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         M: "কেন্দ্রীয় বস্তুর ভর (ভর kg)",
         r: "কক্ষপথের ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "পলায়ন বেগ",
      equation_text: "v_escape = √(2GM / r)",
      summary: "পলায়ন বেগ গণনা করে (v = sqrt(2Gm/r))",
      description:
         "একটি নির্দিষ্ট দূরত্ব থেকে একটি ভরের মহাকর্ষীয় আকর্ষণ থেকে মুক্তি পেতে প্রয়োজনীয় ন্যূনতম বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_escape: "পলায়ন বেগ (গতি m/s)",
         G: "মহাকর্ষ ধ্রুবক (ধ্রুবক N·m²/kg²)",
         M: "কেন্দ্রীয় বস্তুর ভর (ভর kg)",
         r: "কেন্দ্র থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "তাপ সঞ্চালন",
      equation_text: "Q/t = kAΔT/d",
      summary: "তাপ সঞ্চালন হার গণনা করে (Q/t = (kAΔT) / L)",
      description:
         "একটি পদার্থের মাধ্যমে পরিবহন দ্বারা তাপ স্থানান্তরের হার গণনা করে। দ্রষ্টব্য - ফাংশনটি Q গণনা করে, এই অনুমান করে যে হার এর জন্য সমীকরণের স্বাভাবিক ব্যবহারের মাধ্যমে একটি সময় ব্যবধান বোঝানো হয়েছে। ডকুমেন্টেশন Q উল্লেখ করে, কিন্তু সমীকরণটি সাধারণত Q/t এর জন্য। এই পার্থক্যটি স্পষ্ট করা হচ্ছে। ফাংশনটি হারের সমীকরণের ডান পাশের ফলাফল প্রদান করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         "Q/t": "তাপ স্থানান্তর হার (শক্তি W)",
         k: "তাপ পরিবাহিতা (তাপ পরিবাহিতা W/(m·K))",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         ΔT: "তাপমাত্রার পার্থক্য (তাপমাত্রার পার্থক্য K)",
         d: "পুরুত্ব (দৈর্ঘ্য m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "স্টিফেন-বোল্টজম্যানের নিয়ম",
      equation_text: "P = εσAT⁴",
      summary: "তাপীয় বিকিরণ শক্তি গণনা করে (P = εσA(T^4 - T0^4))",
      description: "তার পরিবেশ বিবেচনা করে একটি বস্তু দ্বারা বিকিরিত শক্তির নেট হার গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "নেট বিকিরিত শক্তি (শক্তি W)",
         ε: "নিঃসরণশীলতা (মাত্রাহীন)",
         σ: "স্টিফেন-বোল্টজম্যানের ধ্রুবক (ধ্রুবক W/(m²·K⁴))",
         A: "পৃষ্ঠের ক্ষেত্রফল (ক্ষেত্রফল m²)",
         T: "বস্তুর তাপমাত্রা (তাপমাত্রা K)",
         T0: "পারিপার্শ্বিক তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "ভীনের সরণ সূত্র (সর্বোচ্চ তরঙ্গদৈর্ঘ্য)",
      equation_text: "λ_max = b/T",
      summary: "ভীনের সূত্র (λ_max = b/T) ব্যবহার করে শিখর তরঙ্গদৈর্ঘ্য গণনা করে",
      description: "কৃষ্ণবস্তুর নিঃসরণ বর্ণালীর সর্বোচ্চ যেখানে হয় সেই তরঙ্গদৈর্ঘ্য গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         λ_max: "শিখর নিঃসরণের তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
         b: "ভীনের সরণ ধ্রুবক (ধ্রুবক m·K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "ভীনের সরণ সূত্র (সর্বোচ্চ ফ্রিকোয়েন্সি)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "ভীনের সূত্র (f_max = b' * T) ব্যবহার করে শিখর ফ্রিকোয়েন্সি গণনা করে",
      description:
         "কৃষ্ণবস্তুর নিঃসরণ বর্ণালীর সর্বোচ্চ যেখানে হয় সেই ফ্রিকোয়েন্সি গণনা করে। দ্রষ্টব্য - এই সংস্করণটি একটি পরিবর্তিত ভীন ধ্রুবক b' ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f_max: "শিখর নিঃসরণের ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         "b'": "পরিবর্তিত ভীন ধ্রুবক (ধ্রুবক Hz/K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "সমীকরণ তথ্য (নির্দিষ্ট)",
      equation_text: "প্রযোজ্য নয় (তথ্য পুনরুদ্ধার করে, গণনা করে না)",
      summary: "আইডি এবং ভাষা দ্বারা সমীকরণ তথ্য পান",
      description:
         "তার অনন্য আইডি এবং কাঙ্ক্ষিত ভাষার উপর ভিত্তি করে একটি নির্দিষ্ট সমীকরণের জন্য বিবরণ পুনরুদ্ধার করে। দ্রষ্টব্য - ভাষা 'language_code' পাথ প্যারামিটার থেকে নিষ্কাশিত হয়। কোড স্নিপেটে দেখানো অভ্যন্তরীণ যুক্তি 'lang' ক্যোয়ারী প্যারামিটারকেও দেখে, তবে এই সোয়াগার সংজ্ঞা প্রাথমিক পাথ প্যারামিটারগুলিকে ডকুমেন্ট করে।",
      language_code: "bn",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "API-এর সকল সমীকরণ এন্ডপয়েন্ট পান।",
      description: "API-এর সকল এন্ডপয়েন্ট সম্পর্কে সংক্ষিপ্ত তথ্য পুনরুদ্ধার করে।",
      language_code: "bn",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "বেগ",
      equation_text: "v = Δx / Δt",
      summary: "বেগ গণনা করে",
      description: "সরণ এবং সময়ের উপর ভিত্তি করে বেগ গণনা করে (v = Δs / Δt)।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v: "বেগ (গতি m/s)",
         Δx: "সরণ (দৈর্ঘ্য m)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "ত্বরণ",
      equation_text: "a = Δv / Δt",
      summary: "ত্বরণ গণনা করে",
      description: "বেগের পরিবর্তন এবং সময়ের উপর ভিত্তি করে ত্বরণ গণনা করে (a = Δv / Δt)।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         a: "ত্বরণ (ত্বরণ m/s²)",
         Δv: "বেগের পরিবর্তন (গতি m/s)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "গতিবিদ্যার সমীকরণ (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "চূড়ান্ত বেগ গণনা করে (v = v0 + at)",
      description: "প্রথম গতিবিদ্যার সমীকরণ ব্যবহার করে চূড়ান্ত বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v: "চূড়ান্ত বেগ (গতি m/s)",
         v0: "প্রাথমিক বেগ (গতি m/s)",
         a: "ত্বরণ (ত্বরণ m/s²)",
         t: "সময় (সময় s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "গতিবিদ্যার সমীকরণ (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "চূড়ান্ত অবস্থান গণনা করে (s = s0 + v0t + 0.5at^2)",
      description: "দ্বিতীয় গতিবিদ্যার সমীকরণ ব্যবহার করে চূড়ান্ত অবস্থান গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         s: "চূড়ান্ত অবস্থান (দৈর্ঘ্য m)",
         s0: "প্রাথমিক অবস্থান (দৈর্ঘ্য m)",
         v0: "প্রাথমিক বেগ (গতি m/s)",
         t: "সময় (সময় s)",
         a: "ত্বরণ (ত্বরণ m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "গতিবিদ্যার সমীকরণ (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "চূড়ান্ত বেগের বর্গ গণনা করে (v^2 = v0^2 + 2a(s - s0))",
      description:
         "তৃতীয় গতিবিদ্যার সমীকরণ ব্যবহার করে চূড়ান্ত বেগের বর্গ গণনা করে। দ্রষ্টব্য - v নয়, v^2 ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v: "চূড়ান্ত বেগ (গতি m/s)",
         v0: "প্রাথমিক বেগ (গতি m/s)",
         a: "ত্বরণ (ত্বরণ m/s²)",
         Δs: "সরণ (দৈর্ঘ্য m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "গড় বেগ",
      equation_text: "v_avg = Δx / Δt",
      summary: "গড় বেগ গণনা করে (v_avg = 0.5 * (v + v0))",
      description: "ধ্রুবক ত্বরণ ধরে নিয়ে গড় বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_avg: "গড় বেগ (গতি m/s)",
         v: "চূড়ান্ত বেগ (গতি m/s)",
         v0: "প্রাথমিক বেগ (গতি m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "বল (নিউটন এর দ্বিতীয় নিয়ম)",
      equation_text: "F_net = ma",
      summary: "বল গণনা করে (F = ma)",
      description: "নিউটন এর দ্বিতীয় নিয়ম ব্যবহার করে বল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F_net: "নেট বল (বল N)",
         m: "ভর (ভর kg)",
         a: "ত্বরণ (ত্বরণ m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "ওজন",
      equation_text: "W = mg",
      summary: "ওজন গণনা করে (W = mg)",
      description: "একটি বস্তুর উপর মাধ্যাকর্ষণ শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         W: "ওজন (বল N)",
         m: "ভর (ভর kg)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "সর্বাধিক স্থির ঘর্ষণ",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "সর্বাধিক স্থির ঘর্ষণ গণনা করে (F_s = μ_s * N)",
      description: "সম্ভব সর্বাধিক স্থির ঘর্ষণ বল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f_s_max: "সর্বাধিক স্থির ঘর্ষণ বল (বল N)",
         μ_s: "স্থির ঘর্ষণের সহগ (মাত্রাহীন)",
         F_N: "প্রয়াসী বল (বল N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "গতিশীল ঘর্ষণ",
      equation_text: "f_k = μ_k * F_N",
      summary: "গতিশীল ঘর্ষণ গণনা করে (F_k = μ_k * N)",
      description: "গতিশীল বস্তুর উপর কাজ করে গতিশীল ঘর্ষণ বল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f_k: "গতিশীল ঘর্ষণ বল (বল N)",
         μ_k: "গতিশীল ঘর্ষণের সহগ (মাত্রাহীন)",
         F_N: "প্রয়াসী বল (বল N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "ভরবেগ",
      equation_text: "p = mv",
      summary: "ভরবেগ গণনা করে (p = mv)",
      description: "একটি বস্তুর রৈখিক ভরবেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         p: "ভরবেগ (ভরবেগ kg·m/s)",
         m: "ভর (ভর kg)",
         v: "বেগ (গতি m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "ঘাত",
      equation_text: "J = F_avg * Δt",
      summary: "ঘাত গণনা করে (J = F * Δt)",
      description: "বল এবং সময় ব্যবধান থেকে ঘাত গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         J: "ঘাত (ঘাত N·s)",
         F_avg: "গড় বল (বল N)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "ঘাত-ভরবেগ উপপাদ্য",
      equation_text: "J = Δp",
      summary: "ঘাত-ভরবেগ উপপাদ্য যাচাই করে (F * Δt = m * Δv)",
      description: "প্রদত্ত মানগুলির জন্য ঘাত ভরবেগের পরিবর্তনের সমান কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         J: "ঘাত (ঘাত N·s)",
         Δp: "ভরবেগের পরিবর্তন (ভরবেগ kg·m/s)",
         F: "বল (বল N)",
         Δt: "সময় ব্যবধান (সময় s)",
         m: "ভর (ভর kg)",
         Δv: "বেগের পরিবর্তন (গতি m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "তেজস্ক্রিয় কার্যকলাপ",
      equation_text: "A = λN",
      summary: "তেজস্ক্রিয় ক্ষয়তে গড় কার্যকলাপ গণনা করে (A_avg = ΔN/Δt)",
      description:
         "একটি সময় ব্যবধানে একটি তেজস্ক্রিয় নমুনার গড় কার্যকলাপ (ক্ষয় হার) গণনা করে। দ্রষ্টব্য - ফাংশনটি ΔN নিউক্লিয়াসের সংখ্যার জন্য `nValue` এবং Δt সময়ের জন্য `tValue` ব্যবহার করে। এটি Δt এর উপর একটি সরলীকৃত গড়, তাৎক্ষণিক কার্যকলাপ হল dN/dt = -λN।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         A_avg: "গড় তেজস্ক্রিয় কার্যকলাপ (কার্যকলাপ Bq)",
         ΔN: "ক্ষয়ের সংখ্যা (মাত্রাহীন সংখ্যা)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "অর্ধায়ু",
      equation_text: "T_½ = ln(2) / λ",
      summary: "ক্ষয়ের পর অবশিষ্ট পরিমাণ গণনা করে (N = N0 * (1/2)^(t/T_half))",
      description:
         "একটি পদার্থের নির্দিষ্ট সময়ের পরে অবশিষ্ট পরিমাণ গণনা করে যা তার অর্ধায়ুর উপর ভিত্তি করে। দ্রষ্টব্য - সময় এর জন্য `tValue` এবং অর্ধায়ু এর জন্য `Thalf` ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         N: "অবশিষ্ট পরিমাণ/নিউক্লিয়াস (সংখ্যা)",
         N0: "প্রাথমিক পরিমাণ/নিউক্লিয়াস (সংখ্যা)",
         t: "অতীত সময় (সময় s)",
         T_half: "অর্ধায়ু (সময় s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "শোষিত বিকিরণ ডোজ",
      equation_text: "D = dE / dm",
      summary: "শোষিত বিকিরণ ডোজ গণনা করে (D = E/m)",
      description:
         "একটি ভর দ্বারা শোষিত শক্তির উপর ভিত্তি করে বিকিরণের শোষিত ডোজ গণনা করে। দ্রষ্টব্য - শক্তির জন্য `EValue` এবং ভরের জন্য `mValue` ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         D: "শোষিত ডোজ (শোষিত ডোজ Gy)",
         E: "শোষিত শক্তি (শক্তি J)",
         m: "ভর (ভর kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "সমতুল্য বিকিরণ ডোজ",
      equation_text: "H = D * W_R",
      summary: "সমতুল্য বিকিরণ ডোজ গণনা করে (H = wR * D)",
      description:
         "বিভিন্ন ধরণের বিকিরণের জৈবিক কার্যকারিতা বিবেচনা করে সমতুল্য ডোজ গণনা করে। দ্রষ্টব্য - শোষিত ডোজের জন্য `DValue` ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         H: "সমতুল্য ডোজ (সমতুল্য ডোজ Sv)",
         D: "শোষিত ডোজ (শোষিত ডোজ Gy)",
         W_R: "বিকিরণ ওজন ফ্যাক্টর (মাত্রাহীন)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "কার্যকরী বিকিরণ ডোজ",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "কার্যকরী বিকিরণ ডোজ গণনা করে (E = wT * H)",
      description:
         "বিভিন্ন টিস্যু/অঙ্গের বিকিরণ সংবেদনশীলতা বিবেচনা করে কার্যকরী ডোজ গণনা করে। দ্রষ্টব্য - সমতুল্য ডোজের জন্য `HValue` ব্যবহার করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "কার্যকরী ডোজ (কার্যকরী ডোজ Sv)",
         H_T: "টিস্যু/অর্গান T এর জন্য সমতুল্য ডোজ (সমতুল্য ডোজ Sv)",
         W_T: "টিস্যু/অর্গান T এর জন্য টিস্যু ওজন ফ্যাক্টর (মাত্রাহীন)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "চেরেনকভ কোণ",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "চেরেনকভ কোণ গণনা করে (θ_C = arccos(c/nv_p))",
      description:
         "একটি মাধ্যমে আলোর বেগের চেয়ে দ্রুত চলমান একটি চার্জযুক্ত কণা দ্বারা গঠিত চেরেনকভ শঙ্কুর কোণ গণনা করে। কোণ রেডিয়ানে ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         θ_C: "চেরেনকভ কোণ (কোণ rad)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
         n: "মাধ্যমের প্রতিসরাঙ্ক (মাত্রাহীন)",
         v: "কণা বেগ (গতি m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "ব্যতিচার ফ্রিঞ্জ (যেমন, অবস্থান, ফাঁক)",
      equation_text: "Δy = λL / d (দ্বৈত ফাটল ব্যবধান)",
      summary: "ব্যতিচার ফ্রিঞ্জগুলির অবস্থান গণনা করে (y_n = (nλL)/d)",
      description: "ইয়ং এর দ্বৈত-ফাটল ব্যতিচার প্যাটার্নে n-তম উজ্জ্বল ফ্রিঞ্জের অবস্থান গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         y_n: "n-তম উজ্জ্বল ফ্রিঞ্জের অবস্থান (দৈর্ঘ্য m)",
         n: "ফ্রিঞ্জ ক্রম (মাত্রাহীন পূর্ণসংখ্যা)",
         λ: "তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
         L: "পর্দায় দূরত্ব (দৈর্ঘ্য m)",
         d: "ফাটলের বিচ্ছেদ (দৈর্ঘ্য m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "প্রতিসরাঙ্ক",
      equation_text: "n = c / v",
      summary: "প্রতিসরাঙ্ক গণনা করে (n = c/v)",
      description: "শূন্যস্থান এবং মাধ্যমে আলোর বেগের উপর ভিত্তি করে একটি মাধ্যমের প্রতিসরাঙ্ক গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         n: "প্রতিসরাঙ্ক (মাত্রাহীন)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
         v: "মাধ্যমে আলোর বেগ (গতি m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "স্নেলের নিয়ম",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "স্নেলের নিয়ম যাচাই করে (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "প্রদত্ত প্রতিসরাঙ্ক এবং কোণগুলির সাথে দুটি মাধ্যমের মধ্যে আলো যাওয়ার জন্য স্নেলের নিয়ম প্রযোজ্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। কোণগুলি রেডিয়ানে হতে হবে। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         n1: "মাঝার 1 এর প্রতিসরাঙ্ক (মাত্রাহীন)",
         θ1: "মাঝার 1 এ কোণ (কোণ rad)",
         n2: "মাঝার 2 এর প্রতিসরাঙ্ক (মাত্রাহীন)",
         θ2: "মাঝার 2 এ কোণ (কোণ rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "ক্রান্তিক কোণ",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "ক্রান্তিক কোণ গণনা করে (θ_c = arcsin(n2/n1))",
      description:
         "যখন আলো n1 সূচক সহ একটি মাধ্যম থেকে n2 সূচক সহ একটি মাধ্যমে যায় (n1 > n2), তখন পূর্ণ অভ্যন্তরীণ প্রতিফলনের জন্য সংকট কোণ গণনা করে। কোণ রেডিয়ানে ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         θ_c: "ক্রান্তিক কোণ (কোণ rad)",
         n1: "মাঝার 1 এর প্রতিসরাঙ্ক (মাত্রাহীন)",
         n2: "মাঝার 2 এর প্রতিসরাঙ্ক (মাত্রাহীন)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "ছবির অবস্থান (আলোকবিজ্ঞান)",
      equation_text: "1/f = 1/d_o + 1/d_i (পাতলা লেন্স/আয়না)",
      summary: "পাতলা লেন্স/আয়না সমীকরণ যাচাই করে (1/f = 1/do + 1/di)",
      description:
         "ফোকাল দৈর্ঘ্য, বস্তুর দূরত্ব এবং ছবির দূরত্বের মধ্যে সম্পর্ক সত্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f: "ফোকাল দৈর্ঘ্য (দৈর্ঘ্য m)",
         d_o: "বস্তুর দূরত্ব (দৈর্ঘ্য m)",
         d_i: "ছবির দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "ছবির আকার (ম্যাগনিফিকেশন - আলোকবিজ্ঞান)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "ম্যাগনিফিকেশন সমীকরণ যাচাই করে (h'/h = di/do) (ফাংশন h'/h = di/do ব্যবহার করে)",
      description:
         "বস্তু/ছবির উচ্চতা এবং দূরত্বের মধ্যে সম্পর্ক সত্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে। ফাংশনটি স্বাক্ষরিত ম্যাগনিফিকেশন সমীকরণের পরিবর্তে `h'/h = di/do` ম্যাগনিটিউড সম্পর্ক ব্যবহার করে। ফাংশন বাস্তবায়নের উপর ভিত্তি করে নথিভুক্ত করা হচ্ছে। বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         M: "ম্যাগনিফিকেশন (মাত্রাহীন)",
         h_i: "ছবির উচ্চতা (দৈর্ঘ্য m)",
         h_o: "বস্তুর উচ্চতা (দৈর্ঘ্য m)",
         d_i: "ছবির দূরত্ব (দৈর্ঘ্য m)",
         d_o: "বস্তুর দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "গোলীয় দর্পণ সমীকরণ",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "একটি গোলীয় দর্পণের ফোকাল দৈর্ঘ্য গণনা করে (f = r/2)",
      description: "একটি গোলীয় দর্পণের বক্রতা ব্যাসার্ধের উপর ভিত্তি করে তার ফোকাল দৈর্ঘ্য গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f: "ফোকাল দৈর্ঘ্য (দৈর্ঘ্য m)",
         r: "বক্রতা ব্যাসার্ধ (দৈর্ঘ্য m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "স্প্রিং পটেনশিয়াল শক্তি",
      equation_text: "U_s = ½kx²",
      summary: "স্প্রিং-এ পটেনশিয়াল শক্তি গণনা করে (PE = 0.5 * k * Δx^2)",
      description: "একটি আদর্শ স্প্রিং-এ সঞ্চিত স্থিতিস্থাপক পটেনশিয়াল শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         U_s: "স্প্রিং পটেনশিয়াল শক্তি (শক্তি J)",
         k: "স্প্রিং কনস্ট্যান্ট (স্প্রিং কনস্ট্যান্ট N/m)",
         x: "সাম্য অবস্থা থেকে সরণ (দৈর্ঘ্য m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "সরল হারমোনিক অসিলেটর (SHO) পিরিয়ড",
      equation_text: "T = 2π√(m/k)",
      summary: "একটি স্প্রিং-মাস SHO এর পিরিয়ড গণনা করে (T = 2π√(m/k))",
      description: "একটি স্প্রিংয়ে ভরের সমন্বয়ে গঠিত একটি সরল হারমোনিক অসিলেটরের কম্পনের সময়কাল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         T: "পিরিয়ড (সময় s)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         m: "ভর (ভর kg)",
         k: "স্প্রিং কনস্ট্যান্ট (স্প্রিং কনস্ট্যান্ট N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "সাধারণ দোলকের পিরিয়ড",
      equation_text: "T = 2π√(L/g)",
      summary: "একটি সাধারণ দোলকের পিরিয়ড গণনা করে (T = 2π√(l/g))",
      description: "ছোট কোণে একটি সাধারণ দোলকের কম্পনের সময়কাল গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         T: "পিরিয়ড (সময় s)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         L: "দোলকের দৈর্ঘ্য (দৈর্ঘ্য m)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "ফ্রিকোয়েন্সি",
      equation_text: "f = 1 / T",
      summary: "ফ্রিকোয়েন্সি গণনা করে (f = 1/T)",
      description: "কম্পনের পর্যায় থেকে ফ্রিকোয়েন্সি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         T: "পিরিয়ড (সময় s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "কোণীয় ফ্রিকোয়েন্সি",
      equation_text: "ω = 2πf",
      summary: "কোণীয় ফ্রিকোয়েন্সি গণনা করে (ω = 2πf)",
      description: "ফ্রিকোয়েন্সি থেকে কোণীয় ফ্রিকোয়েন্সি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ω: "কোণীয় ফ্রিকোয়েন্সি (কোণীয় বেগ rad/s)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "লরেন্টজ ফ্যাক্টর",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "লরেন্টজ ফ্যাক্টর (γ) গণনা করে",
      description: "γ = 1/√(1 - (v²/c²)) ব্যবহার করে লরেন্টজ ফ্যাক্টর গণনা করে। v < c হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         γ: "লরেন্টজ ফ্যাক্টর (মাত্রাহীন)",
         v: "বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "সময় প্রসারণ",
      equation_text: "Δt' = γ * Δt₀",
      summary: "সময় প্রসারণ গণনা করে (t' = γ * t₀)",
      description:
         "একটি জড়ত্বীয় ফ্রেম S-এ একজন পর্যবেক্ষকের জন্য অতিবাহিত সময় (t') গণনা করে, যখন একটি চলন্ত ফ্রেম S'-এ পরিমাপ করা উপযুক্ত সময় (t₀) এবং S ও S'-এর মধ্যে আপেক্ষিক বেগ (v) দেওয়া থাকে। এটি t' = t₀ / √(1 - (v²/c²)) সমীকরণ ব্যবহার করে। t₀ ≥ 0 এবং |v| ≤ c হতে হবে। t'-এর একক t₀-এর মতো হবে, এবং v ও c-এর একক সুসংগত হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Δt: "প্রসারিত সময় (সময় s)",
         Δt0: "উপযুক্ত সময় (সময় s)",
         v: "আপেক্ষিক বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "দৈর্ঘ্য সংকোচন",
      equation_text: "L' = L₀ / γ",
      summary: "দৈর্ঘ্য সংকোচন গণনা করে (L' = L₀ / γ)",
      description:
         "একটি গতিশীল ফ্রেম S' থেকে পর্যবেক্ষণ করা বস্তুর দৈর্ঘ্য (L') গণনা করে, যখন তার বিশ্রাম ফ্রেম S-এ পরিমাপ করা তার উপযুক্ত দৈর্ঘ্য (L₀) এবং S ও S'-এর মধ্যে আপেক্ষিক বেগ (v) দেওয়া থাকে। এটি L' = L₀ * √(1 - (v²/c²)) সমীকরণ ব্যবহার করে। L₀ ≥ 0 এবং |v| ≤ c হতে হবে। L'-এর একক L₀-এর মতো হবে, এবং v ও c-এর একক সুসংগত হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         L: "সংকুচিত দৈর্ঘ্য (দৈর্ঘ্য m)",
         L0: "উপযুক্ত দৈর্ঘ্য (দৈর্ঘ্য m)",
         v: "আপেক্ষিক বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "আপেক্ষিক বেগ সংযোজন",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "আপেক্ষিক বেগ সংযোজন গণনা করে",
      description:
         "একটি বস্তুটির বেগ (u') গণনা করে যা একটি ফ্রেম S'-এর সাপেক্ষে, যখন তার বেগ (u) একটি ফ্রেম S-এর সাপেক্ষে এবং ফ্রেম S-এর বেগ (v) ফ্রেম S'-এর সাপেক্ষে জানা থাকে। এটি u' = (u + v) / (1 + uv/c²) সমীকরণ ব্যবহার করে। একই সরলরেখায় গতি অনুমান করে। c ≠ 0 হতে হবে। u, v, এবং c-এর এককগুলি সুসংগত হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         u: "ফ্রেম S-এ বস্তুর বেগ (গতি m/s)",
         v: "S'-এর সাপেক্ষে ফ্রেম S-এর বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
         "u'": "S'-এর সাপেক্ষে বস্তুর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "আপেক্ষিক মোট শক্তি",
      equation_text: "E = γmc²",
      summary: "আপেক্ষিক মোট শক্তি (E) গণনা করে",
      description:
         "বিশ্রাম ভর (m) এবং বেগ (v) সহ একটি কণার মোট আপেক্ষিক শক্তি গণনা করে। এটি E = γmc² = mc² / √(1 - (v²/c²)) সমীকরণ ব্যবহার করে। মূলত বিশ্রাম ভর (m > 0) সহ কণাগুলির জন্য। m ≥ 0 এবং |v| ≤ c হতে হবে। m, v, এবং c-এর এককগুলি উপযুক্ত এককে শক্তি পেতে সুসংগত হতে হবে (যেমন, m কেজি-তে, v/c m/s-এ E জুল-এ দেয়)।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "মোট আপেক্ষিক শক্তি (শক্তি J)",
         m: "বিশ্রাম ভর (ভর kg)",
         v: "বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "আপেক্ষিক ভরবেগ",
      equation_text: "p = γmv",
      summary: "আপেক্ষিক ভরবেগ (p = γmv) গণনা করে",
      description:
         "বিশ্রাম ভর (m) এবং বেগ (v) সহ একটি কণার আপেক্ষিক ভরবেগ গণনা করে। এটি p = γmv = mv / √(1 - (v²/c²)) সমীকরণ ব্যবহার করে। মূলত বিশ্রাম ভর (m > 0) সহ কণাগুলির জন্য। m ≥ 0 এবং |v| ≤ c হতে হবে। m, v, এবং c-এর এককগুলি উপযুক্ত এককে ভরবেগ পেতে সুসংগত হতে হবে (যেমন, m কেজি-তে, v m/s-এ, c m/s-এ p kg·m/s-এ দেয়)।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         p: "আপেক্ষিক ভরবেগ (ভরবেগ kg·m/s)",
         m: "বিশ্রাম ভর (ভর kg)",
         v: "বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "শক্তি-ভরবেগ সম্পর্ক",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "ভরবেগ এবং বিশ্রাম ভর থেকে মোট শক্তি গণনা করে (E)",
      description:
         "একটি কণার মোট আপেক্ষিক শক্তি তার আপেক্ষিক ভরবেগ (p) এবং বিশ্রাম ভর (m) থেকে গণনা করে। শক্তি-ভরবেগ সম্পর্ক ব্যবহার করে: E² = (pc)² + (mc²)²। এই সমীকরণ ভরযুক্ত (m > 0) এবং ভরহীন (m = 0) উভয় কণার জন্য বৈধ। p ≥ 0, m ≥ 0, এবং c > 0 হতে হবে। p, m, এবং c-এর এককগুলি সুসংগত হতে হবে।\n",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "মোট আপেক্ষিক শক্তি (শক্তি J)",
         p: "আপেক্ষিক ভরবেগ (ভরবেগ kg·m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
         m: "বিশ্রাম ভর (ভর kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "ভর-শক্তি সমতুল্যতা (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "ভর-শক্তি সমতুল্যতা গণনা করে (E₀ = mc²)",
      description:
         "আইনস্টাইনের বিখ্যাত E₀ = mc² সমীকরণ ব্যবহার করে প্রদত্ত বিশ্রাম ভর (m)-এর সমতুল্য বিশ্রাম শক্তি (E₀) গণনা করে। m ≥ 0 এবং c > 0 হতে হবে। m এবং c-এর একক সুসংগত হতে হবে (যেমন, m কেজি-তে, c m/s-এ E₀ জুল-এ দেয়)। এই এন্ডপয়েন্ট c-এর জন্য একটি স্ট্যান্ডার্ড মান (প্রায় 299792458 m/s) ব্যবহার করে, যদি না 'c' স্পষ্টভাবে সরবরাহ করা হয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E0: "বিশ্রাম শক্তি (শক্তি J)",
         m: "বিশ্রাম ভর (ভর kg)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "আপেক্ষিক গতিশক্তি",
      equation_text: "KE = (γ - 1)mc²",
      summary: "আপেক্ষিক গতিশক্তি (KE) গণনা করে",
      description:
         "বিশ্রাম ভর (m) এবং বেগ (v) সহ একটি কণার আপেক্ষিক গতিশক্তি গণনা করে। এটি KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc² সমীকরণ ব্যবহার করে। মূলত বিশ্রাম ভর (m > 0) সহ কণাগুলির জন্য। m ≥ 0 এবং |v| < c হতে হবে। m, v, এবং c-এর এককগুলি উপযুক্ত এককে শক্তি পেতে সুসংগত হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE: "আপেক্ষিক গতিশক্তি (শক্তি J)",
         m: "বিশ্রাম ভর (ভর kg)",
         v: "বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "আপেক্ষিক ডপলার প্রভাব (তরঙ্গদৈর্ঘ্য)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "তরঙ্গদৈর্ঘ্যের জন্য আপেক্ষিক অনুদৈর্ঘ্য ডপলার প্রভাব গণনা করে",
      description:
         "একটি উৎস থেকে নির্গত আলোর পর্যবেক্ষণ করা তরঙ্গদৈর্ঘ্য (λ') গণনা করে যা একটি উপযুক্ত তরঙ্গদৈর্ঘ্য (λ₀) সহ দর্শক থেকে সরাসরি দূরে বা তার দিকে আপেক্ষিক বেগ (v_rel) সহ চলমান। এটি λ' = λ₀√((1 + β)/(1 - β)) সমীকরণ ব্যবহার করে, যেখানে β = v_rel/c। v_rel > 0 মন্দার জন্য (রেডশিফট), v_rel < 0approch জন্য (ব্লুশিফট)। λ₀ > 0 এবং |v_rel| < c প্রয়োজন। λ' এর একক λ₀ এর সমান হবে, v_rel এবং c এর একক সামঞ্জস্যপূর্ণ হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         "λ'": "পর্যবেক্ষিত তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
         λ0: "উপযুক্ত তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
         v: "আপেক্ষিক বেগ (গতি m/s)",
         c: "শূন্যস্থানে আলোর বেগ (গতি m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "ফোটন শক্তি (ফ্রিকোয়েন্সি থেকে)",
      equation_text: "E = hf",
      summary: "ফ্রিকোয়েন্সি থেকে ফোটন শক্তি গণনা করে (E = hf)",
      description:
         "ফোটনের শক্তি (E) তার ফ্রিকোয়েন্সি (f) উপর ভিত্তি করে গণনা করে। এটি প্লাঙ্কের সম্পর্ক E = hf ব্যবহার করে। f ≥ 0 এবং h > 0 প্রয়োজন। h এবং f এর একক উপযুক্ত এককে শক্তি পেতে সামঞ্জস্যপূর্ণ হতে হবে (যেমন, h J·s-এ, f Hz (s⁻¹)-এ E জুল-এ দেয়)। এই এন্ডপয়েন্ট h এর জন্য একটি স্ট্যান্ডার্ড মান (প্রায় 6.626e-34 J·s) ব্যবহার করে, যদি না 'h' স্পষ্টভাবে সরবরাহ করা হয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "ফোটন শক্তি (শক্তি J)",
         h: "প্লাঙ্ক ধ্রুবক (ধ্রুবক J·s)",
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "ফোটন ভরবেগ (তরঙ্গদৈর্ঘ্য থেকে)",
      equation_text: "p = h / λ",
      summary: "তরঙ্গদৈর্ঘ্য থেকে ফোটন ভরবেগ গণনা করে (p = h/λ)",
      description:
         "ফোটনের ভরবেগ (p) তার তরঙ্গদৈর্ঘ্য (λ) উপর ভিত্তি করে গণনা করে। এটি p = h/λ সম্পর্ক ব্যবহার করে। λ > 0 এবং h > 0 প্রয়োজন। h এবং λ এর একক উপযুক্ত এককে ভরবেগ পেতে সামঞ্জস্যপূর্ণ হতে হবে (যেমন, h J·s-এ, λ মিটার-এ p kg·m/s-এ দেয়)। এই এন্ডপয়েন্ট h এর জন্য একটি স্ট্যান্ডার্ড মান (প্রায় 6.626e-34 J·s) ব্যবহার করে, যদি না 'h' স্পষ্টভাবে সরবরাহ করা হয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         p: "ফোটন ভরবেগ (ভরবেগ kg·m/s)",
         h: "প্লাঙ্ক ধ্রুবক (ধ্রুবক J·s)",
         λ: "তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "আলোক-বিদ্যুৎ প্রভাব (সর্বোচ্চ KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "আলোক-বিদ্যুৎ প্রভাবে সর্বোচ্চ গতিশক্তি গণনা করে (KE_max)",
      description:
         "আলোক-বিদ্যুৎ প্রভাবে নির্গত ইলেকট্রনের সর্বোচ্চ গতিশক্তি (KE_max) গণনা করে। এটি KE_max = E_photon - φ সমীকরণ ব্যবহার করে, যেখানে E_photon হল আগত ফোটন শক্তি এবং φ হল উপাদানের কার্যকারিতা। যদি E_photon ≤ φ হয়, তবে কোনো ইলেকট্রন নির্গত হয় না, এবং KE_max হল 0। E_photon ≥ 0 এবং φ ≥ 0 প্রয়োজন। E_photon এবং φ এর একক KE_max কে একই এককে পেতে সামঞ্জস্যপূর্ণ হতে হবে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE_max: "সর্বোচ্চ ইলেকট্রন গতিশক্তি (শক্তি J)",
         E_photon: "ফোটন শক্তি (শক্তি J)",
         φ: "কার্যকারিতা (শক্তি J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "রিডবার্গ সমীকরণ (পারমাণবিক স্থানান্তর)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "হাইড্রোজেন-সদৃশ পরমাণু স্থানান্তরের জন্য শক্তি বা তরঙ্গ সংখ্যা গণনা করে",
      description:
         "একটি হাইড্রোজেন-সদৃশ পরমাণুতে (Z) দুটি শক্তি স্তরের মধ্যে একটি ইলেকট্রন স্থানান্তরের জন্য শক্তি পার্থক্য (ΔE) বা তরঙ্গ সংখ্যা (1/λ) গণনা করে। এটি Result = Constant * Z² * (1/n_initial² - 1/n_final²) সমীকরণ ব্যবহার করে। যদি 'Constant' রিডবার্গ শক্তি একক হয় (যেমন, eV এ), ফলাফলটি শক্তি পার্থক্য E_final - E_initial (শোষণের জন্য ধনাত্মক, নিঃসরণের জন্য ঋণাত্মক)। যদি 'Constant' তরঙ্গ সংখ্যার জন্য রিডবার্গ ধ্রুবক হয় (যেমন, m⁻¹ এ), ফলাফলটি তরঙ্গ সংখ্যা 1/λ (নিঃসরণের জন্য ধনাত্মক, শোষণের জন্য ঋণাত্মক)। nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (পূর্ণসংখ্যা), এবং Constant > 0 প্রয়োজন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔE: "শক্তি পার্থক্য (শক্তি J)",
         R_y: "রিডবার্গ ধ্রুবক (ধ্রুবক J বা বিপরীত দৈর্ঘ্য m⁻¹)",
         Z: "পারমাণবিক সংখ্যা (মাত্রাহীন পূর্ণসংখ্যা)",
         n1: "প্রাথমিক প্রধান কোয়ান্টাম সংখ্যা (মাত্রাহীন পূর্ণসংখ্যা)",
         n2: "চূড়ান্ত প্রধান কোয়ান্টাম সংখ্যা (মাত্রাহীন পূর্ণসংখ্যা)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "কোণীয় বেগ",
      equation_text: "ω = Δθ / Δt",
      summary: "কোণীয় বেগ গণনা করে (ω = Δθ / Δt)",
      description: "কোণ এবং সময়ের পরিবর্তনের উপর ভিত্তি করে কোণীয় বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ω: "কোণীয় বেগ (কোণীয় বেগ rad/s)",
         Δθ: "কোণীয় সরণ (কোণ rad)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "কোণীয় ত্বরণ",
      equation_text: "α = Δω / Δt",
      summary: "কোণীয় ত্বরণ গণনা করে (α = Δω / Δt)",
      description: "কোণীয় বেগ এবং সময়ের পরিবর্তনের উপর ভিত্তি করে কোণীয় ত্বরণ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         α: "কোণীয় ত্বরণ (কোণীয় ত্বরণ rad/s²)",
         Δω: "কোণীয় বেগের পরিবর্তন (কোণীয় বেগ rad/s)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "ঘূর্ণন গতিবিদ্যা (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "চূড়ান্ত কোণীয় বেগ গণনা করে (ω = ω0 + αt)",
      description: "প্রথম ঘূর্ণন গতিবিদ্যার সমীকরণ ব্যবহার করে চূড়ান্ত কোণীয় বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ω: "চূড়ান্ত কোণীয় বেগ (কোণীয় বেগ rad/s)",
         ω0: "প্রাথমিক কোণীয় বেগ (কোণীয় বেগ rad/s)",
         α: "কোণীয় ত্বরণ (কোণীয় ত্বরণ rad/s²)",
         t: "সময় (সময় s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "ঘূর্ণন গতিবিদ্যা (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "কোণীয় অবস্থান গণনা করে (θ = θ0 + ω0t + 0.5αt^2)",
      description: "দ্বিতীয় ঘূর্ণন গতিবিদ্যার সমীকরণ ব্যবহার করে কোণীয় অবস্থান গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         θ: "চূড়ান্ত কোণীয় অবস্থান (কোণ rad)",
         θ0: "প্রাথমিক কোণীয় অবস্থান (কোণ rad)",
         ω0: "প্রাথমিক কোণীয় বেগ (কোণীয় বেগ rad/s)",
         t: "সময় (সময় s)",
         α: "কোণীয় ত্বরণ (কোণীয় ত্বরণ rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "ঘূর্ণন গতিবিদ্যা (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "কোণীয় বেগের বর্গ গণনা করে (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "ঘূর্ণন গতিবিদ্যার তৃতীয় সমীকরণ ব্যবহার করে কোণীয় বেগের বর্গ গণনা করে। দ্রষ্টব্য - ω নয়, ω^2 ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ω: "চূড়ান্ত কোণীয় বেগ (কোণীয় বেগ rad/s)",
         ω0: "প্রাথমিক কোণীয় বেগ (কোণীয় বেগ rad/s)",
         α: "কোণীয় ত্বরণ (কোণীয় ত্বরণ rad/s²)",
         Δθ: "কোণীয় সরণ (কোণ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "গড় কোণীয় বেগ",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "গড় কোণীয় বেগ গণনা করে (ω_avg = 0.5 * (ω + ω0))",
      description: "ধ্রুবক কোণীয় ত্বরণ ধরে নিয়ে গড় কোণীয় বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ω_avg: "গড় কোণীয় বেগ (কোণীয় বেগ rad/s)",
         ω: "চূড়ান্ত কোণীয় বেগ (কোণীয় বেগ rad/s)",
         ω0: "প্রাথমিক কোণীয় বেগ (কোণীয় বেগ rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "টর্ক",
      equation_text: "τ = rFsin(θ)",
      summary: "টর্ক গণনা করে (τ = rF sin(θ))",
      description: "ব্যাসার্ধ, বল এবং তাদের মধ্যেকার কোণের উপর ভিত্তি করে টর্ক গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         τ: "টর্ক (টর্ক N·m)",
         r: "লিভার আর্ম (দৈর্ঘ্য m)",
         F: "বল (বল N)",
         θ: "বল এবং লিভার আর্মের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "নিউটন এর দ্বিতীয় নিয়ম (ঘূর্ণন)",
      equation_text: "τ_net = Iα",
      summary: "ঘূর্ণন ২য় নিয়ম ব্যবহার করে টর্ক গণনা করে (τ = Iα)",
      description: "জড়তা এবং কোণীয় ত্বরণের উপর ভিত্তি করে টর্ক গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         τ_net: "নেট টর্ক (টর্ক N·m)",
         I: "জড়তা (জড়তা kg·m²)",
         α: "কোণীয় ত্বরণ (কোণীয় ত্বরণ rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "জড়তা",
      equation_text: "I = mr² (বিন্দু ভর)",
      summary: "একটি বিন্দু ভরের জন্য জড়তা গণনা করে (I = mr^2)",
      description: "একটি অক্ষ সাপেক্ষে একক বিন্দু ভরের জন্য জড়তা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         I: "জড়তা (জড়তা kg·m²)",
         m: "ভর (ভর kg)",
         r: "অক্ষ থেকে দূরত্ব (দৈর্ঘ্য m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "ঘূর্ণন কাজ",
      equation_text: "W = τΔθ (ধ্রুবক টর্ক)",
      summary: "ঘূর্ণন কাজ গণনা করে (W = τΔθ)",
      description: "কোণীয় সরণের উপর একটি ধ্রুবক টর্ক দ্বারা করা কাজ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         W: "ঘূর্ণন কাজ (শক্তি J)",
         τ: "টর্ক (টর্ক N·m)",
         Δθ: "কোণীয় সরণ (কোণ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "ঘূর্ণন শক্তি",
      equation_text: "P = τω",
      summary: "ঘূর্ণন শক্তি গণনা করে (P = τω cos(θ))",
      description: "টর্ক, কোণীয় বেগ এবং তাদের মধ্যেকার কোণের উপর ভিত্তি করে তাত্ক্ষণিক ঘূর্ণন শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "ঘূর্ণন শক্তি (শক্তি W)",
         τ: "টর্ক (টর্ক N·m)",
         ω: "কোণীয় বেগ (কোণীয় বেগ rad/s)",
         θ: "টর্ক এবং কোণীয় বেগের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "ঘূর্ণন গতিশক্তি",
      equation_text: "KE_rot = ½Iω²",
      summary: "ঘূর্ণন গতিশক্তি গণনা করে (KE = 0.5Iω^2)",
      description: "ঘূর্ণায়মান বস্তুর গতিশক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE_rot: "ঘূর্ণন গতিশক্তি (শক্তি J)",
         I: "জড়তা (জড়তা kg·m²)",
         ω: "কোণীয় বেগ (কোণীয় বেগ rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "কোণীয় ভরবেগ",
      equation_text: "L = Iω",
      summary: "কোণীয় ভরবেগ গণনা করে (L = mrv sin(θ))",
      description: "একটি বিন্দু সাপেক্ষে গতিশীল একটি বিন্দু ভরের জন্য কৌণিক ভরবেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         L: "কোণীয় ভরবেগ (কোণীয় ভরবেগ kg·m²/s)",
         m: "ভর (ভর kg)",
         r: "অক্ষ/বিন্দু থেকে দূরত্ব (দৈর্ঘ্য m)",
         v: "বেগ (গতি m/s)",
         θ: "ব্যাসার্ধ ভেক্টর এবং বেগের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "কোণীয় ঘাত",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "কোণীয় ঘাত গণনা করে (J = τΔt)",
      description: "টর্ক এবং সময় ব্যবধান থেকে কৌণিক ঘাত গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         J_angular: "কোণীয় ঘাত (কোণীয় ঘাত N·m·s)",
         τ_avg: "গড় টর্ক (টর্ক N·m)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "ইয়ং-এর মডুলাস",
      equation_text: "E = σ / ε",
      summary: "ইয়ং-এর মডুলাস গণনা করে (E = (F * L0) / (A * ΔL))",
      description: "প্রসারণ বা সংকোচন পীড়নের অধীনে একটি উপাদানের ইয়ং-এর মডুলাস (ইলাস্টিক মডুলাস) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         E: "ইয়ং-এর মডুলাস (চাপ Pa)",
         F: "বল (বল N)",
         L0: "আসল দৈর্ঘ্য (দৈর্ঘ্য m)",
         A: "প্রস্থচ্ছেদ ক্ষেত্রফল (ক্ষেত্রফল m²)",
         ΔL: "দৈর্ঘ্যে পরিবর্তন (দৈর্ঘ্য m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "শিয়ার মডুলাস",
      equation_text: "G = τ / γ",
      summary: "শিয়ার মডুলাস গণনা করে (G = (F * y) / (A * Δx))",
      description: "শিয়ার স্ট্রেসের অধীনে একটি উপাদানের শিয়ার মডুলাস (কঠোরতা মডুলাস) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         G: "শিয়ার মডুলাস (চাপ Pa)",
         F: "বল (বল N)",
         y: "বলের লম্ব দূরত্ব (দৈর্ঘ্য m)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
         Δx: "সরণ (দৈর্ঘ্য m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "বাল্ক মডুলাস",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "বাল্ক মডুলাস গণনা করে (K = (F * V0) / (A * ΔV))",
      description: "অভিন্ন চাপের (হাইড্রস্ট্যাটিক স্ট্রেস) অধীনে একটি উপাদানের বাল্ক মডুলাস গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         K: "বাল্ক মডুলাস (চাপ Pa)",
         ΔP: "চাপের পরিবর্তন (চাপ Pa)",
         ΔV: "আয়তনের পরিবর্তন (আয়তন m³)",
         V0: "আসল আয়তন (আয়তন m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "হুকের নিয়ম",
      equation_text: "F = kx",
      summary: "একটি স্প্রিং এর বল গণনা করে (F = -k * Δx)",
      description:
         "হুকের নিয়ম অনুযায়ী একটি আদর্শ স্প্রিং দ্বারা প্রযুক্ত পুনরুদ্ধারকারী বল গণনা করে। দ্রষ্টব্য - স্থানচ্যুতির বিরোধিতা করে এমন বল নির্দেশ করে একটি ঋণাত্মক মান ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         F: "বল (বল N)",
         k: "স্প্রিং কনস্ট্যান্ট (স্প্রিং কনস্ট্যান্ট N/m)",
         x: "সাম্য অবস্থা থেকে সরণ (দৈর্ঘ্য m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "কঠিন তাপীয় প্রসারণ (দৈর্ঘ্য)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "কঠিন রৈখিক তাপীয় প্রসারণ গণনা করে (ΔL = αL0ΔT)",
      description: "তাপমাত্রা পরিবর্তনের কারণে কঠিন পদার্থের দৈর্ঘ্যের পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔL: "দৈর্ঘ্যে পরিবর্তন (দৈর্ঘ্য m)",
         α: "রৈখিক প্রসারণ সহগ (প্রতি তাপমাত্রা সহগ K⁻¹)",
         L0: "আসল দৈর্ঘ্য (দৈর্ঘ্য m)",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "কঠিন তাপীয় প্রসারণ (ক্ষেত্রফল)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "কঠিন ক্ষেত্রফল তাপীয় প্রসারণ গণনা করে (ΔA = 2αA0ΔT)",
      description:
         "রৈখিক প্রসারণ সহগ ব্যবহার করে তাপমাত্রা পরিবর্তনের কারণে কঠিন পদার্থের ক্ষেত্রফলের পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔA: "ক্ষেত্রফলে পরিবর্তন (ক্ষেত্রফল m²)",
         α: "রৈখিক প্রসারণ সহগ (প্রতি তাপমাত্রা সহগ K⁻¹)",
         A0: "আসল ক্ষেত্রফল (ক্ষেত্রফল m²)",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "কঠিন তাপীয় প্রসারণ (আয়তন)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "কঠিন আয়তন তাপীয় প্রসারণ গণনা করে (ΔV = 3αV0ΔT)",
      description: "রৈখিক প্রসারণ সহগ ব্যবহার করে তাপমাত্রা পরিবর্তনের কারণে কঠিন পদার্থের আয়তনের পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔV: "আয়তনে পরিবর্তন (আয়তন m³)",
         α: "রৈখিক প্রসারণ সহগ (প্রতি তাপমাত্রা সহগ K⁻¹)",
         V0: "আসল আয়তন (আয়তন m³)",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "তরল তাপীয় প্রসারণ",
      equation_text: "ΔV = βV₀ΔT",
      summary: "তরল তাপীয় প্রসারণ গণনা করে (ΔV = βV0ΔT)",
      description: "তাপমাত্রা পরিবর্তনের কারণে তরলের আয়তনের পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔV: "আয়তনে পরিবর্তন (আয়তন m³)",
         β: "আয়তন প্রসারণ সহগ (প্রতি তাপমাত্রা সহগ K⁻¹)",
         V0: "আসল আয়তন (আয়তন m³)",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "সংবেদী তাপ",
      equation_text: "Q = mcΔT",
      summary: "সংবেদী তাপ গণনা করে (Q = mcΔT)",
      description: "একটি পদার্থের তাপমাত্রা পরিবর্তনের কারণকারী স্থানান্তরিত তাপ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Q: "সংবেদী তাপ (শক্তি J)",
         m: "ভর (ভর kg)",
         c: "নির্দিষ্ট তাপ ক্ষমতা (নির্দিষ্ট তাপ ক্ষমতা J/(kg·K))",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "লীন তাপ",
      equation_text: "Q = mL",
      summary: "লীন তাপ গণনা করে (Q = mL)",
      description: "একটি পদার্থের পর্যায় পরিবর্তনের সময় স্থানান্তরিত তাপ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Q: "লীন তাপ (শক্তি J)",
         m: "ভর (ভর kg)",
         L: "লীন তাপ (নির্দিষ্ট শক্তি J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "আদর্শ গ্যাস নিয়ম",
      equation_text: "PV = nRT",
      summary: "আদর্শ গ্যাস নিয়ম যাচাই করে (PV = nRT)",
      description:
         "প্রদত্ত প্যারামিটারগুলির জন্য আদর্শ গ্যাস নিয়ম সমীকরণ সত্য কিনা তা পরীক্ষা করে। বুলিয়ান ফেরত দেয়। দ্রষ্টব্য - কঠোর সমতা (===) ব্যবহার করে যা ফ্লোটিং-পয়েন্ট নির্ভুলতার জন্য সংবেদনশীল হতে পারে; বাস্তব-বিশ্ব যাচাইকরণের জন্য সহনশীলতা বিবেচনা করুন।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "চাপ (চাপ Pa)",
         V: "আয়তন (আয়তন m³)",
         n: "মোল সংখ্যা (পদার্থের পরিমাণ mol)",
         R: "আদর্শ গ্যাস ধ্রুবক (ধ্রুবক J/(mol·K))",
         T: "তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "আণবিক গতিশক্তি",
      equation_text: "KE_avg = (3/2)kT",
      summary: "গড় আণবিক গতিশক্তি গণনা করে (KE = (3/2)kT)",
      description: "একটি আদর্শ গ্যাসের প্রতি অণুর গড় স্থানান্তরণ গতিশক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE_avg: "গড় আণবিক গতিশক্তি (শক্তি J)",
         k: "বোল্টজম্যান ধ্রুবক (ধ্রুবক J/K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
         m: "একক অণুর ভর (ভর kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "আণবিক বেগ (সবচেয়ে সম্ভাবনাময়)",
      equation_text: "v_p = √(2kT/m)",
      summary: "সবচেয়ে সম্ভাব্য আণবিক বেগ গণনা করে (v_p = √(2kT/m))",
      description: "ম্যাক্সওয়েল-বোল্টজম্যান বিতরণ অনুসারে একটি আদর্শ গ্যাসের অণুগুলির সবচেয়ে সম্ভাব্য বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_p: "সবচেয়ে সম্ভাব্য আণবিক বেগ (গতি m/s)",
         k: "বোল্টজম্যান ধ্রুবক (ধ্রুবক J/K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
         m: "একক অণুর ভর (ভর kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "আণবিক বেগ (গড়)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "গড় আণবিক বেগ গণনা করে (v_avg = √(8kT/(πm)))",
      description: "ম্যাক্সওয়েল-বোল্টজম্যান বিতরণ অনুসারে একটি আদর্শ গ্যাসের অণুগুলির গড় বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_avg: "গড় আণবিক বেগ (গতি m/s)",
         k: "বোল্টজম্যান ধ্রুবক (ধ্রুবক J/K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
         π: "পাই (মাত্রাহীন ধ্রুবক)",
         m: "একক অণুর ভর (ভর kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "আণবিক বেগ (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "আণবিক বেগের বর্গমূল গড় বর্গ (v_rms = √(3kT/m)) গণনা করে",
      description: "ম্যাক্সওয়েল-বোল্টজম্যান বিতরণ অনুসারে একটি আদর্শ গ্যাসের অণুগুলির বর্গমূল গড় বর্গ বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v_rms: "আণবিক বেগের বর্গমূল গড় বর্গ (গতি m/s)",
         k: "বোল্টজম্যান ধ্রুবক (ধ্রুবক J/K)",
         T: "তাপমাত্রা (তাপমাত্রা K)",
         m: "একক অণুর ভর (ভর kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "অভ্যন্তরীণ শক্তি পরিবর্তন",
      equation_text: "ΔU = Q - W",
      summary: "আদর্শ এক-পরমাণু গ্যাসের জন্য অভ্যন্তরীণ শক্তি পরিবর্তন গণনা করে (ΔU = (3/2)nRΔT)",
      description: "তাপমাত্রা পরিবর্তন অনুভবকারী এক-পরমাণু আদর্শ গ্যাসের জন্য অভ্যন্তরীণ শক্তি পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         ΔU: "অভ্যন্তরীণ শক্তি পরিবর্তন (শক্তি J)",
         n: "মোল সংখ্যা (পদার্থের পরিমাণ mol)",
         R: "আদর্শ গ্যাস ধ্রুবক (ধ্রুবক J/(mol·K))",
         ΔT: "তাপমাত্রা পরিবর্তন (তাপমাত্রার পার্থক্য K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "তাপগতিবিদ্যার কাজ",
      equation_text: "W = PΔV (ধ্রুব চাপ)",
      summary: "ধ্রুব চাপে সিস্টেম দ্বারা করা তাপগতিবিদ্যার কাজ গণনা করে (W = -PΔV)",
      description:
         "একটি তাপগতিবিদ্যার প্রক্রিয়া চলাকালীন ধ্রুব চাপে সিস্টেম দ্বারা বা সিস্টেমে করা কাজ গণনা করে। দ্রষ্টব্য - সমীকরণটি সিস্টেম দ্বারা করা কাজ গণনা করে, প্রসারণের জন্য ধনাত্মক, সংকোচনের জন্য ঋণাত্মক। ফাংশনটি -P*deltaV ফেরত দেয়, যা W = PΔV সমীকরণ অনুযায়ী সিস্টেম দ্বারা করা কাজের সাথে সামঞ্জস্যপূর্ণ, একটি অতিরিক্ত ঋণাত্মক চিহ্ন যুক্ত করা হয়েছে যা প্রচলিত ধারণা অনুযায়ী সিস্টেমে করা কাজ বোঝাতে পারে। ফাংশনের আউটপুট নথিভুক্ত করা হচ্ছে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         W: "তাপগতিবিদ্যার কাজ (শক্তি J)",
         P: "চাপ (চাপ Pa)",
         ΔV: "আয়তনের পরিবর্তন (আয়তন m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "বাস্তব দক্ষতা",
      equation_text: "η = W_out / Q_in",
      summary: "একটি বাস্তব ইঞ্জিনের দক্ষতা গণনা করে (η_real = 1 - (Q_C / Q_H))",
      description: "শোষিত এবং প্রত্যাখ্যাত তাপের উপর ভিত্তি করে একটি তাপ ইঞ্জিনের তাপীয় দক্ষতা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         η: "দক্ষতা (মাত্রাহীন)",
         Q_H: "গরম জলাধার থেকে শোষিত তাপ (শক্তি J)",
         Q_C: "ঠান্ডা জলাধারে প্রত্যাখ্যাত তাপ (শক্তি J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "আদর্শ দক্ষতা",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "আদর্শ দক্ষতা (কার্নোট) গণনা করে (η_ideal = 1 - (T_C / T_H))",
      description:
         "দুই তাপমাত্রার মধ্যে কাজ করা একটি তাপ ইঞ্জিনের সর্বাধিক তাত্ত্বিক দক্ষতা (কার্নোট দক্ষতা) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         η_ideal: "আদর্শ দক্ষতা (মাত্রাহীন)",
         T_hot: "গরম জলাধারের তাপমাত্রা (তাপমাত্রা K)",
         T_cold: "ঠান্ডা জলাধারের তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "বাস্তব পারফরম্যান্স গুণাঙ্ক (COP)",
      equation_text: "COP_ref = Q_c / W (রেফ্রিজারেটর)",
      summary: "একটি বাস্তব রেফ্রিজারেটরের পারফরম্যান্স গুণাঙ্ক গণনা করে (COP_real = QC / (QH - QC))",
      description: "একটি বাস্তব রেফ্রিজারেটর বা হিট পাম্পের পারফরম্যান্স গুণাঙ্ক গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         COP_real: "পারফরম্যান্স গুণাঙ্ক (মাত্রাহীন)",
         Q_C: "ঠান্ডা জলাধার থেকে তাপ (শক্তি J)",
         Q_H: "গরম জলাধারে তাপ (শক্তি J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "আদর্শ পারফরম্যান্স গুণাঙ্ক (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "একটি আদর্শ রেফ্রিজারেটরের পারফরম্যান্স গুণাঙ্ক গণনা করে (COP_ideal = TC / (TH - TC))",
      description:
         "দুই তাপমাত্রার মধ্যে কাজ করা একটি রেফ্রিজারেটর বা হিট পাম্পের সর্বাধিক তাত্ত্বিক পারফরম্যান্স গুণাঙ্ক গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         COP_ideal: "আদর্শ পারফরম্যান্স গুণাঙ্ক (মাত্রাহীন)",
         T_h: "গরম জলাধারের তাপমাত্রা (তাপমাত্রা K)",
         T_c: "ঠান্ডা জলাধারের তাপমাত্রা (তাপমাত্রা K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "পর্যায়ক্রমিক তরঙ্গের বেগ",
      equation_text: "v = fλ",
      summary: "তরঙ্গের বেগ গণনা করে (v = fλ)",
      description: "একটি পর্যায়ক্রমিক তরঙ্গের তার ফ্রিকোয়েন্সি এবং তরঙ্গদৈর্ঘ্যের উপর ভিত্তি করে বেগ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         v: "তরঙ্গের বেগ (গতি m/s)",
         f: "ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         λ: "তরঙ্গদৈর্ঘ্য (দৈর্ঘ্য m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "তরঙ্গ তীব্রতা",
      equation_text: "I = P / A",
      summary: "তীব্রতা গণনা করে (I = P/A)",
      description: "একটি তরঙ্গের তীব্রতা (প্রতি ইউনিট ক্ষেত্রফলে শক্তি) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         I: "তীব্রতা (তীব্রতা W/m²)",
         P: "শক্তি (শক্তি W)",
         A: "ক্ষেত্রফল (ক্ষেত্রফল m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "তীব্রতা স্তর (ডেসিবেল)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "ডেসিবেলে তীব্রতা স্তর গণনা করে (L = 10 log10(I/I0))",
      description: "একটি রেফারেন্স তীব্রতার সাথে সম্পর্কিত তীব্রতা স্তর (শব্দ তীব্রতা স্তর) গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         β: "তীব্রতা স্তর (তীব্রতা স্তর dB)",
         I: "তীব্রতা (তীব্রতা W/m²)",
         I0: "রেফারেন্স তীব্রতা (তীব্রতা W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "চাপ স্তর (শব্দ চাপ স্তর)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "ডেসিবেলে শব্দ চাপ স্তর গণনা করে (L = 20 log10(ΔP/ΔP0))",
      description: "একটি রেফারেন্স চাপ পরিবর্তনের সাথে সম্পর্কিত শব্দ চাপ স্তর গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         L_p: "শব্দ চাপ স্তর (চাপ স্তর dB)",
         P_rms: "RMS চাপ ওঠানামা (চাপ Pa)",
         P_ref: "রেফারেন্স চাপ (চাপ Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "ডপলার প্রভাব (শব্দ/অ-আপেক্ষিক)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "ডপলার প্রভাব বেগ গুণক গণনা করে ((c + v_o) / (c - v_s))",
      description:
         "ডপলার প্রভাব সমীকরণের বেগ ফ্যাক্টর অংশ (f' = f * factor) গণনা করে। পর্যবেক্ষকের উৎসের দিকে গতি, উৎসের পর্যবেক্ষকের দিকে গতির জন্য বেগ ধনাত্মক।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         f_obs: "পর্যবেক্ষিত ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         f_source: "উৎস ফ্রিকোয়েন্সি (ফ্রিকোয়েন্সি Hz)",
         v_wave: "তরঙ্গের বেগ (গতি m/s)",
         v_observer: "মাধ্যমের সাপেক্ষে পর্যবেক্ষকের বেগ (গতি m/s)",
         v_source: "মাধ্যমের সাপেক্ষে উৎসের বেগ (গতি m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "মাখ কোণ",
      equation_text: "sin(μ) = 1 / M",
      summary: "মাখ কোণ গণনা করে (θ_M = arcsin(c/v))",
      description:
         "শব্দের বেগের চেয়ে দ্রুত গতিশীল বস্তু দ্বারা গঠিত মাখ শঙ্কুর কোণ গণনা করে। কোণ রেডিয়ানে ফেরত দেয়।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         μ: "মাখ কোণ (কোণ rad)",
         M: "মাখ সংখ্যা (মাত্রাহীন)",
         c: "শব্দের বেগ (গতি m/s)",
         v: "বস্তুর বেগ (গতি m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "কাজ",
      equation_text: "W = Fdcos(θ)",
      summary: "করা কাজ গণনা করে (W = F * Δs * cos(θ))",
      description: "বল, সরণ এবং তাদের মধ্যেকার কোণের উপর ভিত্তি করে করা কাজ গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         W: "করা কাজ (শক্তি J)",
         F: "বলের মাত্রা (বল N)",
         d: "সরণের মাত্রা (দৈর্ঘ্য m)",
         θ: "বল এবং সরণের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "গতিশক্তি",
      equation_text: "KE = ½mv²",
      summary: "গতিশক্তি গণনা করে (KE = 0.5 * m * v^2)",
      description: "ভর এবং বেগের উপর ভিত্তি করে গতিশক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE: "গতিশক্তি (শক্তি J)",
         m: "ভর (ভর kg)",
         v: "বেগ (গতি m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "গতিশক্তি (ভরবেগ থেকে)",
      equation_text: "KE = p² / (2m)",
      summary: "ভরবেগ থেকে গতিশক্তি গণনা করে (KE = p^2 / (2m))",
      description: "ভরবেগ এবং ভরের উপর ভিত্তি করে গতিশক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         KE: "গতিশক্তি (শক্তি J)",
         p: "ভরবেগ (ভরবেগ kg·m/s)",
         m: "ভর (ভর kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "মহাকর্ষীয় পটেনশিয়াল শক্তি",
      equation_text: "U_g = mgh (পৃষ্ঠের কাছাকাছি)",
      summary: "মহাকর্ষীয় পটেনশিয়াল শক্তি গণনা করে (PE = mgh)",
      description: "মহাকর্ষীয় পটেনশিয়াল শক্তির পরিবর্তন গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         U_g: "মহাকর্ষীয় পটেনশিয়াল শক্তি (শক্তি J)",
         m: "ভর (ভর kg)",
         g: "মাধ্যাকর্ষণ জনিত ত্বরণ (ত্বরণ m/s²)",
         h: "উচ্চতা (দৈর্ঘ্য m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "দক্ষতা",
      equation_text: "দক্ষতা = Output / Input",
      summary: "দক্ষতা গণনা করে (η = W_out / W_in)",
      description: "একটি প্রক্রিয়া বা মেশিনের দক্ষতা গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         Efficiency: "দক্ষতা (মাত্রাহীন)",
         Output: "দরকারী আউটপুট শক্তি বা শক্তি (শক্তি J বা শক্তি W)",
         Input: "মোট ইনপুট শক্তি বা শক্তি (শক্তি J বা শক্তি W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "শক্তি",
      equation_text: "P = W / t",
      summary: "শক্তি গণনা করে (P = ΔW / Δt)",
      description: "কাজ এবং সময়ের পরিবর্তনের উপর ভিত্তি করে গড় শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "শক্তি (শক্তি W)",
         ΔW: "কাজে পরিবর্তন (শক্তি J)",
         Δt: "সময় ব্যবধান (সময় s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "শক্তি (P = Fv)",
      equation_text: "P = Fv",
      summary: "বল এবং বেগ থেকে শক্তি গণনা করে (P = Fv cos(θ))",
      description: "বল, বেগ, এবং তাদের মধ্যেকার কোণের উপর ভিত্তি করে তাৎক্ষণিক শক্তি গণনা করে।",
      language_code: "bn",
      subject: "Physics",
      variables: {
         P: "শক্তি (শক্তি W)",
         F: "বলের মাত্রা (বল N)",
         v: "বেগের মাত্রা (গতি m/s)",
         θ: "বল এবং বেগের মধ্যে কোণ (কোণ rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = bn;
