const he = [
   {
      equation_id: "centripetal-acceleration",
      name: "תאוצה צנטריפטלית",
      equation_text: "a_c = v² / r",
      summary: "מחשב תאוצה צנטריפטלית (a_c = v^2 / r)",
      description:
         "מחשב את התאוצה המכוונת למרכז מסלול מעגלי באמצעות מהירות קווית ורדיוס.",
      language_code: "he",
      subject: "Physics",
      variables: {
         a_c: "תאוצה צנטריפטלית (תאוצה m/s²)",
         v: "מהירות קווית (מהירות m/s)",
         r: "רדיוס המסלול המעגלי (אורך m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "תאוצה צנטריפטלית (זוויתית)",
      equation_text: "a_c = ω²r",
      summary: "מחשב תאוצה צנטריפטלית (a_c = -ω^2 * r) באמצעות מהירות זוויתית",
      description:
         "מחשב את רכיב וקטור התאוצה הצנטריפטלית באמצעות מהירות זוויתית ורדיוס. הסימן השלילי מציין כיוון אל המרכז.",
      language_code: "he",
      subject: "Physics",
      variables: {
         a_c: "תאוצה צנטריפטלית (תאוצה m/s²)",
         ω: "מהירות זוויתית (מהירות זוויתית rad/s)",
         r: "רדיוס המסלול המעגלי (אורך m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "חוק קולון (כוח)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "מחשב כוח חשמלי באמצעות חוק קולון (F = k * q1*q2 / r^2)",
      description:
         "מחשב את הכוח החשמלי בין שני מטענים נקודתיים. מחזיר כוח עם סימן (חיובי לדחייה, שלילי למשיכה).",
      language_code: "he",
      subject: "Physics",
      variables: {
         F: "כוח חשמלי (כוח N)",
         k: "קבוע קולון (קבוע N·m²/C²)",
         q1: "מטען 1 (מטען C)",
         q2: "מטען 2 (מטען C)",
         r: "מרחק בין מטענים (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "שדה חשמלי",
      equation_text: "E = kq / r² (מטען נקודתי)",
      summary: "מחשב שדה חשמלי מכוח (E = F_E/q)",
      description: "מחשב את עוצמת השדה החשמלי המבוססת על הכוח המופעל על מטען בוחן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "גודל שדה חשמלי (שדה חשמלי N/C)",
         k: "קבוע קולון (קבוע N·m²/C²)",
         q: "מטען מקור (מטען C)",
         r: "מרחק ממטען מקור (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "פוטנציאל חשמלי",
      equation_text: "V = kq / r (מטען נקודתי)",
      summary: "מחשב פוטנציאל חשמלי משינוי באנרגיה פוטנציאלית (V = ΔU_E/q)",
      description:
         "מחשב את הפוטנציאל החשמלי (מתח) על בסיס השינוי באנרגיה פוטנציאלית חשמלית ליחידת מטען. הערה - שם הפונקציה `calculateElectricPotential` נכון, אך הפרמטר `deltaUE` מרמז על שינוי, בעוד שהמשוואה היא בדרך כלל V=U_E/q או ΔV=ΔU_E/q. תיעוד מבוסס על המשוואה ΔV = ΔU_E/q ומחזיר ΔV.",
      language_code: "he",
      subject: "Physics",
      variables: {
         V: "פוטנציאל חשמלי (מתח V)",
         k: "קבוע קולון (קבוע N·m²/C²)",
         q: "מטען מקור (מטען C)",
         r: "מרחק ממטען מקור (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "קשר בין שדה חשמלי לפוטנציאל",
      equation_text: "E_x = -dV/dx",
      summary: "מחשב שדה חשמלי מהפרש פוטנציאלים (E = ΔV/d)",
      description:
         'מחשב את גודל השדה החשמלי האחיד בהתבסס על הפרש הפוטנציאלים לאורך מרחק. הערה - שם הפונקציה "Field and Potential" (שדה ופוטנציאל) מטעה; היא מחשבת את השדה החשמלי E.',
      language_code: "he",
      subject: "Physics",
      variables: {
         E_x: "רכיב שדה חשמלי (שדה חשמלי V/m)",
         V: "פוטנציאל חשמלי (מתח V)",
         x: "מיקום (אורך m)",
         ΔV: "הפרש פוטנציאלים (מתח V)",
         d: "מרחק (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "קיבול",
      equation_text: "C = Q / V",
      summary: "מחשב קיבול (C = Q/V)",
      description: "מחשב קיבול על בסיס מטען אגור ומתח על פני קבל.",
      language_code: "he",
      subject: "Physics",
      variables: {
         C: "קיבול (קיבול F)",
         Q: "מטען (מטען C)",
         V: "מתח (מתח V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "קיבול קבל לוחות",
      equation_text: "C = ε₀A / d",
      summary: "מחשב קיבול קבל לוחות מקבילים (C = (kε₀A)/d)",
      description:
         "מחשב את הקיבול של קבל לוחות מקבילים עם דיאלקטרי. הערה - הפונקציה משתמשת ב- k * ε₀ כקלט יחיד (`kEpsilon`).",
      language_code: "he",
      subject: "Physics",
      variables: {
         C: "קיבול (קיבול F)",
         ε0: "פרמטיביות של ריק (קבוע F/m)",
         k: "קבוע דיאלקטרי (חסר ממדים)",
         A: "שטח לוחות (שטח m²)",
         d: "מרחק בין לוחות (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "קיבול קבל גלילי",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "מחשב קיבול קבל גלילי (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "מחשב את הקיבול של קבל גלילי עם דיאלקטרי. הערה - הפונקציה משתמשת ב- k * ε₀ כקלט יחיד (`kEpsilon`).",
      language_code: "he",
      subject: "Physics",
      variables: {
         C: "קיבול (קיבול F)",
         π: "פאי (קבוע חסר ממדים)",
         ε0: "פרמטיביות של ריק (קבוע F/m)",
         k: "קבוע דיאלקטרי (חסר ממדים)",
         L: "אורך גלילים (אורך m)",
         b: "רדיוס חיצוני (אורך m)",
         a: "רדיוס פנימי (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "קיבול קבל כדורי",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "מחשב קיבול קבל כדורי (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "מחשב את הקיבול של קבל כדורי עם דיאלקטרי. הערה - הפונקציה משתמשת ב- k * ε₀ כקלט יחיד (`kEpsilon`).",
      language_code: "he",
      subject: "Physics",
      variables: {
         C: "קיבול (קיבול F)",
         π: "פאי (קבוע חסר ממדים)",
         ε0: "פרמטיביות של ריק (קבוע F/m)",
         k: "קבוע דיאלקטרי (חסר ממדים)",
         a: "רדיוס פנימי (אורך m)",
         b: "רדיוס חיצוני (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "אנרגיה פוטנציאלית קיבולית",
      equation_text: "U_C = ½CV²",
      summary: "מאמת משוואות אנרגיה פוטנציאלית של קבל (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "בודק אם שלוש המשוואות הנפוצות לאנרגיה פוטנציאלית האגורה בקבל שוות ערך עבור Q, V ו-C הנתונים. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         U_C: "אנרגיה פוטנציאלית קיבולית (אנרגיה J)",
         Q: "מטען (מטען C)",
         V: "מתח (מתח V)",
         C: "קיבול (קיבול F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "זרם חשמלי",
      equation_text: "I = ΔQ / Δt",
      summary: "מחשב זרם חשמלי (I = ΔQ/Δt)",
      description: "מחשב זרם חשמלי המבוסס על כמות המטען העוברת דרך נקודה ליחידת זמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         I: "זרם חשמלי (זרם A)",
         ΔQ: "שינוי במטען (מטען C)",
         Δt: "שינוי בזמן (זמן s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "צפיפות מטען",
      equation_text: "ρ = Q / V (נפח)",
      summary: "מחשב צפיפות מטען (ρ = Q/V)",
      description: "מחשב את צפיפות המטען הממוצעת (מטען ליחידת נפח).",
      language_code: "he",
      subject: "Physics",
      variables: {
         ρ: "צפיפות מטען נפחית (צפיפות מטען C/m³)",
         Q: "מטען כולל (מטען C)",
         V: "נפח (נפח m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "צפיפות זרם",
      equation_text: "J = I / A",
      summary: "מחשב צפיפות זרם (J = I/A)",
      description: "מחשב צפיפות זרם חשמלי (זרם ליחידת שטח חתך).",
      language_code: "he",
      subject: "Physics",
      variables: {
         J: "צפיפות זרם (צפיפות זרם A/m²)",
         I: "זרם חשמלי (זרם A)",
         A: "שטח (שטח m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "חוק אוהם",
      equation_text: "V = IR",
      summary: "מחשב התנגדות באמצעות חוק אוהם (R = V/I)",
      description:
         "מחשב התנגדות המבוססת על מתח וזרם. הערה - הפונקציה מחשבת התנגדות R מ-V ומ-I.",
      language_code: "he",
      subject: "Physics",
      variables: {
         V: "מתח (מתח V)",
         I: "זרם (זרם A)",
         R: "התנגדות (התנגדות Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "התנגדות סגולית ומוליכות",
      equation_text: "ρ = RA / L",
      summary: "מחשב מוליכות מהתנגדות סגולית (σ = 1/ρ)",
      description: "מחשב מוליכות (σ) מהתנגדות סגולית (ρ).",
      language_code: "he",
      subject: "Physics",
      variables: {
         σ: "מוליכות (מוליכות S/m)",
         ρ: "התנגדות סגולית (התנגדות סגולית Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "התנגדות חשמלית",
      equation_text: "R = ρL / A",
      summary: "מחשב התנגדות חשמלית (R = ρ(l/A))",
      description:
         "מחשב את התנגדות המוליך על בסיס התנגדותו הסגולית, אורכו ושטח חתך הרוחב שלו. הערה - משתמש ב- `rhoValue` להתנגדות סגולית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         R: "התנגדות (התנגדות Ω)",
         ρ: "התנגדות סגולית (התנגדות סגולית Ω·m)",
         L: "אורך (אורך m)",
         A: "שטח חתך רוחב (שטח m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "הספק חשמלי",
      equation_text: "P = IV",
      summary: "מאמת משוואות הספק חשמלי (P = VI = I^2R = V^2/R)",
      description:
         "בודק אם שלוש המשוואות הנפוצות להספק חשמלי שוות ערך עבור V, I ו-R הנתונים. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "הספק חשמלי (הספק W)",
         V: "מתח (מתח V)",
         I: "זרם (זרם A)",
         R: "התנגדות (התנגדות Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "נגדים בטור",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "מחשב התנגדות כוללת עבור נגדים בטור (R_total = R1 + R2 + ...)",
      description: "מחשב את ההתנגדות השקולה הכוללת עבור מספר נגדים המחוברים בטור.",
      language_code: "he",
      subject: "Physics",
      variables: {
         R_total: "התנגדות כוללת (התנגדות Ω)",
         R: "התנגדות אינדיבידואלית (התנגדות Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "נגדים במקביל",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "מחשב התנגדות כוללת עבור נגדים במקביל (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "מחשב את ההתנגדות השקולה הכוללת עבור מספר נגדים המחוברים במקביל.",
      language_code: "he",
      subject: "Physics",
      variables: {
         R_total: "התנגדות כוללת (התנגדות Ω)",
         R: "התנגדות אינדיבידואלית (התנגדות Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "קבלים בטור",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "מחשב קיבול כולל עבור קבלים בטור (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "מחשב את הקיבול השקול הכולל עבור מספר קבלים המחוברים בטור.",
      language_code: "he",
      subject: "Physics",
      variables: {
         C_total: "קיבול כולל (קיבול F)",
         C: "קיבול אינדיבידואלי (קיבול F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "קבלים במקביל",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "מחשב קיבול כולל עבור קבלים במקביל (C_total = C1 + C2 + ...)",
      description: "מחשב את הקיבול השקול הכולל עבור מספר קבלים המחוברים במקביל.",
      language_code: "he",
      subject: "Physics",
      variables: {
         C_total: "קיבול כולל (קיבול F)",
         C: "קיבול אינדיבידואלי (קיבול F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "כוח מגנטי על מטען",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "מחשב כוח מגנטי על חלקיק טעון (F = qvB sin(θ))",
      description:
         "מחשב את גודל הכוח המגנטי המופעל על חלקיק טעון נע. הזווית צריכה להיות ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F_B: "גודל כוח מגנטי (כוח N)",
         q: "גודל מטען (מטען C)",
         v: "גודל מהירות (מהירות m/s)",
         B: "גודל שדה מגנטי (שדה מגנטי T)",
         θ: "זווית בין מהירות לשדה מגנטי (זווית rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "כוח מגנטי על זרם",
      equation_text: "F_B = ILBsin(θ)",
      summary: "מחשב כוח מגנטי על מוליך נושא זרם (F = I l B sin(θ))",
      description:
         "מחשב את גודל הכוח המגנטי המופעל על מוליך ישר הנושא זרם בשדה מגנטי. הזווית צריכה להיות ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F_B: "גודל כוח מגנטי (כוח N)",
         I: "זרם (זרם A)",
         L: "אורך מוליך (אורך m)",
         B: "גודל שדה מגנטי (שדה מגנטי T)",
         θ: "זווית בין זרם לשדה מגנטי (זווית rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "חוק ביו-סבר",
      equation_text: "B = μ₀I / (2πr) (חוט ישר אינסופי)",
      summary: "מחשב שדה מגנטי מאלמנט זרם (dB = (μ₀I ds) / (4πr^2))",
      description:
         "מחשב את גודל התרומה לשדה המגנטי מאלמנט זרם דיפרנציאלי ניצב לווקטור הרדיוס. הערה - הפונקציה מיישמת `(μ₀ * I * ds) / (4 * π * r^2)`, תוך השמטת המונח sin(θ) שלעיתים קרובות קיים בצורה הדיפרנציאלית, למעשה מניחה θ=90 מעלות או מחשבת רק את הרכיב ניצב לווקטור הרדיוס במישור הספציפי הזה. תיעוד המבוסס על המשוואה המיושמת.",
      language_code: "he",
      subject: "Physics",
      variables: {
         dB: "גודל תרומה לשדה מגנטי (שדה מגנטי T)",
         μ0: "פרמביליות של ריק (קבוע T·m/A)",
         I: "זרם (זרם A)",
         ds: "אורך דיפרנציאלי של אלמנט זרם (אורך m)",
         r: "מרחק מאלמנט זרם (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "שדה מגנטי של סולנואיד",
      equation_text: "B = μ₀nI (בפנים, אידיאלי)",
      summary: "מחשב שדה מגנטי בתוך סולנואיד ארוך (B = μ₀nI)",
      description: "מחשב את גודל השדה המגנטי בתוך סולנואיד אידיאלי ארוך.",
      language_code: "he",
      subject: "Physics",
      variables: {
         B: "עוצמת שדה מגנטי בתוך סולנואיד (שדה מגנטי T)",
         μ0: "פרמביליות של ריק (קבוע T·m/A)",
         n: "מספר ליפופים ליחידת אורך (מספר ליחידת אורך m⁻¹)",
         I: "זרם (זרם A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "שדה מגנטי של חוט ישר",
      equation_text: "B = μ₀I / (2πr) (חוט אינסופי)",
      summary: "מחשב שדה מגנטי מחוט ישר אינסופי (B = (μ₀I)/(2πr))",
      description:
         "מחשב את גודל השדה המגנטי במרחק מוליך ארוך וישר הנושא זרם.",
      language_code: "he",
      subject: "Physics",
      variables: {
         B: "עוצמת שדה מגנטי מחוט ישר (שדה מגנטי T)",
         μ0: "פרמביליות של ריק (קבוע T·m/A)",
         I: "זרם (זרם A)",
         π: "פאי (קבוע חסר ממדים)",
         r: "מרחק מהחוט (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "כוח בין חוטים מקבילים",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "מחשב כוח ליחידת אורך בין חוטים מקבילים (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "מחשב את גודל הכוח ליחידת אורך בין שני מוליכים ארוכים ומקבילים הנושאים זרמים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         "F/L": "כוח ליחידת אורך (כוח ליחידת אורך N/m)",
         μ0: "פרמביליות של ריק (קבוע T·m/A)",
         I1: "זרם בחוט 1 (זרם A)",
         I2: "זרם בחוט 2 (זרם A)",
         π: "פאי (קבוע חסר ממדים)",
         d: "מרחק בין חוטים (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "שטף חשמלי",
      equation_text: "Φ_E = EAcos(θ) (E אחיד)",
      summary: "מחשב שטף חשמלי (Φ_E = E * A * cos(θ))",
      description:
         "מחשב את השטף החשמלי דרך משטח שטוח בשדה חשמלי אחיד. הזווית צריכה להיות בין וקטור השדה החשמלי לווקטור השטח, ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Φ_E: "שטף חשמלי (שטף חשמלי N·m²/C)",
         E: "גודל שדה חשמלי (שדה חשמלי N/C)",
         A: "שטח (שטח m²)",
         θ: "זווית בין E לווקטור שטח (זווית rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "שטף מגנטי",
      equation_text: "Φ_B = BAcos(θ) (B אחיד)",
      summary: "מחשב שטף מגנטי (Φ_B = B * A * cos(θ))",
      description:
         "מחשב את השטף המגנטי דרך משטח שטוח בשדה מגנטי אחיד. הזווית צריכה להיות בין וקטור השדה המגנטי לווקטור השטח, ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Φ_B: "שטף מגנטי (שטף מגנטי Wb)",
         B: "גודל שדה מגנטי (שדה מגנטי T)",
         A: "שטח (שטח m²)",
         θ: "זווית בין B לווקטור שטח (זווית rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "כא\"מ תנועתי",
      equation_text: "ε = vBL (מוליך ישר)",
      summary: "מחשב כא\"מ תנועתי (fem = Blv)",
      description:
         "מחשב את גודל הכא\"מ המושרה במוליך הנע בניצב לשדה מגנטי. הערה - הפונקציה מחשבת את גודל Blv, תוך השמטת הסימן השלילי שלעיתים משמש לכיוון (חוק לנץ).",
      language_code: "he",
      subject: "Physics",
      variables: {
         ε: "גודל כא\"מ תנועתי (מתח V)",
         v: "מהירות מוליך (מהירות m/s)",
         B: "גודל שדה מגנטי (שדה מגנטי T)",
         L: "אורך מוליך (אורך m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "כא\"מ מושרה (חוק פרדיי)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "מחשב כא\"מ מושרה משינוי שטף (fem = -ΔΦ_B / Δt)",
      description: "מחשב את הכא\"מ המושרה על ידי שטף מגנטי משתנה על פי חוק ההשראה של פרדיי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ε: "כא\"מ מושרה (מתח V)",
         ΔΦ_B: "שינוי בשטף מגנטי (שטף מגנטי Wb)",
         Δt: "שינוי בזמן (זמן s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "כא\"מ מושרה מאינדוקציה",
      equation_text: "ε_L = -L dI / dt",
      summary: "מחשב כא\"מ מושרה משינוי זרם בסליל (fem = -L * ΔI / Δt)",
      description:
         "מחשב את הכא\"מ העצמי המושרה בסליל כתוצאה מזרם משתנה. הערה - הפונקציה נקראת `calculateInductance` אך מחזירה כא\"מ באמצעות משוואה זו. תיעוד מה שהיא מחזירה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ε_L: "כא\"מ מושרה בסליל (מתח V)",
         L: "אינדוקציה (אינדוקציה H)",
         ΔI: "שינוי בזרם (זרם A)",
         Δt: "שינוי בזמן (זמן s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "היגב קיבולי",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "מחשב היגב קיבולי (X_C = 1/(2πfC))",
      description: "מחשב את התנגדות הקבל לזרם חילופין.",
      language_code: "he",
      subject: "Physics",
      variables: {
         X_C: "היגב קיבולי (היגב Ω)",
         π: "פאי (קבוע חסר ממדים)",
         f: "תדר (תדר Hz)",
         C: "קיבול (קיבול F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "היגב השראתי",
      equation_text: "X_L = 2πfL",
      summary: "מחשב היגב השראתי (X_L = 2πfL))",
      description: "מחשב את התנגדות הסליל לזרם חילופין.",
      language_code: "he",
      subject: "Physics",
      variables: {
         X_L: "היגב השראתי (היגב Ω)",
         π: "פאי (קבוע חסר ממדים)",
         f: "תדר (תדר Hz)",
         L: "אינדוקציה (אינדוקציה H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "עכבה",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "מחשב עכבה (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "מחשב את ההתנגדות הכוללת לזרם במעגל AC הכולל התנגדות, היגב השראתי והיגב קיבולי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Z: "עכבה (עכבה Ω)",
         R: "התנגדות (התנגדות Ω)",
         X_L: "היגב השראתי (היגב Ω)",
         X_C: "היגב קיבולי (היגב Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "צפיפות",
      equation_text: "ρ = m / V",
      summary: "מחשב צפיפות (ρ = m/V)",
      description: "מחשב צפיפות על בסיס מסה ונפח.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ρ: "צפיפות (צפיפות kg/m³)",
         m: "מסה (מסה kg)",
         V: "נפח (נפח m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "לחץ",
      equation_text: "P = F / A",
      summary: "מחשב לחץ (P = F/A)",
      description: "מחשב לחץ על בסיס כוח מופעל על שטח.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "לחץ (לחץ Pa)",
         F: "כוח (כוח N)",
         A: "שטח (שטח m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "לחץ בנוזל",
      equation_text: "P = P₀ + ρgh",
      summary: "מחשב לחץ בנוזל (P = P0 + ρgh)",
      description: "מחשב את הלחץ המוחלט בעומק מסוים בנוזל.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "לחץ מוחלט (לחץ Pa)",
         P0: "לחץ אטמוספרי או לחץ פני שטח (לחץ Pa)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
         g: "תאוצת הכובד (תאוצה m/s²)",
         h: "עומק (אורך m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "ציפה",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "מחשב כוח ציפה (F_b = ρgV_displaced)",
      description:
         "מחשב את כוח הציפה המופעל על ידי נוזל על אובייקט שקוע או שקוע חלקית (עיקרון ארכימדס).",
      language_code: "he",
      subject: "Physics",
      variables: {
         F_B: "כוח ציפה (כוח N)",
         ρ_fluid: "צפיפות נוזל (צפיפות kg/m³)",
         V_submerged: "נפח שקוע (נפח m³)",
         g: "תאוצת הכובד (תאוצה m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "קצב זרימת מסה",
      equation_text: "ṁ = ρAv",
      summary: "מחשב קצב זרימת מסה (ṁ = Δm/Δt)",
      description: "מחשב את הקצב שבו מסה עוברת דרך נקודה ליחידת זמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ṁ: "קצב זרימת מסה (קצב זרימת מסה kg/s)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
         A: "שטח (שטח m²)",
         v: "מהירות נוזל (מהירות m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "קצב זרימת נפח",
      equation_text: "Q = Av",
      summary: "מחשב קצב זרימת נפח (Q = ΔV/Δt)",
      description: "מחשב את הקצב שבו נפח עובר דרך נקודה ליחידת זמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Q: "קצב זרימת נפח (קצב זרימת נפח m³/s)",
         A: "שטח (שטח m²)",
         v: "מהירות נוזל (מהירות m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "משוואת ברנולי",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "בודק את משוואת ברנולי (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "מאמת אם משוואת ברנולי נכונה עבור תכונות ותנאי הנוזל הנתונים בשתי נקודות. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "לחץ (לחץ Pa)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
         v: "מהירות נוזל (מהירות m/s)",
         g: "תאוצת הכובד (תאוצה m/s²)",
         y: "גובה (אורך m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "צמיגות דינמית",
      equation_text: "τ = μ * (dv/dy)",
      summary: "מחשב צמיגות דינמית (η = F * Δy / (A * Δvx))",
      description:
         "מחשב צמיגות דינמית על בסיס כוח, גרדיאנט מהירות ושטח. משוואה זו נגזרת ממתח גזירה/קצב עיוות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         μ: "צמיגות דינמית (צמיגות דינמית Pa·s)",
         F: "כוח (כוח N)",
         Δy: "מרחק ניצב לזרימה (אורך m)",
         A: "שטח (שטח m²)",
         Δvx: "שינוי במהירות (מהירות m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "צמיגות קינמטית",
      equation_text: "ν = μ / ρ",
      summary: "מחשב צמיגות קינמטית (ν = η / ρ)",
      description: "מחשב צמיגות קינמטית מצמיגות דינמית וצפיפות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ν: "צמיגות קינמטית (צמיגות קינמטית m²/s)",
         μ: "צמיגות דינמית (צמיגות דינמית Pa·s)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "כוח גרר",
      equation_text: "F_D = ½ρv²CdA",
      summary: "מחשב כוח גרר (F_d = 0.5 * ρ * C_A * v^2)",
      description: "מחשב את כוח הגרר על אובייקט הנע בנוזל.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F_D: "כוח גרר (כוח N)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
         v: "מהירות (מהירות m/s)",
         Cd: "מקדם גרר (חסר ממדים)",
         A: "שטח התייחסות (שטח m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "מספר מאך",
      equation_text: "M = v / c_sound",
      summary: "מחשב את מספר מאך (M = v/c)",
      description: "מחשב את מספר מאך, היחס בין מהירות האובייקט למהירות הקול בתווך.",
      language_code: "he",
      subject: "Physics",
      variables: {
         M: "מספר מאך (חסר ממדים)",
         v: "מהירות אובייקט (מהירות m/s)",
         c_sound: "מהירות קול בתווך (מהירות m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "מספר ריינולדס",
      equation_text: "Re = ρvd / μ",
      summary: "מחשב מספר ריינולדס (Re = (ρ * v * D) / η)",
      description:
         "מחשב את מספר ריינולדס, גודל חסר ממדים המשמש לחיזוי דפוסי זרימה במצבי זרימת נוזלים שונים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Re: "מספר ריינולדס (חסר ממדים)",
         ρ: "צפיפות נוזל (צפיפות kg/m³)",
         v: "מהירות (מהירות m/s)",
         d: "אורך אופייני (אורך m)",
         μ: "צמיגות דינמית (צמיגות דינמית Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "מספר פראוד",
      equation_text: "Fr = v / √(gL)",
      summary: "מחשב מספר פראוד (Fr = v / √(g * l))",
      description:
         "מחשב את מספר פראוד, גודל חסר ממדים המשמש לציון השפעת הכבידה על תנועת נוזלים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Fr: "מספר פראוד (חסר ממדים)",
         v: "מהירות (מהירות m/s)",
         g: "תאוצת הכובד (תאוצה m/s²)",
         L: "אורך אופייני (אורך m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "מתח פנים",
      equation_text: "γ = F / L",
      summary: "מחשב מתח פנים (γ = F / l)",
      description: "מחשב את מתח הפנים של נוזל על בסיס כוח ואורך.",
      language_code: "he",
      subject: "Physics",
      variables: {
         γ: "מתח פנים (מתח פנים N/m)",
         F: "כוח (כוח N)",
         L: "אורך (אורך m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "כבידה אוניברסלית (כוח)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "מחשב כוח כבידה (F = -Gm1m2/r^2)",
      description:
         "מחשב את כוח המשיכה הגרביטציוני בין שתי מסות נקודתיות. הערה - מחזיר ערך שלילי המציין משיכה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F: "כוח כבידה (כוח N)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         m1: "מסה 1 (מסה kg)",
         m2: "מסה 2 (מסה kg)",
         r: "מרחק בין מסות (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "שדה כבידה",
      equation_text: "g = GM / r² (גודל)",
      summary: "מחשב שדה כבידה (g = -Gm/r^2)",
      description:
         "מחשב את עוצמת שדה הכבידה במרחק ממסת נקודה. הערה - מחזיר ערך שלילי המציין כיוון אל המסה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         g: "גודל עוצמת שדה כבידה (שדה כבידה N/kg)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         M: "מסת מקור (מסה kg)",
         r: "מרחק ממסת מקור (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "אנרגיה פוטנציאלית כבידתית",
      equation_text: "U_g = -G m₁m₂ / r (כללי)",
      summary: "מחשב אנרגיה פוטנציאלית כבידתית בין שתי מסות (PE = -Gm1m2/r)",
      description: "מחשב את האנרגיה הפוטנציאלית הכבידתית של מערכת שתי מסות נקודתיות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         U_g: "אנרגיה פוטנציאלית כבידתית (אנרגיה J)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         m1: "מסה 1 (מסה kg)",
         m2: "מסה 2 (מסה kg)",
         r: "מרחק בין מסות (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "פוטנציאל כבידתי",
      equation_text: "V_g = -GM / r",
      summary: "מחשב פוטנציאל כבידתי (V_g = -Gm/r)",
      description: "מחשב את הפוטנציאל הכבידתי במרחק ממסת נקודה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         V_g: "פוטנציאל כבידתי (פוטנציאל כבידתי J/kg)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         M: "מסת מקור (מסה kg)",
         r: "מרחק ממסת מקור (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "מהירות מסלול",
      equation_text: "v_orbit = √(GM / r) (מעגלי)",
      summary: "מחשב מהירות מסלול (v = sqrt(Gm/r))",
      description: "מחשב את מהירותו של אובייקט במסלול מעגלי סביב מסה גדולה יותר.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_orbit: "מהירות מסלול (מהירות m/s)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         M: "מסת גוף מרכזי (מסה kg)",
         r: "רדיוס מסלול (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "מהירות מילוט",
      equation_text: "v_escape = √(2GM / r)",
      summary: "מחשב מהירות מילוט (v = sqrt(2Gm/r))",
      description:
         "מחשב את המהירות המינימלית הדרושה כדי להימלט מכוח המשיכה הגרביטציוני של מסה ממרחק נתון.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_escape: "מהירות מילוט (מהירות m/s)",
         G: "קבוע הכבידה (קבוע N·m²/kg²)",
         M: "מסת גוף מרכזי (מסה kg)",
         r: "מרחק מהמרכז (אורך m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "הולכת חום",
      equation_text: "Q/t = kAΔT/d",
      summary: "מחשב קצב הולכת חום (Q/t = (kAΔT) / L)",
      description:
         "מחשב את קצב מעבר החום באמצעות הולכה דרך חומר. הערה - הפונקציה מחשבת Q, בהנחה שפרק זמן מרומז על ידי שימוש רגיל במשוואה עבור קצב. התיעוד מציין Q, אך המשוואה היא בדרך כלל עבור Q/t. הבהרת הבדל זה. הפונקציה מחזירה את התוצאה של הצד הימני של משוואת הקצב.",
      language_code: "he",
      subject: "Physics",
      variables: {
         "Q/t": "קצב מעבר חום (הספק W)",
         k: "מוליכות חום (מוליכות חום W/(m·K))",
         A: "שטח (שטח m²)",
         ΔT: "הפרש טמפרטורות (הפרש טמפרטורות K)",
         d: "עובי (אורך m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "חוק סטפן-בולצמן",
      equation_text: "P = εσAT⁴",
      summary: "מחשב הספק קרינה תרמית (P = εσA(T^4 - T0^4))",
      description: "מחשב את קצב נטו של אנרגיה הנקראת על ידי אובייקט, בהתחשב בסביבתו.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "הספק נטו מקורן (הספק W)",
         ε: "אמיסיביות (חסר ממדים)",
         σ: "קבוע סטפן-בולצמן (קבוע W/(m²·K⁴))",
         A: "שטח פנים (שטח m²)",
         T: "טמפרטורת אובייקט (טמפרטורה K)",
         T0: "טמפרטורת סביבה (טמפרטורה K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "חוק וין (אורך גל מקסימלי)",
      equation_text: "λ_max = b/T",
      summary: "מחשב אורך גל שיא באמצעות חוק וין (λ_max = b/T)",
      description: "מחשב את אורך הגל שבו ספקטרום הפליטה של גוף שחור הוא מקסימלי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         λ_max: "אורך גל פליטה שיא (אורך m)",
         b: "קבוע ההסטה של וין (קבוע m·K)",
         T: "טמפרטורה (טמפרטורה K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "חוק וין (תדר מקסימלי)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "מחשב תדר שיא באמצעות חוק וין (f_max = b' * T)",
      description:
         "מחשב את התדר שבו ספקטרום הפליטה של גוף שחור הוא מקסימלי. הערה - גרסה זו משתמשת בקבוע וין מתוקן b'.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f_max: "תדר פליטה שיא (תדר Hz)",
         "b'": "קבוע וין מתוקן (קבוע Hz/K)",
         T: "טמפרטורה (טמפרטורה K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "מידע על משוואה (ספציפי)",
      equation_text: "לא ישים (מאחזר מידע, לא מחשב)",
      summary: "קבל מידע על משוואה לפי מזהה ושפה",
      description:
         "מאחזר פרטים עבור משוואה ספציפית על בסיס המזהה הייחודי שלה והשפה הרצויה. הערה - קוד השפה מופק מפרמטר הנתיב 'language_code'. הלוגיקה הפנימית המוצגת בקטע הקוד גם בוחנת פרמטר שאילתה 'lang', אך הגדרת Swagger זו מתעדת את פרמטרי הנתיב העיקריים.",
      language_code: "he",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "קבל את כל נקודות הקצה של המשוואות ב-API.",
      description: "מאחזר מידע מסכם על כל נקודות הקצה ב-API.",
      language_code: "he",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "מהירות",
      equation_text: "v = Δx / Δt",
      summary: "מחשב מהירות",
      description: "מחשב מהירות על בסיס העתק וזמן (v = Δs / Δt).",
      language_code: "he",
      subject: "Physics",
      variables: {
         v: "מהירות (מהירות m/s)",
         Δx: "העתק (אורך m)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "תאוצה",
      equation_text: "a = Δv / Δt",
      summary: "מחשב תאוצה",
      description: "מחשב תאוצה על בסיס שינוי במהירות וזמן (a = Δv / Δt).",
      language_code: "he",
      subject: "Physics",
      variables: {
         a: "תאוצה (תאוצה m/s²)",
         Δv: "שינוי במהירות (מהירות m/s)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "משוואה קינמטית (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "מחשב מהירות סופית (v = v0 + at)",
      description: "מחשב מהירות סופית באמצעות המשוואה הקינמטית הראשונה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v: "מהירות סופית (מהירות m/s)",
         v0: "מהירות התחלתית (מהירות m/s)",
         a: "תאוצה (תאוצה m/s²)",
         t: "זמן (זמן s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "משוואה קינמטית (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "מחשב מיקום סופי (s = s0 + v0t + 0.5at^2)",
      description: "מחשב מיקום סופי באמצעות המשוואה הקינמטית השנייה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         s: "מיקום סופי (אורך m)",
         s0: "מיקום התחלתי (אורך m)",
         v0: "מהירות התחלתית (מהירות m/s)",
         t: "זמן (זמן s)",
         a: "תאוצה (תאוצה m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "משוואה קינמטית (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "מחשב מהירות סופית בריבוע (v^2 = v0^2 + 2a(s - s0))",
      description: "מחשב מהירות סופית בריבוע באמצעות המשוואה הקינמטית השלישית. הערה - מחזיר v^2, לא v.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v: "מהירות סופית (מהירות m/s)",
         v0: "מהירות התחלתית (מהירות m/s)",
         a: "תאוצה (תאוצה m/s²)",
         Δs: "העתק (אורך m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "מהירות ממוצעת",
      equation_text: "v_avg = Δx / Δt",
      summary: "מחשב מהירות ממוצעת (v_avg = 0.5 * (v + v0))",
      description: "מחשב מהירות ממוצעת בהנחה של תאוצה קבועה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_avg: "מהירות ממוצעת (מהירות m/s)",
         v: "מהירות סופית (מהירות m/s)",
         v0: "מהירות התחלתית (מהירות m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "כוח (חוק ניוטון השני)",
      equation_text: "F_net = ma",
      summary: "מחשב כוח (F = ma)",
      description: "מחשב כוח באמצעות חוק ניוטון השני.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F_net: "כוח נטו (כוח N)",
         m: "מסה (מסה kg)",
         a: "תאוצה (תאוצה m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "משקל",
      equation_text: "W = mg",
      summary: "מחשב משקל (W = mg)",
      description: "מחשב את כוח הכבידה על אובייקט.",
      language_code: "he",
      subject: "Physics",
      variables: {
         W: "משקל (כוח N)",
         m: "מסה (מסה kg)",
         g: "תאוצת הכובד (תאוצה m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "חיכוך סטטי מקסימלי",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "מחשב חיכוך סטטי מקסימלי (F_s = μ_s * N)",
      description: "מחשב את כוח החיכוך הסטטי המקסימלי האפשרי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f_s_max: "כוח חיכוך סטטי מקסימלי (כוח N)",
         μ_s: "מקדם חיכוך סטטי (חסר ממדים)",
         F_N: "כוח נורמלי (כוח N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "חיכוך קינטי",
      equation_text: "f_k = μ_k * F_N",
      summary: "מחשב חיכוך קינטי (F_k = μ_k * N)",
      description: "מחשב את כוח החיכוך הקינטי הפועל על אובייקט נע.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f_k: "כוח חיכוך קינטי (כוח N)",
         μ_k: "מקדם חיכוך קינטי (חסר ממדים)",
         F_N: "כוח נורמלי (כוח N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "תנע",
      equation_text: "p = mv",
      summary: "מחשב תנע (p = mv)",
      description: "מחשב תנע קווי של אובייקט.",
      language_code: "he",
      subject: "Physics",
      variables: {
         p: "תנע (תנע kg·m/s)",
         m: "מסה (מסה kg)",
         v: "מהירות (מהירות m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "דחף",
      equation_text: "J = F_avg * Δt",
      summary: "מחשב דחף (J = F * Δt)",
      description: "מחשב דחף מכוח ומרווח זמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         J: "דחף (דחף N·s)",
         F_avg: "כוח ממוצע (כוח N)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "משפט הדחף והתנע",
      equation_text: "J = Δp",
      summary: "מאמת את משפט הדחף והתנע (F * Δt = m * Δv)",
      description: "בודק אם דחף שווה לשינוי בתנע עבור ערכים נתונים. מחזיר ערך בוליאני.",
      language_code: "he",
      subject: "Physics",
      variables: {
         J: "דחף (דחף N·s)",
         Δp: "שינוי בתנע (תנע kg·m/s)",
         F: "כוח (כוח N)",
         Δt: "מרווח זמן (זמן s)",
         m: "מסה (מסה kg)",
         Δv: "שינוי במהירות (מהירות m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "רדיואקטיביות",
      equation_text: "A = λN",
      summary: "מחשב פעילות ממוצעת בדעיכה רדיואקטיבית (A_avg = ΔN/Δt)",
      description:
         "מחשב את הפעילות הממוצעת (קצב הדעיכה) של דגימה רדיואקטיבית על פני מרווח זמן. הערה - הפונקציה משתמשת ב- `nValue` עבור מספר גרעינים ΔN וב- `tValue` עבור זמן Δt. זהו ממוצע מפושט על פני Δt, פעילות מיידית היא dN/dt = -λN.",
      language_code: "he",
      subject: "Physics",
      variables: {
         A_avg: "פעילות רדיואקטיבית ממוצעת (פעילות Bq)",
         ΔN: "מספר דעיכות (מספר חסר ממדים)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "זמן מחצית חיים",
      equation_text: "T_½ = ln(2) / λ",
      summary: "מחשב כמות שנותרה לאחר דעיכה (N = N0 * (1/2)^(t/T_half))",
      description:
         "מחשב את הכמות שנותרה של חומר לאחר זמן מסוים, על בסיס זמן מחצית החיים שלו. הערה - משתמש ב- `tValue` לזמן וב- `Thalf` לזמן מחצית חיים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         N: "כמות/גרעינים שנותרו (מספר)",
         N0: "כמות/גרעינים התחלתית (מספר)",
         t: "זמן שחלף (זמן s)",
         T_half: "זמן מחצית חיים (זמן s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "מנת קרינה נבלעת",
      equation_text: "D = dE / dm",
      summary: "מחשב מנת קרינה נבלעת (D = E/m)",
      description:
         "מחשב את המנה הנבלעת של קרינה על בסיס האנרגיה הנבלעת על ידי מסה. הערה - משתמש ב- `EValue` לאנרגיה וב- `mValue` למסה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         D: "מנה נבלעת (מנה נבלעת Gy)",
         E: "אנרגיה נבלעת (אנרגיה J)",
         m: "מסה (מסה kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "מנת קרינה שקולה",
      equation_text: "H = D * W_R",
      summary: "מחשב מנת קרינה שקולה (H = wR * D)",
      description:
         "מחשב את המנה השקולה, תוך התחשבות באפקטיביות הביולוגית של סוגי קרינה שונים. הערה - משתמש ב- `DValue` למנה נבלעת.",
      language_code: "he",
      subject: "Physics",
      variables: {
         H: "מנה שקולה (מנה שקולה Sv)",
         D: "מנה נבלעת (מנה נבלעת Gy)",
         W_R: "פקטור שקלול קרינה (חסר ממדים)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "מנת קרינה אפקטיבית",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "מחשב מנת קרינה אפקטיבית (E = wT * H)",
      description:
         "מחשב את המנה האפקטיבית, תוך התחשבות ברגישות של רקמות/איברים שונים לקרינה. הערה - משתמש ב- `HValue` למנה שקולה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "מנה אפקטיבית (מנה אפקטיבית Sv)",
         H_T: "מנה שקולה לרקמה/איבר T (מנה שקולה Sv)",
         W_T: "פקטור שקלול רקמה/איבר T (חסר ממדים)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "זווית צ'רנקוב",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "מחשב זווית צ'רנקוב (θ_C = arccos(c/nv_p))",
      description:
         "מחשב את זווית חרוט צ'רנקוב הנוצר על ידי חלקיק טעון הנע מהר יותר ממהירות האור בתווך. מחזיר זווית ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         θ_C: "זווית צ'רנקוב (זווית rad)",
         c: "מהירות אור בריק (מהירות m/s)",
         n: "מקדם שבירה של תווך (חסר ממדים)",
         v: "מהירות חלקיק (מהירות m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "פסגלי התאבכות (למשל, מיקום, מרווח)",
      equation_text: "Δy = λL / d (מרווח סדקים כפולים)",
      summary: "מחשב מיקום פסגלי התאבכות (y_n = (nλL)/d)",
      description: "מחשב את מיקום הפס הגלי המואר ה-n בדגם התאבכות יאנג עם סדקים כפולים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         y_n: "מיקום הפס הגלי המואר ה-n (אורך m)",
         n: "סדר פס גלי (מספר שלם חסר ממדים)",
         λ: "אורך גל (אורך m)",
         L: "מרחק למסך (אורך m)",
         d: "מרחק בין סדקים (אורך m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "מקדם שבירה",
      equation_text: "n = c / v",
      summary: "מחשב מקדם שבירה (n = c/v)",
      description:
         "מחשב את מקדם השבירה של תווך על בסיס מהירות האור בריק ובתווך.",
      language_code: "he",
      subject: "Physics",
      variables: {
         n: "מקדם שבירה (חסר ממדים)",
         c: "מהירות אור בריק (מהירות m/s)",
         v: "מהירות אור בתווך (מהירות m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "חוק סנל",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "מאמת את חוק סנל (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "בודק אם חוק סנל מתקיים עבור אור העובר בין שני תווכים עם מקדמי שבירה וזוויות נתונים. מחזיר ערך בוליאני. הזוויות צריכות להיות ברדיאנים. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         n1: "מקדם שבירה של תווך 1 (חסר ממדים)",
         θ1: "זווית בתווך 1 (זווית rad)",
         n2: "מקדם שבירה של תווך 2 (חסר ממדים)",
         θ2: "זווית בתווך 2 (זווית rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "זווית קריטית",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "מחשב זווית קריטית (θ_c = arcsin(n2/n1))",
      description:
         "מחשב את הזווית הקריטית להחזרה פנימית מלאה כאשר אור עובר מתווך עם מקדם n1 ל-n2 (n1 > n2). מחזיר זווית ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         θ_c: "זווית קריטית (זווית rad)",
         n1: "מקדם שבירה של תווך 1 (חסר ממדים)",
         n2: "מקדם שבירה של תווך 2 (חסר ממדים)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "מיקום דמות (אופטיקה)",
      equation_text: "1/f = 1/d_o + 1/d_i (עדשה דקה/מראה)",
      summary: "מאמת משוואת עדשה/מראה דקה (1/f = 1/do + 1/di)",
      description:
         "בודק אם הקשר בין אורך מוקד, מרחק אובייקט ומרחק דמות נכון. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f: "אורך מוקד (אורך m)",
         d_o: "מרחק אובייקט (אורך m)",
         d_i: "מרחק דמות (אורך m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "גודל דמות (הגדלה - אופטיקה)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "מאמת משוואת הגדלה (h'/h = di/do) (הפונקציה משתמשת h'/h = di/do)",
      description:
         "בודק אם הקשר בין גבהי אובייקט/דמות ומרחקים נכון. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה. הפונקציה משתמשת בקשר הגודל `h'/h = di/do` ולא במשוואת ההגדלה עם סימן. תיעוד מבוסס על יישום הפונקציה. שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         M: "הגדלה (חסר ממדים)",
         h_i: "גובה דמות (אורך m)",
         h_o: "גובה אובייקט (אורך m)",
         d_i: "מרחק דמות (אורך m)",
         d_o: "מרחק אובייקט (אורך m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "משוואת מראה כדורית",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "מחשב אורך מוקד של מראה כדורית (f = r/2)",
      description: "מחשב את אורך המוקד של מראה כדורית על בסיס רדיוס העקמומיות שלה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f: "אורך מוקד (אורך m)",
         r: "רדיוס עקמומיות (אורך m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "אנרגיה פוטנציאלית קפיצית",
      equation_text: "U_s = ½kx²",
      summary: "מחשב אנרגיה פוטנציאלית בקפיץ (PE = 0.5 * k * Δx^2)",
      description: "מחשב את האנרגיה הפוטנציאלית האלסטית האגורה בקפיץ אידיאלי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         U_s: "אנרגיה פוטנציאלית קפיצית (אנרגיה J)",
         k: "קבוע קפיץ (קבוע קפיץ N/m)",
         x: "העתק משיווי משקל (אורך m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "תקופת מתנד הרמוני פשוט (SHO)",
      equation_text: "T = 2π√(m/k)",
      summary: "מחשב תקופת SHO מסה-קפיץ (T = 2π√(m/k))",
      description:
         "מחשב את תקופת התנודה עבור מתנד הרמוני פשוט המורכב ממסה על קפיץ.",
      language_code: "he",
      subject: "Physics",
      variables: {
         T: "תקופה (זמן s)",
         π: "פאי (קבוע חסר ממדים)",
         m: "מסה (מסה kg)",
         k: "קבוע קפיץ (קבוע קפיץ N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "תקופת מטוטלת פשוטה",
      equation_text: "T = 2π√(L/g)",
      summary: "מחשב תקופת מטוטלת פשוטה (T = 2π√(l/g))",
      description: "מחשב את תקופת התנודה עבור מטוטלת פשוטה בזוויות קטנות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         T: "תקופה (זמן s)",
         π: "פאי (קבוע חסר ממדים)",
         L: "אורך מטוטלת (אורך m)",
         g: "תאוצת הכובד (תאוצה m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "תדר",
      equation_text: "f = 1 / T",
      summary: "מחשב תדר (f = 1/T)",
      description: "מחשב תדר מתקופת התנודה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f: "תדר (תדר Hz)",
         T: "תקופה (זמן s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "תדר זוויתי",
      equation_text: "ω = 2πf",
      summary: "מחשב תדר זוויתי (ω = 2πf)",
      description: "מחשב תדר זוויתי מתדר.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ω: "תדר זוויתי (מהירות זוויתית rad/s)",
         π: "פאי (קבוע חסר ממדים)",
         f: "תדר (תדר Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "גורם לורנץ",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "מחשב את גורם לורנץ (γ)",
      description: "מחשב את גורם לורנץ באמצעות γ = 1/√(1 - (v²/c²)). דורש v < c.",
      language_code: "he",
      subject: "Physics",
      variables: {
         γ: "גורם לורנץ (חסר ממדים)",
         v: "מהירות (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "התארכות זמן",
      equation_text: "Δt' = γ * Δt₀",
      summary: "מחשב התארכות זמן (t' = γ * t₀)",
      description:
         "מחשב את הזמן שחלף (t') עבור צופה במערכת ייחוס אינרציאלית S, בהינתן זמן עצמי (t₀) שנמדד במערכת ייחוס נעה S' ומהירות יחסית (v) בין S ל-S'. משתמש ב- t' = t₀ / √(1 - (v²/c²)). דורש t₀ ≥ 0 ו- |v| ≤ c. יחידות של t' יהיו זהות ליחידות של t₀, ויחידות של v ו-c חייבות להיות עקביות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Δt: "זמן מוארך (זמן s)",
         Δt0: "זמן עצמי (זמן s)",
         v: "מהירות יחסית (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "התכווצות אורך",
      equation_text: "L' = L₀ / γ",
      summary: "מחשב התכווצות אורך (L' = L₀ / γ)",
      description:
         "מחשב את אורך (L') של אובייקט הנצפה ממערכת ייחוס נעה S', בהינתן אורכו העצמי (L₀) שנמדד במערכת המנוחה שלו S והמהירות היחסית (v) בין S ל-S'. משתמש ב- L' = L₀ * √(1 - (v²/c²)). דורש L₀ ≥ 0 ו- |v| ≤ c. יחידות של L' יהיו זהות ליחידות של L₀, ויחידות של v ו-c חייבות להיות עקביות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         L: "אורך מכווץ (אורך m)",
         L0: "אורך עצמי (אורך m)",
         v: "מהירות יחסית (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "חיבור מהירויות יחסותי",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "מחשב חיבור מהירויות יחסותי",
      description:
         "מחשב את מהירות (u') של אובייקט ביחס למערכת ייחוס S', בהינתן מהירותו (u) ביחס למערכת ייחוס S, ומהירות (v) של מערכת ייחוס S ביחס למערכת ייחוס S'. משתמש במשוואה u' = (u + v) / (1 + uv/c²). מניח תנועה לאורך אותה קו. דורש c ≠ 0. יחידות של u, v ו-c חייבות להיות עקביות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         u: "מהירות אובייקט במערכת S (מהירות m/s)",
         v: "מהירות מערכת S ביחס ל-S' (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
         "u'": "מהירות אובייקט ביחס למערכת S' (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "אנרגיה כוללת יחסותית",
      equation_text: "E = γmc²",
      summary: "מחשב אנרגיה כוללת יחסותית (E)",
      description:
         "מחשב את האנרגיה הכוללת היחסותית של חלקיק עם מסה עצמית (m) הנע במהירות (v). משתמש במשוואה E = γmc² = mc² / √(1 - (v²/c²)). בעיקר עבור חלקיקים עם מסה עצמית (m > 0). דורש m ≥ 0 ו- |v| ≤ c. יחידות של m, v ו-c חייבות להיות עקביות כדי להשיג אנרגיה ביחידות המתאימות (למשל, m ב-kg, v/c ב-m/s נותן E ב-ג'אולים).",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "אנרגיה כוללת יחסותית (אנרגיה J)",
         m: "מסה עצמית (מסה kg)",
         v: "מהירות (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "תנע יחסותי",
      equation_text: "p = γmv",
      summary: "מחשב תנע יחסותי (p = γmv)",
      description:
         "מחשב את התנע היחסותי של חלקיק עם מסה עצמית (m) הנע במהירות (v). משתמש במשוואה p = γmv = mv / √(1 - (v²/c²)). בעיקר עבור חלקיקים עם מסה עצמית (m > 0). דורש m ≥ 0 ו- |v| ≤ c. יחידות של m, v ו-c חייבות להיות עקביות כדי להשיג תנע ביחידות המתאימות (למשל, m ב-kg, v ב-m/s, c ב-m/s נותן p ב-kg·m/s).",
      language_code: "he",
      subject: "Physics",
      variables: {
         p: "תנע יחסותי (תנע kg·m/s)",
         m: "מסה עצמית (מסה kg)",
         v: "מהירות (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "יחס אנרגיה-תנע",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "מחשב אנרגיה כוללת מתנע ומסה עצמית (E)",
      description:
         "מחשב את האנרגיה הכוללת היחסותית של חלקיק מהתנע היחסותי שלו (p) ומסה העצמית שלו (m). משתמש ביחס אנרגיה-תנע: E² = (pc)² + (mc²)². משוואה זו תקפה הן עבור חלקיקים מסיביים (m > 0) והן עבור חלקיקים חסרי מסה (m = 0). דורש p ≥ 0, m ≥ 0 ו- c > 0. יחידות של p, m ו-c חייבות להיות עקביות.\n",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "אנרגיה כוללת יחסותית (אנרגיה J)",
         p: "תנע יחסותי (תנע kg·m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
         m: "מסה עצמית (מסה kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "שוויון מסה-אנרגיה (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "מחשב שוויון מסה-אנרגיה (E₀ = mc²)",
      description:
         "מחשב את אנרגיית המנוחה (E₀) השקולה למסה עצמית נתונה (m) באמצעות המשוואה המפורסמת של איינשטיין E₀ = mc². דורש m ≥ 0 ו- c > 0. יחידות של m ו-c חייבות להיות עקביות (למשל, m ב-kg, c ב-m/s נותן E₀ ב-ג'אולים). נקודת קצה זו משתמשת בערך סטנדרטי ל-c (בערך 299792458 מטר/שנייה) אלא אם כן 'c' סופק במפורש.",
      language_code: "he",
      subject: "Physics",
      variables: {
         E0: "אנרגיית מנוחה (אנרגיה J)",
         m: "מסה עצמית (מסה kg)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "אנרגיה קינטית יחסותית",
      equation_text: "KE = (γ - 1)mc²",
      summary: "מחשב אנרגיה קינטית יחסותית (KE)",
      description:
         "מחשב את האנרגיה הקינטית היחסותית של חלקיק עם מסה עצמית (m) הנע במהירות (v). משתמש במשוואה KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc². בעיקר עבור חלקיקים עם מסה עצמית (m > 0). דורש m ≥ 0 ו- |v| < c. יחידות של m, v ו-c חייבות להיות עקביות כדי להשיג אנרגיה ביחידות המתאימות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE: "אנרגיה קינטית יחסותית (אנרגיה J)",
         m: "מסה עצמית (מסה kg)",
         v: "מהירות (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "אפקט דופלר יחסותי (אורך גל)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "מחשב אפקט דופלר יחסותי אורכי לאורך גל",
      description:
         "מחשב את אורך הגל הנצפה (λ') של אור הנפלט באורך גל עצמי (λ₀) ממקור הנע במהירות יחסית (v_rel) ישירות הרחק או לקראת הצופה. משתמש במשוואה λ' = λ₀√((1 + β)/(1 - β)), כאשר β = v_rel/c. v_rel > 0 עבור התרחקות (הסחה לאדום), v_rel < 0 עבור התקרבות (הסחה לכחול). דורש λ₀ > 0 ו- |v_rel| < c. יחידות של λ' יהיו זהות ליחידות של λ₀, ויחידות של v_rel ו-c חייבות להיות עקביות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         "λ'": "אורך גל נצפה (אורך m)",
         λ0: "אורך גל עצמי (אורך m)",
         v: "מהירות יחסית (מהירות m/s)",
         c: "מהירות אור בריק (מהירות m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "אנרגיית פוטון (מתדר)",
      equation_text: "E = hf",
      summary: "מחשב אנרגיית פוטון מתדר (E = hf)",
      description:
         "מחשב את אנרגיית (E) פוטון על בסיס התדר שלו (f). משתמש בקשר פלאנק E = hf. דורש f ≥ 0 ו- h > 0. יחידות של h ו-f חייבות להיות עקביות כדי להשיג אנרגיה ביחידות המתאימות (למשל, h ב-J·s, f ב-Hz (s⁻¹) נותן E ב-ג'אולים). נקודת קצה זו משתמשת בערך סטנדרטי ל-h (בערך 6.626e-34 J·s) אלא אם כן 'h' סופק במפורש.",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "אנרגיית פוטון (אנרגיה J)",
         h: "קבוע פלאנק (קבוע J·s)",
         f: "תדר (תדר Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "תנע פוטון (מאורך גל)",
      equation_text: "p = h / λ",
      summary: "מחשב תנע פוטון מאורך גל (p = h/λ)",
      description:
         "מחשב את תנע (p) פוטון על בסיס אורך הגל שלו (λ). משתמש בקשר p = h/λ. דורש λ > 0 ו- h > 0. יחידות של h ו-λ חייבות להיות עקביות כדי להשיג תנע ביחידות המתאימות (למשל, h ב-J·s, λ במטרים נותן p ב-kg·m/s). נקודת קצה זו משתמשת בערך סטנדרטי ל-h (בערך 6.626e-34 J·s) אלא אם כן 'h' סופק במפורש.",
      language_code: "he",
      subject: "Physics",
      variables: {
         p: "תנע פוטון (תנע kg·m/s)",
         h: "קבוע פלאנק (קבוע J·s)",
         λ: "אורך גל (אורך m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "אפקט פוטואלקטרי (KE מקסימלי)",
      equation_text: "KE_max = E_photon - φ",
      summary: "מחשב אנרגיה קינטית מקסימלית באפקט פוטואלקטרי (KE_max)",
      description:
         "מחשב את האנרגיה הקינטית המקסימלית (KE_max) של אלקטרונים נפלטות באפקט הפוטואלקטרי. משתמש במשוואה KE_max = E_photon - φ, כאשר E_photon היא אנרגיית הפוטון הנכנס ו-φ היא פונקציית העבודה של החומר. אם E_photon ≤ φ, לא נפלטו אלקטרונים, ו-KE_max הוא 0. דורש E_photon ≥ 0 ו-φ ≥ 0. יחידות של E_photon ו-φ חייבות להיות עקביות כדי להשיג KE_max באותן יחידות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE_max: "אנרגיה קינטית מקסימלית של אלקטרון (אנרגיה J)",
         E_photon: "אנרגיית פוטון (אנרגיה J)",
         φ: "פונקציית עבודה (אנרגיה J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "משוואת רידברג (מעבר אטומי)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "מחשב אנרגיה או מספר גל עבור מעברים באטומים דמויי מימן",
      description:
         "מחשב את הפרש האנרגיה (ΔE) או מספר הגל (1/λ) עבור מעבר אלקטרוני בין שתי רמות אנרגיה באטום דמוי מימן (Z). משתמש במשוואה תוצאה = קבוע * Z² * (1/n_initial² - 1/n_final²). אם 'קבוע' הוא יחידת אנרגיית רידברג (למשל, ב-eV), התוצאה היא הפרש האנרגיה E_final - E_initial (חיובי לבליעה, שלילי לפליטה). אם 'קבוע' הוא קבוע רידברג למספר גל (למשל, ב-m⁻¹), התוצאה היא מספר הגל 1/λ (חיובי לפליטה, שלילי לבליעה). דורש nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (מספרים שלמים), וקבוע > 0.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔE: "הפרש אנרגיה (אנרגיה J)",
         R_y: "קבוע רידברג (קבוע J או היפוך אורך m⁻¹)",
         Z: "מספר אטומי (מספר שלם חסר ממדים)",
         n1: "מספר קוונטי עיקרי התחלתי (מספר שלם חסר ממדים)",
         n2: "מספר קוונטי עיקרי סופי (מספר שלם חסר ממדים)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "מהירות זוויתית",
      equation_text: "ω = Δθ / Δt",
      summary: "מחשב מהירות זוויתית (ω = Δθ / Δt)",
      description: "מחשב מהירות זוויתית על בסיס שינוי בזווית וזמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ω: "מהירות זוויתית (מהירות זוויתית rad/s)",
         Δθ: "העתק זוויתי (זווית rad)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "תאוצה זוויתית",
      equation_text: "α = Δω / Δt",
      summary: "מחשב תאוצה זוויתית (α = Δω / Δt)",
      description: "מחשב תאוצה זוויתית על בסיס שינוי במהירות זוויתית וזמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         α: "תאוצה זוויתית (תאוצה זוויתית rad/s²)",
         Δω: "שינוי במהירות זוויתית (מהירות זוויתית rad/s)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "קינמטיקה סיבובית (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "מחשב מהירות זוויתית סופית (ω = ω0 + αt)",
      description: "מחשב מהירות זוויתית סופית באמצעות משוואה קינמטית סיבובית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ω: "מהירות זוויתית סופית (מהירות זוויתית rad/s)",
         ω0: "מהירות זוויתית התחלתית (מהירות זוויתית rad/s)",
         α: "תאוצה זוויתית (תאוצה זוויתית rad/s²)",
         t: "זמן (זמן s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "קינמטיקה סיבובית (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "מחשב מיקום זוויתי (θ = θ0 + ω0t + 0.5αt^2)",
      description: "מחשב מיקום זוויתי סופי באמצעות משוואה קינמטית סיבובית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         θ: "מיקום זוויתי סופי (זווית rad)",
         θ0: "מיקום זוויתי התחלתי (זווית rad)",
         ω0: "מהירות זוויתית התחלתית (מהירות זוויתית rad/s)",
         t: "זמן (זמן s)",
         α: "תאוצה זוויתית (תאוצה זוויתית rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "קינמטיקה סיבובית (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "מחשב מהירות זוויתית בריבוע (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "מחשב מהירות זוויתית סופית בריבוע באמצעות משוואה קינמטית סיבובית. הערה - מחזיר ω^2, לא ω.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ω: "מהירות זוויתית סופית (מהירות זוויתית rad/s)",
         ω0: "מהירות זוויתית התחלתית (מהירות זוויתית rad/s)",
         α: "תאוצה זוויתית (תאוצה זוויתית rad/s²)",
         Δθ: "העתק זוויתי (זווית rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "מהירות זוויתית ממוצעת",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "מחשב מהירות זוויתית ממוצעת (ω_avg = 0.5 * (ω + ω0))",
      description: "מחשב מהירות זוויתית ממוצעת בהנחה של תאוצה זוויתית קבועה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ω_avg: "מהירות זוויתית ממוצעת (מהירות זוויתית rad/s)",
         ω: "מהירות זוויתית סופית (מהירות זוויתית rad/s)",
         ω0: "מהירות זוויתית התחלתית (מהירות זוויתית rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "מומנט כוח (Torque)",
      equation_text: "τ = rFsin(θ)",
      summary: "מחשב מומנט כוח (τ = rF sin(θ))",
      description: "מחשב מומנט כוח על בסיס רדיוס, כוח והזווית ביניהם.",
      language_code: "he",
      subject: "Physics",
      variables: {
         τ: "מומנט כוח (מומנט כוח N·m)",
         r: "זרוע כוח (אורך m)",
         F: "כוח (כוח N)",
         θ: "זווית בין כוח לזרוע כוח (זווית rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "חוק ניוטון השני (סיבוב)",
      equation_text: "τ_net = Iα",
      summary: "מחשב מומנט כוח באמצעות החוק הסיבובי השני (τ = Iα)",
      description: "מחשב מומנט כוח על בסיס מומנט אינרציה ותאוצה זוויתית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         τ_net: "מומנט כוח נטו (מומנט כוח N·m)",
         I: "מומנט אינרציה (מומנט אינרציה kg·m²)",
         α: "תאוצה זוויתית (תאוצה זוויתית rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "מומנט אינרציה",
      equation_text: "I = mr² (מסת נקודה)",
      summary: "מחשב מומנט אינרציה למסת נקודה (I = mr^2)",
      description: "מחשב את מומנט האינרציה למסת נקודה יחידה ביחס לציר.",
      language_code: "he",
      subject: "Physics",
      variables: {
         I: "מומנט אינרציה (מומנט אינרציה kg·m²)",
         m: "מסה (מסה kg)",
         r: "מרחק מהציר (אורך m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "עבודה סיבובית",
      equation_text: "W = τΔθ (מומנט כוח קבוע)",
      summary: "מחשב עבודה סיבובית (W = τΔθ)",
      description: "מחשב את העבודה שנעשתה על ידי מומנט כוח קבוע לאורך העתק זוויתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         W: "עבודה סיבובית (אנרגיה J)",
         τ: "מומנט כוח (מומנט כוח N·m)",
         Δθ: "העתק זוויתי (זווית rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "הספק סיבובי",
      equation_text: "P = τω",
      summary: "מחשב הספק סיבובי (P = τω cos(θ))",
      description:
         "מחשב הספק סיבובי מיידי על בסיס מומנט כוח, מהירות זוויתית והזווית ביניהם.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "הספק סיבובי (הספק W)",
         τ: "מומנט כוח (מומנט כוח N·m)",
         ω: "מהירות זוויתית (מהירות זוויתית rad/s)",
         θ: "זווית בין מומנט כוח למהירות זוויתית (זווית rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "אנרגיה קינטית סיבובית",
      equation_text: "KE_rot = ½Iω²",
      summary: "מחשב אנרגיה קינטית סיבובית (KE = 0.5Iω^2)",
      description: "מחשב את האנרגיה הקינטית של אובייקט מסתובב.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE_rot: "אנרגיה קינטית סיבובית (אנרגיה J)",
         I: "מומנט אינרציה (מומנט אינרציה kg·m²)",
         ω: "מהירות זוויתית (מהירות זוויתית rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "תנע זוויתי",
      equation_text: "L = Iω",
      summary: "מחשב תנע זוויתי (L = mrv sin(θ))",
      description: "מחשב תנע זוויתי למסת נקודה הנעה ביחס לנקודה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         L: "תנע זוויתי (תנע זוויתי kg·m²/s)",
         m: "מסה (מסה kg)",
         r: "מרחק מציר/נקודה (אורך m)",
         v: "מהירות (מהירות m/s)",
         θ: "זווית בין וקטור רדיוס למהירות (זווית rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "דחף זוויתי",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "מחשב דחף זוויתי (J = τΔt)",
      description: "מחשב דחף זוויתי ממומנט כוח ומרווח זמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         J_angular: "דחף זוויתי (דחף זוויתי N·m·s)",
         τ_avg: "מומנט כוח ממוצע (מומנט כוח N·m)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "מודול יאנג",
      equation_text: "E = σ / ε",
      summary: "מחשב מודול יאנג (E = (F * L0) / (A * ΔL))",
      description: "מחשב את מודול יאנג (מודול אלסטיות) של חומר תחת מאמץ מתיחה או לחיצה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         E: "מודול יאנג (לחץ Pa)",
         F: "כוח (כוח N)",
         L0: "אורך מקורי (אורך m)",
         A: "שטח חתך רוחב (שטח m²)",
         ΔL: "שינוי באורך (אורך m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "מודול גזירה",
      equation_text: "G = τ / γ",
      summary: "מחשב מודול גזירה (G = (F * y) / (A * Δx))",
      description: "מחשב את מודול הגזירה (מודול קשיחות) של חומר תחת מאמץ גזירה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         G: "מודול גזירה (לחץ Pa)",
         F: "כוח (כוח N)",
         y: "מרחק ניצב לכוח (אורך m)",
         A: "שטח (שטח m²)",
         Δx: "העתק (אורך m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "מודול נופח",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "מחשב מודול נופח (K = (F * V0) / (A * ΔV))",
      description: "מחשב את מודול הנופח של חומר תחת לחץ אחיד (מאמץ הידרוסטטי).",
      language_code: "he",
      subject: "Physics",
      variables: {
         K: "מודול נופח (לחץ Pa)",
         ΔP: "שינוי בלחץ (לחץ Pa)",
         ΔV: "שינוי בנפח (נפח m³)",
         V0: "נפח מקורי (נפח m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "חוק הוק",
      equation_text: "F = kx",
      summary: "מחשב כוח של קפיץ (F = -k * Δx)",
      description:
         "מחשב את הכוח המחזיר המופעל על ידי קפיץ אידיאלי על פי חוק הוק. הערה - מחזיר ערך שלילי המציין שהכוח מנוגד לתנועה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         F: "כוח (כוח N)",
         k: "קבוע קפיץ (קבוע קפיץ N/m)",
         x: "העתק משיווי משקל (אורך m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "התפשטות תרמית של מוצקים (אורך)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "מחשב התפשטות תרמית קווית של מוצקים (ΔL = αL0ΔT)",
      description: "מחשב את שינוי האורך של חומר מוצק כתוצאה משינוי טמפרטורה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔL: "שינוי באורך (אורך m)",
         α: "מקדם התפשטות קווית (מקדם לטמפרטורה K⁻¹)",
         L0: "אורך מקורי (אורך m)",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "התפשטות תרמית של מוצקים (שטח)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "מחשב התפשטות תרמית שטחית של מוצקים (ΔA = 2αA0ΔT)",
      description:
         "מחשב את שינוי השטח של חומר מוצק כתוצאה משינוי טמפרטורה, באמצעות מקדם ההתפשטות הקווית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔA: "שינוי בשטח (שטח m²)",
         α: "מקדם התפשטות קווית (מקדם לטמפרטורה K⁻¹)",
         A0: "שטח מקורי (שטח m²)",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "התפשטות תרמית של מוצקים (נפח)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "מחשב התפשטות תרמית נפחית של מוצקים (ΔV = 3αV0ΔT)",
      description:
         "מחשב את שינוי הנפח של חומר מוצק כתוצאה משינוי טמפרטורה, באמצעות מקדם ההתפשטות הקווית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔV: "שינוי בנפח (נפח m³)",
         α: "מקדם התפשטות קווית (מקדם לטמפרטורה K⁻¹)",
         V0: "נפח מקורי (נפח m³)",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "התפשטות תרמית של נוזלים",
      equation_text: "ΔV = βV₀ΔT",
      summary: "מחשב התפשטות תרמית של נוזלים (ΔV = βV0ΔT)",
      description: "מחשב את שינוי הנפח של נוזל כתוצאה משינוי טמפרטורה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔV: "שינוי בנפח (נפח m³)",
         β: "מקדם התפשטות נפחית (מקדם לטמפרטורה K⁻¹)",
         V0: "נפח מקורי (נפח m³)",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "חום נתפס",
      equation_text: "Q = mcΔT",
      summary: "מחשב חום נתפס (Q = mcΔT)",
      description: "מחשב את החום שהועבר וגרם לשינוי טמפרטורה של חומר.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Q: "חום נתפס (אנרגיה J)",
         m: "מסה (מסה kg)",
         c: "קיבול חום סגולי (קיבול חום סגולי J/(kg·K))",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "חום כמוס",
      equation_text: "Q = mL",
      summary: "מחשב חום כמוס (Q = mL)",
      description: "מחשב את החום שהועבר במהלך שינוי פאזה של חומר.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Q: "חום כמוס (אנרגיה J)",
         m: "מסה (מסה kg)",
         L: "חום כמוס (אנרגיה סגולית J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "חוק הגז האידיאלי",
      equation_text: "PV = nRT",
      summary: "מאמת את חוק הגז האידיאלי (PV = nRT)",
      description:
         "בודק אם משוואת חוק הגז האידיאלי מתקיימת עבור הפרמטרים הנתונים. מחזיר ערך בוליאני. הערה - משתמש בשוויון קפדני (===) שעשוי להיות רגיש לדיוק נקודה צפה; שקול סובלנות עבור בדיקות בעולם האמיתי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "לחץ (לחץ Pa)",
         V: "נפח (נפח m³)",
         n: "מספר מולים (כמות חומר mol)",
         R: "קבוע הגז האידיאלי (קבוע J/(mol·K))",
         T: "טמפרטורה (טמפרטורה K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "אנרגיה קינטית מולקולרית",
      equation_text: "KE_avg = (3/2)kT",
      summary: "מחשב אנרגיה קינטית מולקולרית ממוצעת (KE = (3/2)kT)",
      description: "מחשב את האנרגיה הקינטית הטרנסלציונית הממוצעת למולקולה של גז אידיאלי.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE_avg: "אנרגיה קינטית מולקולרית ממוצעת (אנרגיה J)",
         k: "קבוע בולצמן (קבוע J/K)",
         T: "טמפרטורה (טמפרטורה K)",
         m: "מסה של מולקולה יחידה (מסה kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "מהירות מולקולרית (הסבירה ביותר)",
      equation_text: "v_p = √(2kT/m)",
      summary: "מחשב את המהירות המולקולרית הסבירה ביותר (v_p = √(2kT/m))",
      description:
         "מחשב את המהירות הסבירה ביותר של מולקולות בגז אידיאלי על פי התפלגות מקסוול-בולצמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_p: "מהירות מולקולרית סבירה ביותר (מהירות m/s)",
         k: "קבוע בולצמן (קבוע J/K)",
         T: "טמפרטורה (טמפרטורה K)",
         m: "מסה של מולקולה יחידה (מסה kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "מהירות מולקולרית (ממוצעת)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "מחשב מהירות מולקולרית ממוצעת (v_avg = √(8kT/(πm)))",
      description:
         "מחשב את המהירות הממוצעת של מולקולות בגז אידיאלי על פי התפלגות מקסוול-בולצמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_avg: "מהירות מולקולרית ממוצעת (מהירות m/s)",
         k: "קבוע בולצמן (קבוע J/K)",
         T: "טמפרטורה (טמפרטורה K)",
         π: "פאי (קבוע חסר ממדים)",
         m: "מסה של מולקולה יחידה (מסה kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "מהירות מולקולרית (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "מחשב מהירות מולקולרית שורש ממוצע הריבועים (v_rms = √(3kT/m))",
      description:
         "מחשב את מהירות שורש ממוצע הריבועים של מולקולות בגז אידיאלי על פי התפלגות מקסוול-בולצמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v_rms: "מהירות מולקולרית שורש ממוצע הריבועים (מהירות m/s)",
         k: "קבוע בולצמן (קבוע J/K)",
         T: "טמפרטורה (טמפרטורה K)",
         m: "מסה של מולקולה יחידה (מסה kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "שינוי באנרגיה פנימית",
      equation_text: "ΔU = Q - W",
      summary: "מחשב שינוי באנרגיה פנימית עבור גז אידיאלי חד-אטומי (ΔU = (3/2)nRΔT)",
      description:
         "מחשב את השינוי באנרגיה פנימית עבור גז אידיאלי חד-אטומי העובר שינוי טמפרטורה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         ΔU: "שינוי באנרגיה פנימית (אנרגיה J)",
         n: "מספר מולים (כמות חומר mol)",
         R: "קבוע הגז האידיאלי (קבוע J/(mol·K))",
         ΔT: "שינוי בטמפרטורה (הפרש טמפרטורות K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "עבודה תרמודינמית",
      equation_text: "W = PΔV (לחץ קבוע)",
      summary: "מחשב עבודה תרמודינמית שנעשתה על ידי המערכת בלחץ קבוע (W = -PΔV)",
      description:
         "מחשב את העבודה שנעשתה על ידי או על מערכת במהלך תהליך תרמודינמי בלחץ קבוע. הערה - המשוואה מחשבת את העבודה *שנעשתה על ידי* המערכת, חיובית להתפשטות, שלילית לדחיסה. הפונקציה מחזירה -P*deltaV, עקבי עם העבודה *שנעשתה על ידי* המערכת על פי המשוואה W = PΔV, עם סימן שלילי נוסף שעשוי לרמוז על עבודה *שנעשתה על* המערכת בהתאם למוסכמה. תיעוד פלט הפונקציה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         W: "עבודה תרמודינמית (אנרגיה J)",
         P: "לחץ (לחץ Pa)",
         ΔV: "שינוי בנפח (נפח m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "יעילות אמיתית",
      equation_text: "η = W_out / Q_in",
      summary: "מחשב יעילות של מנוע אמיתי (η_real = 1 - (Q_C / Q_H))",
      description: "מחשב את היעילות התרמית של מנוע חום על בסיס חום נבלע ונפלט.",
      language_code: "he",
      subject: "Physics",
      variables: {
         η: "יעילות (חסר ממדים)",
         Q_H: "חום נבלע ממאגר חם (אנרגיה J)",
         Q_C: "חום נפלט למאגר קר (אנרגיה J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "יעילות אידיאלית",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "מחשב יעילות אידיאלית (קרנו) (η_ideal = 1 - (T_C / T_H))",
      description:
         "מחשב את היעילות התיאורטית המקסימלית של מנוע חום הפועל בין שתי טמפרטורות (יעילות קרנו).",
      language_code: "he",
      subject: "Physics",
      variables: {
         η_ideal: "יעילות אידיאלית (חסר ממדים)",
         T_hot: "טמפרטורת מאגר חם (טמפרטורה K)",
         T_cold: "טמפרטורת מאגר קר (טמפרטורה K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "מקדם ביצועים אמיתי (COP)",
      equation_text: "COP_ref = Q_c / W (מקרר)",
      summary: "מחשב מקדם ביצועים עבור מקרר אמיתי (COP_real = QC / (QH - QC))",
      description: "מחשב את מקדם הביצועים עבור מקרר או משאבת חום אמיתיים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         COP_real: "מקדם ביצועים (חסר ממדים)",
         Q_C: "חום ממאגר קר (אנרגיה J)",
         Q_H: "חום למאגר חם (אנרגיה J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "מקדם ביצועים אידיאלי (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "מחשב מקדם ביצועים עבור מקרר אידיאלי (COP_ideal = TC / (TH - TC))",
      description:
         "מחשב את מקדם הביצועים התיאורטי המקסימלי עבור מקרר או משאבת חום הפועלים בין שתי טמפרטורות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         COP_ideal: "מקדם ביצועים אידיאלי (חסר ממדים)",
         T_h: "טמפרטורת מאגר חם (טמפרטורה K)",
         T_c: "טמפרטורת מאגר קר (טמפרטורה K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "מהירות גל תקופתי",
      equation_text: "v = fλ",
      summary: "מחשב מהירות גל (v = fλ)",
      description: "מחשב את מהירותו של גל תקופתי על בסיס התדר ואורך הגל שלו.",
      language_code: "he",
      subject: "Physics",
      variables: {
         v: "מהירות גל (מהירות m/s)",
         f: "תדר (תדר Hz)",
         λ: "אורך גל (אורך m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "עוצמת גל",
      equation_text: "I = P / A",
      summary: "מחשב עוצמה (I = P/A)",
      description: "מחשב את עוצמת גל (הספק ליחידת שטח).",
      language_code: "he",
      subject: "Physics",
      variables: {
         I: "עוצמה (עוצמה W/m²)",
         P: "הספק (הספק W)",
         A: "שטח (שטח m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "עוצמת קול (דציבלים)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "מחשב עוצמת קול בדציבלים (L = 10 log10(I/I0))",
      description: "מחשב את עוצמת הקול (עוצמת קול) יחסית לעוצמת התייחסות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         β: "עוצמת קול (עוצמת קול dB)",
         I: "עוצמה (עוצמה W/m²)",
         I0: "עוצמת התייחסות (עוצמה W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "עוצמת לחץ (עוצמת לחץ קול)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "מחשב עוצמת לחץ קול בדציבלים (L = 20 log10(ΔP/ΔP0))",
      description: "מחשב את עוצמת לחץ הקול יחסית לשינוי לחץ התייחסות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         L_p: "עוצמת לחץ קול (עוצמת לחץ dB)",
         P_rms: "תנודת לחץ RMS (לחץ Pa)",
         P_ref: "לחץ התייחסות (לחץ Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "אפקט דופלר (קול/לא יחסותי)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "מחשב פקטור מהירות אפקט דופלר ((c + v_o) / (c - v_s))",
      description:
         "מחשב את חלק פקטור המהירות של משוואת אפקט דופלר (f' = f * factor). מהירויות חיוביות עבור צופה הנע לכיוון מקור, מקור הנע לכיוון צופה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         f_obs: "תדר נצפה (תדר Hz)",
         f_source: "תדר מקור (תדר Hz)",
         v_wave: "מהירות גל (מהירות m/s)",
         v_observer: "מהירות צופה ביחס לתווך (מהירות m/s)",
         v_source: "מהירות מקור ביחס לתווך (מהירות m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "זווית מאך",
      equation_text: "sin(μ) = 1 / M",
      summary: "מחשב זווית מאך (θ_M = arcsin(c/v))",
      description:
         "מחשב את זווית חרוט מאך הנוצר על ידי אובייקט הנע מהר יותר ממהירות הקול. מחזיר זווית ברדיאנים.",
      language_code: "he",
      subject: "Physics",
      variables: {
         μ: "זווית מאך (זווית rad)",
         M: "מספר מאך (חסר ממדים)",
         c: "מהירות קול (מהירות m/s)",
         v: "מהירות אובייקט (מהירות m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "עבודה",
      equation_text: "W = Fdcos(θ)",
      summary: "מחשב עבודה שנעשתה (W = F * Δs * cos(θ))",
      description: "מחשב עבודה שנעשתה על בסיס כוח, העתק והזווית ביניהם.",
      language_code: "he",
      subject: "Physics",
      variables: {
         W: "עבודה שנעשתה (אנרגיה J)",
         F: "גודל כוח (כוח N)",
         d: "גודל העתק (אורך m)",
         θ: "זווית בין כוח להעתק (זווית rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "אנרגיה קינטית",
      equation_text: "KE = ½mv²",
      summary: "מחשב אנרגיה קינטית (KE = 0.5 * m * v^2)",
      description: "מחשב אנרגיה קינטית על בסיס מסה ומהירות.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE: "אנרגיה קינטית (אנרגיה J)",
         m: "מסה (מסה kg)",
         v: "מהירות (מהירות m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "אנרגיה קינטית (מתנע)",
      equation_text: "KE = p² / (2m)",
      summary: "מחשב אנרגיה קינטית מתנע (KE = p^2 / (2m))",
      description: "מחשב אנרגיה קינטית על בסיס תנע ומסה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         KE: "אנרגיה קינטית (אנרגיה J)",
         p: "תנע (תנע kg·m/s)",
         m: "מסה (מסה kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "אנרגיה פוטנציאלית כבידתית",
      equation_text: "U_g = mgh (קרוב לפני השטח)",
      summary: "מחשב אנרגיה פוטנציאלית כבידתית (PE = mgh)",
      description: "מחשב את השינוי באנרגיה פוטנציאלית כבידתית.",
      language_code: "he",
      subject: "Physics",
      variables: {
         U_g: "אנרגיה פוטנציאלית כבידתית (אנרגיה J)",
         m: "מסה (מסה kg)",
         g: "תאוצת הכובד (תאוצה m/s²)",
         h: "גובה (אורך m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "יעילות",
      equation_text: "יעילות = Output / Input",
      summary: "מחשב יעילות (η = W_out / W_in)",
      description: "מחשב את יעילות של תהליך או מכונה.",
      language_code: "he",
      subject: "Physics",
      variables: {
         Efficiency: "יעילות (חסר ממדים)",
         Output: "אנרגיה או הספק פלט שימושי (אנרגיה J או הספק W)",
         Input: "אנרגיה או הספק קלט כולל (אנרגיה J או הספק W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "הספק",
      equation_text: "P = W / t",
      summary: "מחשב הספק (P = ΔW / Δt)",
      description: "מחשב הספק ממוצע על בסיס שינוי בעבודה וזמן.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "הספק (הספק W)",
         ΔW: "שינוי בעבודה (אנרגיה J)",
         Δt: "מרווח זמן (זמן s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "הספק (P = Fv)",
      equation_text: "P = Fv",
      summary: "מחשב הספק מכוח ומהירות (P = Fv cos(θ))",
      description: "מחשב הספק מיידי על בסיס כוח, מהירות והזווית ביניהם.",
      language_code: "he",
      subject: "Physics",
      variables: {
         P: "הספק (הספק W)",
         F: "גודל כוח (כוח N)",
         v: "גודל מהירות (מהירות m/s)",
         θ: "זווית בין כוח למהירות (זווית rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = he;