const hi = [
   {
      equation_id: "centripetal-acceleration",
      name: "अभिकेंद्री त्वरण",
      equation_text: "a_c = v² / r",
      summary: "अभिकेंद्री त्वरण (a_c = v^2 / r) की गणना करता है",
      description:
         "रेखीय वेग और त्रिज्या का उपयोग करके वृत्ताकार पथ के केंद्र की ओर निर्देशित त्वरण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         a_c: "अभिकेंद्री त्वरण (त्वरण m/s²)",
         v: "रेखीय वेग (गति m/s)",
         r: "वृत्ताकार पथ की त्रिज्या (लंबाई m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "अभिकेंद्री त्वरण (कोणीय)",
      equation_text: "a_c = ω²r",
      summary: "कोणीय वेग का उपयोग करके अभिकेंद्री त्वरण (a_c = -ω^2 * r) की गणना करता है",
      description:
         "कोणीय वेग और त्रिज्या का उपयोग करके अभिकेंद्री त्वरण वेक्टर घटक की गणना करता है। नकारात्मक चिह्न केंद्र की ओर दिशा को इंगित करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         a_c: "अभिकेंद्री त्वरण (त्वरण m/s²)",
         ω: "कोणीय वेग (कोणीय वेग rad/s)",
         r: "वृत्ताकार पथ की त्रिज्या (लंबाई m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "कूलॉम का नियम (बल)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "कूलॉम के नियम (F = k * q1*q2 / r^2) का उपयोग करके विद्युत बल की गणना करता है",
      description:
         "दो बिंदु आवेशों के बीच विद्युत बल की गणना करता है। हस्ताक्षरित बल लौटाता है (प्रतिकर्षण के लिए सकारात्मक, आकर्षण के लिए नकारात्मक)।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F: "विद्युत बल (बल N)",
         k: "कूलॉम स्थिरांक (स्थिरांक N·m²/C²)",
         q1: "आवेश 1 (आवेश C)",
         q2: "आवेश 2 (आवेश C)",
         r: "आवेशों के बीच दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "विद्युत क्षेत्र",
      equation_text: "E = kq / r² (बिंदु आवेश)",
      summary: "बल से विद्युत क्षेत्र की गणना करता है (E = F_E/q)",
      description: "परीक्षण आवेश पर लगाए गए बल के आधार पर विद्युत क्षेत्र की तीव्रता की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "विद्युत क्षेत्र का परिमाण (विद्युत क्षेत्र N/C)",
         k: "कूलॉम स्थिरांक (स्थिरांक N·m²/C²)",
         q: "स्रोत आवेश (आवेश C)",
         r: "स्रोत आवेश से दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "विद्युत विभव",
      equation_text: "V = kq / r (बिंदु आवेश)",
      summary: "विभव ऊर्जा परिवर्तन से विद्युत विभव की गणना करता है (V = ΔU_E/q)",
      description:
         "प्रति इकाई आवेश पर विद्युत विभव ऊर्जा में परिवर्तन के आधार पर विद्युत विभव (वोल्टेज) की गणना करता है। नोट - फ़ंक्शन नाम `calculateElectricPotential` सही है, लेकिन पैरामीटर `deltaUE` परिवर्तन का तात्पर्य है, जबकि समीकरण आमतौर पर V=U_E/q या ΔV=ΔU_E/q होता है। समीकरण ΔV = ΔU_E/q पर आधारित दस्तावेज़ीकरण और ΔV लौटाना।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         V: "विद्युत विभव (वोल्टेज V)",
         k: "कूलॉम स्थिरांक (स्थिरांक N·m²/C²)",
         q: "स्रोत आवेश (आवेश C)",
         r: "स्रोत आवेश से दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "विद्युत क्षेत्र और विभव संबंध",
      equation_text: "E_x = -dV/dx",
      summary: "विभव अंतर से विद्युत क्षेत्र की गणना करता है (E = ΔV/d)",
      description:
         'एक दूरी पर विभव अंतर के आधार पर एक समान विद्युत क्षेत्र के परिमाण की गणना करता है। नोट - फ़ंक्शन नाम "फील्ड और पोटेंशियल" भ्रामक है; यह विद्युत क्षेत्र E की गणना करता है।',
      language_code: "hi",
      subject: "Physics",
      variables: {
         E_x: "विद्युत क्षेत्र घटक (विद्युत क्षेत्र V/m)",
         V: "विद्युत विभव (वोल्टेज V)",
         x: "स्थिति (लंबाई m)",
         ΔV: "विभव अंतर (वोल्टेज V)",
         d: "दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "धारिता",
      equation_text: "C = Q / V",
      summary: "धारिता की गणना करता है (C = Q/V)",
      description: "धारिता की गणना संग्रहीत आवेश और संधारित्र पर वोल्टेज के आधार पर करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C: "धारिता (धारिता F)",
         Q: "आवेश (आवेश C)",
         V: "वोल्टेज (वोल्टेज V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "प्लेट संधारित्र धारिता",
      equation_text: "C = ε₀A / d",
      summary: "समानांतर प्लेट संधारित्र धारिता की गणना करता है (C = (kε₀A)/d)",
      description:
         "एक परावैद्युत के साथ समानांतर प्लेट संधारित्र की धारिता की गणना करता है। नोट - फ़ंक्शन k * ε₀ को एकल इनपुट (`kEpsilon`) के रूप में उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C: "धारिता (धारिता F)",
         ε0: "मुक्त स्थान की परावैद्युतांक (स्थिरांक F/m)",
         k: "परावैद्युत स्थिरांक (विमाहीन)",
         A: "प्लेटों का क्षेत्रफल (क्षेत्रफल m²)",
         d: "प्लेटों के बीच दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "बेलनाकार संधारित्र धारिता",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "बेलनाकार संधारित्र धारिता की गणना करता है (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "एक परावैद्युत के साथ बेलनाकार संधारित्र की धारिता की गणना करता है। नोट - फ़ंक्शन k * ε₀ को एकल इनपुट (`kEpsilon`) के रूप में उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C: "धारिता (धारिता F)",
         π: "पाई (विमाहीन स्थिरांक)",
         ε0: "मुक्त स्थान की परावैद्युतांक (स्थिरांक F/m)",
         k: "परावैद्युत स्थिरांक (विमाहीन)",
         L: "सिलेंडरों की लंबाई (लंबाई m)",
         b: "बाहरी त्रिज्या (लंबाई m)",
         a: "आंतरिक त्रिज्या (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "गोलीय संधारित्र धारिता",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "गोलीय संधारित्र धारिता की गणना करता है (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "एक परावैद्युत के साथ गोलीय संधारित्र की धारिता की गणना करता है। नोट - फ़ंक्शन k * ε₀ को एकल इनपुट (`kEpsilon`) के रूप में उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C: "धारिता (धारिता F)",
         π: "पाई (विमाहीन स्थिरांक)",
         ε0: "मुक्त स्थान की परावैद्युतांक (स्थिरांक F/m)",
         k: "परावैद्युत स्थिरांक (विमाहीन)",
         a: "आंतरिक त्रिज्या (लंबाई m)",
         b: "बाहरी त्रिज्या (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "संधारित्र विभव ऊर्जा",
      equation_text: "U_C = ½CV²",
      summary: "संधारित्र विभव ऊर्जा समीकरणों को मान्य करता है (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "दिए गए Q, V और C के लिए एक संधारित्र में संग्रहीत विभव ऊर्जा के तीन सामान्य समीकरणों के समतुल्य होने की जांच करता है। बूलियन लौटाता है। नोट - सख्त समानता (===) का उपयोग करता है जो फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         U_C: "संधारित्र विभव ऊर्जा (ऊर्जा J)",
         Q: "आवेश (आवेश C)",
         V: "वोल्टेज (वोल्टेज V)",
         C: "धारिता (धारिता F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "विद्युत धारा",
      equation_text: "I = ΔQ / Δt",
      summary: "विद्युत धारा की गणना करता है (I = ΔQ/Δt)",
      description: "प्रति इकाई समय में एक बिंदु से गुजरने वाले आवेश की मात्रा के आधार पर विद्युत धारा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         I: "विद्युत धारा (धारा A)",
         ΔQ: "आवेश में परिवर्तन (आवेश C)",
         Δt: "समय में परिवर्तन (समय s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "आवेश घनत्व",
      equation_text: "ρ = Q / V (आयतन)",
      summary: "आवेश घनत्व की गणना करता है (ρ = Q/V)",
      description: "औसत आवेश घनत्व (प्रति इकाई आयतन आवेश) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ρ: "आयतन आवेश घनत्व (आवेश घनत्व C/m³)",
         Q: "कुल आवेश (आवेश C)",
         V: "आयतन (आयतन m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "धारा घनत्व",
      equation_text: "J = I / A",
      summary: "धारा घनत्व की गणना करता है (J = I/A)",
      description: "विद्युत धारा घनत्व (प्रति इकाई अनुप्रस्थ काट क्षेत्र धारा) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         J: "धारा घनत्व (धारा घनत्व A/m²)",
         I: "विद्युत धारा (धारा A)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "ओम का नियम",
      equation_text: "V = IR",
      summary: "ओम के नियम (R = V/I) का उपयोग करके प्रतिरोध की गणना करता है",
      description:
         "वोल्टेज और धारा के आधार पर प्रतिरोध की गणना करता है। नोट - फ़ंक्शन V और I से प्रतिरोध R की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         V: "वोल्टेज (वोल्टेज V)",
         I: "धारा (धारा A)",
         R: "प्रतिरोध (प्रतिरोध Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "प्रतिरोधकता और चालकता",
      equation_text: "ρ = RA / L",
      summary: "प्रतिरोधकता से चालकता की गणना करता है (σ = 1/ρ)",
      description: "प्रतिरोधकता (ρ) से चालकता (σ) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         σ: "चालकता (चालकता S/m)",
         ρ: "प्रतिरोधकता (प्रतिरोधकता Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "विद्युत प्रतिरोध",
      equation_text: "R = ρL / A",
      summary: "विद्युत प्रतिरोध की गणना करता है (R = ρ(l/A))",
      description:
         "एक चालक की प्रतिरोधकता, लंबाई और अनुप्रस्थ काट क्षेत्र के आधार पर उसके प्रतिरोध की गणना करता है। नोट - प्रतिरोधकता के लिए `rhoValue` का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         R: "प्रतिरोध (प्रतिरोध Ω)",
         ρ: "प्रतिरोधकता (प्रतिरोधकता Ω·m)",
         L: "लंबाई (लंबाई m)",
         A: "अनुप्रस्थ काट क्षेत्रफल (क्षेत्रफल m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "विद्युत शक्ति",
      equation_text: "P = IV",
      summary: "विद्युत शक्ति समीकरणों को मान्य करता है (P = VI = I^2R = V^2/R)",
      description:
         "दिए गए V, I और R के लिए विद्युत शक्ति के तीन सामान्य समीकरणों के समतुल्य होने की जांच करता है। बूलियन लौटाता है। नोट - सख्त समानता (===) का उपयोग करता है जो फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "विद्युत शक्ति (शक्ति W)",
         V: "वोल्टेज (वोल्टेज V)",
         I: "धारा (धारा A)",
         R: "प्रतिरोध (प्रतिरोध Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "श्रृंखला में प्रतिरोधक",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "श्रृंखला में प्रतिरोधकों के लिए कुल प्रतिरोध की गणना करता है (R_total = R1 + R2 + ...)",
      description: "श्रृंखला में जुड़े कई प्रतिरोधकों के लिए कुल समतुल्य प्रतिरोध की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         R_total: "कुल प्रतिरोध (प्रतिरोध Ω)",
         R: "व्यक्तिगत प्रतिरोध (प्रतिरोध Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "समानांतर में प्रतिरोधक",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "समानांतर में प्रतिरोधकों के लिए कुल प्रतिरोध की गणना करता है (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "समानांतर में जुड़े कई प्रतिरोधकों के लिए कुल समतुल्य प्रतिरोध की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         R_total: "कुल प्रतिरोध (प्रतिरोध Ω)",
         R: "व्यक्तिगत प्रतिरोध (प्रतिरोध Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "श्रृंखला में संधारित्र",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "श्रृंखला में संधारित्रों के लिए कुल धारिता की गणना करता है (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "श्रृंखला में जुड़े कई संधारित्रों के लिए कुल समतुल्य धारिता की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C_total: "कुल धारिता (धारिता F)",
         C: "व्यक्तिगत धारिता (धारिता F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "समानांतर में संधारित्र",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "समानांतर में संधारित्रों के लिए कुल धारिता की गणना करता है (C_total = C1 + C2 + ...)",
      description: "समानांतर में जुड़े कई संधारित्रों के लिए कुल समतुल्य धारिता की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         C_total: "कुल धारिता (धारिता F)",
         C: "व्यक्तिगत धारिता (धारिता F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "आवेश पर चुंबकीय बल",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "आवेशित कण पर चुंबकीय बल की गणना करता है (F = qvB sin(θ))",
      description:
         "गतिमान आवेशित कण पर लगाए गए चुंबकीय बल के परिमाण की गणना करता है। कोण रेडियन में होना चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F_B: "चुंबकीय बल का परिमाण (बल N)",
         q: "आवेश का परिमाण (आवेश C)",
         v: "वेग का परिमाण (गति m/s)",
         B: "चुंबकीय क्षेत्र का परिमाण (चुंबकीय क्षेत्र T)",
         θ: "वेग और चुंबकीय क्षेत्र के बीच का कोण (कोण rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "धारा पर चुंबकीय बल",
      equation_text: "F_B = ILBsin(θ)",
      summary: "धारावाही चालक पर चुंबकीय बल की गणना करता है (F = I l B sin(θ))",
      description:
         "चुंबकीय क्षेत्र में धारावाही सीधी तार पर लगाए गए चुंबकीय बल के परिमाण की गणना करता है। कोण रेडियन में होना चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F_B: "चुंबकीय बल का परिमाण (बल N)",
         I: "धारा (धारा A)",
         L: "चालक की लंबाई (लंबाई m)",
         B: "चुंबकीय क्षेत्र का परिमाण (चुंबकीय क्षेत्र T)",
         θ: "धारा और चुंबकीय क्षेत्र के बीच का कोण (कोण rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "बायो-सावर्ट नियम",
      equation_text: "B = μ₀I / (2πr) (अनंत सीधा तार)",
      summary: "एक धारा तत्व से चुंबकीय क्षेत्र की गणना करता है (dB = (μ₀I ds) / (4πr^2))",
      description:
         "त्रिज्या वेक्टर के लंबवत एक विभेदक धारा तत्व से चुंबकीय क्षेत्र में योगदान के परिमाण की गणना करता है। नोट - फ़ंक्शन `(μ₀ * I * ds) / (4 * π * r^2)` को लागू करता है, जो विभेदक रूप में अक्सर मौजूद sin(θ) पद को छोड़ देता है, प्रभावी रूप से θ=90 डिग्री मानकर या उस विशिष्ट तल में केवल त्रिज्या वेक्टर के लंबवत घटक की गणना करता है। लागू किए गए समीकरण को प्रलेखित किया जा रहा है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         dB: "चुंबकीय क्षेत्र योगदान का परिमाण (चुंबकीय क्षेत्र T)",
         μ0: "मुक्त स्थान की पारगम्यता (स्थिरांक T·m/A)",
         I: "धारा (धारा A)",
         ds: "धारा तत्व की विभेदक लंबाई (लंबाई m)",
         r: "धारा तत्व से दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "परिनालिका का चुंबकीय क्षेत्र",
      equation_text: "B = μ₀nI (अंदर, आदर्श)",
      summary: "एक लंबी परिनालिका के अंदर चुंबकीय क्षेत्र की गणना करता है (B = μ₀nI)",
      description: "एक लंबी आदर्श परिनालिका के अंदर चुंबकीय क्षेत्र के परिमाण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         B: "परिनालिका के अंदर चुंबकीय क्षेत्र की तीव्रता (चुंबकीय क्षेत्र T)",
         μ0: "मुक्त स्थान की पारगम्यता (स्थिरांक T·m/A)",
         n: "प्रति इकाई लंबाई घुमावों की संख्या (प्रति लंबाई संख्या m⁻¹)",
         I: "धारा (धारा A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "सीधे तार का चुंबकीय क्षेत्र",
      equation_text: "B = μ₀I / (2πr) (अनंत तार)",
      summary: "एक अनंत सीधे तार से चुंबकीय क्षेत्र की गणना करता है (B = (μ₀I)/(2πr))",
      description:
         "धारावाही लंबी, सीधी तार से कुछ दूरी पर चुंबकीय क्षेत्र के परिमाण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         B: "सीधे तार से चुंबकीय क्षेत्र की तीव्रता (चुंबकीय क्षेत्र T)",
         μ0: "मुक्त स्थान की पारगम्यता (स्थिरांक T·m/A)",
         I: "धारा (धारा A)",
         π: "पाई (विमाहीन स्थिरांक)",
         r: "तार से दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "समानांतर तारों के बीच बल",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "समानांतर तारों के बीच प्रति इकाई लंबाई बल की गणना करता है (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "धारावाही दो लंबी, समानांतर तारों के बीच प्रति इकाई लंबाई बल के परिमाण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         "F/L": "प्रति इकाई लंबाई बल (प्रति लंबाई बल N/m)",
         μ0: "मुक्त स्थान की पारगम्यता (स्थिरांक T·m/A)",
         I1: "तार 1 में धारा (धारा A)",
         I2: "तार 2 में धारा (धारा A)",
         π: "पाई (विमाहीन स्थिरांक)",
         d: "तारों के बीच दूरी (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "विद्युत प्रवाह",
      equation_text: "Φ_E = EAcos(θ) (समान E)",
      summary: "विद्युत प्रवाह की गणना करता है (Φ_E = E * A * cos(θ))",
      description:
         "एक समान विद्युत क्षेत्र में एक समतल सतह से गुजरने वाले विद्युत प्रवाह की गणना करता है। कोण विद्युत क्षेत्र वेक्टर और क्षेत्र वेक्टर के बीच होना चाहिए, रेडियन में।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Φ_E: "विद्युत प्रवाह (विद्युत प्रवाह N·m²/C)",
         E: "विद्युत क्षेत्र का परिमाण (विद्युत क्षेत्र N/C)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         θ: "E और क्षेत्र वेक्टर के बीच का कोण (कोण rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "चुंबकीय प्रवाह",
      equation_text: "Φ_B = BAcos(θ) (समान B)",
      summary: "चुंबकीय प्रवाह की गणना करता है (Φ_B = B * A * cos(θ))",
      description:
         "एक समान चुंबकीय क्षेत्र में एक समतल सतह से गुजरने वाले चुंबकीय प्रवाह की गणना करता है। कोण चुंबकीय क्षेत्र वेक्टर और क्षेत्र वेक्टर के बीच होना चाहिए, रेडियन में।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Φ_B: "चुंबकीय प्रवाह (चुंबकीय प्रवाह Wb)",
         B: "चुंबकीय क्षेत्र का परिमाण (चुंबकीय क्षेत्र T)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         θ: "B और क्षेत्र वेक्टर के बीच का कोण (कोण rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "गतिशील ईएमएफ",
      equation_text: "ε = vBL (सीधा चालक)",
      summary: "गतिशील ईएमएफ की गणना करता है (emf = Blv)",
      description:
         "चुंबकीय क्षेत्र के लंबवत गतिमान चालक में प्रेरित ईएमएफ के परिमाण की गणना करता है। नोट - फ़ंक्शन Blv परिमाण की गणना करता है, दिशा के लिए कभी-कभी उपयोग किए जाने वाले ऋणात्मक चिह्न (लेन्ज़ का नियम) को छोड़ देता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ε: "गतिशील ईएमएफ का परिमाण (वोल्टेज V)",
         v: "चालक की गति (गति m/s)",
         B: "चुंबकीय क्षेत्र का परिमाण (चुंबकीय क्षेत्र T)",
         L: "चालक की लंबाई (लंबाई m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "प्रेरित ईएमएफ (फैराडे का नियम)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "बदलते फ्लक्स से प्रेरित ईएमएफ की गणना करता है (emf = -ΔΦ_B / Δt)",
      description: "फैराडे के प्रेरण के नियम के अनुसार बदलते चुंबकीय फ्लक्स द्वारा प्रेरित ईएमएफ की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ε: "प्रेरित ईएमएफ (वोल्टेज V)",
         ΔΦ_B: "चुंबकीय फ्लक्स में परिवर्तन (चुंबकीय फ्लक्स Wb)",
         Δt: "समय में परिवर्तन (समय s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "प्रेरण से प्रेरित ईएमएफ",
      equation_text: "ε_L = -L dI / dt",
      summary: "एक इंडक्टर में बदलते धारा से प्रेरित ईएमएफ की गणना करता है (emf = -L * ΔI / Δt)",
      description:
         "एक इंडक्टर में बदलते धारा के कारण स्व-प्रेरित ईएमएफ की गणना करता है। नोट - फ़ंक्शन का नाम `calculateInductance` है, लेकिन इस समीकरण का उपयोग करके ईएमएफ लौटाता है। जो लौटाता है उसे प्रलेखित किया जा रहा है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ε_L: "इंडक्टर में प्रेरित ईएमएफ (वोल्टेज V)",
         L: "प्रेरकत्व (प्रेरकत्व H)",
         ΔI: "धारा में परिवर्तन (धारा A)",
         Δt: "समय में परिवर्तन (समय s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "संधारित्रिक प्रतिघात",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "संधारित्रिक प्रतिघात की गणना करता है (X_C = 1/(2πfC))",
      description: "एक संधारित्र का प्रत्यावर्ती धारा के प्रति विरोध की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         X_C: "संधारित्रिक प्रतिघात (प्रतिघात Ω)",
         π: "पाई (विमाहीन स्थिरांक)",
         f: "आवृत्ति (आवृत्ति Hz)",
         C: "धारिता (धारिता F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "प्रेरकत्विक प्रतिघात",
      equation_text: "X_L = 2πfL",
      summary: "प्रेरकत्विक प्रतिघात की गणना करता है (X_L = 2πfL))",
      description: "एक इंडक्टर का प्रत्यावर्ती धारा के प्रति विरोध की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         X_L: "प्रेरकत्विक प्रतिघात (प्रतिघात Ω)",
         π: "पाई (विमाहीन स्थिरांक)",
         f: "आवृत्ति (आवृत्ति Hz)",
         L: "प्रेरकत्व (प्रेरकत्व H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "प्रतिबाधा",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "प्रतिबाधा की गणना करता है (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "एक AC सर्किट में प्रतिरोध, प्रेरकत्विक प्रतिघात और संधारित्रिक प्रतिघात सहित धारा प्रवाह के प्रति कुल विरोध की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Z: "प्रतिबाधा (प्रतिबाधा Ω)",
         R: "प्रतिरोध (प्रतिरोध Ω)",
         X_L: "प्रेरकत्विक प्रतिघात (प्रतिघात Ω)",
         X_C: "संधारित्रिक प्रतिघात (प्रतिघात Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "घनत्व",
      equation_text: "ρ = m / V",
      summary: "घनत्व की गणना करता है (ρ = m/V)",
      description: "द्रव्यमान और आयतन के आधार पर घनत्व की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ρ: "घनत्व (घनत्व kg/m³)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         V: "आयतन (आयतन m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "दबाव",
      equation_text: "P = F / A",
      summary: "दबाव की गणना करता है (P = F/A)",
      description: "एक क्षेत्र पर लगाए गए बल के आधार पर दबाव की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "दबाव (दबाव Pa)",
         F: "बल (बल N)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "तरल में दबाव",
      equation_text: "P = P₀ + ρgh",
      summary: "तरल में दबाव की गणना करता है (P = P0 + ρgh)",
      description: "एक तरल में एक निश्चित गहराई पर पूर्ण दबाव की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "पूर्ण दबाव (दबाव Pa)",
         P0: "वायुमंडलीय या सतह का दबाव (दबाव Pa)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
         h: "गहराई (लंबाई m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "उत्प्लावन",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "उत्प्लावन बल की गणना करता है (F_b = ρgV_displaced)",
      description:
         "एक द्रव द्वारा डूबे हुए या आंशिक रूप से डूबे हुए पिंड पर लगाए गए उत्प्लावन बल (आर्किमिडीज का सिद्धांत) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F_B: "उत्प्लावन बल (बल N)",
         ρ_fluid: "द्रव घनत्व (घनत्व kg/m³)",
         V_submerged: "डूबा हुआ आयतन (आयतन m³)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "द्रव्यमान प्रवाह दर",
      equation_text: "ṁ = ρAv",
      summary: "द्रव्यमान प्रवाह दर की गणना करता है (ṁ = Δm/Δt)",
      description: "प्रति इकाई समय में एक बिंदु से गुजरने वाले द्रव्यमान की दर की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ṁ: "द्रव्यमान प्रवाह दर (द्रव्यमान प्रवाह दर kg/s)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         v: "द्रव वेग (गति m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "आयतन प्रवाह दर",
      equation_text: "Q = Av",
      summary: "आयतन प्रवाह दर की गणना करता है (Q = ΔV/Δt)",
      description: "प्रति इकाई समय में एक बिंदु से गुजरने वाले आयतन की दर की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Q: "आयतन प्रवाह दर (आयतन प्रवाह दर m³/s)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         v: "द्रव वेग (गति m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "बरनौली का समीकरण",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "बरनौली के समीकरण को मान्य करता है (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "दो बिंदुओं पर दिए गए द्रव गुणों और स्थितियों के लिए बरनौली का समीकरण सत्य है या नहीं, यह मान्य करता है। बूलियन लौटाता है। नोट - फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकने वाली सख्त समानता (===) का उपयोग करता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "दबाव (दबाव Pa)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
         v: "द्रव वेग (गति m/s)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
         y: "ऊंचाई (लंबाई m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "गतिशील श्यानता",
      equation_text: "τ = μ * (dv/dy)",
      summary: "गतिशील श्यानता की गणना करता है (η = F * Δy / (A * Δvx))",
      description:
         "बल, वेग प्रवणता और क्षेत्रफल के आधार पर गतिशील श्यानता की गणना करता है। यह समीकरण अपरूपण प्रतिबल/विकृति दर से व्युत्पन्न होता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         μ: "गतिशील श्यानता (गतिशील श्यानता Pa·s)",
         F: "बल (बल N)",
         Δy: "प्रवाह के लंबवत दूरी (लंबाई m)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         Δvx: "वेग में परिवर्तन (गति m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "काइनेमेटिक श्यानता",
      equation_text: "ν = μ / ρ",
      summary: "काइनेमेटिक श्यानता की गणना करता है (ν = η / ρ)",
      description: "गतिशील श्यानता और घनत्व से काइनेमेटिक श्यानता की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ν: "काइनेमेटिक श्यानता (काइनेमेटिक श्यानता m²/s)",
         μ: "गतिशील श्यानता (गतिशील श्यानता Pa·s)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "घर्षण बल",
      equation_text: "F_D = ½ρv²CdA",
      summary: "घर्षण बल की गणना करता है (F_d = 0.5 * ρ * C_A * v^2)",
      description: "द्रव में गतिमान वस्तु पर लगने वाले घर्षण बल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F_D: "घर्षण बल (बल N)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
         v: "वेग (गति m/s)",
         Cd: "घर्षण गुणांक (विमाहीन)",
         A: "संदर्भ क्षेत्रफल (क्षेत्रफल m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "माच संख्या",
      equation_text: "M = v / c_sound",
      summary: "माच संख्या की गणना करता है (M = v/c)",
      description: "माच संख्या की गणना करता है, जो किसी वस्तु की गति का माध्यम में ध्वनि की गति से अनुपात है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         M: "माच संख्या (विमाहीन)",
         v: "वस्तु की गति (गति m/s)",
         c_sound: "माध्यम में ध्वनि की गति (गति m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "रेनॉल्ड्स संख्या",
      equation_text: "Re = ρvd / μ",
      summary: "रेनॉल्ड्स संख्या की गणना करता है (Re = (ρ * v * D) / η)",
      description:
         "रेनॉल्ड्स संख्या की गणना करता है, जो एक विमाहीन मात्रा है जिसका उपयोग विभिन्न द्रव प्रवाह स्थितियों में प्रवाह पैटर्न की भविष्यवाणी करने के लिए किया जाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Re: "रेनॉल्ड्स संख्या (विमाहीन)",
         ρ: "द्रव घनत्व (घनत्व kg/m³)",
         v: "वेग (गति m/s)",
         d: "विशेषता लंबाई (लंबाई m)",
         μ: "गतिशील श्यानता (गतिशील श्यानता Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "फ्रूड संख्या",
      equation_text: "Fr = v / √(gL)",
      summary: "फ्रूड संख्या की गणना करता है (Fr = v / √(g * l))",
      description:
         "फ्रूड संख्या की गणना करता है, जो एक विमाहीन मात्रा है जिसका उपयोग द्रव गति पर गुरुत्वाकर्षण के प्रभाव को इंगित करने के लिए किया जाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Fr: "फ्रूड संख्या (विमाहीन)",
         v: "वेग (गति m/s)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
         L: "विशेषता लंबाई (लंबाई m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "पृष्ठ तनाव",
      equation_text: "γ = F / L",
      summary: "पृष्ठ तनाव की गणना करता है (γ = F / l)",
      description: "बल और लंबाई के आधार पर एक तरल के पृष्ठ तनाव की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         γ: "पृष्ठ तनाव (पृष्ठ तनाव N/m)",
         F: "बल (बल N)",
         L: "लंबाई (लंबाई m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "सार्वभौमिक गुरुत्वाकर्षण (बल)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "गुरुत्वाकर्षण बल की गणना करता है (F = -Gm1m2/r^2)",
      description:
         "दो बिंदु द्रव्यमानों के बीच आकर्षक गुरुत्वाकर्षण बल की गणना करता है। नोट - आकर्षण को इंगित करने वाला एक नकारात्मक मान लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F: "गुरुत्वाकर्षण बल (बल N)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         m1: "द्रव्यमान 1 (द्रव्यमान kg)",
         m2: "द्रव्यमान 2 (द्रव्यमान kg)",
         r: "द्रव्यमानों के बीच दूरी (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "गुरुत्वाकर्षण क्षेत्र",
      equation_text: "g = GM / r² (परिमाण)",
      summary: "गुरुत्वाकर्षण क्षेत्र की गणना करता है (g = -Gm/r^2)",
      description:
         "एक बिंदु द्रव्यमान से दूरी पर गुरुत्वाकर्षण क्षेत्र की तीव्रता की गणना करता है। नोट - द्रव्यमान की ओर दिशा को इंगित करने वाला एक नकारात्मक मान लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         g: "गुरुत्वाकर्षण क्षेत्र की तीव्रता का परिमाण (गुरुत्वाकर्षण क्षेत्र N/kg)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         M: "स्रोत द्रव्यमान (द्रव्यमान kg)",
         r: "स्रोत द्रव्यमान से दूरी (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "गुरुत्वाकर्षण विभव ऊर्जा",
      equation_text: "U_g = -G m₁m₂ / r (सामान्य)",
      summary: "दो द्रव्यमानों के बीच गुरुत्वाकर्षण विभव ऊर्जा की गणना करता है (PE = -Gm1m2/r)",
      description: "दो बिंदु द्रव्यमानों की प्रणाली की गुरुत्वाकर्षण विभव ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         U_g: "गुरुत्वाकर्षण विभव ऊर्जा (ऊर्जा J)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         m1: "द्रव्यमान 1 (द्रव्यमान kg)",
         m2: "द्रव्यमान 2 (द्रव्यमान kg)",
         r: "द्रव्यमानों के बीच दूरी (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "गुरुत्वाकर्षण विभव",
      equation_text: "V_g = -GM / r",
      summary: "गुरुत्वाकर्षण विभव की गणना करता है (V_g = -Gm/r)",
      description: "एक बिंदु द्रव्यमान से दूरी पर गुरुत्वाकर्षण विभव की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         V_g: "गुरुत्वाकर्षण विभव (गुरुत्वाकर्षण विभव J/kg)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         M: "स्रोत द्रव्यमान (द्रव्यमान kg)",
         r: "स्रोत द्रव्यमान से दूरी (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "कक्षीय गति",
      equation_text: "v_orbit = √(GM / r) (वृत्ताकार)",
      summary: "कक्षीय गति की गणना करता है (v = sqrt(Gm/r))",
      description: "बड़े द्रव्यमान के चारों ओर वृत्ताकार कक्षा में वस्तु की गति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_orbit: "कक्षीय गति (गति m/s)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         M: "केंद्रीय पिंड का द्रव्यमान (द्रव्यमान kg)",
         r: "कक्षीय त्रिज्या (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "पलायन वेग",
      equation_text: "v_escape = √(2GM / r)",
      summary: "पलायन वेग की गणना करता है (v = sqrt(2Gm/r))",
      description:
         "दिए गए दूरी से एक द्रव्यमान के गुरुत्वाकर्षण खिंचाव से बचने के लिए आवश्यक न्यूनतम गति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_escape: "पलायन वेग (गति m/s)",
         G: "गुरुत्वाकर्षण स्थिरांक (स्थिरांक N·m²/kg²)",
         M: "केंद्रीय पिंड का द्रव्यमान (द्रव्यमान kg)",
         r: "केंद्र से दूरी (लंबाई m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "ऊष्मा चालन",
      equation_text: "Q/t = kAΔT/d",
      summary: "ऊष्मा चालन दर की गणना करता है (Q/t = (kAΔT) / L)",
      description:
         "एक सामग्री के माध्यम से चालन द्वारा ऊष्मा स्थानांतरण की दर की गणना करता है। नोट - फ़ंक्शन Q की गणना करता है, यह मानते हुए कि समय अंतराल दर के लिए समीकरण के सामान्य उपयोग से निहित है। दस्तावेज़ Q बताता है, लेकिन समीकरण आमतौर पर Q/t के लिए होता है। इस अंतर को स्पष्ट करना। फ़ंक्शन दर समीकरण के दाहिने पक्ष का परिणाम लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         "Q/t": "ऊष्मा स्थानांतरण दर (शक्ति W)",
         k: "ऊष्मा चालकता (ऊष्मा चालकता W/(m·K))",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         ΔT: "तापमान अंतर (तापमान अंतर K)",
         d: "मोटाई (लंबाई m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "स्टीफन-बोल्ट्जमैन नियम",
      equation_text: "P = εσAT⁴",
      summary: "तापीय विकिरण शक्ति की गणना करता है (P = εσA(T^4 - T0^4))",
      description: "एक वस्तु द्वारा उत्सर्जित ऊर्जा की शुद्ध दर की गणना करता है, उसके परिवेश को ध्यान में रखते हुए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "शुद्ध विकीर्ण शक्ति (शक्ति W)",
         ε: "उत्सर्जनता (विमाहीन)",
         σ: "स्टीफन-बोल्ट्जमैन स्थिरांक (स्थिरांक W/(m²·K⁴))",
         A: "सतह क्षेत्र (क्षेत्रफल m²)",
         T: "वस्तु का तापमान (तापमान K)",
         T0: "परिवेश का तापमान (तापमान K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "वीन का विस्थापन नियम (अधिकतम तरंग दैर्ध्य)",
      equation_text: "λ_max = b/T",
      summary: "वीन के नियम (λ_max = b/T) का उपयोग करके चरम तरंग दैर्ध्य की गणना करता है",
      description: "उस तरंग दैर्ध्य की गणना करता है जिस पर एक कृष्णिका के उत्सर्जन स्पेक्ट्रम का अधिकतम होता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         λ_max: "चरम उत्सर्जन की तरंग दैर्ध्य (लंबाई m)",
         b: "वीन का विस्थापन स्थिरांक (स्थिरांक m·K)",
         T: "तापमान (तापमान K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "वीन का विस्थापन नियम (अधिकतम आवृत्ति)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "वीन के नियम (f_max = b' * T) का उपयोग करके चरम आवृत्ति की गणना करता है",
      description:
         "उस आवृत्ति की गणना करता है जिस पर एक कृष्णिका के उत्सर्जन स्पेक्ट्रम का अधिकतम होता है। नोट - यह संस्करण एक संशोधित वीन स्थिरांक b' का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f_max: "चरम उत्सर्जन की आवृत्ति (आवृत्ति Hz)",
         "b'": "संशोधित वीन स्थिरांक (स्थिरांक Hz/K)",
         T: "तापमान (तापमान K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "समीकरण जानकारी (विशिष्ट)",
      equation_text: "लागू नहीं (जानकारी पुनर्प्राप्त करता है, गणना नहीं करता)",
      summary: "ID और भाषा द्वारा समीकरण जानकारी प्राप्त करें",
      description:
         "अपने अद्वितीय ID और वांछित भाषा के आधार पर एक विशिष्ट समीकरण के लिए विवरण प्राप्त करता है। नोट - भाषा को 'language_code' पथ पैरामीटर से निकाला जाता है। कोड स्निपेट में दिखाया गया आंतरिक तर्क एक 'lang' क्वेरी पैरामीटर को भी देखता है, लेकिन यह स्वैगर परिभाषा प्राथमिक पथ पैरामीटर को दस्तावेज़ करती है।",
      language_code: "hi",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "एपीआई में सभी समीकरण एंडपॉइंट प्राप्त करें।",
      description: "एपीआई में सभी एंडपॉइंट के बारे में सारांश जानकारी प्राप्त करता है।",
      language_code: "hi",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "वेग",
      equation_text: "v = Δx / Δt",
      summary: "वेग की गणना करता है",
      description: "विस्थापन और समय के आधार पर वेग की गणना करता है (v = Δs / Δt)।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v: "वेग (गति m/s)",
         Δx: "विस्थापन (लंबाई m)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "त्वरण",
      equation_text: "a = Δv / Δt",
      summary: "त्वरण की गणना करता है",
      description: "वेग और समय में परिवर्तन के आधार पर त्वरण की गणना करता है (a = Δv / Δt)।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         a: "त्वरण (त्वरण m/s²)",
         Δv: "वेग में परिवर्तन (गति m/s)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "गतिज समीकरण (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "अंतिम वेग की गणना करता है (v = v0 + at)",
      description: "पहले गतिज समीकरण का उपयोग करके अंतिम वेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v: "अंतिम वेग (गति m/s)",
         v0: "प्रारंभिक वेग (गति m/s)",
         a: "त्वरण (त्वरण m/s²)",
         t: "समय (समय s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "गतिज समीकरण (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "अंतिम स्थिति की गणना करता है (s = s0 + v0t + 0.5at^2)",
      description: "दूसरे गतिज समीकरण का उपयोग करके अंतिम स्थिति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         s: "अंतिम स्थिति (लंबाई m)",
         s0: "प्रारंभिक स्थिति (लंबाई m)",
         v0: "प्रारंभिक वेग (गति m/s)",
         t: "समय (समय s)",
         a: "त्वरण (त्वरण m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "गतिज समीकरण (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "अंतिम वेग का वर्ग गणना करता है (v^2 = v0^2 + 2a(s - s0))",
      description: "तीसरे गतिज समीकरण का उपयोग करके अंतिम वेग के वर्ग की गणना करता है। नोट - v नहीं, v^2 लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v: "अंतिम वेग (गति m/s)",
         v0: "प्रारंभिक वेग (गति m/s)",
         a: "त्वरण (त्वरण m/s²)",
         Δs: "विस्थापन (लंबाई m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "औसत वेग",
      equation_text: "v_avg = Δx / Δt",
      summary: "औसत वेग की गणना करता है (v_avg = 0.5 * (v + v0))",
      description: "स्थिर त्वरण मानते हुए औसत वेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_avg: "औसत वेग (गति m/s)",
         v: "अंतिम वेग (गति m/s)",
         v0: "प्रारंभिक वेग (गति m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "बल (न्यूटन का दूसरा नियम)",
      equation_text: "F_net = ma",
      summary: "बल की गणना करता है (F = ma)",
      description: "न्यूटन के दूसरे नियम का उपयोग करके बल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F_net: "शुद्ध बल (बल N)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         a: "त्वरण (त्वरण m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "भार",
      equation_text: "W = mg",
      summary: "भार की गणना करता है (W = mg)",
      description: "किसी वस्तु पर गुरुत्वाकर्षण बल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         W: "भार (बल N)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "अधिकतम स्थैतिक घर्षण",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "अधिकतम स्थैतिक घर्षण की गणना करता है (F_s = μ_s * N)",
      description: "संभव अधिकतम स्थैतिक घर्षण बल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f_s_max: "अधिकतम स्थैतिक घर्षण बल (बल N)",
         μ_s: "स्थैतिक घर्षण गुणांक (विमाहीन)",
         F_N: "अभिलंब बल (बल N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "गतिज घर्षण",
      equation_text: "f_k = μ_k * F_N",
      summary: "गतिज घर्षण की गणना करता है (F_k = μ_k * N)",
      description: "गतिशील वस्तु पर लगने वाले गतिज घर्षण बल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f_k: "गतिज घर्षण बल (बल N)",
         μ_k: "गतिज घर्षण गुणांक (विमाहीन)",
         F_N: "अभिलंब बल (बल N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "संवेग",
      equation_text: "p = mv",
      summary: "संवेग की गणना करता है (p = mv)",
      description: "किसी वस्तु के रैखिक संवेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         p: "संवेग (संवेग kg·m/s)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         v: "वेग (गति m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "आवेग",
      equation_text: "J = F_avg * Δt",
      summary: "आवेग की गणना करता है (J = F * Δt)",
      description: "बल और समय अंतराल से आवेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         J: "आवेग (आवेग N·s)",
         F_avg: "औसत बल (बल N)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "आवेग-संवेग प्रमेय",
      equation_text: "J = Δp",
      summary: "आवेग-संवेग प्रमेय को मान्य करता है (F * Δt = m * Δv)",
      description: "दिए गए मानों के लिए आवेग संवेग में परिवर्तन के बराबर है या नहीं, यह जांचता है। बूलियन लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         J: "आवेग (आवेग N·s)",
         Δp: "संवेग में परिवर्तन (संवेग kg·m/s)",
         F: "बल (बल N)",
         Δt: "समय अंतराल (समय s)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         Δv: "वेग में परिवर्तन (गति m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "रेडियोधर्मी सक्रियता",
      equation_text: "A = λN",
      summary: "रेडियोधर्मी क्षय में औसत सक्रियता की गणना करता है (A_avg = ΔN/Δt)",
      description:
         "समय अंतराल में रेडियोधर्मी नमूने की औसत सक्रियता (क्षय दर) की गणना करता है। नोट - फ़ंक्शन ΔN नाभिक की संख्या के लिए `nValue` और Δt समय के लिए `tValue` का उपयोग करता है। यह Δt पर एक सरलीकृत औसत है, तात्कालिक सक्रियता dN/dt = -λN है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         A_avg: "औसत रेडियोधर्मी सक्रियता (सक्रियता Bq)",
         ΔN: "क्षय की संख्या (विमाहीन संख्या)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "अर्धायु",
      equation_text: "T_½ = ln(2) / λ",
      summary: "क्षय के बाद बची हुई मात्रा की गणना करता है (N = N0 * (1/2)^(t/T_half))",
      description:
         "एक पदार्थ की उसकी अर्धायु के आधार पर कुछ समय बाद बची हुई मात्रा की गणना करता है। नोट - समय के लिए `tValue` और अर्धायु के लिए `Thalf` का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         N: "बची हुई मात्रा/नाभिक (संख्या)",
         N0: "प्रारंभिक मात्रा/नाभिक (संख्या)",
         t: "बीता हुआ समय (समय s)",
         T_half: "अर्धायु (समय s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "अवशोषित विकिरण खुराक",
      equation_text: "D = dE / dm",
      summary: "अवशोषित विकिरण खुराक की गणना करता है (D = E/m)",
      description:
         "एक द्रव्यमान द्वारा अवशोषित ऊर्जा के आधार पर विकिरण की अवशोषित खुराक की गणना करता है। नोट - ऊर्जा के लिए `EValue` और द्रव्यमान के लिए `mValue` का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         D: "अवशोषित खुराक (अवशोषित खुराक Gy)",
         E: "अवशोषित ऊर्जा (ऊर्जा J)",
         m: "द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "समतुल्य विकिरण खुराक",
      equation_text: "H = D * W_R",
      summary: "समतुल्य विकिरण खुराक की गणना करता है (H = wR * D)",
      description:
         "विभिन्न प्रकार के विकिरणों की जैविक प्रभावशीलता को ध्यान में रखते हुए समतुल्य खुराक की गणना करता है। नोट - अवशोषित खुराक के लिए `DValue` का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         H: "समतुल्य खुराक (समतुल्य खुराक Sv)",
         D: "अवशोषित खुराक (अवशोषित खुराक Gy)",
         W_R: "विकिरण भारांक कारक (विमाहीन)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "प्रभावी विकिरण खुराक",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "प्रभावी विकिरण खुराक की गणना करता है (E = wT * H)",
      description:
         "विभिन्न ऊतकों/अंगों की विकिरण के प्रति संवेदनशीलता को ध्यान में रखते हुए प्रभावी खुराक की गणना करता है। नोट - समतुल्य खुराक के लिए `HValue` का उपयोग करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "प्रभावी खुराक (प्रभावी खुराक Sv)",
         H_T: "ऊतक/अंग T के लिए समतुल्य खुराक (समतुल्य खुराक Sv)",
         W_T: "ऊतक/अंग T के लिए ऊतक भारांक कारक (विमाहीन)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "चैरेन्कोव कोण",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "चैरेन्कोव कोण की गणना करता है (θ_C = arccos(c/nv_p))",
      description:
         "एक माध्यम में प्रकाश की गति से तेज गतिमान आवेशित कण द्वारा निर्मित चैरेन्कोव शंकु के कोण की गणना करता है। कोण रेडियन में लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         θ_C: "चैरेन्कोव कोण (कोण rad)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
         n: "माध्यम का अपवर्तनांक (विमाहीन)",
         v: "कण की गति (गति m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "व्यतिकरण फ्रिंज (जैसे, स्थिति, रिक्ति)",
      equation_text: "Δy = λL / d (डबल स्लिट रिक्ति)",
      summary: "व्यतिकरण फ्रिंजों की स्थिति की गणना करता है (y_n = (nλL)/d)",
      description: "यंग के डबल-स्लिट व्यतिकरण पैटर्न में nवें चमकीले फ्रिंज की स्थिति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         y_n: "nवें चमकीले फ्रिंज की स्थिति (लंबाई m)",
         n: "फ्रिंज क्रम (विमाहीन पूर्णांक)",
         λ: "तरंग दैर्ध्य (लंबाई m)",
         L: "पर्दे तक की दूरी (लंबाई m)",
         d: "स्लिट पृथक्करण (लंबाई m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "अपवर्तनांक",
      equation_text: "n = c / v",
      summary: "अपवर्तनांक की गणना करता है (n = c/v)",
      description:
         "निर्वात और माध्यम में प्रकाश की गति के आधार पर एक माध्यम के अपवर्तनांक की गणना करता है।",
language_code: "hi",
      subject: "Physics",
      variables: {
         n: "अपवर्तनांक (विमाहीन)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
         v: "माध्यम में प्रकाश की गति (गति m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "स्नेल का नियम",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "स्नेल के नियम को मान्य करता है (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "दिए गए अपवर्तनांक और कोणों के साथ दो माध्यमों के बीच से गुजरने वाले प्रकाश के लिए स्नेल का नियम लागू होता है या नहीं, इसकी जांच करता है। बूलियन लौटाता है। कोण रेडियन में होने चाहिए। नोट - फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकने वाली सख्त समानता (===) का उपयोग करता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         n1: "माध्यम 1 का अपवर्तनांक (विमाहीन)",
         θ1: "माध्यम 1 में कोण (कोण rad)",
         n2: "माध्यम 2 का अपवर्तनांक (विमाहीन)",
         θ2: "माध्यम 2 में कोण (कोण rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "क्रांतिक कोण",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "क्रांतिक कोण की गणना करता है (θ_c = arcsin(n2/n1))",
      description:
         "प्रकाश के n1 से n2 अपवर्तनांक वाले माध्यम में जाने पर (n1 > n2) पूर्ण आंतरिक परावर्तन के लिए क्रांतिक कोण की गणना करता है। कोण रेडियन में लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         θ_c: "क्रांतिक कोण (कोण rad)",
         n1: "माध्यम 1 का अपवर्तनांक (विमाहीन)",
         n2: "माध्यम 2 का अपवर्तनांक (विमाहीन)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "छवि स्थान (प्रकाशिकी)",
      equation_text: "1/f = 1/d_o + 1/d_i (पतला लेंस/दर्पण)",
      summary: "पतले लेंस/दर्पण समीकरण को मान्य करता है (1/f = 1/do + 1/di)",
      description:
         "जांच करता है कि फोकल लंबाई, वस्तु दूरी और छवि दूरी के बीच संबंध सही है या नहीं। बूलियन लौटाता है। नोट - फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकने वाली सख्त समानता (===) का उपयोग करता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f: "फोकल लंबाई (लंबाई m)",
         d_o: "वस्तु दूरी (लंबाई m)",
         d_i: "छवि दूरी (लंबाई m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "छवि आकार (आवर्धन - प्रकाशिकी)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "आवर्धन समीकरण को मान्य करता है (h'/h = di/do) (फ़ंक्शन h'/h = di/do का उपयोग करता है)",
      description:
         "जांच करता है कि वस्तु/छवि ऊंचाइयों और दूरियों के बीच संबंध सही है या नहीं। बूलियन लौटाता है। नोट - फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकने वाली सख्त समानता (===) का उपयोग करता है। फ़ंक्शन हस्ताक्षरित आवर्धन समीकरण के बजाय `h'/h = di/do` परिमाण संबंध का उपयोग करता है। फ़ंक्शन कार्यान्वयन के आधार पर दस्तावेज़ीकरण। वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         M: "आवर्धन (विमाहीन)",
         h_i: "छवि ऊंचाई (लंबाई m)",
         h_o: "वस्तु ऊंचाई (लंबाई m)",
         d_i: "छवि दूरी (लंबाई m)",
         d_o: "वस्तु दूरी (लंबाई m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "गोलीय दर्पण समीकरण",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "एक गोलीय दर्पण की फोकल लंबाई की गणना करता है (f = r/2)",
      description: "एक गोलीय दर्पण की वक्रता त्रिज्या के आधार पर उसकी फोकल लंबाई की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f: "फोकल लंबाई (लंबाई m)",
         r: "वक्रता त्रिज्या (लंबाई m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "स्प्रिंग विभव ऊर्जा",
      equation_text: "U_s = ½kx²",
      summary: "एक स्प्रिंग में विभव ऊर्जा की गणना करता है (PE = 0.5 * k * Δx^2)",
      description: "एक आदर्श स्प्रिंग में संग्रहीत प्रत्यास्थ विभव ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         U_s: "स्प्रिंग विभव ऊर्जा (ऊर्जा J)",
         k: "स्प्रिंग स्थिरांक (स्प्रिंग स्थिरांक N/m)",
         x: "संतुलन से विस्थापन (लंबाई m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "सरल हार्मोनिक ऑसिलेटर (SHO) आवर्तकाल",
      equation_text: "T = 2π√(m/k)",
      summary: "एक स्प्रिंग-द्रव्यमान SHO के आवर्तकाल की गणना करता है (T = 2π√(m/k))",
      description:
         "एक स्प्रिंग पर द्रव्यमान से मिलकर बने सरल हार्मोनिक ऑसिलेटर के दोलन काल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         T: "आवर्तकाल (समय s)",
         π: "पाई (विमाहीन स्थिरांक)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         k: "स्प्रिंग स्थिरांक (स्प्रिंग स्थिरांक N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "सरल पेंडुलम आवर्तकाल",
      equation_text: "T = 2π√(L/g)",
      summary: "एक सरल पेंडुलम के आवर्तकाल की गणना करता है (T = 2π√(l/g))",
      description: "छोटे कोणों पर एक सरल पेंडुलम के दोलन काल की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         T: "आवर्तकाल (समय s)",
         π: "पाई (विमाहीन स्थिरांक)",
         L: "पेंडुलम की लंबाई (लंबाई m)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "आवृत्ति",
      equation_text: "f = 1 / T",
      summary: "आवृत्ति की गणना करता है (f = 1/T)",
      description: "दोलन के आवर्तकाल से आवृत्ति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f: "आवृत्ति (आवृत्ति Hz)",
         T: "आवर्तकाल (समय s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "कोणीय आवृत्ति",
      equation_text: "ω = 2πf",
      summary: "कोणीय आवृत्ति की गणना करता है (ω = 2πf)",
      description: "आवृत्ति से कोणीय आवृत्ति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ω: "कोणीय आवृत्ति (कोणीय वेग rad/s)",
         π: "पाई (विमाहीन स्थिरांक)",
         f: "आवृत्ति (आवृत्ति Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "लोरेन्ट्स कारक",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "लोरेन्ट्स कारक (γ) की गणना करता है",
      description: "γ = 1/√(1 - (v²/c²)) का उपयोग करके लोरेन्ट्स कारक की गणना करता है। v < c की आवश्यकता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         γ: "लोरेन्ट्स कारक (विमाहीन)",
         v: "वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "समय फैलाव",
      equation_text: "Δt' = γ * Δt₀",
      summary: "समय फैलाव की गणना करता है (t' = γ * t₀)",
      description:
         "एक जड़त्वीय फ्रेम S में एक पर्यवेक्षक के लिए बीते हुए समय (t') की गणना करता है, जो एक गतिमान फ्रेम S' में मापा गया उचित समय (t₀) और S और S' के बीच की सापेक्ष वेग (v) दिया गया है। यह t' = t₀ / √(1 - (v²/c²)) समीकरण का उपयोग करता है। इसके लिए t₀ ≥ 0 और |v| ≤ c आवश्यक है। t' की इकाइयां t₀ के समान होंगी, v और c की इकाइयां सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Δt: "विस्तारित समय (समय s)",
         Δt0: "उचित समय (समय s)",
         v: "सापेक्ष वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "लंबाई संकुचन",
      equation_text: "L' = L₀ / γ",
      summary: "लंबाई संकुचन की गणना करता है (L' = L₀ / γ)",
      description:
         "एक गतिमान फ्रेम S' से प्रेक्षित एक वस्तु की लंबाई (L') की गणना करता है, जो उसके विराम फ्रेम S में मापी गई उसकी उचित लंबाई (L₀) और S और S' के बीच सापेक्ष वेग (v) को देखते हुए। यह L' = L₀ * √(1 - (v²/c²)) समीकरण का उपयोग करता है। इसके लिए L₀ ≥ 0 और |v| ≤ c आवश्यक है। L' की इकाइयां L₀ के समान होंगी, v और c की इकाइयां सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         L: "संकुचित लंबाई (लंबाई m)",
         L0: "उचित लंबाई (लंबाई m)",
         v: "सापेक्ष वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "सापेक्षिक वेग योग",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "सापेक्षिक वेग योग की गणना करता है",
      description:
         "एक फ्रेम S के सापेक्ष उसके वेग (u) और फ्रेम S' के सापेक्ष फ्रेम S के वेग (v) को देखते हुए, एक वस्तु के फ्रेम S' के सापेक्ष वेग (u') की गणना करता है। यह u' = (u + v) / (1 + uv/c²) समीकरण का उपयोग करता है। समान रेखा के अनुगमन को मानता है। c ≠ 0 की आवश्यकता है। u, v और c की इकाइयां सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         u: "फ्रेम S में वस्तु का वेग (गति m/s)",
         v: "S' के सापेक्ष फ्रेम S का वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
         "u'": "फ्रेम S' के सापेक्ष वस्तु का वेग (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "सापेक्षिक कुल ऊर्जा",
      equation_text: "E = γmc²",
      summary: "सापेक्षिक कुल ऊर्जा (E) की गणना करता है",
      description:
         "विराम द्रव्यमान (m) वाले और वेग (v) से गतिमान कण की कुल सापेक्षिक ऊर्जा की गणना करता है। यह E = γmc² = mc² / √(1 - (v²/c²)) समीकरण का उपयोग करता है। मुख्य रूप से विराम द्रव्यमान (m > 0) वाले कणों के लिए। इसके लिए m ≥ 0 और |v| ≤ c आवश्यक है। m, v और c की इकाइयां उपयुक्त इकाइयों में ऊर्जा प्राप्त करने के लिए सुसंगत होनी चाहिए (उदाहरण के लिए, m किलोग्राम में, v/c मीटर/सेकंड में E जूल में देता है)।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "कुल सापेक्षिक ऊर्जा (ऊर्जा J)",
         m: "विराम द्रव्यमान (द्रव्यमान kg)",
         v: "वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "सापेक्षिक संवेग",
      equation_text: "p = γmv",
      summary: "सापेक्षिक संवेग (p = γmv) की गणना करता है",
      description:
         "विराम द्रव्यमान (m) वाले और वेग (v) से गतिमान कण के सापेक्षिक संवेग की गणना करता है। यह p = γmv = mv / √(1 - (v²/c²)) समीकरण का उपयोग करता है। मुख्य रूप से विराम द्रव्यमान (m > 0) वाले कणों के लिए। इसके लिए m ≥ 0 और |v| ≤ c आवश्यक है। m, v और c की इकाइयां उपयुक्त इकाइयों में संवेग प्राप्त करने के लिए सुसंगत होनी चाहिए (उदाहरण के लिए, m किलोग्राम में, v मीटर/सेकंड में, c मीटर/सेकंड में p kg·m/s में देता है)।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         p: "सापेक्षिक संवेग (संवेग kg·m/s)",
         m: "विराम द्रव्यमान (द्रव्यमान kg)",
         v: "वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "ऊर्जा-संवेग संबंध",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "संवेग और विराम द्रव्यमान से कुल ऊर्जा की गणना करता है (E)",
      description:
         "एक कण की कुल सापेक्षिक ऊर्जा की गणना उसके सापेक्षिक संवेग (p) और विराम द्रव्यमान (m) से करता है। ऊर्जा-संवेग संबंध का उपयोग करता है: E² = (pc)² + (mc²)²। यह समीकरण द्रव्यमान वाले (m > 0) और द्रव्यमान रहित (m = 0) कणों दोनों के लिए मान्य है। p ≥ 0, m ≥ 0 और c > 0 की आवश्यकता है। p, m और c की इकाइयां सुसंगत होनी चाहिए।\n",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "कुल सापेक्षिक ऊर्जा (ऊर्जा J)",
         p: "सापेक्षिक संवेग (संवेग kg·m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
         m: "विराम द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "द्रव्यमान-ऊर्जा समतुल्यता (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "द्रव्यमान-ऊर्जा समतुल्यता की गणना करता है (E₀ = mc²)",
      description:
         "आइंस्टीन के प्रसिद्ध समीकरण E₀ = mc² का उपयोग करके दिए गए विराम द्रव्यमान (m) के समतुल्य विराम ऊर्जा (E₀) की गणना करता है। इसके लिए m ≥ 0 और c > 0 आवश्यक है। m और c की इकाइयां सुसंगत होनी चाहिए (उदाहरण के लिए, m किलोग्राम में, c मीटर/सेकंड में E₀ जूल में देता है)। यह एंडपॉइंट c के लिए एक मानक मान (लगभग 299792458 m/s) का उपयोग करता है जब तक कि 'c' स्पष्ट रूप से प्रदान न किया जाए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E0: "विराम ऊर्जा (ऊर्जा J)",
         m: "विराम द्रव्यमान (द्रव्यमान kg)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "सापेक्षिक गतिज ऊर्जा",
      equation_text: "KE = (γ - 1)mc²",
      summary: "सापेक्षिक गतिज ऊर्जा (KE) की गणना करता है",
      description:
         "विराम द्रव्यमान (m) वाले और वेग (v) से गतिमान कण की सापेक्षिक गतिज ऊर्जा की गणना करता है। यह KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc² समीकरण का उपयोग करता है। मुख्य रूप से विराम द्रव्यमान (m > 0) वाले कणों के लिए। इसके लिए m ≥ 0 और |v| < c आवश्यक है। m, v और c की इकाइयां उपयुक्त इकाइयों में ऊर्जा प्राप्त करने के लिए सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE: "सापेक्षिक गतिज ऊर्जा (ऊर्जा J)",
         m: "विराम द्रव्यमान (द्रव्यमान kg)",
         v: "वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "सापेक्षिक डॉपलर प्रभाव (तरंग दैर्ध्य)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "तरंग दैर्ध्य के लिए सापेक्षिक अनुदैर्ध्य डॉपलर प्रभाव की गणना करता है",
      description:
         "प्रकाश के प्रेक्षित तरंग दैर्ध्य (λ') की गणना करता है जो उचित तरंग दैर्ध्य (λ₀) के साथ एक स्रोत से उत्सर्जित होता है जो पर्यवेक्षक से सीधे दूर या उसकी ओर सापेक्ष वेग (v_rel) से गतिमान है। यह λ' = λ₀√((1 + β)/(1 - β)) समीकरण का उपयोग करता है, जहां β = v_rel/c है। v_rel > 0 दूर जाने के लिए है (लाल विस्थापन), v_rel < 0 पास आने के लिए है (नीला विस्थापन)। λ₀ > 0 और |v_rel| < c की आवश्यकता है। λ' की इकाइयां λ₀ के समान होंगी, v_rel और c की इकाइयां सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         "λ'": "प्रेक्षित तरंग दैर्ध्य (लंबाई m)",
         λ0: "उचित तरंग दैर्ध्य (लंबाई m)",
         v: "सापेक्ष वेग (गति m/s)",
         c: "निर्वात में प्रकाश की गति (गति m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "फोटॉन ऊर्जा (आवृत्ति से)",
      equation_text: "E = hf",
      summary: "आवृत्ति से फोटॉन ऊर्जा की गणना करता है (E = hf)",
      description:
         "एक फोटॉन की ऊर्जा (E) की गणना उसकी आवृत्ति (f) के आधार पर करता है। प्लैंक संबंध E = hf का उपयोग करता है। f ≥ 0 और h > 0 की आवश्यकता है। h और f की इकाइयां उपयुक्त इकाइयों में ऊर्जा प्राप्त करने के लिए सुसंगत होनी चाहिए (उदाहरण के लिए, h जूल·सेकंड में, f हर्ट्ज (से⁻¹) में E जूल में देता है)। यह एंडपॉइंट h के लिए एक मानक मान (लगभग 6.626e-34 जूल·सेकंड) का उपयोग करता है जब तक कि 'h' स्पष्ट रूप से प्रदान न किया जाए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "फोटॉन ऊर्जा (ऊर्जा J)",
         h: "प्लैंक स्थिरांक (स्थिरांक J·s)",
         f: "आवृत्ति (आवृत्ति Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "फोटॉन संवेग (तरंग दैर्ध्य से)",
      equation_text: "p = h / λ",
      summary: "तरंग दैर्ध्य से फोटॉन संवेग की गणना करता है (p = h/λ)",
      description:
         "एक फोटॉन के संवेग (p) की गणना उसकी तरंग दैर्ध्य (λ) के आधार पर करता है। संबंध p = h/λ का उपयोग करता है। λ > 0 और h > 0 की आवश्यकता है। h और λ की इकाइयां उपयुक्त इकाइयों में संवेग प्राप्त करने के लिए सुसंगत होनी चाहिए (उदाहरण के लिए, h जूल·सेकंड में, λ मीटर में p kg·m/s में देता है)। यह एंडपॉइंट h के लिए एक मानक मान (लगभग 6.626e-34 जूल·सेकंड) का उपयोग करता है जब तक कि 'h' स्पष्ट रूप से प्रदान न किया जाए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         p: "फोटॉन संवेग (संवेग kg·m/s)",
         h: "प्लैंक स्थिरांक (स्थिरांक J·s)",
         λ: "तरंग दैर्ध्य (लंबाई m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "प्रकाशविद्युत प्रभाव (अधिकतम KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "प्रकाशविद्युत प्रभाव में अधिकतम गतिज ऊर्जा की गणना करता है (KE_max)",
      description:
         "प्रकाशविद्युत प्रभाव में उत्सर्जित इलेक्ट्रॉनों की अधिकतम गतिज ऊर्जा (KE_max) की गणना करता है। यह KE_max = E_photon - φ समीकरण का उपयोग करता है, जहां E_photon आने वाले फोटॉन की ऊर्जा है और φ सामग्री का कार्य फलन है। यदि E_photon ≤ φ, तो कोई इलेक्ट्रॉन उत्सर्जित नहीं होता है, और KE_max 0 होता है। E_photon ≥ 0 और φ ≥ 0 आवश्यक है। E_photon और φ की इकाइयां KE_max को समान इकाइयों में प्राप्त करने के लिए सुसंगत होनी चाहिए।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE_max: "अधिकतम इलेक्ट्रॉन गतिज ऊर्जा (ऊर्जा J)",
         E_photon: "फोटॉन ऊर्जा (ऊर्जा J)",
         φ: "कार्य फलन (ऊर्जा J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "रिडबर्ग समीकरण (परमाणु संक्रमण)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "हाइड्रोजन जैसे परमाणु संक्रमणों के लिए ऊर्जा या तरंग संख्या की गणना करता है",
      description:
         "हाइड्रोजन जैसे परमाणु (Z) में दो ऊर्जा स्तरों के बीच एक इलेक्ट्रॉन संक्रमण के लिए ऊर्जा अंतर (ΔE) या तरंग संख्या (1/λ) की गणना करता है। यह परिणाम = स्थिरांक * Z² * (1/n_initial² - 1/n_final²) समीकरण का उपयोग करता है। यदि 'स्थिरांक' रिडबर्ग ऊर्जा इकाई है (उदाहरण के लिए, eV में), तो परिणाम ऊर्जा अंतर E_final - E_initial है (अवशोषण के लिए सकारात्मक, उत्सर्जन के लिए नकारात्मक)। यदि 'स्थिरांक' तरंग संख्या के लिए रिडबर्ग स्थिरांक है (उदाहरण के लिए, m⁻¹ में), तो परिणाम तरंग संख्या 1/λ है (उत्सर्जन के लिए सकारात्मक, अवशोषण के लिए नकारात्मक)। nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (पूर्णांक), और स्थिरांक > 0 की आवश्यकता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔE: "ऊर्जा अंतर (ऊर्जा J)",
         R_y: "रिडबर्ग स्थिरांक (स्थिरांक J या प्रति लंबाई m⁻¹)",
         Z: "परमाणु संख्या (विमाहीन पूर्णांक)",
         n1: "प्रारंभिक मुख्य क्वांटम संख्या (विमाहीन पूर्णांक)",
         n2: "अंतिम मुख्य क्वांटम संख्या (विमाहीन पूर्णांक)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "कोणीय वेग",
      equation_text: "ω = Δθ / Δt",
      summary: "कोणीय वेग की गणना करता है (ω = Δθ / Δt)",
      description: "कोण और समय में परिवर्तन के आधार पर कोणीय वेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ω: "कोणीय वेग (कोणीय वेग rad/s)",
         Δθ: "कोणीय विस्थापन (कोण rad)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "कोणीय त्वरण",
      equation_text: "α = Δω / Δt",
      summary: "कोणीय त्वरण की गणना करता है (α = Δω / Δt)",
      description: "कोणीय वेग और समय में परिवर्तन के आधार पर कोणीय त्वरण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         α: "कोणीय त्वरण (कोणीय त्वरण rad/s²)",
         Δω: "कोणीय वेग में परिवर्तन (कोणीय वेग rad/s)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "घूर्णी गतिकी (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "अंतिम कोणीय वेग की गणना करता है (ω = ω0 + αt)",
      description: "घूर्णी गतिज समीकरण का उपयोग करके अंतिम कोणीय वेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ω: "अंतिम कोणीय वेग (कोणीय वेग rad/s)",
         ω0: "प्रारंभिक कोणीय वेग (कोणीय वेग rad/s)",
         α: "कोणीय त्वरण (कोणीय त्वरण rad/s²)",
         t: "समय (समय s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "घूर्णी गतिकी (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "कोणीय स्थिति की गणना करता है (θ = θ0 + ω0t + 0.5αt^2)",
      description: "घूर्णी गतिज समीकरण का उपयोग करके अंतिम कोणीय स्थिति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         θ: "अंतिम कोणीय स्थिति (कोण rad)",
         θ0: "प्रारंभिक कोणीय स्थिति (कोण rad)",
         ω0: "प्रारंभिक कोणीय वेग (कोणीय वेग rad/s)",
         t: "समय (समय s)",
         α: "कोणीय त्वरण (कोणीय त्वरण rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "घूर्णी गतिकी (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "कोणीय वेग का वर्ग गणना करता है (ω^2 = ω0^2 + 2α(θ - θ0))",
      description: "घूर्णी गतिज समीकरण का उपयोग करके अंतिम कोणीय वेग के वर्ग की गणना करता है। नोट - ω नहीं, ω^2 लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ω: "अंतिम कोणीय वेग (कोणीय वेग rad/s)",
         ω0: "प्रारंभिक कोणीय वेग (कोणीय वेग rad/s)",
         α: "कोणीय त्वरण (कोणीय त्वरण rad/s²)",
         Δθ: "कोणीय विस्थापन (कोण rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "औसत कोणीय वेग",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "औसत कोणीय वेग की गणना करता है (ω_avg = 0.5 * (ω + ω0))",
      description: "स्थिर कोणीय त्वरण मानते हुए औसत कोणीय वेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ω_avg: "औसत कोणीय वेग (कोणीय वेग rad/s)",
         ω: "अंतिम कोणीय वेग (कोणीय वेग rad/s)",
         ω0: "प्रारंभिक कोणीय वेग (कोणीय वेग rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "टॉर्क",
      equation_text: "τ = rFsin(θ)",
      summary: "टॉर्क की गणना करता है (τ = rF sin(θ))",
      description: "त्रिज्या, बल, और उनके बीच के कोण के आधार पर टॉर्क की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         τ: "टॉर्क (टॉर्क N·m)",
         r: "उत्तोलन भुजा (लंबाई m)",
         F: "बल (बल N)",
         θ: "बल और उत्तोलन भुजा के बीच का कोण (कोण rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "न्यूटन का दूसरा नियम (घूर्णन)",
      equation_text: "τ_net = Iα",
      summary: "घूर्णी दूसरे नियम (τ = Iα) का उपयोग करके टॉर्क की गणना करता है",
      description: "जड़त्व आघूर्ण और कोणीय त्वरण के आधार पर टॉर्क की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         τ_net: "शुद्ध टॉर्क (टॉर्क N·m)",
         I: "जड़त्व आघूर्ण (जड़त्व आघूर्ण kg·m²)",
         α: "कोणीय त्वरण (कोणीय त्वरण rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "जड़त्व आघूर्ण",
      equation_text: "I = mr² (बिंदु द्रव्यमान)",
      summary: "एक बिंदु द्रव्यमान के लिए जड़त्व आघूर्ण की गणना करता है (I = mr^2)",
      description: "एक अक्ष के सापेक्ष एकल बिंदु द्रव्यमान के लिए जड़त्व आघूर्ण की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         I: "जड़त्व आघूर्ण (जड़त्व आघूर्ण kg·m²)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         r: "अक्ष से दूरी (लंबाई m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "घूर्णी कार्य",
      equation_text: "W = τΔθ (स्थिर टॉर्क)",
      summary: "घूर्णी कार्य की गणना करता है (W = τΔθ)",
      description: "एक कोणीय विस्थापन पर एक स्थिर टॉर्क द्वारा किए गए कार्य की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         W: "घूर्णी कार्य (ऊर्जा J)",
         τ: "टॉर्क (टॉर्क N·m)",
         Δθ: "कोणीय विस्थापन (कोण rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "घूर्णी शक्ति",
      equation_text: "P = τω",
      summary: "घूर्णी शक्ति की गणना करता है (P = τω cos(θ))",
      description:
         "टॉर्क, कोणीय वेग, और उनके बीच के कोण के आधार पर तात्कालिक घूर्णी शक्ति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "घूर्णी शक्ति (शक्ति W)",
         τ: "टॉर्क (टॉर्क N·m)",
         ω: "कोणीय वेग (कोणीय वेग rad/s)",
         θ: "टॉर्क और कोणीय वेग के बीच का कोण (कोण rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "घूर्णी गतिज ऊर्जा",
      equation_text: "KE_rot = ½Iω²",
      summary: "घूर्णी गतिज ऊर्जा की गणना करता है (KE = 0.5Iω^2)",
      description: "घूमने वाली वस्तु की गतिज ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE_rot: "घूर्णी गतिज ऊर्जा (ऊर्जा J)",
         I: "जड़त्व आघूर्ण (जड़त्व आघूर्ण kg·m²)",
         ω: "कोणीय वेग (कोणीय वेग rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "कोणीय संवेग",
      equation_text: "L = Iω",
      summary: "कोणीय संवेग की गणना करता है (L = mrv sin(θ))",
      description: "एक बिंदु के सापेक्ष गतिमान बिंदु द्रव्यमान के लिए कोणीय संवेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         L: "कोणीय संवेग (कोणीय संवेग kg·m²/s)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         r: "अक्ष/बिंदु से दूरी (लंबाई m)",
         v: "वेग (गति m/s)",
         θ: "त्रिज्या वेक्टर और वेग के बीच का कोण (कोण rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "कोणीय आवेग",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "कोणीय आवेग की गणना करता है (J = τΔt)",
      description: "टॉर्क और समय अंतराल से कोणीय आवेग की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         J_angular: "कोणीय आवेग (कोणीय आवेग N·m·s)",
         τ_avg: "औसत टॉर्क (टॉर्क N·m)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "यंग का मापांक",
      equation_text: "E = σ / ε",
      summary: "यंग के मापांक (E = (F * L0) / (A * ΔL)) की गणना करता है",
      description: "तन्य या संपीड़न तनाव के तहत एक सामग्री के यंग के मापांक (लोचदार मापांक) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         E: "यंग का मापांक (दबाव Pa)",
         F: "बल (बल N)",
         L0: "मूल लंबाई (लंबाई m)",
         A: "अनुप्रस्थ काट क्षेत्रफल (क्षेत्रफल m²)",
         ΔL: "लंबाई में परिवर्तन (लंबाई m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "अपरूपण मापांक",
      equation_text: "G = τ / γ",
      summary: "अपरूपण मापांक (G = (F * y) / (A * Δx)) की गणना करता है",
      description: "अपरूपण तनाव के तहत एक सामग्री के अपरूपण मापांक (कठोरता का मापांक) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         G: "अपरूपण मापांक (दबाव Pa)",
         F: "बल (बल N)",
         y: "बल के लंबवत दूरी (लंबाई m)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
         Δx: "विस्थापन (लंबाई m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "आयतन मापांक",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "आयतन मापांक (K = (F * V0) / (A * ΔV)) की गणना करता है",
      description: "समान दबाव (हाइड्रोस्टैटिक तनाव) के तहत एक सामग्री के आयतन मापांक की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         K: "आयतन मापांक (दबाव Pa)",
         ΔP: "दबाव में परिवर्तन (दबाव Pa)",
         ΔV: "आयतन में परिवर्तन (आयतन m³)",
         V0: "मूल आयतन (आयतन m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "हुक का नियम",
      equation_text: "F = kx",
      summary: "एक स्प्रिंग के बल (F = -k * Δx) की गणना करता है",
      description:
         "हुक के नियम के अनुसार एक आदर्श स्प्रिंग द्वारा लगाए गए बहाल बल की गणना करता है। नोट - विस्थापन का विरोध करने वाले बल को इंगित करने वाला एक नकारात्मक मान लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         F: "बल (बल N)",
         k: "स्प्रिंग स्थिरांक (स्प्रिंग स्थिरांक N/m)",
         x: "संतुलन से विस्थापन (लंबाई m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "ठोस तापीय विस्तार (लंबाई)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "ठोस रेखीय तापीय विस्तार (ΔL = αL0ΔT) की गणना करता है",
      description: "तापमान परिवर्तन के कारण ठोस सामग्री की लंबाई में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔL: "लंबाई में परिवर्तन (लंबाई m)",
         α: "रेखीय विस्तार गुणांक (प्रति तापमान गुणांक K⁻¹)",
         L0: "मूल लंबाई (लंबाई m)",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "ठोस तापीय विस्तार (क्षेत्रफल)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "ठोस क्षेत्रफल तापीय विस्तार (ΔA = 2αA0ΔT) की गणना करता है",
      description:
         "रेखीय विस्तार गुणांक का उपयोग करके तापमान परिवर्तन के कारण ठोस सामग्री के क्षेत्रफल में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔA: "क्षेत्रफल में परिवर्तन (क्षेत्रफल m²)",
         α: "रेखीय विस्तार गुणांक (प्रति तापमान गुणांक K⁻¹)",
         A0: "मूल क्षेत्रफल (क्षेत्रफल m²)",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "ठोस तापीय विस्तार (आयतन)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "ठोस आयतन तापीय विस्तार (ΔV = 3αV0ΔT) की गणना करता है",
      description:
         "रेखीय विस्तार गुणांक का उपयोग करके तापमान परिवर्तन के कारण ठोस सामग्री के आयतन में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔV: "आयतन में परिवर्तन (आयतन m³)",
         α: "रेखीय विस्तार गुणांक (प्रति तापमान गुणांक K⁻¹)",
         V0: "मूल आयतन (आयतन m³)",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "तरल तापीय विस्तार",
      equation_text: "ΔV = βV₀ΔT",
      summary: "तरल तापीय विस्तार (ΔV = βV0ΔT) की गणना करता है",
      description: "तापमान परिवर्तन के कारण तरल के आयतन में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔV: "आयतन में परिवर्तन (आयतन m³)",
         β: "आयतन विस्तार गुणांक (प्रति तापमान गुणांक K⁻¹)",
         V0: "मूल आयतन (आयतन m³)",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "संवेदी ऊष्मा",
      equation_text: "Q = mcΔT",
      summary: "संवेदी ऊष्मा (Q = mcΔT) की गणना करता है",
      description: "किसी पदार्थ के तापमान में परिवर्तन का कारण बनने वाली स्थानांतरित ऊष्मा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Q: "संवेदी ऊष्मा (ऊर्जा J)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         c: "विशिष्ट ऊष्मा क्षमता (विशिष्ट ऊष्मा क्षमता J/(kg·K))",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "गुप्त ऊष्मा",
      equation_text: "Q = mL",
      summary: "गुप्त ऊष्मा (Q = mL) की गणना करता है",
      description: "किसी पदार्थ की अवस्था परिवर्तन के दौरान स्थानांतरित ऊष्मा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Q: "गुप्त ऊष्मा (ऊर्जा J)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         L: "गुप्त ऊष्मा (विशिष्ट ऊर्जा J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "आदर्श गैस नियम",
      equation_text: "PV = nRT",
      summary: "आदर्श गैस नियम (PV = nRT) को मान्य करता है",
      description:
         "दिए गए मापदंडों के लिए आदर्श गैस नियम समीकरण सही है या नहीं, इसकी जांच करता है। बूलियन लौटाता है। नोट - फ़्लोटिंग-पॉइंट सटीकता के प्रति संवेदनशील हो सकने वाली सख्त समानता (===) का उपयोग करता है; वास्तविक-विश्व जांचों के लिए सहनशीलता पर विचार करें।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "दबाव (दबाव Pa)",
         V: "आयतन (आयतन m³)",
         n: "मोलों की संख्या (पदार्थ की मात्रा mol)",
         R: "आदर्श गैस स्थिरांक (स्थिरांक J/(mol·K))",
         T: "तापमान (तापमान K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "आणविक गतिज ऊर्जा",
      equation_text: "KE_avg = (3/2)kT",
      summary: "औसत आणविक गतिज ऊर्जा (KE = (3/2)kT) की गणना करता है",
      description: "एक आदर्श गैस के प्रति अणु की औसत अनुवादात्मक गतिज ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE_avg: "औसत आणविक गतिज ऊर्जा (ऊर्जा J)",
         k: "बोल्ट्जमैन स्थिरांक (स्थिरांक J/K)",
         T: "तापमान (तापमान K)",
         m: "एकल अणु का द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "आणविक गति (सबसे संभावित)",
      equation_text: "v_p = √(2kT/m)",
      summary: "सबसे संभावित आणविक गति की गणना करता है (v_p = √(2kT/m))",
      description:
         "मैक्सवेल-बोल्ट्जमैन वितरण के अनुसार एक आदर्श गैस में अणुओं की सबसे संभावित गति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_p: "सबसे संभावित आणविक गति (गति m/s)",
         k: "बोल्ट्जमैन स्थिरांक (स्थिरांक J/K)",
         T: "तापमान (तापमान K)",
         m: "एकल अणु का द्रव्यमान (द्रव्यमान kg)",
      },
topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "आणविक गति (औसत)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "औसत आणविक गति की गणना करता है (v_avg = √(8kT/(πm)))",
      description:
         "मैक्सवेल-बोल्ट्जमैन वितरण के अनुसार एक आदर्श गैस में अणुओं की औसत गति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_avg: "औसत आणविक गति (गति m/s)",
         k: "बोल्ट्जमैन स्थिरांक (स्थिरांक J/K)",
         T: "तापमान (तापमान K)",
         π: "पाई (विमाहीन स्थिरांक)",
         m: "एकल अणु का द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "आणविक गति (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "मूल माध्य वर्ग आणविक गति की गणना करता है (v_rms = √(3kT/m))",
      description:
         "मैक्सवेल-बोल्ट्जमैन वितरण के अनुसार एक आदर्श गैस में अणुओं की मूल माध्य वर्ग गति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v_rms: "मूल माध्य वर्ग आणविक गति (गति m/s)",
         k: "बोल्ट्जमैन स्थिरांक (स्थिरांक J/K)",
         T: "तापमान (तापमान K)",
         m: "एकल अणु का द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "आंतरिक ऊर्जा में परिवर्तन",
      equation_text: "ΔU = Q - W",
      summary: "आदर्श एकल-परमाणु गैस के लिए आंतरिक ऊर्जा में परिवर्तन की गणना करता है (ΔU = (3/2)nRΔT)",
      description:
         "तापमान परिवर्तन से गुजरने वाली एक-परमाणु आदर्श गैस के लिए आंतरिक ऊर्जा में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         ΔU: "आंतरिक ऊर्जा में परिवर्तन (ऊर्जा J)",
         n: "मोलों की संख्या (पदार्थ की मात्रा mol)",
         R: "आदर्श गैस स्थिरांक (स्थिरांक J/(mol·K))",
         ΔT: "तापमान में परिवर्तन (तापमान अंतर K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "थर्मोडायनामिक कार्य",
      equation_text: "W = PΔV (स्थिर दबाव)",
      summary: "स्थिर दबाव पर सिस्टम द्वारा किए गए थर्मोडायनामिक कार्य की गणना करता है (W = -PΔV)",
      description:
         "स्थिर दबाव पर एक थर्मोडायनामिक प्रक्रिया के दौरान सिस्टम द्वारा किए गए या सिस्टम पर किए गए कार्य की गणना करता है। नोट - समीकरण सिस्टम द्वारा किए गए कार्य की गणना करता है, विस्तार के लिए सकारात्मक, संपीड़न के लिए नकारात्मक। फ़ंक्शन -P*deltaV लौटाता है, जो W = PΔV समीकरण के अनुसार सिस्टम द्वारा किए गए कार्य के अनुरूप है, एक जोड़ा गया ऋणात्मक चिह्न जो कन्वेंशन के आधार पर सिस्टम पर किए गए कार्य को इंगित कर सकता है। फ़ंक्शन के आउटपुट को दस्तावेज़ करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         W: "थर्मोडायनामिक कार्य (ऊर्जा J)",
         P: "दबाव (दबाव Pa)",
         ΔV: "आयतन में परिवर्तन (आयतन m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "वास्तविक दक्षता",
      equation_text: "η = W_out / Q_in",
      summary: "एक वास्तविक इंजन की दक्षता की गणना करता है (η_real = 1 - (Q_C / Q_H))",
      description: "एक ऊष्मा इंजन की थर्मल दक्षता की गणना अवशोषित और अस्वीकृत ऊष्मा के आधार पर करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         η: "दक्षता (विमाहीन)",
         Q_H: "गर्म जलाशय से अवशोषित ऊष्मा (ऊर्जा J)",
         Q_C: "ठंडे जलाशय में अस्वीकृत ऊष्मा (ऊर्जा J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "आदर्श दक्षता",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "आदर्श दक्षता (कार्नोट) की गणना करता है (η_ideal = 1 - (T_C / T_H))",
      description:
         "दो तापमानों के बीच कार्य करने वाले ऊष्मा इंजन की अधिकतम सैद्धांतिक दक्षता (कार्नोट दक्षता) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         η_ideal: "आदर्श दक्षता (विमाहीन)",
         T_hot: "गर्म जलाशय का तापमान (तापमान K)",
         T_cold: "ठंडे जलाशय का तापमान (तापमान K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "वास्तविक प्रदर्शन गुणांक (COP)",
      equation_text: "COP_ref = Q_c / W (रेफ्रिजरेटर)",
      summary: "एक वास्तविक रेफ्रिजरेटर के प्रदर्शन गुणांक की गणना करता है (COP_real = QC / (QH - QC))",
      description: "एक वास्तविक रेफ्रिजरेटर या हीट पंप के प्रदर्शन गुणांक की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         COP_real: "प्रदर्शन गुणांक (विमाहीन)",
         Q_C: "ठंडे जलाशय से ऊष्मा (ऊर्जा J)",
         Q_H: "गर्म जलाशय को ऊष्मा (ऊर्जा J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "आदर्श प्रदर्शन गुणांक (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "एक आदर्श रेफ्रिजरेटर के प्रदर्शन गुणांक की गणना करता है (COP_ideal = TC / (TH - TC))",
      description:
         "दो तापमानों के बीच कार्य करने वाले रेफ्रिजरेटर या हीट पंप के अधिकतम सैद्धांतिक प्रदर्शन गुणांक की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         COP_ideal: "आदर्श प्रदर्शन गुणांक (विमाहीन)",
         T_h: "गर्म जलाशय का तापमान (तापमान K)",
         T_c: "ठंडे जलाशय का तापमान (तापमान K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "आवधिक तरंग वेग",
      equation_text: "v = fλ",
      summary: "तरंग गति की गणना करता है (v = fλ)",
      description: "एक आवधिक तरंग की गति की गणना उसकी आवृत्ति और तरंग दैर्ध्य के आधार पर करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         v: "तरंग गति (गति m/s)",
         f: "आवृत्ति (आवृत्ति Hz)",
         λ: "तरंग दैर्ध्य (लंबाई m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "तरंग तीव्रता",
      equation_text: "I = P / A",
      summary: "तीव्रता की गणना करता है (I = P/A)",
      description: "एक तरंग की तीव्रता (प्रति इकाई क्षेत्रफल शक्ति) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         I: "तीव्रता (तीव्रता W/m²)",
         P: "शक्ति (शक्ति W)",
         A: "क्षेत्रफल (क्षेत्रफल m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "तीव्रता स्तर (डेसिबल)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "डेसिबल में तीव्रता स्तर की गणना करता है (L = 10 log10(I/I0))",
      description: "एक संदर्भ तीव्रता के सापेक्ष तीव्रता स्तर (ध्वनि तीव्रता स्तर) की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         β: "तीव्रता स्तर (तीव्रता स्तर dB)",
         I: "तीव्रता (तीव्रता W/m²)",
         I0: "संदर्भ तीव्रता (तीव्रता W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "दबाव स्तर (ध्वनि दबाव स्तर)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "डेसिबल में ध्वनि दबाव स्तर की गणना करता है (L = 20 log10(ΔP/ΔP0))",
      description: "एक संदर्भ दबाव परिवर्तन के सापेक्ष ध्वनि दबाव स्तर की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         L_p: "ध्वनि दबाव स्तर (दबाव स्तर dB)",
         P_rms: "RMS दबाव उतार-चढ़ाव (दबाव Pa)",
         P_ref: "संदर्भ दबाव (दबाव Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "डॉपलर प्रभाव (ध्वनि/गैर-सापेक्षिक)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "डॉपलर प्रभाव वेग कारक की गणना करता है ((c + v_o) / (c - v_s))",
      description:
         "डॉपलर प्रभाव समीकरण के वेग कारक भाग (f' = f * factor) की गणना करता है। प्रेक्षक के स्रोत की ओर बढ़ने, स्रोत के प्रेक्षक की ओर बढ़ने के लिए वेग सकारात्मक होते हैं।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         f_obs: "प्रेक्षित आवृत्ति (आवृत्ति Hz)",
         f_source: "स्रोत आवृत्ति (आवृत्ति Hz)",
         v_wave: "तरंग गति (गति m/s)",
         v_observer: "माध्यम के सापेक्ष प्रेक्षक वेग (गति m/s)",
         v_source: "माध्यम के सापेक्ष स्रोत वेग (गति m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "माच कोण",
      equation_text: "sin(μ) = 1 / M",
      summary: "माच कोण की गणना करता है (θ_M = arcsin(c/v))",
      description:
         "ध्वनि की गति से तेज गतिमान वस्तु द्वारा निर्मित माच शंकु के कोण की गणना करता है। कोण रेडियन में लौटाता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         μ: "माच कोण (कोण rad)",
         M: "माच संख्या (विमाहीन)",
         c: "ध्वनि की गति (गति m/s)",
         v: "वस्तु की गति (गति m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "कार्य",
      equation_text: "W = Fdcos(θ)",
      summary: "किए गए कार्य की गणना करता है (W = F * Δs * cos(θ))",
      description: "बल, विस्थापन, और उनके बीच के कोण के आधार पर किए गए कार्य की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         W: "किया गया कार्य (ऊर्जा J)",
         F: "बल का परिमाण (बल N)",
         d: "विस्थापन का परिमाण (लंबाई m)",
         θ: "बल और विस्थापन के बीच का कोण (कोण rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "गतिज ऊर्जा",
      equation_text: "KE = ½mv²",
      summary: "गतिज ऊर्जा की गणना करता है (KE = 0.5 * m * v^2)",
      description: "द्रव्यमान और वेग के आधार पर गतिज ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE: "गतिज ऊर्जा (ऊर्जा J)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         v: "वेग (गति m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "गतिज ऊर्जा (संवेग से)",
      equation_text: "KE = p² / (2m)",
      summary: "संवेग से गतिज ऊर्जा की गणना करता है (KE = p^2 / (2m))",
      description: "संवेग और द्रव्यमान के आधार पर गतिज ऊर्जा की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         KE: "गतिज ऊर्जा (ऊर्जा J)",
         p: "संवेग (संवेग kg·m/s)",
         m: "द्रव्यमान (द्रव्यमान kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "गुरुत्वाकर्षण विभव ऊर्जा",
      equation_text: "U_g = mgh (सतह के निकट)",
      summary: "गुरुत्वाकर्षण विभव ऊर्जा की गणना करता है (PE = mgh)",
      description: "गुरुत्वाकर्षण विभव ऊर्जा में परिवर्तन की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         U_g: "गुरुत्वाकर्षण विभव ऊर्जा (ऊर्जा J)",
         m: "द्रव्यमान (द्रव्यमान kg)",
         g: "गुरुत्वाकर्षण के कारण त्वरण (त्वरण m/s²)",
         h: "ऊंचाई (लंबाई m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "दक्षता",
      equation_text: "दक्षता = Output / Input",
      summary: "दक्षता की गणना करता है (η = W_out / W_in)",
      description: "एक प्रक्रिया या मशीन की दक्षता की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         Efficiency: "दक्षता (विमाहीन)",
         Output: "उपयोगी आउटपुट ऊर्जा या शक्ति (ऊर्जा J या शक्ति W)",
         Input: "कुल इनपुट ऊर्जा या शक्ति (ऊर्जा J या शक्ति W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "शक्ति",
      equation_text: "P = W / t",
      summary: "शक्ति की गणना करता है (P = ΔW / Δt)",
      description: "कार्य और समय में परिवर्तन के आधार पर औसत शक्ति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "शक्ति (शक्ति W)",
         ΔW: "कार्य में परिवर्तन (ऊर्जा J)",
         Δt: "समय अंतराल (समय s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "शक्ति (P = Fv)",
      equation_text: "P = Fv",
      summary: "बल और वेग से शक्ति की गणना करता है (P = Fv cos(θ))",
      description: "बल, वेग और उनके बीच के कोण के आधार पर तात्कालिक शक्ति की गणना करता है।",
      language_code: "hi",
      subject: "Physics",
      variables: {
         P: "शक्ति (शक्ति W)",
         F: "बल का परिमाण (बल N)",
         v: "वेग का परिमाण (गति m/s)",
         θ: "बल और वेग के बीच का कोण (कोण rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = hi;
