const ja = [
   {
      equation_id: "centripetal-acceleration",
      name: "向心加速度",
      equation_text: "a_c = v² / r",
      summary: "向心加速度を計算します (a_c = v^2 / r)",
      description:
         "直線速度と半径を用いて、円軌道の中心方向に向かう加速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         a_c: "向心加速度 (加速度 m/s²)",
         v: "直線速度 (速さ m/s)",
         r: "円軌道の半径 (長さ m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "向心加速度 (角速度)",
      equation_text: "a_c = ω²r",
      summary: "角速度を用いて向心加速度を計算します (a_c = -ω^2 * r)",
      description:
         "角速度と半径を用いて、向心加速度のベクトル成分を計算します。負の符号は中心方向を示します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         a_c: "向心加速度 (加速度 m/s²)",
         ω: "角速度 (角速度 rad/s)",
         r: "円軌道の半径 (長さ m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "クーロンの法則 (力)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "クーロンの法則を用いて電気力を計算します (F = k * q1*q2 / r^2)",
      description:
         "2つの点電荷間の電気力を計算します。符号付きの力 (斥力は正、引力は負) を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F: "電気力 (力 N)",
         k: "クーロン定数 (定数 N·m²/C²)",
         q1: "電荷 1 (電荷 C)",
         q2: "電荷 2 (電荷 C)",
         r: "電荷間の距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "電場",
      equation_text: "E = kq / r² (点電荷)",
      summary: "力から電場を計算します (E = F_E/q)",
      description: "試験電荷に働く力に基づいて電場の強さを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "電場の大きさ (電場 N/C)",
         k: "クーロン定数 (定数 N·m²/C²)",
         q: "源電荷 (電荷 C)",
         r: "源電荷からの距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "電位",
      equation_text: "V = kq / r (点電荷)",
      summary: "ポテンシャルエネルギーの変化から電位を計算します (V = ΔU_E/q)",
      description:
         "単位電荷あたりの電位エネルギーの変化に基づいて電位（電圧）を計算します。注：関数名`calculateElectricPotential`は正しいですが、パラメータ`deltaUE`は変化を意味し、一方、等式は通常V=U_E/qまたはΔV=ΔU_E/qです。等式ΔV=ΔU_E/qに基づいて記述し、ΔVを返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         V: "電位 (電圧 V)",
         k: "クーロン定数 (定数 N·m²/C²)",
         q: "源電荷 (電荷 C)",
         r: "源電荷からの距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "電場と電位の関係",
      equation_text: "E_x = -dV/dx",
      summary: "電位差から電場を計算します (E = ΔV/d)",
      description:
         'ある距離間の電位差に基づいて一様な電場の大きさを計算します。注：関数名「Field and Potential」は紛らわしいです。これは電場Eを計算します。',
      language_code: "ja",
      subject: "Physics",
      variables: {
         E_x: "電場成分 (電場 V/m)",
         V: "電位 (電圧 V)",
         x: "位置 (長さ m)",
         ΔV: "電位差 (電圧 V)",
         d: "距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "静電容量",
      equation_text: "C = Q / V",
      summary: "静電容量を計算します (C = Q/V)",
      description: "蓄えられた電荷とコンデンサにかかる電圧に基づいて静電容量を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C: "静電容量 (静電容量 F)",
         Q: "電荷 (電荷 C)",
         V: "電圧 (電圧 V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "平行板コンデンサの静電容量",
      equation_text: "C = ε₀A / d",
      summary: "平行板コンデンサの静電容量を計算します (C = (kε₀A)/d)",
      description:
         "誘電体を含む平行板コンデンサの静電容量を計算します。注：関数はk * ε₀を単一の入力（`kEpsilon`）として使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C: "静電容量 (静電容量 F)",
         ε0: "真空の誘電率 (定数 F/m)",
         k: "誘電率 (無次元)",
         A: "プレートの面積 (面積 m²)",
         d: "プレート間の距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "円筒形コンデンサの静電容量",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "円筒形コンデンサの静電容量を計算します (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "誘電体を含む円筒形コンデンサの静電容量を計算します。注：関数はk * ε₀を単一の入力（`kEpsilon`）として使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C: "静電容量 (静電容量 F)",
         π: "パイ (無次元の定数)",
         ε0: "真空の誘電率 (定数 F/m)",
         k: "誘電率 (無次元)",
         L: "円筒の長さ (長さ m)",
         b: "外側半径 (長さ m)",
         a: "内側半径 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "球形コンデンサの静電容量",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "球形コンデンサの静電容量を計算します (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "誘電体を含む球形コンデンサの静電容量を計算します。注：関数はk * ε₀を単一の入力（`kEpsilon`）として使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C: "静電容量 (静電容量 F)",
         π: "パイ (無次元の定数)",
         ε0: "真空の誘電率 (定数 F/m)",
         k: "誘電率 (無次元)",
         a: "内側半径 (長さ m)",
         b: "外側半径 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "静電エネルギー",
      equation_text: "U_C = ½CV²",
      summary: "コンデンサのポテンシャルエネルギーの等式を検証します (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "与えられたQ、V、Cに対して、コンデンサに蓄えられたポテンシャルエネルギーの3つの一般的な等式が等価であるかチェックします。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         U_C: "静電エネルギー (エネルギー J)",
         Q: "電荷 (電荷 C)",
         V: "電圧 (電圧 V)",
         C: "静電容量 (静電容量 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "電流",
      equation_text: "I = ΔQ / Δt",
      summary: "電流を計算します (I = ΔQ/Δt)",
      description: "単位時間あたりにある点を通過する電荷量に基づいて電流を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         I: "電流 (電流 A)",
         ΔQ: "電荷の変化 (電荷 C)",
         Δt: "時間の変化 (時間 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "電荷密度",
      equation_text: "ρ = Q / V (体積)",
      summary: "電荷密度を計算します (ρ = Q/V)",
      description: "平均電荷密度（単位体積あたりの電荷）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ρ: "体積電荷密度 (電荷密度 C/m³)",
         Q: "総電荷 (電荷 C)",
         V: "体積 (体積 m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "電流密度",
      equation_text: "J = I / A",
      summary: "電流密度を計算します (J = I/A)",
      description: "電流密度（単位断面積あたりの電流）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         J: "電流密度 (電流密度 A/m²)",
         I: "電流 (電流 A)",
         A: "面積 (面積 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "オームの法則",
      equation_text: "V = IR",
      summary: "オームの法則を用いて抵抗を計算します (R = V/I)",
      description:
         "電圧と電流に基づいて抵抗を計算します。注：この関数はVとIから抵抗Rを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         V: "電圧 (電圧 V)",
         I: "電流 (電流 A)",
         R: "抵抗 (抵抗 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "抵抗率と導電率",
      equation_text: "ρ = RA / L",
      summary: "抵抗率から導電率を計算します (σ = 1/ρ)",
      description: "抵抗率 (ρ) から導電率 (σ) を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         σ: "導電率 (導電率 S/m)",
         ρ: "抵抗率 (抵抗率 Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "電気抵抗",
      equation_text: "R = ρL / A",
      summary: "電気抵抗を計算します (R = ρ(l/A))",
      description:
         "導体の抵抗を、その抵抗率、長さ、断面積に基づいて計算します。注：抵抗率には`rhoValue`を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         R: "抵抗 (抵抗 Ω)",
         ρ: "抵抗率 (抵抗率 Ω·m)",
         L: "長さ (長さ m)",
         A: "断面積 (面積 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "電力",
      equation_text: "P = IV",
      summary: "電力の等式を検証します (P = VI = I^2R = V^2/R)",
      description:
         "与えられたV、I、Rに対して、電力の3つの一般的な等式が等価であるかチェックします。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "電力 (電力 W)",
         V: "電圧 (電圧 V)",
         I: "電流 (電流 A)",
         R: "抵抗 (抵抗 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "直列抵抗",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "直列接続された抵抗の合計抵抗を計算します (R_total = R1 + R2 + ...)",
      description: "複数の抵抗が直列に接続された場合の合計等価抵抗を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         R_total: "合計抵抗 (抵抗 Ω)",
         R: "個々の抵抗 (抵抗 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "並列抵抗",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "並列接続された抵抗の合計抵抗を計算します (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "複数の抵抗が並列に接続された場合の合計等価抵抗を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         R_total: "合計抵抗 (抵抗 Ω)",
         R: "個々の抵抗 (抵抗 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "直列コンデンサ",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "直列接続されたコンデンサの合計静電容量を計算します (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "複数のコンデンサが直列に接続された場合の合計等価静電容量を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C_total: "合計静電容量 (静電容量 F)",
         C: "個々の静電容量 (静電容量 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "並列コンデンサ",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "並列接続されたコンデンサの合計静電容量を計算します (C_total = C1 + C2 + ...)",
      description: "複数のコンデンサが並列に接続された場合の合計等価静電容量を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         C_total: "合計静電容量 (静電容量 F)",
         C: "個々の静電容量 (静電容量 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "電荷に働く磁気力",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "荷電粒子に働く磁気力を計算します (F = qvB sin(θ))",
      description:
         "運動している荷電粒子に働く磁気力の大きさを計算します。角度はラジアンである必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F_B: "磁気力の大きさ (力 N)",
         q: "電荷の大きさ (電荷 C)",
         v: "速度の大きさ (速さ m/s)",
         B: "磁場の大きさ (磁場 T)",
         θ: "速度と磁場の間の角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "電流に働く磁気力",
      equation_text: "F_B = ILBsin(θ)",
      summary: "電流を帯びた導体に働く磁気力を計算します (F = I l B sin(θ))",
      description:
         "磁場中で電流を帯びた直線導体に働く磁気力の大きさを計算します。角度はラジアンである必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F_B: "磁気力の大きさ (力 N)",
         I: "電流 (電流 A)",
         L: "導体の長さ (長さ m)",
         B: "磁場の大きさ (磁場 T)",
         θ: "電流と磁場の間の角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "ビオ・サバールの法則",
      equation_text: "B = μ₀I / (2πr) (無限長の直線電流)",
      summary: "電流素子から磁場を計算します (dB = (μ₀I ds) / (4πr^2))",
      description:
         "半径ベクトルに垂直な微小電流要素からの磁場への貢献の大きさを計算します。注：この関数は `(μ₀ * I * ds) / (4 * π * r^2)` を実装しており、微分形式にしばしば存在するsin(θ)項を省略しています。これは事実上、θ=90度を仮定しているか、その特定の平面内で半径ベクトルに垂直な成分のみを計算しています。実装された等式に基づいて記述しています。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         dB: "磁場への貢献の大きさ (磁場 T)",
         μ0: "真空の透磁率 (定数 T·m/A)",
         I: "電流 (電流 A)",
         ds: "電流素子の微小長さ (長さ m)",
         r: "電流素子からの距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "ソレノイドの磁場",
      equation_text: "B = μ₀nI (内部, 理想)",
      summary: "長いソレノイド内部の磁場を計算します (B = μ₀nI)",
      description: "長い理想ソレノイド内部の磁場の大きさを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         B: "ソレノイド内部の磁場強度 (磁場 T)",
         μ0: "真空の透磁率 (定数 T·m/A)",
         n: "単位長さあたりの巻数 (長さあたりの数 m⁻¹)",
         I: "電流 (電流 A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "直線電流の磁場",
      equation_text: "B = μ₀I / (2πr) (無限長)",
      summary: "無限長の直線電流からの磁場を計算します (B = (μ₀I)/(2πr))",
      description:
         "長い直線導体を流れる電流からの距離における磁場の大きさを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         B: "直線電流からの磁場強度 (磁場 T)",
         μ0: "真空の透磁率 (定数 T·m/A)",
         I: "電流 (電流 A)",
         π: "パイ (無次元の定数)",
         r: "ワイヤーからの距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "平行電流間に働く力",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "平行電流間の単位長さあたりの力を計算します (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "長い平行導体を流れる2つの電流間の単位長さあたりの力の大きさを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         "F/L": "単位長さあたりの力 (長さあたりの力 N/m)",
         μ0: "真空の透磁率 (定数 T·m/A)",
         I1: "ワイヤー 1 の電流 (電流 A)",
         I2: "ワイヤー 2 の電流 (電流 A)",
         π: "パイ (無次元の定数)",
         d: "ワイヤー間の距離 (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "電束",
      equation_text: "Φ_E = EAcos(θ) (E uniforme)",
      summary: "電束を計算します (Φ_E = E * A * cos(θ))",
      description:
         "一様な電場中の平面を通過する電束を計算します。角度は電場ベクトルと面積ベクトルの間であり、ラジアンである必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Φ_E: "電束 (電束 N·m²/C)",
         E: "電場の大きさ (電場 N/C)",
         A: "面積 (面積 m²)",
         θ: "Eと面積ベクトルの間の角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "磁束",
      equation_text: "Φ_B = BAcos(θ) (B uniforme)",
      summary: "磁束を計算します (Φ_B = B * A * cos(θ))",
      description:
         "一様な磁場中の平面を通過する磁束を計算します。角度は磁場ベクトルと面積ベクトルの間であり、ラジアンである必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Φ_B: "磁束 (磁束 Wb)",
         B: "磁場の大きさ (磁場 T)",
         A: "面積 (面積 m²)",
         θ: "Bと面積ベクトルの間の角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "誘導起電力 (運動)",
      equation_text: "ε = vBL (直線導体)",
      summary: "運動による誘導起電力を計算します (emf = Blv)",
      description:
         "磁場に垂直に移動する導体に誘導される起電力の大きさを計算します。注：この関数はBlvの大きさを計算しており、方向を示すために時々使用される負の符号（レンツの法則）は省略されています。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ε: "運動による誘導起電力の大きさ (電圧 V)",
         v: "導体の速さ (速さ m/s)",
         B: "磁場の大きさ (磁場 T)",
         L: "導体の長さ (長さ m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "誘導起電力 (ファラデーの法則)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "変化する磁束から誘導起電力を計算します (emf = -ΔΦ_B / Δt)",
      description: "ファラデーの電磁誘導の法則に従い、変化する磁束によって誘導される起電力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ε: "誘導起電力 (電圧 V)",
         ΔΦ_B: "磁束の変化 (磁束 Wb)",
         Δt: "時間の変化 (時間 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "自己誘導による誘導起電力",
      equation_text: "ε_L = -L dI / dt",
      summary: "インダクタ内の電流の変化から誘導起電力を計算します (emf = -L * ΔI / Δt)",
      description:
         "電流の変化によるインダクタ内の自己誘導起電力を計算します。注：関数名は`calculateInductance`ですが、この等式を用いて起電力を返します。返される値を記述しています。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ε_L: "インダクタ内の誘導起電力 (電圧 V)",
         L: "インダクタンス (インダクタンス H)",
         ΔI: "電流の変化 (電流 A)",
         Δt: "時間の変化 (時間 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "容量性リアクタンス",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "容量性リアクタンスを計算します (X_C = 1/(2πfC))",
      description: "コンデンサの交流に対する抵抗を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         X_C: "容量性リアクタンス (リアクタンス Ω)",
         π: "パイ (無次元の定数)",
         f: "周波数 (周波数 Hz)",
         C: "静電容量 (静電容量 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "誘導性リアクタンス",
      equation_text: "X_L = 2πfL",
      summary: "誘導性リアクタンスを計算します (X_L = 2πfL))",
      description: "インダクタの交流に対する抵抗を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         X_L: "誘導性リアクタンス (リアクタンス Ω)",
         π: "パイ (無次元の定数)",
         f: "周波数 (周波数 Hz)",
         L: "インダクタンス (インダクタンス H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "インピーダンス",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "インピーダンスを計算します (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "抵抗、誘導性リアクタンス、容量性リアクタンスを含む交流回路における電流の流れに対する総抵抗を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Z: "インピーダンス (インピーダンス Ω)",
         R: "抵抗 (抵抗 Ω)",
         X_L: "誘導性リアクタンス (リアクタンス Ω)",
         X_C: "容量性リアクタンス (リアクタンス Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "密度",
      equation_text: "ρ = m / V",
      summary: "密度を計算します (ρ = m/V)",
      description: "質量と体積に基づいて密度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ρ: "密度 (密度 kg/m³)",
         m: "質量 (質量 kg)",
         V: "体積 (体積 m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "圧力",
      equation_text: "P = F / A",
      summary: "圧力を計算します (P = F/A)",
      description: "面積にかかる力に基づいて圧力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "圧力 (圧力 Pa)",
         F: "力 (力 N)",
         A: "面積 (面積 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "流体中の圧力",
      equation_text: "P = P₀ + ρgh",
      summary: "流体中の圧力を計算します (P = P0 + ρgh)",
      description: "流体中のある深さにおける絶対圧力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "絶対圧力 (圧力 Pa)",
         P0: "大気圧または表面圧力 (圧力 Pa)",
         ρ: "流体の密度 (密度 kg/m³)",
         g: "重力加速度 (加速度 m/s²)",
         h: "深さ (長さ m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "浮力",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "浮力を計算します (F_b = ρgV_displaced)",
      description:
         "流体が水没または部分的に水没した物体に及ぼす浮力を計算します（アルキメデスの原理）。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F_B: "浮力 (力 N)",
         ρ_fluid: "流体の密度 (密度 kg/m³)",
         V_submerged: "水没体積 (体積 m³)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "質量流量",
      equation_text: "ṁ = ρAv",
      summary: "質量流量を計算します (ṁ = Δm/Δt)",
      description: "単位時間あたりにある点を通過する質量の割合を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ṁ: "質量流量 (質量流量 kg/s)",
         ρ: "流体の密度 (密度 kg/m³)",
         A: "面積 (面積 m²)",
         v: "流体速度 (速さ m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "体積流量",
      equation_text: "Q = Av",
      summary: "体積流量を計算します (Q = ΔV/Δt)",
      description: "単位時間あたりにある点を通過する体積の割合を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Q: "体積流量 (体積流量 m³/s)",
         A: "面積 (面積 m²)",
         v: "流体速度 (速さ m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "ベルヌーイの定理",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "ベルヌーイの定理をチェックします (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "与えられた流体の性質と2つの点での条件に対して、ベルヌーイの定理が成り立つか検証します。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "圧力 (圧力 Pa)",
         ρ: "流体の密度 (密度 kg/m³)",
         v: "流体速度 (速さ m/s)",
         g: "重力加速度 (加速度 m/s²)",
         y: "高さ (長さ m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "動粘性率",
      equation_text: "τ = μ * (dv/dy)",
      summary: "動粘性率を計算します (η = F * Δy / (A * Δvx))",
      description:
         "力、速度勾配、面積に基づいて動粘性率を計算します。この等式はせん断応力/ひずみ速度から導出されます。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         μ: "動粘性率 (動粘性率 Pa·s)",
         F: "力 (力 N)",
         Δy: "流れに垂直な距離 (長さ m)",
         A: "面積 (面積 m²)",
         Δvx: "速度の変化 (速さ m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "動粘度",
      equation_text: "ν = μ / ρ",
      summary: "動粘度を計算します (ν = η / ρ)",
      description: "動粘性率と密度から動粘度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ν: "動粘度 (動粘度 m²/s)",
         μ: "動粘性率 (動粘性率 Pa·s)",
         ρ: "流体の密度 (密度 kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "抗力",
      equation_text: "F_D = ½ρv²CdA",
      summary: "抗力を計算します (F_d = 0.5 * ρ * C_A * v^2)",
      description: "流体中を移動する物体に働く抗力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F_D: "抗力 (力 N)",
         ρ: "流体の密度 (密度 kg/m³)",
         v: "速度 (速さ m/s)",
         Cd: "抗力係数 (無次元)",
         A: "基準面積 (面積 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "マッハ数",
      equation_text: "M = v / c_sound",
      summary: "マッハ数を計算します (M = v/c)",
      description: "物体の速さと媒質中の音速の比であるマッハ数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         M: "マッハ数 (無次元)",
         v: "物体の速さ (速さ m/s)",
         c_sound: "媒質中の音速 (速さ m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "レイノルズ数",
      equation_text: "Re = ρvd / μ",
      summary: "レイノルズ数を計算します (Re = (ρ * v * D) / η)",
      description:
         "さまざまな流体流動状況における流動パターンを予測するために使用される無次元量であるレイノルズ数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Re: "レイノルズ数 (無次元)",
         ρ: "流体の密度 (密度 kg/m³)",
         v: "速度 (速さ m/s)",
         d: "代表長さ (長さ m)",
         μ: "動粘性率 (動粘性率 Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "フルード数",
      equation_text: "Fr = v / √(gL)",
      summary: "フルード数を計算します (Fr = v / √(g * l))",
      description:
         "流体の運動に対する重力の影響を示すために使用される無次元量であるフルード数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Fr: "フルード数 (無次元)",
         v: "速度 (速さ m/s)",
         g: "重力加速度 (加速度 m/s²)",
         L: "代表長さ (長さ m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "表面張力",
      equation_text: "γ = F / L",
      summary: "表面張力を計算します (γ = F / l)",
      description: "力と長さに基づいて液体の表面張力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         γ: "表面張力 (表面張力 N/m)",
         F: "力 (力 N)",
         L: "長さ (長さ m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "万有引力 (力)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "万有引力を計算します (F = -Gm1m2/r^2)",
      description:
         "2つの点質量間の引力である万有引力を計算します。注：引力を示す負の値を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F: "万有引力 (力 N)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         m1: "質量 1 (質量 kg)",
         m2: "質量 2 (質量 kg)",
         r: "質量間の距離 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "重力場",
      equation_text: "g = GM / r² (大きさ)",
      summary: "重力場を計算します (g = -Gm/r^2)",
      description:
         "点質量からの距離における重力場の強さを計算します。注：質量に向かう方向を示す負の値を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         g: "重力場強度の大きさ (重力場 N/kg)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         M: "源質量 (質量 kg)",
         r: "源質量からの距離 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "重力ポテンシャルエネルギー",
      equation_text: "U_g = -G m₁m₂ / r (一般)",
      summary: "2つの質量間の重力ポテンシャルエネルギーを計算します (PE = -Gm1m2/r)",
      description: "2つの点質量の系の重力ポテンシャルエネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         U_g: "重力ポテンシャルエネルギー (エネルギー J)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         m1: "質量 1 (質量 kg)",
         m2: "質量 2 (質量 kg)",
         r: "質量間の距離 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "重力ポテンシャル",
      equation_text: "V_g = -GM / r",
      summary: "重力ポテンシャルを計算します (V_g = -Gm/r)",
      description: "点質量からの距離における重力ポテンシャルを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         V_g: "重力ポテンシャル (重力ポテンシャル J/kg)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         M: "源質量 (質量 kg)",
         r: "源質量からの距離 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "軌道速度",
      equation_text: "v_orbit = √(GM / r) (円軌道)",
      summary: "軌道速度を計算します (v = sqrt(Gm/r))",
      description: "より大きな質量の周りの円軌道にある物体の速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_orbit: "軌道速度 (速さ m/s)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         M: "中心体の質量 (質量 kg)",
         r: "軌道半径 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "脱出速度",
      equation_text: "v_escape = √(2GM / r)",
      summary: "脱出速度を計算します (v = sqrt(2Gm/r))",
      description:
         "与えられた距離から質量の引力圏から脱出するために必要な最小速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_escape: "脱出速度 (速さ m/s)",
         G: "万有引力定数 (定数 N·m²/kg²)",
         M: "中心体の質量 (質量 kg)",
         r: "中心からの距離 (長さ m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "熱伝導",
      equation_text: "Q/t = kAΔT/d",
      summary: "熱伝導率を計算します (Q/t = (kAΔT) / L)",
      description:
         "材料を介した伝導による熱伝達率を計算します。注：この関数はQを計算しており、等式が通常率を示すために使用されることから時間間隔が暗示されていると仮定しています。ドキュメントはQを示していますが、等式は典型的にはQ/tです。この違いを明確にします。関数は率の等式の右辺の結果を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         "Q/t": "熱伝達率 (仕事率 W)",
         k: "熱伝導率 (熱伝導率 W/(m·K))",
         A: "面積 (面積 m²)",
         ΔT: "温度差 (温度差 K)",
         d: "厚さ (長さ m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "シュテファン・ボルツマンの法則",
      equation_text: "P = εσAT⁴",
      summary: "熱放射パワーを計算します (P = εσA(T^4 - T0^4))",
      description: "物体が周囲を考慮して放射するエネルギーの正味の速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "正味放射パワー (仕事率 W)",
         ε: "放射率 (無次元)",
         σ: "シュテファン・ボルツマン定数 (定数 W/(m²·K⁴))",
         A: "表面積 (面積 m²)",
         T: "物体の温度 (温度 K)",
         T0: "周囲の温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "ウィーンの変位則 (最大波長)",
      equation_text: "λ_max = b/T",
      summary: "ウィーンの法則を用いてピーク波長を計算します (λ_max = b/T)",
      description: "黒体の放射スペクトルが最大になる波長を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         λ_max: "ピーク放出の波長 (長さ m)",
         b: "ウィーンの変位定数 (定数 m·K)",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "ウィーンの変位則 (最大周波数)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "ウィーンの法則を用いてピーク周波数を計算します (f_max = b' * T)",
      description:
         "黒体の放射スペクトルが最大になる周波数を計算します。注：このバージョンは修正されたウィーン定数b'を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f_max: "ピーク放出の周波数 (周波数 Hz)",
         "b'": "修正ウィーン定数 (定数 Hz/K)",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "等式情報 (特定)",
      equation_text: "N/A (情報を取得し、計算はしません)",
      summary: "IDと言語で等式情報を取得",
      description:
         "固有のIDと希望する言語に基づいて、特定の等式の詳細を取得します。注 - 言語は 'language_code' パスパラメータから抽出されます。コードスニペットに示されている内部ロジックは、'lang' クエリパラメータも見ていますが、このSwagger定義は主要なパスパラメータを記述しています。",
      language_code: "ja",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "APIの全ての等式エンドポイントを取得します。",
      description: "APIの全てのエンドポイントの概要情報を取得します。",
      language_code: "ja",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "速度",
      equation_text: "v = Δx / Δt",
      summary: "速度を計算します",
      description: "変位と時間に基づいて速度を計算します (v = Δs / Δt)。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v: "速度 (速度 m/s)",
         Δx: "変位 (長さ m)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "加速度",
      equation_text: "a = Δv / Δt",
      summary: "加速度を計算します",
      description: "速度の変化と時間に基づいて加速度を計算します (a = Δv / Δt)。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         a: "加速度 (加速度 m/s²)",
         Δv: "速度の変化 (速度 m/s)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "運動方程式 (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "終速度を計算します (v = v0 + at)",
      description: "最初の運動方程式を用いて終速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v: "終速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
         a: "加速度 (加速度 m/s²)",
         t: "時間 (時間 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "運動方程式 (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "終位置を計算します (s = s0 + v0t + 0.5at^2)",
      description: "2番目の運動方程式を用いて終位置を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         s: "終位置 (長さ m)",
         s0: "初位置 (長さ m)",
         v0: "初速度 (速度 m/s)",
         t: "時間 (時間 s)",
         a: "加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "運動方程式 (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "終速度の二乗を計算します (v^2 = v0^2 + 2a(s - s0))",
      description: "3番目の運動方程式を用いて終速度の二乗を計算します。注：vではなくv^2を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v: "終速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
         a: "加速度 (加速度 m/s²)",
         Δs: "変位 (長さ m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "平均速度",
      equation_text: "v_avg = Δx / Δt",
      summary: "平均速度を計算します (v_avg = 0.5 * (v + v0))",
      description: "等加速度を仮定して平均速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_avg: "平均速度 (速度 m/s)",
         v: "終速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "力 (ニュートンの第2法則)",
      equation_text: "F_net = ma",
      summary: "力を計算します (F = ma)",
      description: "ニュートンの第2法則を用いて力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F_net: "正味の力 (力 N)",
         m: "質量 (質量 kg)",
         a: "加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "重さ",
      equation_text: "W = mg",
      summary: "重さを計算します (W = mg)",
      description: "物体に働く重力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         W: "重さ (力 N)",
         m: "質量 (質量 kg)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "最大静止摩擦力",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "最大静止摩擦力を計算します (F_s = μ_s * N)",
      description: "可能な最大静止摩擦力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f_s_max: "最大静止摩擦力 (力 N)",
         μ_s: "静止摩擦係数 (無次元)",
         F_N: "垂直抗力 (力 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "動摩擦力",
      equation_text: "f_k = μ_k * F_N",
      summary: "動摩擦力を計算します (F_k = μ_k * N)",
      description: "動いている物体に働く動摩擦力を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f_k: "動摩擦力 (力 N)",
         μ_k: "動摩擦係数 (無次元)",
         F_N: "垂直抗力 (力 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "運動量",
      equation_text: "p = mv",
      summary: "運動量を計算します (p = mv)",
      description: "物体の線形運動量を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         p: "運動量 (運動量 kg·m/s)",
         m: "質量 (質量 kg)",
         v: "速度 (速度 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "力積",
      equation_text: "J = F_avg * Δt",
      summary: "力積を計算します (J = F * Δt)",
      description: "力と時間間隔から力積を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         J: "力積 (力積 N·s)",
         F_avg: "平均力 (力 N)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "力積と運動量の関係",
      equation_text: "J = Δp",
      summary: "力積と運動量の関係を検証します (F * Δt = m * Δv)",
      description: "与えられた値に対して力積が運動量の変化に等しいかチェックします。ブール値を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         J: "力積 (力積 N·s)",
         Δp: "運動量の変化 (運動量 kg·m/s)",
         F: "力 (力 N)",
         Δt: "時間間隔 (時間 s)",
         m: "質量 (質量 kg)",
         Δv: "速度の変化 (速度 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "放射能活性度",
      equation_text: "A = λN",
      summary: "放射性崩壊の平均活性度を計算します (A_avg = ΔN/Δt)",
      description:
         "時間間隔にわたる放射性試料の平均活性度（崩壊率）を計算します。注：関数は核の数 ΔN に `nValue` を、時間 Δt に `tValue` を使用しています。これは Δt における簡略化された平均であり、瞬間活性度は dN/dt = -λN です。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         A_avg: "平均放射能活性度 (活性度 Bq)",
         ΔN: "崩壊数 (無次元の数)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "半減期",
      equation_text: "T_½ = ln(2) / λ",
      summary: "崩壊後の残存量を計算します (N = N0 * (1/2)^(t/T_half))",
      description:
         "半減期に基づいて、ある時間後の物質の残存量を計算します。注：時間には`tValue`を、半減期には`Thalf`を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         N: "残存量/核 (数)",
         N0: "初期量/核 (数)",
         t: "経過時間 (時間 s)",
         T_half: "半減期 (時間 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "吸収線量",
      equation_text: "D = dE / dm",
      summary: "吸収線量を計算します (D = E/m)",
      description:
         "質量によって吸収されたエネルギーに基づいて、放射線の吸収線量を計算します。注：エネルギーには`EValue`を、質量には`mValue`を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         D: "吸収線量 (吸収線量 Gy)",
         E: "吸収されたエネルギー (エネルギー J)",
         m: "質量 (質量 kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "等価線量",
      equation_text: "H = D * W_R",
      summary: "等価線量を計算します (H = wR * D)",
      description:
         "異なる種類の放射線の生物学的効果を考慮して、等価線量を計算します。注：吸収線量には`DValue`を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         H: "等価線量 (等価線量 Sv)",
         D: "吸収線量 (吸収線量 Gy)",
         W_R: "放射線加重係数 (無次元)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "実効線量",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "実効線量を計算します (E = wT * H)",
      description:
         "異なる組織/臓器の放射線に対する感度を考慮して、実効線量を計算します。注：等価線量には`HValue`を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "実効線量 (実効線量 Sv)",
         H_T: "組織/臓器 T の等価線量 (等価線量 Sv)",
         W_T: "組織/臓器 T の組織加重係数 (無次元)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "チェレンコフ角",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "チェレンコフ角を計算します (θ_C = arccos(c/nv_p))",
      description:
         "媒質中の光速よりも速く移動する荷電粒子によって形成されるチェレンコフ円錐の角度を計算します。角度はラジアンで返されます。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         θ_C: "チェレンコフ角 (角度 rad)",
         c: "真空中の光速 (速さ m/s)",
         n: "媒質の屈折率 (無次元)",
         v: "粒子速度 (速さ m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "干渉縞 (例：位置、間隔)",
      equation_text: "Δy = λL / d (二重スリット間隔)",
      summary: "干渉縞の位置を計算します (y_n = (nλL)/d)",
      description: "ヤングの二重スリット干渉パターンにおけるn番目の明るい縞の位置を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         y_n: "n番目の明るい縞の位置 (長さ m)",
         n: "縞の次数 (無次元の整数)",
         λ: "波長 (長さ m)",
         L: "スクリーンまでの距離 (長さ m)",
         d: "スリット間隔 (長さ m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "屈折率",
      equation_text: "n = c / v",
      summary: "屈折率を計算します (n = c/v)",
      description:
         "真空中の光速と媒質中の光速に基づいて、媒質の屈折率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         n: "屈折率 (無次元)",
         c: "真空中の光速 (速さ m/s)",
         v: "媒質中の光速 (速さ m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "スネルの法則",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "スネルの法則を検証します (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "与えられた屈折率と角度を持つ2つの媒質間を光が通過する場合に、スネルの法則が成り立つか検証します。ブール値を返します。角度はラジアンである必要があります。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         n1: "媒質 1 の屈折率 (無次元)",
         θ1: "媒質 1 の角度 (角度 rad)",
         n2: "媒質 2 の屈折率 (無次元)",
         θ2: "媒質 2 の角度 (角度 rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "臨界角",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "臨界角を計算します (θ_c = arcsin(n2/n1))",
      description:
         "光が屈折率n1からn2の媒質（n1 > n2）に進む場合の全反射の臨界角を計算します。角度はラジアンで返されます。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         θ_c: "臨界角 (角度 rad)",
         n1: "媒質 1 の屈折率 (無次元)",
         n2: "媒質 2 の屈折率 (無次元)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "像の位置 (光学)",
      equation_text: "1/f = 1/d_o + 1/d_i (薄レンズ/鏡)",
      summary: "薄レンズ/鏡の等式を検証します (1/f = 1/do + 1/di)",
      description:
         "焦点距離、物体距離、像距離の関係が成り立つかチェックします。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f: "焦点距離 (長さ m)",
         d_o: "物体距離 (長さ m)",
         d_i: "像距離 (長さ m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "像の大きさ (倍率 - 光学)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "倍率の等式を検証します (h'/h = di/do) (関数は h'/h = di/do を使用)",
      description:
         "物体/像の高さと距離の関係が成り立つかチェックします。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。この関数は符号付きの倍率等式ではなく、大きさの関係 `h'/h = di/do` を使用します。関数の実装に基づいて記述しています。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         M: "倍率 (無次元)",
         h_i: "像の高さ (長さ m)",
         h_o: "物体の高さ (長さ m)",
         d_i: "像距離 (長さ m)",
         d_o: "物体距離 (長さ m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "球面鏡の等式",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "球面鏡の焦点距離を計算します (f = r/2)",
      description: "球面鏡の曲率半径に基づいて焦点距離を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f: "焦点距離 (長さ m)",
         r: "曲率半径 (長さ m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "ばねのポテンシャルエネルギー",
      equation_text: "U_s = ½kx²",
      summary: "ばねのポテンシャルエネルギーを計算します (PE = 0.5 * k * Δx^2)",
      description: "理想的なばねに蓄えられた弾性ポテンシャルエネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         U_s: "ばねのポテンシャルエネルギー (エネルギー J)",
         k: "ばね定数 (ばね定数 N/m)",
         x: "平衡位置からの変位 (長さ m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "単振動 (SHO) の周期",
      equation_text: "T = 2π√(m/k)",
      summary: "ばね-質量系の単振動の周期を計算します (T = 2π√(m/k))",
      description:
         "ばねに繋がれた質量からなる単振動の周期を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         T: "周期 (時間 s)",
         π: "パイ (無次元の定数)",
         m: "質量 (質量 kg)",
         k: "ばね定数 (ばね定数 N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "単振り子の周期",
      equation_text: "T = 2π√(L/g)",
      summary: "単振り子の周期を計算します (T = 2π√(l/g))",
      description: "小さな角度における単振り子の周期を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         T: "周期 (時間 s)",
         π: "パイ (無次元の定数)",
         L: "振り子の長さ (長さ m)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "周波数",
      equation_text: "f = 1 / T",
      summary: "周波数を計算します (f = 1/T)",
      description: "振動の周期から周波数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f: "周波数 (周波数 Hz)",
         T: "周期 (時間 s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "角周波数",
      equation_text: "ω = 2πf",
      summary: "角周波数を計算します (ω = 2πf)",
      description: "周波数から角周波数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ω: "角周波数 (角速度 rad/s)",
         π: "パイ (無次元の定数)",
         f: "周波数 (周波数 Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "ローレンツ因子",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "ローレンツ因子を計算します (γ)",
      description: "γ = 1/√(1 - (v²/c²)) を用いてローレンツ因子を計算します。v < c が必要です。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         γ: "ローレンツ因子 (無次元)",
         v: "速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "時間の遅れ",
      equation_text: "Δt' = γ * Δt₀",
      summary: "時間の遅れを計算します (t' = γ * t₀)",
      description:
         "運動している慣性系 S' で測定された固有時 (t₀) と、S' に対する慣性系 S の相対速度 (v) が与えられた場合、慣性系 S の観測者にとっての経過時間 (t') を計算します。t' = t₀ / √(1 - (v²/c²)) を使用します。t₀ ≥ 0 かつ |v| ≤ c である必要があります。t' の単位は t₀ と同じになり、v と c の単位は整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Δt: "遅れた時間 (時間 s)",
         Δt0: "固有時 (時間 s)",
         v: "相対速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "ローレンツ収縮",
      equation_text: "L' = L₀ / γ",
      summary: "ローレンツ収縮を計算します (L' = L₀ / γ)",
      description:
         "静止系 S で測定された物体の固有長 (L₀) と、S' に対する S の相対速度 (v) が与えられた場合、運動している参照系 S' から観測される物体の長さ (L') を計算します。L' = L₀ * √(1 - (v²/c²)) を使用します。L₀ ≥ 0 かつ |v| ≤ c である必要があります。L' の単位は L₀ と同じになり、v と c の単位は整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         L: "収縮した長さ (長さ m)",
         L0: "固有長 (長さ m)",
         v: "相対速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "相対論的速度の合成",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "相対論的速度の合成を計算します",
      description:
         "参照系 S に対する物体の速度 (u) と、S' に対する S の速度 (v) が与えられた場合、参照系 S' に対する物体の速度 (u') を計算します。u' = (u + v) / (1 + uv/c²) という等式を使用します。同じ直線上での運動を仮定します。c ≠ 0 が必要です。u、v、c の単位は整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         u: "参照系 S における物体の速度 (速さ m/s)",
         v: "S' に対する参照系 S の速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
         "u'": "参照系 S' に対する物体の速度 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "相対論的エネルギー",
      equation_text: "E = γmc²",
      summary: "相対論的エネルギーを計算します (E)",
      description:
         "静止質量 (m) を持ち、速度 (v) で運動する粒子の全相対論的エネルギーを計算します。E = γmc² = mc² / √(1 - (v²/c²)) という等式を使用します。主に静止質量を持つ粒子 (m > 0) を対象としています。m ≥ 0 かつ |v| ≤ c である必要があります。m、v、c の単位は整合している必要があります (例: m が kg、v/c が m/s の場合、E はジュール単位)。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "全相対論的エネルギー (エネルギー J)",
         m: "静止質量 (質量 kg)",
         v: "速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "相対論的運動量",
      equation_text: "p = γmv",
      summary: "相対論的運動量を計算します (p = γmv)",
      description:
         "静止質量 (m) を持ち、速度 (v) で運動する粒子の相対論的運動量を計算します。p = γmv = mv / √(1 - (v²/c²)) という等式を使用します。主に静止質量を持つ粒子 (m > 0) を対象としています。m ≥ 0 かつ |v| ≤ c である必要があります。m、v、c の単位は整合している必要があります (例: m が kg、v が m/s、c が m/s の場合、p は kg·m/s 単位)。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         p: "相対論的運動量 (運動量 kg·m/s)",
         m: "静止質量 (質量 kg)",
         v: "速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "エネルギー・運動量関係",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "運動量と静止質量から全エネルギーを計算します (E)",
      description:
         "粒子の相対論的運動量 (p) と静止質量 (m) から、その全相対論的エネルギーを計算します。エネルギー・運動量関係: E² = (pc)² + (mc²)² を使用します。この等式は、質量を持つ粒子 (m > 0) と質量のない粒子 (m = 0) の両方で有効です。p ≥ 0、m ≥ 0、c > 0 が必要です。p、m、c の単位は整合している必要があります。\n",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "全相対論的エネルギー (エネルギー J)",
         p: "相対論的運動量 (運動量 kg·m/s)",
         c: "真空中の光速 (速さ m/s)",
         m: "静止質量 (質量 kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "質量とエネルギーの等価性 (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "質量とエネルギーの等価性を計算します (E₀ = mc²)",
      description:
         "アインシュタインの有名な等式 E₀ = mc² を用いて、与えられた静止質量 (m) に等価な静止エネルギー (E₀) を計算します。m ≥ 0 かつ c > 0 が必要です。m と c の単位は整合している必要があります (例: m が kg、c が m/s の場合、E₀ はジュール単位)。このエンドポイントは、'c' が明示的に提供されない限り、c の標準値 (約 299792458 m/s) を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E0: "静止エネルギー (エネルギー J)",
         m: "静止質量 (質量 kg)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "相対論的運動エネルギー",
      equation_text: "KE = (γ - 1)mc²",
      summary: "相対論的運動エネルギーを計算します (KE)",
      description:
         "静止質量 (m) を持ち、速度 (v) で運動する粒子の相対論的運動エネルギーを計算します。KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc² という等式を使用します。主に静止質量を持つ粒子 (m > 0) を対象としています。m ≥ 0 かつ |v| < c である必要があります。m、v、c の単位は、適切な単位でエネルギーを得るために整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE: "相対論的運動エネルギー (エネルギー J)",
         m: "静止質量 (質量 kg)",
         v: "速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "相対論的ドップラー効果 (波長)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "波長に対する相対論的縦方向ドップラー効果を計算します",
      description:
         "固有波長 (λ₀) を持つ光の観測波長 (λ') を、観測者から直接遠ざかる、または近づく相対速度 (v_rel) で運動している光源から計算します。λ' = λ₀√((1 + β)/(1 - β)) という等式を使用します。ここで β = v_rel/c です。v_rel > 0 は遠ざかる場合（赤方偏移）、v_rel < 0 は近づく場合（青方偏移）です。λ₀ > 0 かつ |v_rel| < c である必要があります。λ' の単位は λ₀ と同じになり、v_rel と c の単位は整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         "λ'": "観測波長 (長さ m)",
         λ0: "固有波長 (長さ m)",
         v: "相対速度 (速さ m/s)",
         c: "真空中の光速 (速さ m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "光子エネルギー (周波数から)",
      equation_text: "E = hf",
      summary: "周波数から光子エネルギーを計算します (E = hf)",
      description:
         "光子のエネルギー (E) をその周波数 (f) に基づいて計算します。プランクの関係式 E = hf を使用します。f ≥ 0 かつ h > 0 が必要です。h と f の単位は、適切な単位でエネルギーを得るために整合している必要があります (例: h が J·s、f が Hz (s⁻¹) の場合、E はジュール単位)。このエンドポイントは、'h' が明示的に提供されない限り、h の標準値 (約 6.626e-34 J·s) を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "光子エネルギー (エネルギー J)",
         h: "プランク定数 (定数 J·s)",
         f: "周波数 (周波数 Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "光子運動量 (波長から)",
      equation_text: "p = h / λ",
      summary: "波長から光子運動量を計算します (p = h/λ)",
      description:
         "光子の運動量 (p) をその波長 (λ) に基づいて計算します。関係式 p = h/λ を使用します。λ > 0 かつ h > 0 が必要です。h と λ の単位は、適切な単位で運動量を得るために整合している必要があります (例: h が J·s、λ がメートル の場合、p は kg·m/s 単位)。このエンドポイントは、'h' が明示的に提供されない限り、h の標準値 (約 6.626e-34 J·s) を使用します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         p: "光子運動量 (運動量 kg·m/s)",
         h: "プランク定数 (定数 J·s)",
         λ: "波長 (長さ m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "光電効果 (最大運動エネルギー)",
      equation_text: "KE_max = E_photon - φ",
      summary: "光電効果における最大運動エネルギーを計算します (KE_max)",
      description:
         "光電効果で放出された電子の最大運動エネルギー (KE_max) を計算します。KE_max = E_photon - φ という等式を使用します。ここで E_photon は入射光子エネルギー、φ は材料の仕事関数です。E_photon ≤ φ の場合、電子は放出されず、KE_max は 0 です。E_photon ≥ 0 かつ φ ≥ 0 が必要です。E_photon と φ の単位は、KE_max を同じ単位で得るために整合している必要があります。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE_max: "最大電子運動エネルギー (エネルギー J)",
         E_photon: "光子エネルギー (エネルギー J)",
         φ: "仕事関数 (エネルギー J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "リュードベリ方程式 (原子遷移)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "水素様原子の遷移に対するエネルギーまたは波数計算",
      description:
         "水素様原子 (Z) の2つのエネルギー準位間の電子遷移に対するエネルギー差 (ΔE) または波数 (1/λ) を計算します。結果 = 定数 * Z² * (1/n_initial² - 1/n_final²) という等式を使用します。'定数' がリュードベリエネルギー単位 (例: eV) の場合、結果はエネルギー差 E_final - E_initial (吸収は正、放出は負) です。'定数' が波数に対するリュードベリ定数 (例: m⁻¹) の場合、結果は波数 1/λ (放出は正、吸収は負) です。nInitial > 0、nFinal > 0、nInitial ≠ nFinal、Z > 0 (整数)、定数 > 0 が必要です。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔE: "エネルギー差 (エネルギー J)",
         R_y: "リュードベリ定数 (定数 J または逆長さ m⁻¹)",
         Z: "原子番号 (無次元の整数)",
         n1: "初期主量子数 (無次元の整数)",
         n2: "最終主量子数 (無次元の整数)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "角速度",
      equation_text: "ω = Δθ / Δt",
      summary: "角速度を計算します (ω = Δθ / Δt)",
      description: "角度の変化と時間に基づいて角速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ω: "角速度 (角速度 rad/s)",
         Δθ: "角変位 (角度 rad)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "角加速度",
      equation_text: "α = Δω / Δt",
      summary: "角加速度を計算します (α = Δω / Δt)",
      description: "角速度の変化と時間に基づいて角加速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         α: "角加速度 (角加速度 rad/s²)",
         Δω: "角速度の変化 (角速度 rad/s)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "回転運動の運動学 (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "最終角速度を計算します (ω = ω0 + αt)",
      description: "回転運動の最初の運動学的等式を用いて最終角速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ω: "最終角速度 (角速度 rad/s)",
         ω0: "初期角速度 (角速度 rad/s)",
         α: "角加速度 (角加速度 rad/s²)",
         t: "時間 (時間 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "回転運動の運動学 (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "角位置を計算します (θ = θ0 + ω0t + 0.5αt^2)",
      description: "回転運動の2番目の運動学的等式を用いて最終角位置を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         θ: "最終角位置 (角度 rad)",
         θ0: "初期角位置 (角度 rad)",
         ω0: "初期角速度 (角速度 rad/s)",
         t: "時間 (時間 s)",
         α: "角加速度 (角加速度 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "回転運動の運動学 (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "角速度の二乗を計算します (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "回転運動の3番目の運動学的等式を用いて最終角速度の二乗を計算します。注：ωではなくω^2を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ω: "最終角速度 (角速度 rad/s)",
         ω0: "初期角速度 (角速度 rad/s)",
         α: "角加速度 (角加速度 rad/s²)",
         Δθ: "角変位 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "平均角速度",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "平均角速度を計算します (ω_avg = 0.5 * (ω + ω0))",
      description: "一定の角加速度を仮定して平均角速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ω_avg: "平均角速度 (角速度 rad/s)",
         ω: "最終角速度 (角速度 rad/s)",
         ω0: "初期角速度 (角速度 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "トルク (力のモーメント)",
      equation_text: "τ = rFsin(θ)",
      summary: "トルクを計算します (τ = rF sin(θ))",
      description: "半径、力、およびそれらの間の角度に基づいてトルクを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         τ: "トルク (トルク N·m)",
         r: "てこ腕 (長さ m)",
         F: "力 (力 N)",
         θ: "力とてこ腕の間の角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "ニュートンの第2法則 (回転)",
      equation_text: "τ_net = Iα",
      summary: "回転の第2法則を用いてトルクを計算します (τ = Iα)",
      description: "慣性モーメントと角加速度に基づいてトルクを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         τ_net: "正味のトルク (トルク N·m)",
         I: "慣性モーメント (慣性モーメント kg·m²)",
         α: "角加速度 (角加速度 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "慣性モーメント",
      equation_text: "I = mr² (点質量)",
      summary: "点質量の慣性モーメントを計算します (I = mr^2)",
      description: "軸に対する単一の点質量の慣性モーメントを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         I: "慣性モーメント (慣性モーメント kg·m²)",
         m: "質量 (質量 kg)",
         r: "軸からの距離 (長さ m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "回転の仕事",
      equation_text: "W = τΔθ (一定トルク)",
      summary: "回転の仕事を計算します (W = τΔθ)",
      description: "一定トルクが角変位に対して行う仕事を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         W: "回転の仕事 (エネルギー J)",
         τ: "トルク (トルク N·m)",
         Δθ: "角変位 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "回転の仕事率",
      equation_text: "P = τω",
      summary: "回転の仕事率を計算します (P = τω cos(θ))",
      description:
         "トルク、角速度、およびそれらの間の角度に基づいて瞬間的な回転の仕事率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "回転の仕事率 (仕事率 W)",
         τ: "トルク (トルク N·m)",
         ω: "角速度 (角速度 rad/s)",
         θ: "トルクと角速度の間の角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "回転運動エネルギー",
      equation_text: "KE_rot = ½Iω²",
      summary: "回転運動エネルギーを計算します (KE = 0.5Iω^2)",
      description: "回転している物体の運動エネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE_rot: "回転運動エネルギー (エネルギー J)",
         I: "慣性モーメント (慣性モーメント kg·m²)",
         ω: "角速度 (角速度 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "角運動量",
      equation_text: "L = Iω",
      summary: "角運動量を計算します (L = mrv sin(θ))",
      description: "ある点に対して移動する点質量の角運動量を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         L: "角運動量 (角運動量 kg·m²/s)",
         m: "質量 (質量 kg)",
         r: "軸/点からの距離 (長さ m)",
         v: "速度 (速さ m/s)",
         θ: "半径ベクトルと速度の間の角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "角力積",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "角力積を計算します (J = τΔt)",
      description: "トルクと時間間隔から角力積を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         J_angular: "角力積 (角力積 N·m·s)",
         τ_avg: "平均トルク (トルク N·m)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "ヤング率",
      equation_text: "E = σ / ε",
      summary: "ヤング率を計算します (E = (F * L0) / (A * ΔL))",
      description: "引張または圧縮応力下の材料のヤング率（弾性率）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         E: "ヤング率 (圧力 Pa)",
         F: "力 (力 N)",
         L0: "元の長さ (長さ m)",
         A: "断面積 (面積 m²)",
         ΔL: "長さの変化 (長さ m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "せん断弾性率",
      equation_text: "G = τ / γ",
      summary: "せん断弾性率を計算します (G = (F * y) / (A * Δx))",
      description: "せん断応力下の材料のせん断弾性率（剛性率）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         G: "せん断弾性率 (圧力 Pa)",
         F: "力 (力 N)",
         y: "力に垂直な距離 (長さ m)",
         A: "面積 (面積 m²)",
         Δx: "変位 (長さ m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "体積弾性率",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "体積弾性率を計算します (K = (F * V0) / (A * ΔV))",
      description: "一様な圧力（静水圧）下の材料の体積弾性率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         K: "体積弾性率 (圧力 Pa)",
         ΔP: "圧力の変化 (圧力 Pa)",
         ΔV: "体積の変化 (体積 m³)",
         V0: "元の体積 (体積 m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "フックの法則",
      equation_text: "F = kx",
      summary: "ばねの力を計算します (F = -k * Δx)",
      description:
         "フックの法則に従って、理想的なばねが発揮する復元力を計算します。注 - 変位に抵抗する力を示す負の値を返します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         F: "力 (力 N)",
         k: "ばね定数 (ばね定数 N/m)",
         x: "平衡位置からの変位 (長さ m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "固体熱膨張 (長さ)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "固体の線熱膨張を計算します (ΔL = αL0ΔT)",
      description: "温度変化による固体材料の長さの変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔL: "長さの変化 (長さ m)",
         α: "線膨張係数 (温度あたりの係数 K⁻¹)",
         L0: "元の長さ (長さ m)",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "固体熱膨張 (面積)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "固体の面積熱膨張を計算します (ΔA = 2αA0ΔT)",
      description:
         "線膨張係数を使用して、温度変化による固体材料の面積の変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔA: "面積の変化 (面積 m²)",
         α: "線膨張係数 (温度あたりの係数 K⁻¹)",
         A0: "元の面積 (面積 m²)",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "固体熱膨張 (体積)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "固体の体積熱膨張を計算します (ΔV = 3αV0ΔT)",
      description:
         "線膨張係数を使用して、温度変化による固体材料の体積の変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔV: "体積の変化 (体積 m³)",
         α: "線膨張係数 (温度あたりの係数 K⁻¹)",
         V0: "元の体積 (体積 m³)",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "液体熱膨張",
      equation_text: "ΔV = βV₀ΔT",
      summary: "液体熱膨張を計算します (ΔV = βV0ΔT)",
      description: "温度変化による液体の体積の変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔV: "体積の変化 (体積 m³)",
         β: "体積膨張係数 (温度あたりの係数 K⁻¹)",
         V0: "元の体積 (体積 m³)",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "顕熱",
      equation_text: "Q = mcΔT",
      summary: "顕熱を計算します (Q = mcΔT)",
      description: "物質の温度変化を引き起こす伝達された熱を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Q: "顕熱 (エネルギー J)",
         m: "質量 (質量 kg)",
         c: "比熱容量 (比熱容量 J/(kg·K))",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "潜熱",
      equation_text: "Q = mL",
      summary: "潜熱を計算します (Q = mL)",
      description: "物質の相変化中に伝達される熱を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Q: "潜熱 (エネルギー J)",
         m: "質量 (質量 kg)",
         L: "比潜熱 (比エネルギー J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "理想気体の法則",
      equation_text: "PV = nRT",
      summary: "理想気体の法則を検証します (PV = nRT)",
      description:
         "与えられたパラメータに対して理想気体の法則の等式が成り立つかチェックします。ブール値を返します。注：厳密等価演算子 (===) を使用しているため、浮動小数点精度に影響を受ける可能性があります。現実世界でのチェックには許容誤差を考慮してください。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "圧力 (圧力 Pa)",
         V: "体積 (体積 m³)",
         n: "モル数 (物質量 mol)",
         R: "理想気体定数 (定数 J/(mol·K))",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "分子運動エネルギー",
      equation_text: "KE_avg = (3/2)kT",
      summary: "平均分子運動エネルギーを計算します (KE = (3/2)kT)",
      description: "理想気体の分子あたりの平均並進運動エネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE_avg: "平均分子運動エネルギー (エネルギー J)",
         k: "ボルツマン定数 (定数 J/K)",
         T: "温度 (温度 K)",
         m: "単一分子の質量 (質量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "分子速度 (最確率)",
      equation_text: "v_p = √(2kT/m)",
      summary: "最確率分子速度を計算します (v_p = √(2kT/m))",
      description:
         "マクスウェル・ボルツマン分布に従って、理想気体の分子の最確率速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_p: "最確率分子速度 (速さ m/s)",
         k: "ボルツマン定数 (定数 J/K)",
         T: "温度 (温度 K)",
         m: "単一分子の質量 (質量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "分子速度 (平均)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "平均分子速度を計算します (v_avg = √(8kT/(πm)))",
      description:
         "マクスウェル・ボルツマン分布に従って、理想気体の分子の平均速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_avg: "平均分子速度 (速さ m/s)",
         k: "ボルツマン定数 (定数 J/K)",
         T: "温度 (温度 K)",
         π: "パイ (無次元の定数)",
         m: "単一分子の質量 (質量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "分子速度 (実効値 - RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "分子速度の実効値を計算します (v_rms = √(3kT/m))",
      description:
         "マクスウェル・ボルツマン分布に従って、理想気体の分子の二乗平均平方根速度を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v_rms: "二乗平均平方根分子速度 (速さ m/s)",
         k: "ボルツマン定数 (定数 J/K)",
         T: "温度 (温度 K)",
         m: "単一分子の質量 (質量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "内部エネルギーの変化",
      equation_text: "ΔU = Q - W",
      summary: "理想的な単原子分子ガスの内部エネルギーの変化を計算します (ΔU = (3/2)nRΔT)",
      description:
         "温度変化を経験する理想的な単原子分子ガスの内部エネルギーの変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         ΔU: "内部エネルギーの変化 (エネルギー J)",
         n: "モル数 (物質量 mol)",
         R: "理想気体定数 (定数 J/(mol·K))",
         ΔT: "温度の変化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "熱力学的仕事",
      equation_text: "W = PΔV (定圧)",
      summary: "定圧下で系が行う熱力学的仕事を計算します (W = -PΔV)",
      description:
         "定圧下で熱力学的プロセス中に系が行う、または系になされる仕事を計算します。注 - この等式は系が*行う*仕事を計算しており、膨張は正、圧縮は負です。関数は -P*deltaV を返します。これは等式 W = PΔV に従った系が*行う*仕事と一致しますが、慣例によっては系に*なされる*仕事を示す負の符号が追加されている場合があります。関数の出力を記述しています。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         W: "熱力学的仕事 (エネルギー J)",
         P: "圧力 (圧力 Pa)",
         ΔV: "体積の変化 (体積 m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "実際の効率",
      equation_text: "η = W_out / Q_in",
      summary: "実際の機関の効率を計算します (η_real = 1 - (Q_C / Q_H))",
      description: "吸収および放出された熱に基づいて、熱機関の熱効率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         η: "効率 (無次元)",
         Q_H: "高温リザーバーから吸収された熱 (エネルギー J)",
         Q_C: "低温リザーバーに放出された熱 (エネルギー J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "理想的な効率",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "理想的な効率 (カルノー効率) を計算します (η_ideal = 1 - (T_C / T_H))",
      description:
         "2つの温度間で動作する熱機関の最大理論効率（カルノー効率）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         η_ideal: "理想的な効率 (無次元)",
         T_hot: "高温リザーバーの温度 (温度 K)",
         T_cold: "低温リザーバーの温度 (温度 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "実際の成績係数 (COP)",
      equation_text: "COP_ref = Q_c / W (冷蔵庫)",
      summary: "実際の冷蔵庫の成績係数を計算します (COP_real = QC / (QH - QC))",
      description: "実際の冷蔵庫またはヒートポンプの成績係数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         COP_real: "成績係数 (無次元)",
         Q_C: "低温リザーバーからの熱 (エネルギー J)",
         Q_H: "高温リザーバーへの熱 (エネルギー J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "理想的な成績係数 (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "理想的な冷蔵庫の成績係数を計算します (COP_ideal = TC / (TH - TC))",
      description:
         "2つの温度間で動作する冷蔵庫またはヒートポンプの最大理論成績係数を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         COP_ideal: "理想的な成績係数 (無次元)",
         T_h: "高温リザーバーの温度 (温度 K)",
         T_c: "低温リザーバーの温度 (温度 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "周期波の速度",
      equation_text: "v = fλ",
      summary: "波の速さを計算します (v = fλ)",
      description: "周期波の速度を、その周波数と波長に基づいて計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         v: "波の速さ (速さ m/s)",
         f: "周波数 (周波数 Hz)",
         λ: "波長 (長さ m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "波の強度",
      equation_text: "I = P / A",
      summary: "強度を計算します (I = P/A)",
      description: "波の強度（単位面積あたりの仕事率）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         I: "強度 (強度 W/m²)",
         P: "仕事率 (仕事率 W)",
         A: "面積 (面積 m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "強度レベル (デシベル)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "強度レベルをデシベルで計算します (L = 10 log10(I/I0))",
      description: "基準強度に対する強度レベル（音の強さレベル）を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         β: "強度レベル (強度レベル dB)",
         I: "強度 (強度 W/m²)",
         I0: "基準強度 (強度 W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "圧力レベル (音圧レベル)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "音圧レベルをデシベルで計算します (L = 20 log10(ΔP/ΔP0))",
      description: "基準圧力変化に対する音圧レベルを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         L_p: "音圧レベル (圧力レベル dB)",
         P_rms: "実効圧力変動値 (圧力 Pa)",
         P_ref: "基準圧力 (圧力 Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "ドップラー効果 (音/非相対論的)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "ドップラー効果の速度係数を計算します ((c + v_o) / (c - v_s))",
      description:
         "ドップラー効果の等式 (f' = f * 係数) の速度係数部分を計算します。観測者が音源に向かって移動する場合、音源が観測者に向かって移動する場合の速度は正です。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         f_obs: "観測周波数 (周波数 Hz)",
         f_source: "音源周波数 (周波数 Hz)",
         v_wave: "波の速さ (速さ m/s)",
         v_observer: "媒質に対する観測者の速度 (速さ m/s)",
         v_source: "媒質に対する音源の速度 (速さ m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "マッハ角",
      equation_text: "sin(μ) = 1 / M",
      summary: "マッハ角を計算します (θ_M = arcsin(c/v))",
      description:
         "音速より速く移動する物体によって形成されるマッハ円錐の角度を計算します。角度はラジアンで返されます。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         μ: "マッハ角 (角度 rad)",
         M: "マッハ数 (無次元)",
         c: "音速 (速さ m/s)",
         v: "物体の速さ (速さ m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "仕事",
      equation_text: "W = Fdcos(θ)",
      summary: "行われた仕事を計算します (W = F * Δs * cos(θ))",
      description: "力、変位、およびそれらの間の角度に基づいて行われた仕事を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         W: "行われた仕事 (エネルギー J)",
         F: "力の大きさ (力 N)",
         d: "変位の大きさ (長さ m)",
         θ: "力と変位の間の角度 (角度 rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "運動エネルギー",
      equation_text: "KE = ½mv²",
      summary: "運動エネルギーを計算します (KE = 0.5 * m * v^2)",
      description: "質量と速度に基づいて運動エネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE: "運動エネルギー (エネルギー J)",
         m: "質量 (質量 kg)",
         v: "速度 (速さ m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "運動エネルギー (運動量から)",
      equation_text: "KE = p² / (2m)",
      summary: "運動量から運動エネルギーを計算します (KE = p^2 / (2m))",
      description: "運動量と質量に基づいて運動エネルギーを計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         KE: "運動エネルギー (エネルギー J)",
         p: "運動量 (運動量 kg·m/s)",
         m: "質量 (質量 kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "重力ポテンシャルエネルギー",
      equation_text: "U_g = mgh (表面近く)",
      summary: "重力ポテンシャルエネルギーを計算します (PE = mgh)",
      description: "重力ポテンシャルエネルギーの変化を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         U_g: "重力ポテンシャルエネルギー (エネルギー J)",
         m: "質量 (質量 kg)",
         g: "重力加速度 (加速度 m/s²)",
         h: "高さ (長さ m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "効率",
      equation_text: "効率 = 出力 / 入力",
      summary: "効率を計算します (η = W_out / W_in)",
      description: "プロセスまたは機械の効率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         Efficiency: "効率 (無次元)",
         Output: "有効な出力エネルギーまたは仕事率 (エネルギー J または 仕事率 W)",
         Input: "総入力エネルギーまたは仕事率 (エネルギー J または 仕事率 W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "仕事率",
      equation_text: "P = W / t",
      summary: "仕事率を計算します (P = ΔW / Δt)",
      description: "仕事の変化と時間に基づいて平均仕事率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "仕事率 (仕事率 W)",
         ΔW: "仕事の変化 (エネルギー J)",
         Δt: "時間間隔 (時間 s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "仕事率 (P = Fv)",
      equation_text: "P = Fv",
      summary: "力と速度から仕事率を計算します (P = Fv cos(θ))",
      description: "力、速度、およびそれらの間の角度に基づいて瞬間的な仕事率を計算します。",
      language_code: "ja",
      subject: "Physics",
      variables: {
         P: "仕事率 (仕事率 W)",
         F: "力の大きさ (力 N)",
         v: "速度の大きさ (速さ m/s)",
         θ: "力と速度の間の角度 (角度 rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = ja;