const ko = [
   {
      equation_id: "centripetal-acceleration",
      name: "구심 가속도",
      equation_text: "a_c = v² / r",
      summary: "구심 가속도를 계산합니다 (a_c = v^2 / r)",
      description:
         "선형 속도와 반지름을 사용하여 원형 경로의 중심으로 향하는 가속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         a_c: "구심 가속도 (가속도 m/s²)",
         v: "선형 속도 (속도 m/s)",
         r: "원형 경로의 반지름 (길이 m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "구심 가속도 (각속도)",
      equation_text: "a_c = ω²r",
      summary: "각속도를 사용하여 구심 가속도를 계산합니다 (a_c = -ω^2 * r)",
      description:
         "각속도와 반지름을 사용하여 구심 가속도 벡터 성분을 계산합니다. 음수 부호는 중심 방향을 나타냅니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         a_c: "구심 가속도 (가속도 m/s²)",
         ω: "각속도 (각속도 rad/s)",
         r: "원형 경로의 반지름 (길이 m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "쿨롱 법칙 (힘)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "쿨롱 법칙을 사용하여 전기력을 계산합니다 (F = k * q1*q2 / r^2)",
      description:
         "두 점 전하 사이의 전기력을 계산합니다. 부호 있는 힘 (척력은 양수, 인력은 음수)을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F: "전기력 (힘 N)",
         k: "쿨롱 상수 (상수 N·m²/C²)",
         q1: "전하 1 (전하 C)",
         q2: "전하 2 (전하 C)",
         r: "전하 간 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "전기장",
      equation_text: "E = kq / r² (점 전하)",
      summary: "힘에서 전기장을 계산합니다 (E = F_E/q)",
      description: "시험 전하에 가해지는 힘을 기준으로 전기장 강도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "전기장 크기 (전기장 N/C)",
         k: "쿨롱 상수 (상수 N·m²/C²)",
         q: "원천 전하 (전하 C)",
         r: "원천 전하로부터의 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "전위",
      equation_text: "V = kq / r (점 전하)",
      summary: "퍼텐셜 에너지 변화에서 전위를 계산합니다 (V = ΔU_E/q)",
      description:
         "단위 전하당 전기적 퍼텐셜 에너지 변화를 기준으로 전위(전압)를 계산합니다. 참고 - 함수 이름 `calculateElectricPotential`은 올바르지만, 매개변수 `deltaUE`는 변화를 의미하며, 반면 방정식은 일반적으로 V=U_E/q 또는 ΔV=ΔU_E/q입니다. 방정식 ΔV = ΔU_E/q를 기반으로 설명하고 ΔV를 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         V: "전위 (전압 V)",
         k: "쿨롱 상수 (상수 N·m²/C²)",
         q: "원천 전하 (전하 C)",
         r: "원천 전하로부터의 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "전기장과 전위의 관계",
      equation_text: "E_x = -dV/dx",
      summary: "전위차에서 전기장을 계산합니다 (E = ΔV/d)",
      description:
         '거리에 따른 전위차를 기준으로 균일한 전기장의 크기를 계산합니다. 참고 - 함수 이름 "Field and Potential"은 오해의 소지가 있습니다. 이는 전기장 E를 계산합니다.',
      language_code: "ko",
      subject: "Physics",
      variables: {
         E_x: "전기장 성분 (전기장 V/m)",
         V: "전위 (전압 V)",
         x: "위치 (길이 m)",
         ΔV: "전위차 (전압 V)",
         d: "거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "전기 용량",
      equation_text: "C = Q / V",
      summary: "전기 용량을 계산합니다 (C = Q/V)",
      description: "저장된 전하량과 커패시터 양단의 전압을 기준으로 전기 용량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C: "전기 용량 (전기 용량 F)",
         Q: "전하 (전하 C)",
         V: "전압 (전압 V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "평행판 커패시터 전기 용량",
      equation_text: "C = ε₀A / d",
      summary: "평행판 커패시터 전기 용량을 계산합니다 (C = (kε₀A)/d)",
      description:
         "유전체가 있는 평행판 커패시터의 전기 용량을 계산합니다. 참고 - 함수는 k * ε₀를 단일 입력(`kEpsilon`)으로 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C: "전기 용량 (전기 용량 F)",
         ε0: "자유 공간의 유전율 (상수 F/m)",
         k: "유전 상수 (무차원)",
         A: "극판 면적 (면적 m²)",
         d: "극판 간 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "원통형 커패시터 전기 용량",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "원통형 커패시터 전기 용량을 계산합니다 (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "유전체가 있는 원통형 커패시터의 전기 용량을 계산합니다. 참고 - 함수는 k * ε₀를 단일 입력(`kEpsilon`)으로 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C: "전기 용량 (전기 용량 F)",
         π: "파이 (무차원 상수)",
         ε0: "자유 공간의 유전율 (상수 F/m)",
         k: "유전 상수 (무차원)",
         L: "원통 길이 (길이 m)",
         b: "외부 반경 (길이 m)",
         a: "내부 반경 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "구형 커패시터 전기 용량",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "구형 커패시터 전기 용량을 계산합니다 (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "유전체가 있는 구형 커패시터의 전기 용량을 계산합니다. 참고 - 함수는 k * ε₀를 단일 입력(`kEpsilon`)으로 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C: "전기 용량 (전기 용량 F)",
         π: "파이 (무차원 상수)",
         ε0: "자유 공간의 유전율 (상수 F/m)",
         k: "유전 상수 (무차원)",
         a: "내부 반경 (길이 m)",
         b: "외부 반경 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "커패시터 퍼텐셜 에너지",
      equation_text: "U_C = ½CV²",
      summary: "커패시터 퍼텐셜 에너지 방정식을 검증합니다 (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "주어진 Q, V, C에 대해 커패시터에 저장된 퍼텐셜 에너지에 대한 세 가지 일반적인 방정식이 등가인지 확인합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         U_C: "커패시터 퍼텐셜 에너지 (에너지 J)",
         Q: "전하 (전하 C)",
         V: "전압 (전압 V)",
         C: "전기 용량 (전기 용량 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "전류",
      equation_text: "I = ΔQ / Δt",
      summary: "전류를 계산합니다 (I = ΔQ/Δt)",
      description: "단위 시간당 한 지점을 통과하는 전하량에 따라 전류를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         I: "전류 (전류 A)",
         ΔQ: "전하 변화 (전하 C)",
         Δt: "시간 변화 (시간 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "전하 밀도",
      equation_text: "ρ = Q / V (부피)",
      summary: "전하 밀도를 계산합니다 (ρ = Q/V)",
      description: "평균 전하 밀도(단위 부피당 전하)를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ρ: "부피 전하 밀도 (전하 밀도 C/m³)",
         Q: "총 전하 (전하 C)",
         V: "부피 (부피 m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "전류 밀도",
      equation_text: "J = I / A",
      summary: "전류 밀도를 계산합니다 (J = I/A)",
      description: "전기 전류 밀도(단위 단면적당 전류)를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         J: "전류 밀도 (전류 밀도 A/m²)",
         I: "전류 (전류 A)",
         A: "면적 (면적 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "옴의 법칙",
      equation_text: "V = IR",
      summary: "옴의 법칙을 사용하여 저항을 계산합니다 (R = V/I)",
      description:
         "전압과 전류를 기준으로 저항을 계산합니다. 참고 - 함수는 V와 I로부터 저항 R을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         V: "전압 (전압 V)",
         I: "전류 (전류 A)",
         R: "저항 (저항 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "저항률 및 전도율",
      equation_text: "ρ = RA / L",
      summary: "저항률에서 전도율을 계산합니다 (σ = 1/ρ)",
      description: "저항률(ρ)로부터 전도율(σ)을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         σ: "전도율 (전도율 S/m)",
         ρ: "저항률 (저항률 Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "전기 저항",
      equation_text: "R = ρL / A",
      summary: "전기 저항을 계산합니다 (R = ρ(l/A))",
      description:
         "도체의 저항률, 길이, 단면적을 기준으로 전기 저항을 계산합니다. 참고 - 저항률에는 `rhoValue`를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         R: "저항 (저항 Ω)",
         ρ: "저항률 (저항률 Ω·m)",
         L: "길이 (길이 m)",
         A: "단면적 (면적 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "전력",
      equation_text: "P = IV",
      summary: "전력 방정식을 검증합니다 (P = VI = I^2R = V^2/R)",
      description:
         "주어진 V, I, R에 대해 전력에 대한 세 가지 일반적인 방정식이 등가인지 확인합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "전력 (일률 W)",
         V: "전압 (전압 V)",
         I: "전류 (전류 A)",
         R: "저항 (저항 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "직렬 저항",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "직렬 연결된 저항의 총 저항을 계산합니다 (R_total = R1 + R2 + ...)",
      description: "여러 개의 직렬 연결된 저항에 대한 총 등가 저항을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         R_total: "총 저항 (저항 Ω)",
         R: "개별 저항 (저항 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "병렬 저항",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "병렬 연결된 저항의 총 저항을 계산합니다 (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "여러 개의 병렬 연결된 저항에 대한 총 등가 저항을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         R_total: "총 저항 (저항 Ω)",
         R: "개별 저항 (저항 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "직렬 커패시터",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "직렬 연결된 커패시터의 총 용량을 계산합니다 (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "여러 개의 직렬 연결된 커패시터에 대한 총 등가 용량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C_total: "총 용량 (전기 용량 F)",
         C: "개별 용량 (전기 용량 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "병렬 커패시터",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "병렬 연결된 커패시터의 총 용량을 계산합니다 (C_total = C1 + C2 + ...)",
      description: "여러 개의 병렬 연결된 커패시터에 대한 총 등가 용량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         C_total: "총 용량 (전기 용량 F)",
         C: "개별 용량 (전기 용량 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "전하에 작용하는 자기력",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "대전 입자에 작용하는 자기력을 계산합니다 (F = qvB sin(θ))",
      description:
         "움직이는 대전 입자에 작용하는 자기력의 크기를 계산합니다. 각도는 라디안이어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F_B: "자기력 크기 (힘 N)",
         q: "전하 크기 (전하 C)",
         v: "속도 크기 (속도 m/s)",
         B: "자기장 크기 (자기장 T)",
         θ: "속도와 자기장 사이의 각도 (각도 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "전류에 작용하는 자기력",
      equation_text: "F_B = ILBsin(θ)",
      summary: "전류가 흐르는 도선에 작용하는 자기력을 계산합니다 (F = I l B sin(θ))",
      description:
         "자기장 내에서 전류가 흐르는 직선 도선에 작용하는 자기력의 크기를 계산합니다. 각도는 라디안이어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F_B: "자기력 크기 (힘 N)",
         I: "전류 (전류 A)",
         L: "도선 길이 (길이 m)",
         B: "자기장 크기 (자기장 T)",
         θ: "전류와 자기장 사이의 각도 (각도 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "비오-사바르 법칙",
      equation_text: "B = μ₀I / (2πr) (무한장 직선 전류)",
      summary: "전류 요소에서 자기장을 계산합니다 (dB = (μ₀I ds) / (4πr^2))",
      description:
         "반지름 벡터에 수직인 미소 전류 요소로부터 자기장 기여도의 크기를 계산합니다. 참고 - 이 함수는 `(μ₀ * I * ds) / (4 * π * r^2)`를 구현하며, 미분 형식에 자주 나타나는 sin(θ) 항을 생략합니다. 이는 사실상 θ=90도를 가정하거나 해당 평면에서 반지름 벡터에 수직인 구성 요소만 계산하는 것입니다. 구현된 방정식을 문서화합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         dB: "자기장 기여도 크기 (자기장 T)",
         μ0: "자유 공간 투자율 (상수 T·m/A)",
         I: "전류 (전류 A)",
         ds: "전류 요소의 미소 길이 (길이 m)",
         r: "전류 요소로부터의 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "솔레노이드 자기장",
      equation_text: "B = μ₀nI (내부, 이상)",
      summary: "긴 솔레노이드 내부 자기장을 계산합니다 (B = μ₀nI)",
      description: "긴 이상 솔레노이드 내부 자기장의 크기를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         B: "솔레노이드 내부 자기장 강도 (자기장 T)",
         μ0: "자유 공간 투자율 (상수 T·m/A)",
         n: "단위 길이당 감은 수 (단위 길이당 수 m⁻¹)",
         I: "전류 (전류 A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "직선 도선 자기장",
      equation_text: "B = μ₀I / (2πr) (무한장 도선)",
      summary: "무한 직선 도선에서 자기장을 계산합니다 (B = (μ₀I)/(2πr))",
      description:
         "전류가 흐르는 길고 곧은 도선으로부터 일정 거리 떨어진 지점의 자기장 크기를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         B: "직선 도선 자기장 강도 (자기장 T)",
         μ0: "자유 공간 투자율 (상수 T·m/A)",
         I: "전류 (전류 A)",
         π: "파이 (무차원 상수)",
         r: "도선으로부터의 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "평행 도선 간 힘",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "평행 도선 간 단위 길이당 힘을 계산합니다 (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "전류가 흐르는 두 개의 길고 평행한 도체 사이의 단위 길이당 힘의 크기를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         "F/L": "단위 길이당 힘 (단위 길이당 힘 N/m)",
         μ0: "자유 공간 투자율 (상수 T·m/A)",
         I1: "도선 1의 전류 (전류 A)",
         I2: "도선 2의 전류 (전류 A)",
         π: "파이 (무차원 상수)",
         d: "도선 간 거리 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "전기 선속",
      equation_text: "Φ_E = EAcos(θ) (E 균일)",
      summary: "전기 선속을 계산합니다 (Φ_E = E * A * cos(θ))",
      description:
         "균일한 전기장 내의 평면을 통과하는 전기 선속을 계산합니다. 각도는 전기장 벡터와 면적 벡터 사이의 각도이며, 라디안 단위여야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Φ_E: "전기 선속 (전기 선속 N·m²/C)",
         E: "전기장 크기 (전기장 N/C)",
         A: "면적 (면적 m²)",
         θ: "E와 면적 벡터 사이의 각도 (각도 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "자기 선속",
      equation_text: "Φ_B = BAcos(θ) (B 균일)",
      summary: "자기 선속을 계산합니다 (Φ_B = B * A * cos(θ))",
      description:
         "균일한 자기장 내의 평면을 통과하는 자기 선속을 계산합니다. 각도는 자기장 벡터와 면적 벡터 사이의 각도이며, 라디안 단위여야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Φ_B: "자기 선속 (자기 선속 Wb)",
         B: "자기장 크기 (자기장 T)",
         A: "면적 (면적 m²)",
         θ: "B와 면적 벡터 사이의 각도 (각도 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "운동 기전력",
      equation_text: "ε = vBL (직선 도체)",
      summary: "운동 기전력을 계산합니다 (emf = Blv)",
      description:
         "자기장에 수직으로 움직이는 도체에 유도되는 기전력의 크기를 계산합니다. 참고 - 함수는 Blv의 크기를 계산하며, 방향에 사용되는 음수 부호(렌츠의 법칙)는 생략합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ε: "운동 기전력 크기 (전압 V)",
         v: "도체 속도 (속도 m/s)",
         B: "자기장 크기 (자기장 T)",
         L: "도체 길이 (길이 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "유도 기전력 (패러데이 법칙)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "변화하는 자속에서 유도 기전력을 계산합니다 (emf = -ΔΦ_B / Δt)",
      description: "패러데이 전자기 유도 법칙에 따라 변화하는 자기 선속에 의해 유도되는 기전력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ε: "유도 기전력 (전압 V)",
         ΔΦ_B: "자기 선속의 변화 (자기 선속 Wb)",
         Δt: "시간 변화 (시간 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "인덕턴스 유도 기전력",
      equation_text: "ε_L = -L dI / dt",
      summary: "인덕터 전류 변화에서 유도 기전력을 계산합니다 (emf = -L * ΔI / Δt)",
      description:
         "변화하는 전류로 인해 인덕터에 자기 유도되는 기전력을 계산합니다. 참고 - 함수 이름은 `calculateInductance`이지만, 이 방정식을 사용하여 기전력을 반환합니다. 반환값을 문서화합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ε_L: "인덕터의 유도 기전력 (전압 V)",
         L: "인덕턴스 (인덕턴스 H)",
         ΔI: "전류 변화 (전류 A)",
         Δt: "시간 변화 (시간 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "용량 리액턴스",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "용량 리액턴스를 계산합니다 (X_C = 1/(2πfC))",
      description: "커패시터가 교류에 대해 갖는 반대 성분을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         X_C: "용량 리액턴스 (리액턴스 Ω)",
         π: "파이 (무차원 상수)",
         f: "주파수 (주파수 Hz)",
         C: "전기 용량 (전기 용량 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "유도 리액턴스",
      equation_text: "X_L = 2πfL",
      summary: "유도 리액턴스를 계산합니다 (X_L = 2πfL))",
      description: "인덕터가 교류에 대해 갖는 반대 성분을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         X_L: "유도 리액턴스 (리액턴스 Ω)",
         π: "파이 (무차원 상수)",
         f: "주파수 (주파수 Hz)",
         L: "인덕턴스 (인덕턴스 H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "임피던스",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "임피던스를 계산합니다 (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "저항, 유도 리액턴스, 용량 리액턴스를 포함하는 AC 회로에서 전류 흐름에 대한 전체 반대 성분을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Z: "임피던스 (임피던스 Ω)",
         R: "저항 (저항 Ω)",
         X_L: "유도 리액턴스 (리액턴스 Ω)",
         X_C: "용량 리액턴스 (리액턴스 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "밀도",
      equation_text: "ρ = m / V",
      summary: "밀도를 계산합니다 (ρ = m/V)",
      description: "질량과 부피를 기준으로 밀도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ρ: "밀도 (밀도 kg/m³)",
         m: "질량 (질량 kg)",
         V: "부피 (부피 m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "압력",
      equation_text: "P = F / A",
      summary: "압력을 계산합니다 (P = F/A)",
      description: "면적에 가해지는 힘을 기준으로 압력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "압력 (압력 Pa)",
         F: "힘 (힘 N)",
         A: "면적 (면적 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "유체 내 압력",
      equation_text: "P = P₀ + ρgh",
      summary: "유체 내 압력을 계산합니다 (P = P0 + ρgh)",
      description: "유체 내 특정 깊이에서의 절대 압력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "절대 압력 (압력 Pa)",
         P0: "대기압 또는 표면 압력 (압력 Pa)",
         ρ: "유체 밀도 (밀도 kg/m³)",
         g: "중력 가속도 (가속도 m/s²)",
         h: "깊이 (길이 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "부력",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "부력을 계산합니다 (F_b = ρgV_displaced)",
      description:
         "유체가 잠수 또는 부분적으로 잠수된 물체에 가하는 부력(아르키메데스의 원리)을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F_B: "부력 (힘 N)",
         ρ_fluid: "유체 밀도 (밀도 kg/m³)",
         V_submerged: "잠수 부피 (부피 m³)",
         g: "중력 가속도 (가속도 m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "질량 유량",
      equation_text: "ṁ = ρAv",
      summary: "질량 유량을 계산합니다 (ṁ = Δm/Δt)",
      description: "단위 시간당 한 지점을 통과하는 질량의 비율을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ṁ: "질량 유량 (질량 유량 kg/s)",
         ρ: "유체 밀도 (밀도 kg/m³)",
         A: "면적 (면적 m²)",
         v: "유체 속도 (속도 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "부피 유량",
      equation_text: "Q = Av",
      summary: "부피 유량을 계산합니다 (Q = ΔV/Δt)",
      description: "단위 시간당 한 지점을 통과하는 부피의 비율을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Q: "부피 유량 (부피 유량 m³/s)",
         A: "면적 (면적 m²)",
         v: "유체 속도 (속도 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "베르누이 방정식",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "베르누이 방정식을 확인합니다 (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "주어진 두 지점에서의 유체 속성 및 조건에 대해 베르누이 방정식이 성립하는지 검증합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "압력 (압력 Pa)",
         ρ: "유체 밀도 (밀도 kg/m³)",
         v: "유체 속도 (속도 m/s)",
         g: "중력 가속도 (가속도 m/s²)",
         y: "높이 (길이 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "동점성 계수",
      equation_text: "τ = μ * (dv/dy)",
      summary: "동점성 계수를 계산합니다 (η = F * Δy / (A * Δvx))",
      description:
         "힘, 속도 기울기 및 면적을 기준으로 동점성 계수를 계산합니다. 이 방정식은 전단 응력/변형률 속도에서 파생되었습니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         μ: "동점성 계수 (동점성 계수 Pa·s)",
         F: "힘 (힘 N)",
         Δy: "흐름에 수직인 거리 (길이 m)",
         A: "면적 (면적 m²)",
         Δvx: "속도 변화 (속도 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "동점도",
      equation_text: "ν = μ / ρ",
      summary: "동점도를 계산합니다 (ν = η / ρ)",
      description: "동점성 계수와 밀도에서 동점도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ν: "동점도 (동점도 m²/s)",
         μ: "동점성 계수 (동점성 계수 Pa·s)",
         ρ: "유체 밀도 (밀도 kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "항력",
      equation_text: "F_D = ½ρv²CdA",
      summary: "항력을 계산합니다 (F_d = 0.5 * ρ * C_A * v^2)",
      description: "유체를 통과하는 물체에 대한 항력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F_D: "항력 (힘 N)",
         ρ: "유체 밀도 (밀도 kg/m³)",
         v: "속도 (속도 m/s)",
         Cd: "항력 계수 (무차원)",
         A: "기준 면적 (면적 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "마하수",
      equation_text: "M = v / c_sound",
      summary: "마하수를 계산합니다 (M = v/c)",
      description: "마하수, 즉 물체의 속도와 매질 내 음속의 비를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         M: "마하수 (무차원)",
         v: "물체 속도 (속도 m/s)",
         c_sound: "매질 내 음속 (속도 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "레이놀즈 수",
      equation_text: "Re = ρvd / μ",
      summary: "레이놀즈 수를 계산합니다 (Re = (ρ * v * D) / η)",
      description:
         "레이놀즈 수, 즉 다양한 유체 흐름 상황에서 흐름 패턴을 예측하는 데 사용되는 무차원량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Re: "레이놀즈 수 (무차원)",
         ρ: "유체 밀도 (밀도 kg/m³)",
         v: "속도 (속도 m/s)",
         d: "특성 길이 (길이 m)",
         μ: "동점성 계수 (동점성 계수 Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "프루드 수",
      equation_text: "Fr = v / √(gL)",
      summary: "프루드 수를 계산합니다 (Fr = v / √(g * l))",
      description:
         "프루드 수, 즉 중력이 유체 운동에 미치는 영향을 나타내는 데 사용되는 무차원량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Fr: "프루드 수 (무차원)",
         v: "속도 (속도 m/s)",
         g: "중력 가속도 (가속도 m/s²)",
         L: "특성 길이 (길이 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "표면 장력",
      equation_text: "γ = F / L",
      summary: "표면 장력을 계산합니다 (γ = F / l)",
      description: "힘과 길이를 기준으로 액체의 표면 장력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         γ: "표면 장력 (표면 장력 N/m)",
         F: "힘 (힘 N)",
         L: "길이 (길이 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "만유인력 (힘)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "중력을 계산합니다 (F = -Gm1m2/r^2)",
      description:
         "두 점 질량 사이의 인력인 중력을 계산합니다. 참고 - 인력을 나타내는 음수 값을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F: "중력 (힘 N)",
         G: "중력 상수 (상수 N·m²/kg²)",
         m1: "질량 1 (질량 kg)",
         m2: "질량 2 (질량 kg)",
         r: "질량 간 거리 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "중력장",
      equation_text: "g = GM / r² (크기)",
      summary: "중력장을 계산합니다 (g = -Gm/r^2)",
      description:
         "점 질량으로부터 거리에서의 중력장 강도를 계산합니다. 참고 - 질량 방향을 나타내는 음수 값을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         g: "중력장 강도 크기 (중력장 N/kg)",
         G: "중력 상수 (상수 N·m²/kg²)",
         M: "원천 질량 (질량 kg)",
         r: "원천 질량으로부터의 거리 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "중력 퍼텐셜 에너지",
      equation_text: "U_g = -G m₁m₂ / r (일반)",
      summary: "두 질량 사이의 중력 퍼텐셜 에너지를 계산합니다 (PE = -Gm1m2/r)",
      description: "두 점 질량 시스템의 중력 퍼텐셜 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         U_g: "중력 퍼텐셜 에너지 (에너지 J)",
         G: "중력 상수 (상수 N·m²/kg²)",
         m1: "질량 1 (질량 kg)",
         m2: "질량 2 (질량 kg)",
         r: "질량 간 거리 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "중력 퍼텐셜",
      equation_text: "V_g = -GM / r",
      summary: "중력 퍼텐셜을 계산합니다 (V_g = -Gm/r)",
      description: "점 질량으로부터 거리에서의 중력 퍼텐셜을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         V_g: "중력 퍼텐셜 (중력 퍼텐셜 J/kg)",
         G: "중력 상수 (상수 N·m²/kg²)",
         M: "원천 질량 (질량 kg)",
         r: "원천 질량으로부터의 거리 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "궤도 속도",
      equation_text: "v_orbit = √(GM / r) (원궤도)",
      summary: "궤도 속도를 계산합니다 (v = sqrt(Gm/r))",
      description: "더 큰 질량 주위의 원형 궤도에 있는 물체의 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_orbit: "궤도 속도 (속도 m/s)",
         G: "중력 상수 (상수 N·m²/kg²)",
         M: "중심체 질량 (질량 kg)",
         r: "궤도 반지름 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "탈출 속도",
      equation_text: "v_escape = √(2GM / r)",
      summary: "탈출 속도를 계산합니다 (v = sqrt(2Gm/r))",
      description:
         "주어진 거리에서 질량의 중력으로부터 탈출하는 데 필요한 최소 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_escape: "탈출 속도 (속도 m/s)",
         G: "중력 상수 (상수 N·m²/kg²)",
         M: "중심체 질량 (질량 kg)",
         r: "중심으로부터의 거리 (길이 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "열전도",
      equation_text: "Q/t = kAΔT/d",
      summary: "열전도율을 계산합니다 (Q/t = (kAΔT) / L)",
      description:
         "재료를 통한 전도에 의한 열 전달 속도를 계산합니다. 참고 - 함수는 Q를 계산하며, 시간 간격은 방정식이 일반적으로 속도에 사용됨을 암시한다고 가정합니다. 문서에는 Q로 명시되어 있지만, 방정식은 일반적으로 Q/t에 사용됩니다. 이 차이를 명확히 합니다. 함수는 속도 방정식의 우변 결과를 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         "Q/t": "열 전달 속도 (일률 W)",
         k: "열전도율 (열전도율 W/(m·K))",
         A: "면적 (면적 m²)",
         ΔT: "온도차 (온도차 K)",
         d: "두께 (길이 m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "스테판-볼츠만 법칙",
      equation_text: "P = εσAT⁴",
      summary: "열 복사 전력을 계산합니다 (P = εσA(T^4 - T0^4))",
      description: "주변 환경을 고려하여 물체가 복사하는 순 에너지율을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "순 복사 전력 (일률 W)",
         ε: "방사율 (무차원)",
         σ: "스테판-볼츠만 상수 (상수 W/(m²·K⁴))",
         A: "표면적 (면적 m²)",
         T: "물체 온도 (온도 K)",
         T0: "주변 온도 (온도 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "빈의 변위 법칙 (최대 파장)",
      equation_text: "λ_max = b/T",
      summary: "빈의 법칙을 사용하여 최대 파장을 계산합니다 (λ_max = b/T)",
      description: "흑체 방출 스펙트럼이 최대가 되는 파장을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         λ_max: "피크 방출 파장 (길이 m)",
         b: "빈 변위 상수 (상수 m·K)",
         T: "온도 (온도 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "빈의 변위 법칙 (최대 주파수)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "빈의 법칙을 사용하여 최대 주파수를 계산합니다 (f_max = b' * T)",
      description:
         "흑체 방출 스펙트럼이 최대가 되는 주파수를 계산합니다. 참고 - 이 버전은 수정된 빈 상수 b'를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f_max: "피크 방출 주파수 (주파수 Hz)",
         "b'": "수정된 빈 상수 (상수 Hz/K)",
         T: "온도 (온도 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "공식 정보 (특정)",
      equation_text: "해당 없음 (정보를 검색하며 계산하지 않음)",
      summary: "ID와 언어로 공식 정보를 가져옵니다",
      description:
         "고유 ID와 원하는 언어를 기반으로 특정 방정식의 세부 정보를 검색합니다. 참고 - 언어는 'language_code' 경로 매개변수에서 추출됩니다. 코드 스니펫에 표시된 내부 논리는 'lang' 쿼리 매개변수도 찾지만, 이 Swagger 정의는 주요 경로 매개변수를 문서화합니다.",
      language_code: "ko",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "API의 모든 공식 엔드포인트를 가져옵니다.",
      description: "API의 모든 엔드포인트에 대한 요약 정보를 검색합니다.",
      language_code: "ko",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "속도",
      equation_text: "v = Δx / Δt",
      summary: "속도를 계산합니다",
      description: "변위와 시간을 기준으로 속도를 계산합니다 (v = Δs / Δt).",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v: "속도 (속도 m/s)",
         Δx: "변위 (길이 m)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "가속도",
      equation_text: "a = Δv / Δt",
      summary: "가속도를 계산합니다",
      description: "속도 변화량과 시간을 기준으로 가속도를 계산합니다 (a = Δv / Δt).",
      language_code: "ko",
      subject: "Physics",
      variables: {
         a: "가속도 (가속도 m/s²)",
         Δv: "속도 변화량 (속도 m/s)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "운동학 방정식 (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "최종 속도를 계산합니다 (v = v0 + at)",
      description: "첫 번째 운동학 방정식을 사용하여 최종 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v: "최종 속도 (속도 m/s)",
         v0: "초기 속도 (속도 m/s)",
         a: "가속도 (가속도 m/s²)",
         t: "시간 (시간 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "운동학 방정식 (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "최종 위치를 계산합니다 (s = s0 + v0t + 0.5at^2)",
      description: "두 번째 운동 방정식을 사용하여 최종 위치를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         s: "최종 위치 (길이 m)",
         s0: "초기 위치 (길이 m)",
         v0: "초기 속도 (속도 m/s)",
         t: "시간 (시간 s)",
         a: "가속도 (가속도 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "운동학 방정식 (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "최종 속도의 제곱을 계산합니다 (v^2 = v0^2 + 2a(s - s0))",
      description: "세 번째 운동 방정식을 사용하여 최종 속도의 제곱을 계산합니다. 참고 - v 대신 v^2을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v: "최종 속도 (속도 m/s)",
         v0: "초기 속도 (속도 m/s)",
         a: "가속도 (가속도 m/s²)",
         Δs: "변위 (길이 m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "평균 속도",
      equation_text: "v_avg = Δx / Δt",
      summary: "평균 속도를 계산합니다 (v_avg = 0.5 * (v + v0))",
      description: "일정한 가속도를 가정하여 평균 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_avg: "평균 속도 (속도 m/s)",
         v: "최종 속도 (속도 m/s)",
         v0: "초기 속도 (속도 m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "힘 (뉴턴 제2법칙)",
      equation_text: "F_net = ma",
      summary: "힘을 계산합니다 (F = ma)",
      description: "뉴턴 제2법칙을 사용하여 힘을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F_net: "합력 (힘 N)",
         m: "질량 (질량 kg)",
         a: "가속도 (가속도 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "무게",
      equation_text: "W = mg",
      summary: "무게를 계산합니다 (W = mg)",
      description: "물체에 작용하는 중력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         W: "무게 (힘 N)",
         m: "질량 (질량 kg)",
         g: "중력 가속도 (가속도 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "최대 정지 마찰력",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "최대 정지 마찰력을 계산합니다 (F_s = μ_s * N)",
      description: "가능한 최대 정지 마찰력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f_s_max: "최대 정지 마찰력 (힘 N)",
         μ_s: "정지 마찰 계수 (무차원)",
         F_N: "수직 항력 (힘 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "운동 마찰",
      equation_text: "f_k = μ_k * F_N",
      summary: "운동 마찰력을 계산합니다 (F_k = μ_k * N)",
      description: "움직이는 물체에 작용하는 운동 마찰력을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f_k: "운동 마찰력 (힘 N)",
         μ_k: "운동 마찰 계수 (무차원)",
         F_N: "수직 항력 (힘 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "운동량",
      equation_text: "p = mv",
      summary: "운동량을 계산합니다 (p = mv)",
      description: "물체의 선형 운동량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         p: "운동량 (운동량 kg·m/s)",
         m: "질량 (질량 kg)",
         v: "속도 (속도 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "충격량",
      equation_text: "J = F_avg * Δt",
      summary: "충격량을 계산합니다 (J = F * Δt)",
      description: "힘과 시간 간격에서 충격량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         J: "충격량 (충격량 N·s)",
         F_avg: "평균 힘 (힘 N)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "충격량-운동량 정리",
      equation_text: "J = Δp",
      summary: "충격량-운동량 정리를 검증합니다 (F * Δt = m * Δv)",
      description: "주어진 값에 대해 충격량이 운동량 변화와 같은지 확인합니다. 부울 값을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         J: "충격량 (충격량 N·s)",
         Δp: "운동량 변화 (운동량 kg·m/s)",
         F: "힘 (힘 N)",
         Δt: "시간 간격 (시간 s)",
         m: "질량 (질량 kg)",
         Δv: "속도 변화량 (속도 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "방사능 활성도",
      equation_text: "A = λN",
      summary: "방사성 붕괴의 평균 활성도를 계산합니다 (A_avg = ΔN/Δt)",
      description:
         "주어진 시간 간격 동안 방사성 샘플의 평균 활동(붕괴율)을 계산합니다. 참고 - 함수는 핵의 수 ΔN에 대해 `nValue`를 사용하고 시간 Δt에 대해 `tValue`를 사용합니다. 이는 Δt에 대한 단순화된 평균이며, 순간 활동은 dN/dt = -λN입니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         A_avg: "평균 방사능 활성도 (활성도 Bq)",
         ΔN: "붕괴 수 (무차원 수)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "반감기",
      equation_text: "T_½ = ln(2) / λ",
      summary: "붕괴 후 잔여량 계산 (N = N0 * (1/2)^(t/T_half))",
      description:
         "주어진 시간 후 물질의 반감기를 기준으로 남은 양을 계산합니다. 참고 - 시간에는 `tValue`를 사용하고 반감기에는 `Thalf`를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         N: "남은 양/핵 (수)",
         N0: "초기 양/핵 (수)",
         t: "경과 시간 (시간 s)",
         T_half: "반감기 (시간 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "흡수된 방사선량",
      equation_text: "D = dE / dm",
      summary: "흡수된 방사선량을 계산합니다 (D = E/m)",
      description:
         "질량에 의해 흡수된 에너지를 기반으로 방사선 흡수량을 계산합니다. 참고 - 에너지에는 `EValue`를 사용하고 질량에는 `mValue`를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         D: "흡수량 (흡수량 Gy)",
         E: "흡수된 에너지 (에너지 J)",
         m: "질량 (질량 kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "등가 방사선량",
      equation_text: "H = D * W_R",
      summary: "등가 방사선량을 계산합니다 (H = wR * D)",
      description:
         "등가 선량을 계산하여 방사선 종류에 따른 생물학적 효과를 고려합니다. 참고 - 흡수 선량에는 `DValue`를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         H: "등가 선량 (등가 선량 Sv)",
         D: "흡수량 (흡수량 Gy)",
         W_R: "방사선 가중 계수 (무차원)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "유효 방사선량",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "유효 방사선량을 계산합니다 (E = wT * H)",
      description:
         "유효 선량을 계산하여 방사선에 대한 다양한 조직/기관의 민감도를 고려합니다. 참고 - 등가 선량에는 `HValue`를 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "유효 선량 (유효 선량 Sv)",
         H_T: "조직/기관 T에 대한 등가 선량 (등가 선량 Sv)",
         W_T: "조직/기관 T에 대한 조직 가중 계수 (무차원)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "체렌코프 각",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "체렌코프 각을 계산합니다 (θ_C = arccos(c/nv_p))",
      description:
         "매질에서 빛보다 빠르게 움직이는 대전 입자에 의해 형성되는 체렌코프 원뿔의 각도를 계산합니다. 각도는 라디안 단위로 반환됩니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         θ_C: "체렌코프 각 (각도 rad)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
         n: "매질의 굴절률 (무차원)",
         v: "입자 속도 (속도 m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "간섭무늬 (예: 위치, 간격)",
      equation_text: "Δy = λL / d (이중 슬릿 간격)",
      summary: "간섭무늬 위치 계산 (y_n = (nλL)/d)",
      description: "영의 이중 슬릿 간섭 패턴에서 n번째 밝은 무늬의 위치를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         y_n: "n번째 밝은 무늬 위치 (길이 m)",
         n: "무늬 차수 (무차원 정수)",
         λ: "파장 (길이 m)",
         L: "스크린까지의 거리 (길이 m)",
         d: "슬릿 간격 (길이 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "굴절률",
      equation_text: "n = c / v",
      summary: "굴절률을 계산합니다 (n = c/v)",
      description:
         "진공과 매질에서의 빛의 속도를 기준으로 매질의 굴절률을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         n: "굴절률 (무차원)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
         v: "매질에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "스넬의 법칙",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "스넬의 법칙을 검증합니다 (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "주어진 굴절률과 각도를 가진 두 매질 사이를 통과하는 빛에 대해 스넬의 법칙이 성립하는지 확인합니다. 부울 값을 반환합니다. 각도는 라디안 단위여야 합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         n1: "매질 1의 굴절률 (무차원)",
         θ1: "매질 1에서의 각도 (각도 rad)",
         n2: "매질 2의 굴절률 (무차원)",
         θ2: "매질 2에서의 각도 (각도 rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "임계각",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "임계각을 계산합니다 (θ_c = arcsin(n2/n1))",
      description:
         "빛이 굴절률 n1인 매질에서 n2인 매질로 갈 때(n1 > n2) 전반사가 일어나는 임계각을 계산합니다. 각도는 라디안 단위로 반환됩니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         θ_c: "임계각 (각도 rad)",
         n1: "매질 1의 굴절률 (무차원)",
         n2: "매질 2의 굴절률 (무차원)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "상 위치 (광학)",
      equation_text: "1/f = 1/d_o + 1/d_i (얇은 렌즈/거울)",
      summary: "얇은 렌즈/거울 방정식을 검증합니다 (1/f = 1/do + 1/di)",
      description:
         "초점 거리, 물체 거리, 상 거리 사이의 관계가 성립하는지 확인합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f: "초점 거리 (길이 m)",
         d_o: "물체 거리 (길이 m)",
         d_i: "상 거리 (길이 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "상 크기 (확대율 - 광학)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "확대율 방정식을 검증합니다 (h'/h = di/do) (함수는 h'/h = di/do를 사용합니다)",
      description:
         "물체/상 높이와 거리 사이의 관계가 성립하는지 확인합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 이 함수는 부호가 있는 확대율 방정식 대신 크기 관계 `h'/h = di/do`를 사용합니다. 함수 구현에 따라 문서화합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         M: "확대율 (무차원)",
         h_i: "상 높이 (길이 m)",
         h_o: "물체 높이 (길이 m)",
         d_i: "상 거리 (길이 m)",
         d_o: "물체 거리 (길이 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "구면 거울 방정식",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "구면 거울의 초점 거리를 계산합니다 (f = r/2)",
      description: "구면 거울의 곡률 반지름을 기준으로 초점 거리를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f: "초점 거리 (길이 m)",
         r: "곡률 반지름 (길이 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "탄성 퍼텐셜 에너지",
      equation_text: "U_s = ½kx²",
      summary: "용수철의 퍼텐셜 에너지를 계산합니다 (PE = 0.5 * k * Δx^2)",
      description: "이상적인 용수철에 저장된 탄성 퍼텐셜 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         U_s: "용수철 퍼텐셜 에너지 (에너지 J)",
         k: "용수철 상수 (용수철 상수 N/m)",
         x: "평형 위치로부터의 변위 (길이 m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "단조화 진동자 (SHO) 주기",
      equation_text: "T = 2π√(m/k)",
      summary: "용수철-질량 단조화 진동자(SHO)의 주기를 계산합니다 (T = 2π√(m/k))",
      description:
         "용수철에 매달린 질량으로 구성된 단조화 진동자의 주기 계산.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         T: "주기 (시간 s)",
         π: "파이 (무차원 상수)",
         m: "질량 (질량 kg)",
         k: "용수철 상수 (용수철 상수 N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "단진자 주기",
      equation_text: "T = 2π√(L/g)",
      summary: "단진자의 주기를 계산합니다 (T = 2π√(l/g))",
      description: "작은 각도에서 단진자의 주기 계산.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         T: "주기 (시간 s)",
         π: "파이 (무차원 상수)",
         L: "진자 길이 (길이 m)",
         g: "중력 가속도 (가속도 m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "주파수",
      equation_text: "f = 1 / T",
      summary: "주파수를 계산합니다 (f = 1/T)",
      description: "진동 주기에서 주파수를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f: "주파수 (주파수 Hz)",
         T: "주기 (시간 s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "각주파수",
      equation_text: "ω = 2πf",
      summary: "각주파수를 계산합니다 (ω = 2πf)",
      description: "주파수에서 각주파수를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ω: "각주파수 (각속도 rad/s)",
         π: "파이 (무차원 상수)",
         f: "주파수 (주파수 Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "로렌츠 인자",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "로렌츠 인자 (γ)를 계산합니다",
      description: "γ = 1/√(1 - (v²/c²))를 사용하여 로렌츠 인자를 계산합니다. v < c여야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         γ: "로렌츠 인자 (무차원)",
         v: "속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "시간 지연",
      equation_text: "Δt' = γ * Δt₀",
      summary: "시간 지연을 계산합니다 (t' = γ * t₀)",
      description:
         "운동 기준계 S'에서 측정된 고유 시간(t₀)과 S와 S' 사이의 상대 속도(v)가 주어졌을 때, 관성 기준계 S에서 관찰자에게 경과된 시간(t')을 계산합니다. t' = t₀ / √(1 - (v²/c²))를 사용합니다. t₀ ≥ 0이고 |v| ≤ c이어야 합니다. t'의 단위는 t₀와 같아야 하며, v와 c의 단위는 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Δt: "지연된 시간 (시간 s)",
         Δt0: "고유 시간 (시간 s)",
         v: "상대 속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "길이 수축",
      equation_text: "L' = L₀ / γ",
      summary: "길이 수축을 계산합니다 (L' = L₀ / γ)",
      description:
         "운동 기준계 S'에서 관찰된 물체의 길이(L')를 계산합니다. 이는 물체의 정지 기준계 S에서 측정된 고유 길이(L₀)와 S와 S' 사이의 상대 속도(v)를 사용하여 계산합니다. L' = L₀ * √(1 - (v²/c²))를 사용합니다. L₀ ≥ 0이고 |v| ≤ c이어야 합니다. L'의 단위는 L₀와 같아야 하며, v와 c의 단위는 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         L: "수축된 길이 (길이 m)",
         L0: "고유 길이 (길이 m)",
         v: "상대 속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "상대론적 속도 덧셈",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "상대론적 속도 덧셈을 계산합니다",
      description:
         "물체의 기준계 S에 대한 속도(u)와 기준계 S'에 대한 기준계 S의 속도(v)가 주어졌을 때, 기준계 S'에 대한 물체의 속도(u')를 계산합니다. u' = (u + v) / (1 + uv/c²)라는 방정식을 사용합니다. 같은 직선 상에서의 운동을 가정합니다. c ≠ 0이어야 합니다. u, v, c의 단위는 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         u: "기준계 S에서의 물체 속도 (속도 m/s)",
         v: "S'에 대한 기준계 S의 속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
         "u'": "S'에 대한 물체의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "상대론적 전체 에너지",
      equation_text: "E = γmc²",
      summary: "상대론적 전체 에너지 (E)를 계산합니다",
      description:
         "정지 질량(m)을 갖고 속도(v)로 움직이는 입자의 전체 상대론적 에너지를 계산합니다. E = γmc² = mc² / √(1 - (v²/c²))라는 방정식을 사용합니다. 주로 정지 질량을 가진 입자(m > 0)에 사용됩니다. m ≥ 0이고 |v| ≤ c이어야 합니다. m, v, c의 단위는 적절한 단위의 에너지를 얻기 위해 일관되어야 합니다(예: m은 kg, v/c는 m/s일 때 E는 줄).",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "전체 상대론적 에너지 (에너지 J)",
         m: "정지 질량 (질량 kg)",
         v: "속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "상대론적 운동량",
      equation_text: "p = γmv",
      summary: "상대론적 운동량 (p = γmv)을 계산합니다",
      description:
         "정지 질량(m)을 갖고 속도(v)로 움직이는 입자의 상대론적 운동량을 계산합니다. p = γmv = mv / √(1 - (v²/c²))라는 방정식을 사용합니다. 주로 정지 질량을 가진 입자(m > 0)에 사용됩니다. m ≥ 0이고 |v| ≤ c이어야 합니다. m, v, c의 단위는 적절한 단위의 운동량을 얻기 위해 일관되어야 합니다(예: m은 kg, v는 m/s, c는 m/s일 때 p는 kg·m/s).",
      language_code: "ko",
      subject: "Physics",
      variables: {
         p: "상대론적 운동량 (운동량 kg·m/s)",
         m: "정지 질량 (질량 kg)",
         v: "속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "에너지-운동량 관계",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "운동량과 정지 질량에서 전체 에너지 (E)를 계산합니다",
      description:
         "입자의 상대론적 운동량(p)과 정지 질량(m)으로부터 전체 상대론적 에너지를 계산합니다. 에너지-운동량 관계: E² = (pc)² + (mc²)²를 사용합니다. 이 방정식은 질량이 있는 입자(m > 0)와 질량이 없는 입자(m = 0) 모두에 유효합니다. p ≥ 0, m ≥ 0, c > 0이어야 합니다. p, m, c의 단위는 일관되어야 합니다.\n",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "전체 상대론적 에너지 (에너지 J)",
         p: "상대론적 운동량 (운동량 kg·m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
         m: "정지 질량 (질량 kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "질량-에너지 등가성 (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "질량-에너지 등가성을 계산합니다 (E₀ = mc²)",
      description:
         "아인슈타인의 유명한 방정식 E₀ = mc²을 사용하여 주어진 정지 질량(m)에 해당하는 정지 에너지(E₀)를 계산합니다. m ≥ 0이고 c > 0이어야 합니다. m과 c의 단위는 일관되어야 합니다(예: m은 kg, c는 m/s일 때 E₀는 줄). 이 엔드포인트는 'c'가 명시적으로 제공되지 않는 한 c의 표준값(약 299792458 m/s)을 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E0: "정지 에너지 (에너지 J)",
         m: "정지 질량 (질량 kg)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "상대론적 운동 에너지",
      equation_text: "KE = (γ - 1)mc²",
      summary: "상대론적 운동 에너지 (KE)를 계산합니다",
      description:
         "정지 질량(m)을 갖고 속도(v)로 움직이는 입자의 상대론적 운동 에너지를 계산합니다. KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc²라는 방정식을 사용합니다. 주로 정지 질량을 가진 입자(m > 0)에 사용됩니다. m ≥ 0이고 |v| < c이어야 합니다. m, v, c의 단위는 적절한 단위의 에너지를 얻기 위해 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE: "상대론적 운동 에너지 (에너지 J)",
         m: "정지 질량 (질량 kg)",
         v: "속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "상대론적 도플러 효과 (파장)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "파장에 대한 상대론적 종방향 도플러 효과 계산",
      description:
         "관찰자로부터 직접 멀어지거나 가까워지는 상대 속도(v_rel)로 움직이는 광원에서 방출된 고유 파장(λ₀)의 관찰 파장(λ')을 계산합니다. λ' = λ₀√((1 + β)/(1 - β))라는 방정식을 사용하며, β = v_rel/c입니다. v_rel > 0은 후퇴(적색편이), v_rel < 0은 접근(청색편이)을 나타냅니다. λ₀ > 0이고 |v_rel| < c여야 합니다. λ'의 단위는 λ₀와 같아야 하며, v_rel과 c의 단위는 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         "λ'": "관찰 파장 (길이 m)",
         λ0: "고유 파장 (길이 m)",
         v: "상대 속도 (속도 m/s)",
         c: "진공에서의 빛의 속도 (속도 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "광자 에너지 (주파수에서)",
      equation_text: "E = hf",
      summary: "주파수에서 광자 에너지를 계산합니다 (E = hf)",
      description:
         "광자의 에너지(E)를 그 주파수(f)를 기반으로 계산합니다. 플랑크 관계 E = hf를 사용합니다. f ≥ 0이고 h > 0이어야 합니다. h와 f의 단위는 적절한 단위의 에너지를 얻기 위해 일관되어야 합니다(예: h는 J·s, f는 Hz(s⁻¹)일 때 E는 줄). 이 엔드포인트는 'h'가 명시적으로 제공되지 않는 한 h의 표준값(약 6.626e-34 J·s)을 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "광자 에너지 (에너지 J)",
         h: "플랑크 상수 (상수 J·s)",
         f: "주파수 (주파수 Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "광자 운동량 (파장에서)",
      equation_text: "p = h / λ",
      summary: "파장에서 광자 운동량을 계산합니다 (p = h/λ)",
      description:
         "광자의 운동량(p)을 그 파장(λ)을 기반으로 계산합니다. 관계 p = h/λ를 사용합니다. λ > 0이고 h > 0이어야 합니다. h와 λ의 단위는 적절한 단위의 운동량을 얻기 위해 일관되어야 합니다(예: h는 J·s, λ는 미터일 때 p는 kg·m/s). 이 엔드포인트는 'h'가 명시적으로 제공되지 않는 한 h의 표준값(약 6.626e-34 J·s)을 사용합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         p: "광자 운동량 (운동량 kg·m/s)",
         h: "플랑크 상수 (상수 J·s)",
         λ: "파장 (길이 m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "광전 효과 (최대 KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "광전 효과에서의 최대 운동 에너지를 계산합니다 (KE_max)",
      description:
         "광전 효과에서 방출된 전자의 최대 운동 에너지(KE_max)를 계산합니다. KE_max = E_photon - φ라는 방정식을 사용하며, E_photon은 입사 광자 에너지, φ는 재료의 일 함수입니다. E_photon ≤ φ이면 전자가 방출되지 않으며 KE_max는 0입니다. E_photon ≥ 0이고 φ ≥ 0이어야 합니다. E_photon과 φ의 단위는 KE_max를 같은 단위로 얻기 위해 일관되어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE_max: "최대 전자 운동 에너지 (에너지 J)",
         E_photon: "광자 에너지 (에너지 J)",
         φ: "일 함수 (에너지 J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "리드버그 방정식 (원자 전이)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "수소와 유사한 원자 전이의 에너지 또는 파수 계산",
      description:
         "수소와 유사한 원자(Z)에서 두 에너지 준위 사이의 전자 전이에 대한 에너지 차이(ΔE) 또는 파수(1/λ)를 계산합니다. 결과 = 상수 * Z² * (1/n_initial² - 1/n_final²)이라는 방정식을 사용합니다. '상수'가 리드버그 에너지 단위(예: eV)이면 결과는 에너지 차이 E_final - E_initial(흡수는 양수, 방출은 음수)입니다. '상수'가 파수에 대한 리드버그 상수(예: m⁻¹)이면 결과는 파수 1/λ(방출은 양수, 흡수는 음수)입니다. nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0(정수) 및 상수 > 0이어야 합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔE: "에너지 차이 (에너지 J)",
         R_y: "리드버그 상수 (상수 J 또는 역길이 m⁻¹)",
         Z: "원자 번호 (무차원 정수)",
         n1: "초기 주 양자수 (무차원 정수)",
         n2: "최종 주 양자수 (무차원 정수)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "각속도",
      equation_text: "ω = Δθ / Δt",
      summary: "각속도를 계산합니다 (ω = Δθ / Δt)",
      description: "각도의 변화량과 시간을 기준으로 각속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ω: "각속도 (각속도 rad/s)",
         Δθ: "각 변위 (각도 rad)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "각가속도",
      equation_text: "α = Δω / Δt",
      summary: "각가속도를 계산합니다 (α = Δω / Δt)",
      description: "각속도의 변화량과 시간을 기준으로 각가속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         α: "각가속도 (각가속도 rad/s²)",
         Δω: "각속도 변화량 (각속도 rad/s)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "회전 운동학 (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "최종 각속도를 계산합니다 (ω = ω0 + αt)",
      description: "첫 번째 회전 운동학 방정식을 사용하여 최종 각속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ω: "최종 각속도 (각속도 rad/s)",
         ω0: "초기 각속도 (각속도 rad/s)",
         α: "각가속도 (각가속도 rad/s²)",
         t: "시간 (시간 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "회전 운동학 (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "각 위치를 계산합니다 (θ = θ0 + ω0t + 0.5αt^2)",
      description: "두 번째 회전 운동학 방정식을 사용하여 최종 각 위치를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         θ: "최종 각 위치 (각도 rad)",
         θ0: "초기 각 위치 (각도 rad)",
         ω0: "초기 각속도 (각속도 rad/s)",
         t: "시간 (시간 s)",
         α: "각가속도 (각가속도 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "회전 운동학 (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "각속도의 제곱을 계산합니다 (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "회전 운동학의 세 번째 방정식을 사용하여 최종 각속도의 제곱을 계산합니다. 참고 - ω 대신 ω^2을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ω: "최종 각속도 (각속도 rad/s)",
         ω0: "초기 각속도 (각속도 rad/s)",
         α: "각가속도 (각가속도 rad/s²)",
         Δθ: "각 변위 (각도 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "평균 각속도",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "평균 각속도를 계산합니다 (ω_avg = 0.5 * (ω + ω0))",
      description: "일정한 각가속도를 가정하여 평균 각속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ω_avg: "평균 각속도 (각속도 rad/s)",
         ω: "최종 각속도 (각속도 rad/s)",
         ω0: "초기 각속도 (각속도 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "돌림힘 (토크)",
      equation_text: "τ = rFsin(θ)",
      summary: "돌림힘을 계산합니다 (τ = rF sin(θ))",
      description: "반지름, 힘, 그리고 그것들 사이의 각도를 기준으로 돌림힘을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         τ: "돌림힘 (돌림힘 N·m)",
         r: "힘의 팔 (길이 m)",
         F: "힘 (힘 N)",
         θ: "힘과 힘의 팔 사이의 각도 (각도 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "뉴턴 제2법칙 (회전)",
      equation_text: "τ_net = Iα",
      summary: "회전 제2법칙을 사용하여 돌림힘을 계산합니다 (τ = Iα)",
      description: "관성 모멘트와 각가속도를 기준으로 돌림힘을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         τ_net: "알짜 돌림힘 (돌림힘 N·m)",
         I: "관성 모멘트 (관성 모멘트 kg·m²)",
         α: "각가속도 (각가속도 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "관성 모멘트",
      equation_text: "I = mr² (점 질량)",
      summary: "점 질량의 관성 모멘트를 계산합니다 (I = mr^2)",
      description: "축에 대한 단일 점 질량의 관성 모멘트를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         I: "관성 모멘트 (관성 모멘트 kg·m²)",
         m: "질량 (질량 kg)",
         r: "축으로부터의 거리 (길이 m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "회전 일",
      equation_text: "W = τΔθ (일정 토크)",
      summary: "회전 일을 계산합니다 (W = τΔθ)",
      description: "일정한 돌림힘이 각 변위에 대해 수행한 일을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         W: "회전 일 (에너지 J)",
         τ: "돌림힘 (돌림힘 N·m)",
         Δθ: "각 변위 (각도 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "회전 일률",
      equation_text: "P = τω",
      summary: "회전 일률을 계산합니다 (P = τω cos(θ))",
      description:
         "돌림힘, 각속도 및 그것들 사이의 각도를 기준으로 순간 회전 일률을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "회전 일률 (일률 W)",
         τ: "돌림힘 (돌림힘 N·m)",
         ω: "각속도 (각속도 rad/s)",
         θ: "돌림힘과 각속도 사이의 각도 (각도 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "회전 운동 에너지",
      equation_text: "KE_rot = ½Iω²",
      summary: "회전 운동 에너지를 계산합니다 (KE = 0.5Iω^2)",
      description: "회전하는 물체의 운동 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE_rot: "회전 운동 에너지 (에너지 J)",
         I: "관성 모멘트 (관성 모멘트 kg·m²)",
         ω: "각속도 (각속도 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "각운동량",
      equation_text: "L = Iω",
      summary: "각운동량을 계산합니다 (L = mrv sin(θ))",
      description: "어떤 점에 대한 점 질량의 각운동량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         L: "각운동량 (각운동량 kg·m²/s)",
         m: "질량 (질량 kg)",
         r: "축/점에서 거리 (길이 m)",
         v: "속도 (속도 m/s)",
         θ: "반경 벡터와 속도 사이의 각도 (각도 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "각충격량",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "각충격량을 계산합니다 (J = τΔt)",
      description: "돌림힘과 시간 간격에서 각충격량을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         J_angular: "각충격량 (각충격량 N·m·s)",
         τ_avg: "평균 돌림힘 (돌림힘 N·m)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "영률",
      equation_text: "E = σ / ε",
      summary: "영률을 계산합니다 (E = (F * L0) / (A * ΔL))",
      description: "인장 또는 압축 응력을 받는 재료의 영률(탄성 계수)을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         E: "영률 (압력 Pa)",
         F: "힘 (힘 N)",
         L0: "원본 길이 (길이 m)",
         A: "단면적 (면적 m²)",
         ΔL: "길이 변화 (길이 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "전단 탄성 계수",
      equation_text: "G = τ / γ",
      summary: "전단 탄성 계수를 계산합니다 (G = (F * y) / (A * Δx))",
      description: "전단 응력을 받는 재료의 전단 탄성 계수(강성 계수)를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         G: "전단 탄성 계수 (압력 Pa)",
         F: "힘 (힘 N)",
         y: "힘에 수직인 거리 (길이 m)",
         A: "면적 (면적 m²)",
         Δx: "변위 (길이 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "체적 탄성 계수",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "체적 탄성 계수를 계산합니다 (K = (F * V0) / (A * ΔV))",
      description: "균일한 압력(정수압 응력)을 받는 재료의 체적 탄성 계수를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         K: "체적 탄성 계수 (압력 Pa)",
         ΔP: "압력 변화 (압력 Pa)",
         ΔV: "부피 변화 (부피 m³)",
         V0: "원본 부피 (부피 m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "후크의 법칙",
      equation_text: "F = kx",
      summary: "용수철의 힘을 계산합니다 (F = -k * Δx)",
      description:
         "후크의 법칙에 따라 이상적인 용수철에 의해 가해지는 복원력을 계산합니다. 참고 - 변위에 반대되는 힘을 나타내는 음수 값을 반환합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         F: "힘 (힘 N)",
         k: "용수철 상수 (용수철 상수 N/m)",
         x: "평형 위치로부터의 변위 (길이 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "고체 열팽창 (길이)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "고체 선팽창을 계산합니다 (ΔL = αL0ΔT)",
      description: "온도 변화로 인한 고체 재료의 길이 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔL: "길이 변화 (길이 m)",
         α: "선팽창 계수 (단위 온도당 계수 K⁻¹)",
         L0: "원본 길이 (길이 m)",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "고체 열팽창 (면적)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "고체 면적 열팽창을 계산합니다 (ΔA = 2αA0ΔT)",
      description:
         "선팽창 계수를 사용하여 온도 변화로 인한 고체 재료의 면적 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔA: "면적 변화 (면적 m²)",
         α: "선팽창 계수 (단위 온도당 계수 K⁻¹)",
         A0: "원본 면적 (면적 m²)",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "고체 열팽창 (부피)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "고체 부피 열팽창을 계산합니다 (ΔV = 3αV0ΔT)",
      description:
         "선팽창 계수를 사용하여 온도 변화로 인한 고체 재료의 부피 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔV: "부피 변화 (부피 m³)",
         α: "선팽창 계수 (단위 온도당 계수 K⁻¹)",
         V0: "원본 부피 (부피 m³)",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "액체 열팽창",
      equation_text: "ΔV = βV₀ΔT",
      summary: "액체 열팽창을 계산합니다 (ΔV = βV0ΔT)",
      description: "온도 변화로 인한 액체의 부피 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔV: "부피 변화 (부피 m³)",
         β: "부피 팽창 계수 (단위 온도당 계수 K⁻¹)",
         V0: "원본 부피 (부피 m³)",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "현열",
      equation_text: "Q = mcΔT",
      summary: "현열을 계산합니다 (Q = mcΔT)",
      description: "물질의 온도 변화를 일으키는 전달된 열을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Q: "현열 (에너지 J)",
         m: "질량 (질량 kg)",
         c: "비열 용량 (비열 용량 J/(kg·K))",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "잠열",
      equation_text: "Q = mL",
      summary: "잠열을 계산합니다 (Q = mL)",
      description: "물질의 상변화 중에 전달되는 열을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Q: "잠열 (에너지 J)",
         m: "질량 (질량 kg)",
         L: "잠열 (비에너지 J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "이상 기체 법칙",
      equation_text: "PV = nRT",
      summary: "이상 기체 법칙을 검증합니다 (PV = nRT)",
      description:
         "주어진 매개변수에 대해 이상 기체 법칙 방정식이 성립하는지 확인합니다. 부울 값을 반환합니다. 참고 - 부동 소수점 정밀도에 민감할 수 있는 엄격한 등가(===)를 사용합니다. 실제 검사 시 허용 오차를 고려하십시오.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "압력 (압력 Pa)",
         V: "부피 (부피 m³)",
         n: "몰 수 (물질량 mol)",
         R: "이상 기체 상수 (상수 J/(mol·K))",
         T: "온도 (온도 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "분자 운동 에너지",
      equation_text: "KE_avg = (3/2)kT",
      summary: "평균 분자 운동 에너지를 계산합니다 (KE = (3/2)kT)",
      description: "이상 기체 분자당 평균 병진 운동 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE_avg: "평균 분자 운동 에너지 (에너지 J)",
         k: "볼츠만 상수 (상수 J/K)",
         T: "온도 (온도 K)",
         m: "단일 분자 질량 (질량 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "분자 속도 (최빈값)",
      equation_text: "v_p = √(2kT/m)",
      summary: "가장 가능성이 높은 분자 속도 계산 (v_p = √(2kT/m))",
      description:
         "맥스웰-볼츠만 분포에 따라 이상 기체에서 분자의 가장 가능성이 높은 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_p: "가장 가능성이 높은 분자 속도 (속도 m/s)",
         k: "볼츠만 상수 (상수 J/K)",
         T: "온도 (온도 K)",
         m: "단일 분자 질량 (질량 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "분자 속도 (평균)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "평균 분자 속도 계산 (v_avg = √(8kT/(πm)))",
      description:
         "맥스웰-볼츠만 분포에 따라 이상 기체에서 분자의 평균 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_avg: "평균 분자 속도 (속도 m/s)",
         k: "볼츠만 상수 (상수 J/K)",
         T: "온도 (온도 K)",
         π: "파이 (무차원 상수)",
         m: "단일 분자 질량 (질량 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "분자 속도 (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "평균 제곱근 분자 속도 계산 (v_rms = √(3kT/m))",
      description:
         "맥스웰-볼츠만 분포에 따라 이상 기체에서 분자의 제곱근 평균 제곱 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v_rms: "평균 제곱근 분자 속도 (속도 m/s)",
         k: "볼츠만 상수 (상수 J/K)",
         T: "온도 (온도 K)",
         m: "단일 분자 질량 (질량 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "내부 에너지 변화",
      equation_text: "ΔU = Q - W",
      summary: "이상적인 단원자 기체의 내부 에너지 변화 계산 (ΔU = (3/2)nRΔT)",
      description:
         "온도 변화를 겪는 단원자 이상 기체의 내부 에너지 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         ΔU: "내부 에너지 변화 (에너지 J)",
         n: "몰 수 (물질량 mol)",
         R: "이상 기체 상수 (상수 J/(mol·K))",
         ΔT: "온도 변화 (온도차 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "열역학적 일",
      equation_text: "W = PΔV (일정 압력)",
      summary: "일정 압력에서 시스템이 하는 열역학적 일 계산 (W = -PΔV)",
      description:
         "일정 압력에서 열역학 과정 중 시스템이 하는 일 또는 시스템에 가해지는 일을 계산합니다. 참고 - 방정식은 시스템이 하는 일을 계산하며, 팽창은 양수, 압축은 음수입니다. 함수는 -P*deltaV를 반환하며, 이는 W = PΔV 방정식에 따른 시스템이 하는 일과 일관되지만, 관례에 따라 시스템에 가해지는 일을 의미할 수 있는 음수 부호가 추가되었습니다. 함수의 출력을 문서화합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         W: "열역학적 일 (에너지 J)",
         P: "압력 (압력 Pa)",
         ΔV: "부피 변화 (부피 m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "실제 효율",
      equation_text: "η = W_out / Q_in",
      summary: "실제 열기관의 효율 계산 (η_real = 1 - (Q_C / Q_H))",
      description: "흡수 및 방출된 열을 기준으로 열기관의 열효율을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         η: "효율 (무차원)",
         Q_H: "고온 저장소에서 흡수된 열 (에너지 J)",
         Q_C: "저온 저장소로 방출된 열 (에너지 J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "이상적 효율",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "이상적 효율 (카르노) 계산 (η_ideal = 1 - (T_C / T_H))",
      description:
         "두 온도 사이에서 작동하는 열기관의 최대 이론적 효율(카르노 효율)을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         η_ideal: "이상적 효율 (무차원)",
         T_hot: "고온 저장소 온도 (온도 K)",
         T_cold: "저온 저장소 온도 (온도 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "실제 성능 계수 (COP)",
      equation_text: "COP_ref = Q_c / W (냉장고)",
      summary: "실제 냉장고의 성능 계수 계산 (COP_real = QC / (QH - QC))",
      description: "실제 냉장고 또는 열펌프의 성능 계수를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         COP_real: "성능 계수 (무차원)",
         Q_C: "저온 저장소에서 얻은 열 (에너지 J)",
         Q_H: "고온 저장소로 전달된 열 (에너지 J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "이상적 성능 계수 (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "이상적인 냉장고의 성능 계수 계산 (COP_ideal = TC / (TH - TC))",
      description:
         "두 온도 사이에서 작동하는 냉장고 또는 열펌프의 최대 이론적 성능 계수를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         COP_ideal: "이상적 성능 계수 (무차원)",
         T_h: "고온 저장소 온도 (온도 K)",
         T_c: "저온 저장소 온도 (온도 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "주기파 속도",
      equation_text: "v = fλ",
      summary: "파 속도를 계산합니다 (v = fλ)",
      description: "주기파의 주파수와 파장을 기준으로 파의 속도를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         v: "파 속도 (속도 m/s)",
         f: "주파수 (주파수 Hz)",
         λ: "파장 (길이 m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "파의 강도",
      equation_text: "I = P / A",
      summary: "강도를 계산합니다 (I = P/A)",
      description: "파의 강도(단위 면적당 일률)를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         I: "강도 (강도 W/m²)",
         P: "일률 (일률 W)",
         A: "면적 (면적 m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "강도 수준 (데시벨)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "데시벨 단위로 강도 수준 계산 (L = 10 log10(I/I0))",
      description: "기준 강도에 대한 강도 수준(음향 강도 수준)을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         β: "강도 수준 (강도 수준 dB)",
         I: "강도 (강도 W/m²)",
         I0: "기준 강도 (강도 W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "압력 수준 (음압 수준)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "데시벨 단위로 음압 수준 계산 (L = 20 log10(ΔP/ΔP0))",
      description: "기준 압력 변화에 대한 음압 수준을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         L_p: "음압 수준 (압력 수준 dB)",
         P_rms: "RMS 압력 변동 (압력 Pa)",
         P_ref: "기준 압력 (압력 Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "도플러 효과 (소리/비상대론적)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "도플러 효과 속도 요인 계산 ((c + v_o) / (c - v_s))",
      description:
         "도플러 효과 방정식의 속도 요인 부분(f' = f * factor)을 계산합니다. 관찰자가 음원 쪽으로 이동하거나 음원이 관찰자 쪽으로 이동하는 경우 속도는 양수입니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         f_obs: "관찰된 주파수 (주파수 Hz)",
         f_source: "음원 주파수 (주파수 Hz)",
         v_wave: "파 속도 (속도 m/s)",
         v_observer: "매질에 대한 관찰자 속도 (속도 m/s)",
         v_source: "매질에 대한 음원 속도 (속도 m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "마하 각",
      equation_text: "sin(μ) = 1 / M",
      summary: "마하 각을 계산합니다 (θ_M = arcsin(c/v))",
      description:
         "음속보다 빠르게 움직이는 물체에 의해 형성되는 마하 원뿔의 각도를 계산합니다. 각도는 라디안 단위로 반환됩니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         μ: "마하 각 (각도 rad)",
         M: "마하수 (무차원)",
         c: "음속 (속도 m/s)",
         v: "물체 속도 (속도 m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "일",
      equation_text: "W = Fdcos(θ)",
      summary: "수행된 일 계산 (W = F * Δs * cos(θ))",
      description: "힘, 변위 및 그것들 사이의 각도를 기준으로 수행된 일을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         W: "수행된 일 (에너지 J)",
         F: "힘 크기 (힘 N)",
         d: "변위 크기 (길이 m)",
         θ: "힘과 변위 사이의 각도 (각도 rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "운동 에너지",
      equation_text: "KE = ½mv²",
      summary: "운동 에너지를 계산합니다 (KE = 0.5 * m * v^2)",
      description: "질량과 속도를 기준으로 운동 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE: "운동 에너지 (에너지 J)",
         m: "질량 (질량 kg)",
         v: "속도 (속도 m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "운동 에너지 (운동량에서)",
      equation_text: "KE = p² / (2m)",
      summary: "운동량에서 운동 에너지를 계산합니다 (KE = p^2 / (2m))",
      description: "운동량과 질량을 기준으로 운동 에너지를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         KE: "운동 에너지 (에너지 J)",
         p: "운동량 (운동량 kg·m/s)",
         m: "질량 (질량 kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "중력 퍼텐셜 에너지",
      equation_text: "U_g = mgh (표면 근처)",
      summary: "중력 퍼텐셜 에너지를 계산합니다 (PE = mgh)",
      description: "중력 퍼텐셜 에너지 변화를 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         U_g: "중력 퍼텐셜 에너지 (에너지 J)",
         m: "질량 (질량 kg)",
         g: "중력 가속도 (가속도 m/s²)",
         h: "높이 (길이 m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "효율",
      equation_text: "효율 = 출력 / 입력",
      summary: "효율을 계산합니다 (η = W_out / W_in)",
      description: "과정 또는 기계의 효율을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         Efficiency: "효율 (무차원)",
         Output: "유용한 출력 에너지 또는 일률 (에너지 J 또는 일률 W)",
         Input: "총 입력 에너지 또는 일률 (에너지 J 또는 일률 W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "일률",
      equation_text: "P = W / t",
      summary: "일률을 계산합니다 (P = ΔW / Δt)",
      description: "일의 변화량과 시간을 기준으로 평균 일률을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "일률 (일률 W)",
         ΔW: "일 변화량 (에너지 J)",
         Δt: "시간 간격 (시간 s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "일률 (P = Fv)",
      equation_text: "P = Fv",
      summary: "힘과 속도에서 일률을 계산합니다 (P = Fv cos(θ))",
      description: "힘, 속도 및 그것들 사이의 각도를 기준으로 순간 일률을 계산합니다.",
      language_code: "ko",
      subject: "Physics",
      variables: {
         P: "일률 (일률 W)",
         F: "힘 크기 (힘 N)",
         v: "속도 크기 (속도 m/s)",
         θ: "힘과 속도 사이의 각도 (각도 rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = ko;