const tr = [
   {
      equation_id: "centripetal-acceleration",
      name: "Merkezcil İvme",
      equation_text: "a_c = v² / r",
      summary: "Merkezcil ivmeyi hesaplar (a_c = v^2 / r)",
      description:
         "Doğrusal hız ve yarıçap kullanarak dairesel bir yolun merkezine doğru yönelen ivmeyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         a_c: "Merkezcil ivme (İvme m/s²)",
         v: "Doğrusal hız (Hız m/s)",
         r: "Dairesel yolun yarıçapı (Uzunluk m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "Merkezcil İvme (Açısal)",
      equation_text: "a_c = ω²r",
      summary: "Açısal hız kullanarak merkezcil ivmeyi hesaplar (a_c = -ω^2 * r)",
      description:
         "Açısal hız ve yarıçap kullanarak merkezcil ivme vektör bileşenini hesaplar. Eksi işareti merkeze doğru yönü gösterir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         a_c: "Merkezcil ivme (İvme m/s²)",
         ω: "Açısal hız (Açısal Hız rad/s)",
         r: "Dairesel yolun yarıçapı (Uzunluk m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "Coulomb Yasası (Kuvvet)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "Coulomb Yasasını kullanarak elektrik kuvvetini hesaplar (F = k * q1*q2 / r^2)",
      description:
         "İki noktasal yük arasındaki elektrik kuvvetini hesaplar. İşaretli kuvveti döndürür (itme için pozitif, çekme için negatif).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F: "Elektrik kuvveti (Kuvvet N)",
         k: "Coulomb sabiti (Sabit N·m²/C²)",
         q1: "Yük 1 (Yük C)",
         q2: "Yük 2 (Yük C)",
         r: "Yükler arasındaki mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "Elektrik Alanı",
      equation_text: "E = kq / r² (nokta yük)",
      summary: "Kuvvetten elektrik alanını hesaplar (E = F_E/q)",
      description: "Bir test yüküne uygulanan kuvvete dayalı olarak elektrik alan şiddetini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Elektrik alan büyüklüğü (Elektrik Alan N/C)",
         k: "Coulomb sabiti (Sabit N·m²/C²)",
         q: "Kaynak yük (Yük C)",
         r: "Kaynak yükten mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "Elektrik Potansiyeli",
      equation_text: "V = kq / r (nokta yük)",
      summary: "Potansiyel enerji değişiminden elektrik potansiyelini hesaplar (V = ΔU_E/q)",
      description:
         "Birim yük başına düşen elektrik potansiyeli enerji değişimine dayalı olarak elektrik potansiyelini (gerilim) hesaplar. Not - `calculateElectricPotential` fonksiyon adı doğrudur, ancak `deltaUE` parametresi değişimi ima ederken, denklem genellikle V=U_E/q veya ΔV=ΔU_E/q'dir. ΔV = ΔU_E/q denklemine dayanarak belgeleyip ΔV döndürülmektedir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         V: "Elektrik potansiyeli (Gerilim V)",
         k: "Coulomb sabiti (Sabit N·m²/C²)",
         q: "Kaynak yük (Yük C)",
         r: "Kaynak yükten mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "Elektrik Alanı ve Potansiyel İlişkisi",
      equation_text: "E_x = -dV/dx",
      summary: "Potansiyel farktan elektrik alanını hesaplar (E = ΔV/d)",
      description:
         'Bir mesafe boyunca potansiyel farka dayalı olarak düzgün bir elektrik alanın büyüklüğünü hesaplar. Not - "Alan ve Potansiyel" fonksiyon adı yanıltıcıdır; Elektrik Alan E\'yi hesaplar.',
      language_code: "tr",
      subject: "Physics",
      variables: {
         E_x: "Elektrik alan bileşeni (Elektrik Alan V/m)",
         V: "Elektrik potansiyeli (Gerilim V)",
         x: "Konum (Uzunluk m)",
         ΔV: "Potansiyel fark (Gerilim V)",
         d: "Mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "Kapasite",
      equation_text: "C = Q / V",
      summary: "Kapasiteyi hesaplar (C = Q/V)",
      description: "Depolanan yüke ve bir kapasitör üzerindeki gerilime dayalı olarak kapasiteyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C: "Kapasite (Kapasite F)",
         Q: "Yük (Yük C)",
         V: "Gerilim (Gerilim V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "Plaka Kapasitör Kapasitesi",
      equation_text: "C = ε₀A / d",
      summary: "Paralel plakalı kapasitör kapasitesini hesaplar (C = (kε₀A)/d)",
      description:
         "Bir dielektrik içeren paralel plakalı bir kapasitörün kapasitesini hesaplar. Not - Fonksiyon k * ε₀ değerini tek bir girdi (`kEpsilon`) olarak kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C: "Kapasite (Kapasite F)",
         ε0: "Boş alanın permitivitesi (Sabit F/m)",
         k: "Dielektrik sabiti (Boyutsuz)",
         A: "Plakaların alanı (Alan m²)",
         d: "Plakalar arasındaki mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "Silindirik Kapasitör Kapasitesi",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "Silindirik kapasitör kapasitesini hesaplar (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "Bir dielektrik içeren silindirik bir kapasitörün kapasitesini hesaplar. Not - Fonksiyon k * ε₀ değerini tek bir girdi (`kEpsilon`) olarak kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C: "Kapasite (Kapasite F)",
         π: "Pi (Boyutsuz sabit)",
         ε0: "Boş alanın permitivitesi (Sabit F/m)",
         k: "Dielektrik sabiti (Boyutsuz)",
         L: "Silindirlerin uzunluğu (Uzunluk m)",
         b: "Dış yarıçap (Uzunluk m)",
         a: "İç yarıçap (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "Küresel Kapasitör Kapasitesi",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "Küresel kapasitör kapasitesini hesaplar (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "Bir dielektrik içeren küresel bir kapasitörün kapasitesini hesaplar. Not - Fonksiyon k * ε₀ değerini tek bir girdi (`kEpsilon`) olarak kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C: "Kapasite (Kapasite F)",
         π: "Pi (Boyutsuz sabit)",
         ε0: "Boş alanın permitivitesi (Sabit F/m)",
         k: "Dielektrik sabiti (Boyutsuz)",
         a: "İç yarıçap (Uzunluk m)",
         b: "Dış yarıçap (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "Kapasitif Potansiyel Enerji",
      equation_text: "U_C = ½CV²",
      summary: "Kapasitör potansiyel enerji denklemlerini doğrular (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "Verilen Q, V ve C değerleri için bir kapasitörde depolanan potansiyel enerjiye ilişkin üç yaygın denklemin eşdeğer olup olmadığını kontrol eder. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         U_C: "Kapasitif potansiyel enerji (Enerji J)",
         Q: "Yük (Yük C)",
         V: "Gerilim (Gerilim V)",
         C: "Kapasite (Kapasite F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "Elektrik Akımı",
      equation_text: "I = ΔQ / Δt",
      summary: "Elektrik akımını hesaplar (I = ΔQ/Δt)",
      description: "Elektrik akımını, birim zamanda bir noktadan geçen yük miktarına dayalı olarak hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         I: "Elektrik akımı (Akım A)",
         ΔQ: "Yük değişimi (Yük C)",
         Δt: "Zaman değişimi (Zaman s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "Yük Yoğunluğu",
      equation_text: "ρ = Q / V (Hacim)",
      summary: "Yük yoğunluğunu hesaplar (ρ = Q/V)",
      description: "Ortalama yük yoğunluğunu (birim hacim başına düşen yük) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ρ: "Hacimsel yük yoğunluğu (Yük Yoğunluğu C/m³)",
         Q: "Toplam yük (Yük C)",
         V: "Hacim (Hacim m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "Akım Yoğunluğu",
      equation_text: "J = I / A",
      summary: "Akım yoğunluğunu hesaplar (J = I/A)",
      description: "Elektrik akım yoğunluğunu (birim kesit alanı başına düşen akım) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         J: "Akım yoğunluğu (Akım Yoğunluğu A/m²)",
         I: "Elektrik akımı (Akım A)",
         A: "Alan (Alan m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "Ohm Yasası",
      equation_text: "V = IR",
      summary: "Ohm Yasasını kullanarak direnci hesaplar (R = V/I)",
      description:
         "Gerilim ve akıma dayalı olarak direnci hesaplar. Not - Fonksiyon R Direncini V ve I'den hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         V: "Gerilim (Gerilim V)",
         I: "Akım (Akım A)",
         R: "Direnç (Direnç Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "Dirençlilik ve İletkenlik",
      equation_text: "ρ = RA / L",
      summary: "Dirençlilikten iletkenliği hesaplar (σ = 1/ρ)",
      description: "Dirençlilikten (ρ) iletkenliği (σ) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         σ: "İletkenlik (İletkenlik S/m)",
         ρ: "Dirençlilik (Dirençlilik Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "Elektrik Direnci",
      equation_text: "R = ρL / A",
      summary: "Elektrik direncini hesaplar (R = ρ(l/A))",
      description:
         "Bir iletkenin direncini, onun dirençliliğine, uzunluğuna ve kesit alanına dayalı olarak hesaplar. Not - Dirençlilik için `rhoValue` kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         R: "Direnç (Direnç Ω)",
         ρ: "Dirençlilik (Dirençlilik Ω·m)",
         L: "Uzunluk (Uzunluk m)",
         A: "Kesit alanı (Alan m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "Elektrik Gücü",
      equation_text: "P = IV",
      summary: "Elektrik güç denklemlerini doğrular (P = VI = I^2R = V^2/R)",
      description:
         "Verilen V, I ve R değerleri için elektrik gücüne ilişkin üç yaygın denklemin eşdeğer olup olmadığını kontrol eder. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Elektrik gücü (Güç W)",
         V: "Gerilim (Gerilim V)",
         I: "Akım (Akım A)",
         R: "Direnç (Direnç Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "Seri Bağlı Dirençler",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "Seri bağlı dirençler için toplam direnci hesaplar (R_total = R1 + R2 + ...)",
      description: "Seri bağlı birden çok direnç için toplam eşdeğer direnci hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         R_total: "Toplam direnç (Direnç Ω)",
         R: "Bireysel direnç (Direnç Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "Paralel Bağlı Dirençler",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "Paralel bağlı dirençler için toplam direnci hesaplar (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "Paralel bağlı birden çok direnç için toplam eşdeğer direnci hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         R_total: "Toplam direnç (Direnç Ω)",
         R: "Bireysel direnç (Direnç Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "Seri Bağlı Kapasitörler",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "Seri bağlı kapasitörler için toplam kapasiteyi hesaplar (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "Seri bağlı birden çok kapasitör için toplam eşdeğer kapasiteyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C_total: "Toplam kapasite (Kapasite F)",
         C: "Bireysel kapasite (Kapasite F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "Paralel Bağlı Kapasitörler",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "Paralel bağlı kapasitörler için toplam kapasiteyi hesaplar (C_total = C1 + C2 + ...)",
      description: "Paralel bağlı birden çok kapasitör için toplam eşdeğer kapasiteyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         C_total: "Toplam kapasite (Kapasite F)",
         C: "Bireysel kapasite (Kapasite F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "Bir Yüke Etki Eden Manyetik Kuvvet",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "Yüklü bir parçacık üzerindeki manyetik kuvveti hesaplar (F = qvB sin(θ))",
      description:
         "Hareket eden yüklü bir parçacık üzerinde uygulanan manyetik kuvvetin büyüklüğünü hesaplar. Açı radyan cinsinden olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F_B: "Manyetik kuvvet büyüklüğü (Kuvvet N)",
         q: "Yük büyüklüğü (Yük C)",
         v: "Hız büyüklüğü (Hız m/s)",
         B: "Manyetik alan büyüklüğü (Manyetik Alan T)",
         θ: "Hız ve manyetik alan arasındaki açı (Açı rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "Bir Akıma Etki Eden Manyetik Kuvvet",
      equation_text: "F_B = ILBsin(θ)",
      summary: "Akım taşıyan bir iletken üzerindeki manyetik kuvveti hesaplar (F = I l B sin(θ))",
      description:
         "Manyetik alanda akım taşıyan düz bir iletken üzerinde uygulanan manyetik kuvvetin büyüklüğünü hesaplar. Açı radyan cinsinden olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F_B: "Manyetik kuvvet büyüklüğü (Kuvvet N)",
         I: "Akım (Akım A)",
         L: "İletken uzunluğu (Uzunluk m)",
         B: "Manyetik alan büyüklüğü (Manyetik Alan T)",
         θ: "Akım ve manyetik alan arasındaki açı (Açı rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "Biot-Savart Yasası",
      equation_text: "B = μ₀I / (2πr) (sonsuz düz tel)",
      summary: "Bir akım elementinden manyetik alanı hesaplar (dB = (μ₀I ds) / (4πr^2))",
      description:
         "Yarıçap vektörüne dik olan bir diferansiyel akım elementinin manyetik alana katkısının büyüklüğünü hesaplar. Not - Fonksiyon `(μ₀ * I * ds) / (4 * π * r^2)` formülünü uygular, diferansiyel formda sıklıkla bulunan sin(θ) terimini atlar, etkili bir şekilde θ=90 derece olduğunu varsayar veya yalnızca o belirli düzlemde yarıçap vektörüne dik olan bileşeni hesaplar. Uygulanan denklem belgelenmektedir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         dB: "Manyetik alan katkısının büyüklüğü (Manyetik Alan T)",
         μ0: "Boş alanın manyetik geçirgenliği (Sabit T·m/A)",
         I: "Akım (Akım A)",
         ds: "Akım elementinin diferansiyel uzunluğu (Uzunluk m)",
         r: "Akım elementinden mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "Bobin (Solenoit) Manyetik Alanı",
      equation_text: "B = μ₀nI (içinde, ideal)",
      summary: "Uzun bir bobinin (solenoit) içindeki manyetik alanı hesaplar (B = μ₀nI)",
      description: "Uzun bir ideal bobinin (solenoit) içindeki manyetik alanın büyüklüğünü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         B: "Bobin içindeki manyetik alan şiddeti (Manyetik Alan T)",
         μ0: "Boş alanın manyetik geçirgenliği (Sabit T·m/A)",
         n: "Birim uzunluk başına sarım sayısı (Uzunluk başına Sayı m⁻¹)",
         I: "Akım (Akım A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "Düz Telin Manyetik Alanı",
      equation_text: "B = μ₀I / (2πr) (sonsuz tel)",
      summary: "Sonsuz uzunluktaki düz bir telden manyetik alanı hesaplar (B = (μ₀I)/(2πr))",
      description:
         "Akım taşıyan uzun, düz bir iletkenden belirli bir mesafedeki manyetik alanın büyüklüğünü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         B: "Düz telden manyetik alan şiddeti (Manyetik Alan T)",
         μ0: "Boş alanın manyetik geçirgenliği (Sabit T·m/A)",
         I: "Akım (Akım A)",
         π: "Pi (Boyutsuz sabit)",
         r: "Telden mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "Paralel Teller Arasındaki Kuvvet",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "Paralel teller arasındaki birim uzunluk başına kuvveti hesaplar (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "Akım taşıyan iki uzun, paralel iletken arasındaki birim uzunluk başına düşen kuvvetin büyüklüğünü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         "F/L": "Birim uzunluk başına kuvvet (Uzunluk başına Kuvvet N/m)",
         μ0: "Boş alanın manyetik geçirgenliği (Sabit T·m/A)",
         I1: "Tel 1'deki akım (Akım A)",
         I2: "Tel 2'deki akım (Akım A)",
         π: "Pi (Boyutsuz sabit)",
         d: "Teller arasındaki mesafe (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "Elektrik Akısı",
      equation_text: "Φ_E = EAcos(θ) (düzgün E)",
      summary: "Elektrik akısını hesaplar (Φ_E = E * A * cos(θ))",
      description:
         "Düzgün bir elektrik alanındaki düz bir yüzeyden geçen elektrik akısını hesaplar. Açı, elektrik alan vektörü ile alan vektörü arasında, radyan cinsinden olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Φ_E: "Elektrik akısı (Elektrik Akısı N·m²/C)",
         E: "Elektrik alan büyüklüğü (Elektrik Alan N/C)",
         A: "Alan (Alan m²)",
         θ: "E ve alan vektörü arasındaki açı (Açı rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "Manyetik Akı",
      equation_text: "Φ_B = BAcos(θ) (düzgün B)",
      summary: "Manyetik akıyı hesaplar (Φ_B = B * A * cos(θ))",
      description:
         "Düzgün bir manyetik alandaki düz bir yüzeyden geçen manyetik akıyı hesaplar. Açı, manyetik alan vektörü ile alan vektörü arasında, radyan cinsinden olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Φ_B: "Manyetik akı (Manyetik Akı Wb)",
         B: "Manyetik alan büyüklüğü (Manyetik Alan T)",
         A: "Alan (Alan m²)",
         θ: "B ve alan vektörü arasındaki açı (Açı rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "Hareket EMK'sı",
      equation_text: "ε = vBL (düz iletken)",
      summary: "Hareket EMK'sını hesaplar (emf = Blv)",
      description:
         "Manyetik alana dik hareket eden bir iletkende indüklenen EMK'nın büyüklüğünü hesaplar. Not - Fonksiyon Blv büyüklüğünü hesaplar, yön için bazen kullanılan negatif işareti (Lenz Yasası) atlar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ε: "Hareket EMK'sı büyüklüğü (Gerilim V)",
         v: "İletken hızı (Hız m/s)",
         B: "Manyetik alan büyüklüğü (Manyetik Alan T)",
         L: "İletken uzunluğu (Uzunluk m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "İndüklenen EMK (Faraday Yasası)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "Değişen akıdan indüklenen EMK'yı hesaplar (emf = -ΔΦ_B / Δt)",
      description: "Faraday'ın İndüksiyon Yasasına göre değişen manyetik akı tarafından indüklenen EMK'yı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ε: "İndüklenen EMK (Gerilim V)",
         ΔΦ_B: "Manyetik akı değişimi (Manyetik Akı Wb)",
         Δt: "Zaman değişimi (Zaman s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "İndüktansdan İndüklenen EMK",
      equation_text: "ε_L = -L dI / dt",
      summary: "Bir indüktördeki değişen akımdan indüklenen EMK'yı hesaplar (emf = -L * ΔI / Δt)",
      description:
         "Bir indüktörde değişen akımdan kaynaklanan öz indüklenen EMK'yı hesaplar. Not - Fonksiyon `calculateInductance` olarak adlandırılmış ancak bu denklemi kullanarak EMK döndürür. Döndürdüğü şey belgelenmektedir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ε_L: "İndüktörde indüklenen EMK (Gerilim V)",
         L: "İndüktans (İndüktans H)",
         ΔI: "Akım değişimi (Akım A)",
         Δt: "Zaman değişimi (Zaman s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "Kapasitif Reaktans",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "Kapasitif reaktansı hesaplar (X_C = 1/(2πfC))",
      description: "Bir kapasitörün alternatif akıma karşı direncini hesaplar.",
language_code: "tr",
      subject: "Physics",
      variables: {
         X_C: "Kapasitif reaktans (Reaktans Ω)",
         π: "Pi (Boyutsuz sabit)",
         f: "Frekans (Frekans Hz)",
         C: "Kapasite (Kapasite F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "İndüktif Reaktans",
      equation_text: "X_L = 2πfL",
      summary: "İndüktif reaktansı hesaplar (X_L = 2πfL))",
      description: "Bir indüktörün alternatif akıma karşı direncini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         X_L: "İndüktif reaktans (Reaktans Ω)",
         π: "Pi (Boyutsuz sabit)",
         f: "Frekans (Frekans Hz)",
         L: "İndüktans (İndüktans H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "Empedans",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "Empedansı hesaplar (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "Direnç, indüktif reaktans ve kapasitif reaktans içeren bir AC devresindeki akım akışına karşı toplam direnci hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Z: "Empedans (Empedans Ω)",
         R: "Direnç (Direnç Ω)",
         X_L: "İndüktif reaktans (Reaktans Ω)",
         X_C: "Kapasitif reaktans (Reaktans Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "Yoğunluk",
      equation_text: "ρ = m / V",
      summary: "Yoğunluğu hesaplar (ρ = m/V)",
      description: "Kütle ve hacme dayalı olarak yoğunluğu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ρ: "Yoğunluk (Yoğunluk kg/m³)",
         m: "Kütle (Kütle kg)",
         V: "Hacim (Hacim m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "Basınç",
      equation_text: "P = F / A",
      summary: "Basıncı hesaplar (P = F/A)",
      description: "Bir alana uygulanan kuvvete dayalı olarak basıncı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Basınç (Basınç Pa)",
         F: "Kuvvet (Kuvvet N)",
         A: "Alan (Alan m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "Bir Akışkandaki Basınç",
      equation_text: "P = P₀ + ρgh",
      summary: "Bir akışkandaki basıncı hesaplar (P = P0 + ρgh)",
      description: "Bir akışkanda belirli bir derinlikteki mutlak basıncı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Mutlak basınç (Basınç Pa)",
         P0: "Atmosferik veya yüzey basıncı (Basınç Pa)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
         h: "Derinlik (Uzunluk m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "Kaldırma Kuvveti",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "Kaldırma kuvvetini hesaplar (F_b = ρgV_displaced)",
      description:
         "Bir akışkan tarafından batırılmış veya kısmen batırılmış bir nesneye uygulanan kaldırma kuvvetini hesaplar (Arşimet prensibi).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F_B: "Kaldırma kuvveti (Kuvvet N)",
         ρ_fluid: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         V_submerged: "Batırılmış hacim (Hacim m³)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "Kütlesel Akış Hızı",
      equation_text: "ṁ = ρAv",
      summary: "Kütlesel akış hızını hesaplar (ṁ = Δm/Δt)",
      description: "Birim zamanda bir noktadan geçen kütle oranını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ṁ: "Kütlesel akış hızı (Kütlesel Akış Hızı kg/s)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         A: "Alan (Alan m²)",
         v: "Akışkan hızı (Hız m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "Hacimsel Akış Hızı",
      equation_text: "Q = Av",
      summary: "Hacimsel akış hızını hesaplar (Q = ΔV/Δt)",
      description: "Birim zamanda bir noktadan geçen hacim oranını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Q: "Hacimsel akış hızı (Hacimsel Akış Hızı m³/s)",
         A: "Alan (Alan m²)",
         v: "Akışkan hızı (Hız m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "Bernoulli Denklemi",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "Bernoulli denklemini doğrular (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "İki noktada verilen akışkan özellikleri ve koşulları için Bernoulli denkleminin doğru olup olmadığını doğrular. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Basınç (Basınç Pa)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         v: "Akışkan hızı (Hız m/s)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
         y: "Yükseklik (Uzunluk m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "Dinamik Viskozite",
      equation_text: "τ = μ * (dv/dy)",
      summary: "Dinamik viskoziteyi hesaplar (η = F * Δy / (A * Δvx))",
      description:
         "Kuvvet, hız gradyanı ve alana dayalı olarak dinamik viskoziteyi hesaplar. Bu denklem kayma gerilmesi/gerinim oranından türetilmiştir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         μ: "Dinamik viskozite (Dinamik Viskozite Pa·s)",
         F: "Kuvvet (Kuvvet N)",
         Δy: "Akışa dik mesafe (Uzunluk m)",
         A: "Alan (Alan m²)",
         Δvx: "Hız değişimi (Hız m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "Kinematik Viskozite",
      equation_text: "ν = μ / ρ",
      summary: "Kinematik viskoziteyi hesaplar (ν = η / ρ)",
      description: "Dinamik viskozite ve yoğunluktan kinematik viskoziteyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ν: "Kinematik viskozite (Kinematik Viskozite m²/s)",
         μ: "Dinamik viskozite (Dinamik Viskozite Pa·s)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "Sürükleme Kuvveti",
      equation_text: "F_D = ½ρv²CdA",
      summary: "Sürükleme kuvvetini hesaplar (F_d = 0.5 * ρ * C_A * v^2)",
      description: "Bir akışkanda hareket eden bir nesne üzerindeki sürükleme kuvvetini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F_D: "Sürükleme kuvveti (Kuvvet N)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         v: "Hız (Hız m/s)",
         Cd: "Sürükleme katsayısı (Boyutsuz)",
         A: "Referans alanı (Alan m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "Mach Sayısı",
      equation_text: "M = v / c_sound",
      summary: "Mach sayısını hesaplar (M = v/c)",
      description: "Bir nesnenin hızı ile ortamdaki ses hızının oranı olan Mach sayısını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         M: "Mach sayısı (Boyutsuz)",
         v: "Nesne hızı (Hız m/s)",
         c_sound: "Ortamdaki ses hızı (Hız m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "Reynolds Sayısı",
      equation_text: "Re = ρvd / μ",
      summary: "Reynolds sayısını hesaplar (Re = (ρ * v * D) / η)",
      description:
         "Farklı akışkan akış durumlarında akış desenlerini tahmin etmek için kullanılan boyutsuz bir miktar olan Reynolds sayısını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Re: "Reynolds sayısı (Boyutsuz)",
         ρ: "Akışkan yoğunluğu (Yoğunluk kg/m³)",
         v: "Hız (Hız m/s)",
         d: "Karakteristik uzunluk (Uzunluk m)",
         μ: "Dinamik viskozite (Dinamik Viskozite Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "Froude Sayısı",
      equation_text: "Fr = v / √(gL)",
      summary: "Froude sayısını hesaplar (Fr = v / √(g * l))",
      description:
         "Yerçekiminin akışkan hareketine etkisini belirtmek için kullanılan boyutsuz bir miktar olan Froude sayısını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Fr: "Froude sayısı (Boyutsuz)",
         v: "Hız (Hız m/s)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
         L: "Karakteristik uzunluk (Uzunluk m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "Yüzey Gerilimi",
      equation_text: "γ = F / L",
      summary: "Yüzey gerilimini hesaplar (γ = F / l)",
      description: "Kuvvet ve uzunluğa dayalı olarak bir sıvının yüzey gerilimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         γ: "Yüzey gerilimi (Yüzey Gerilimi N/m)",
         F: "Kuvvet (Kuvvet N)",
         L: "Uzunluk (Uzunluk m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "Evrensel Kütleçekim (Kuvvet)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "Kütleçekim kuvvetini hesaplar (F = -Gm1m2/r^2)",
      description:
         "İki noktasal kütle arasındaki çekici kütleçekim kuvvetini hesaplar. Not - çekimi gösteren negatif bir değer döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F: "Kütleçekim kuvveti (Kuvvet N)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         m1: "Kütle 1 (Kütle kg)",
         m2: "Kütle 2 (Kütle kg)",
         r: "Kütleler arasındaki mesafe (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "Kütleçekim Alanı",
      equation_text: "g = GM / r² (büyüklük)",
      summary: "Kütleçekim alanını hesaplar (g = -Gm/r^2)",
      description:
         "Bir noktasal kütleden belirli bir mesafedeki kütleçekim alan şiddetini hesaplar. Not - kütleye doğru yönü gösteren negatif bir değer döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         g: "Kütleçekim alan şiddeti büyüklüğü (Kütleçekim Alanı N/kg)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         M: "Kaynak kütle (Kütle kg)",
         r: "Kaynak kütleden mesafe (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "Kütleçekim Potansiyel Enerjisi",
      equation_text: "U_g = -G m₁m₂ / r (genel)",
      summary: "İki kütle arasındaki kütleçekim potansiyel enerjisini hesaplar (PE = -Gm1m2/r)",
      description: "İki noktasal kütle sisteminin kütleçekim potansiyel enerjisini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         U_g: "Kütleçekim potansiyel enerjisi (Enerji J)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         m1: "Kütle 1 (Kütle kg)",
         m2: "Kütle 2 (Kütle kg)",
         r: "Kütleler arasındaki mesafe (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "Kütleçekim Potansiyeli",
      equation_text: "V_g = -GM / r",
      summary: "Kütleçekim potansiyelini hesaplar (V_g = -Gm/r)",
      description: "Bir noktasal kütleden belirli bir mesafedeki kütleçekim potansiyelini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         V_g: "Kütleçekim potansiyeli (Kütleçekim Potansiyeli J/kg)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         M: "Kaynak kütle (Kütle kg)",
         r: "Kaynak kütleden mesafe (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "Yörünge Hızı",
      equation_text: "v_orbit = √(GM / r) (dairesel)",
      summary: "Yörünge hızını hesaplar (v = sqrt(Gm/r))",
      description: "Daha büyük bir kütlenin etrafındaki dairesel bir yörüngede bulunan bir nesnenin hızını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_orbit: "Yörünge hızı (Hız m/s)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         M: "Merkez cisim kütlesi (Kütle kg)",
         r: "Yörünge yarıçapı (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "Kurtulma Hızı",
      equation_text: "v_escape = √(2GM / r)",
      summary: "Kurtulma hızını hesaplar (v = sqrt(2Gm/r))",
      description:
         "Belirli bir mesafeden bir kütlenin kütleçekiminden kurtulmak için gereken minimum hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_escape: "Kurtulma hızı (Hız m/s)",
         G: "Kütleçekim sabiti (Sabit N·m²/kg²)",
         M: "Merkez cisim kütlesi (Kütle kg)",
         r: "Merkezden mesafe (Uzunluk m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "Isı İletimi",
      equation_text: "Q/t = kAΔT/d",
      summary: "Isı iletim hızını hesaplar (Q/t = (kAΔT) / L)",
      description:
         "Bir madde boyunca iletim yoluyla ısı transfer hızını hesaplar. Not - Fonksiyon Q'yu hesaplar, zaman aralığının denklemin normalde hız için kullanımına bağlı olarak ima edildiği varsayılır. Dokümantasyon Q'yu belirtir, ancak denklem tipik olarak Q/t içindir. Bu farkı açıklığa kavuşturuyoruz. Fonksiyon, hız denkleminin sağ tarafının sonucunu döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         "Q/t": "Isı transfer hızı (Güç W)",
         k: "Isı iletkenliği (Isı İletkenliği W/(m·K))",
         A: "Alan (Alan m²)",
         ΔT: "Sıcaklık farkı (Sıcaklık Farkı K)",
         d: "Kalınlık (Uzunluk m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "Stefan-Boltzmann Yasası",
      equation_text: "P = εσAT⁴",
      summary: "Termal radyasyon gücünü hesaplar (P = εσA(T^4 - T0^4))",
      description: "Bir nesnenin ortamını dikkate alarak yayılan enerjinin net hızını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Net yayılan güç (Güç W)",
         ε: "Emisivite (Boyutsuz)",
         σ: "Stefan-Boltzmann sabiti (Sabit W/(m²·K⁴))",
         A: "Yüzey alanı (Alan m²)",
         T: "Nesne sıcaklığı (Sıcaklık K)",
         T0: "Çevre sıcaklığı (Sıcaklık K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "Wien Kaydırma Yasası (Maksimum Dalga Boyu)",
      equation_text: "λ_max = b/T",
      summary: "Wien Yasasını kullanarak tepe dalga boyunu hesaplar (λ_max = b/T)",
      description: "Siyah cismin emisyon spektrumunun maksimum olduğu dalga boyunu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         λ_max: "Tepe emisyon dalga boyu (Uzunluk m)",
         b: "Wien kaydırma sabiti (Sabit m·K)",
         T: "Sıcaklık (Sıcaklık K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "Wien Kaydırma Yasası (Maksimum Frekans)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "Wien Yasasını kullanarak tepe frekansını hesaplar (f_max = b' * T)",
      description:
         "Siyah cismin emisyon spektrumunun maksimum olduğu frekansı hesaplar. Not - Bu sürüm değiştirilmiş bir Wien sabiti b' kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f_max: "Tepe emisyon frekansı (Frekans Hz)",
         "b'": "Değiştirilmiş Wien sabiti (Sabit Hz/K)",
         T: "Sıcaklık (Sıcaklık K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "Denklem Bilgisi (Özel)",
      equation_text: "N/A (Bilgi alır, hesaplamaz)",
      summary: "ID ve dile göre denklem bilgisi al",
      description:
         "Belirli bir denklemin ayrıntılarını, benzersiz kimliğine ve istenen dile göre alır. Not - Dil, 'language_code' yol parametresinden çıkarılır. Kod snippetinde gösterilen iç mantık, 'lang' sorgu parametresini de inceler, ancak bu Swagger tanımı birincil yol parametrelerini belgeler.",
      language_code: "tr",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "API'deki tüm denklem uç noktalarını al.",
      description: "API'deki tüm uç noktalar hakkında özet bilgi alır.",
      language_code: "tr",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "Hız",
      equation_text: "v = Δx / Δt",
      summary: "Hızı hesaplar",
      description: "Yerdeğiştirme ve zamana dayalı olarak hızı hesaplar (v = Δs / Δt).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v: "Hız (Hız m/s)",
         Δx: "Yerdeğiştirme (Comprimento m)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "İvme",
      equation_text: "a = Δv / Δt",
      summary: "İvmeyi hesaplar",
      description: "Hız değişimine ve zamana dayalı olarak ivmeyi hesaplar (a = Δv / Δt).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         a: "İvme (İvme m/s²)",
         Δv: "Hız değişimi (Hız m/s)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "Kinematik Denklem (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "Son hızı hesaplar (v = v0 + at)",
      description: "İlk kinematik denklemi kullanarak son hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v: "Son hız (Hız m/s)",
         v0: "İlk hız (Hız m/s)",
         a: "İvme (İvme m/s²)",
         t: "Zaman (Zaman s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "Kinematik Denklem (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "Son konumu hesaplar (s = s0 + v0t + 0.5at^2)",
      description: "İkinci kinematik denklemi kullanarak son konumu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         s: "Son konum (Comprimento m)",
         s0: "İlk konum (Comprimento m)",
         v0: "İlk hız (Hız m/s)",
         t: "Zaman (Zaman s)",
         a: "İvme (İvme m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "Kinematik Denklem (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "Son hızın karesini hesaplar (v^2 = v0^2 + 2a(s - s0))",
      description: "Üçüncü kinematik denklemi kullanarak son hızın karesini hesaplar. Not - v'yi değil, v^2'yi döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v: "Son hız (Hız m/s)",
         v0: "İlk hız (Hız m/s)",
         a: "İvme (İvme m/s²)",
         Δs: "Yerdeğiştirme (Comprimento m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "Ortalama Hız",
      equation_text: "v_avg = Δx / Δt",
      summary: "Ortalama hızı hesaplar (v_avg = 0.5 * (v + v0))",
      description: "Sabit ivme varsayarak ortalama hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_avg: "Ortalama hız (Hız m/s)",
         v: "Son hız (Hız m/s)",
         v0: "İlk hız (Hız m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "Kuvvet (Newton'un İkinci Yasası)",
      equation_text: "F_net = ma",
      summary: "Kuvveti hesaplar (F = ma)",
      description: "Newton'un ikinci yasasını kullanarak kuvveti hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F_net: "Net kuvvet (Kuvvet N)",
         m: "Kütle (Kütle kg)",
         a: "İvme (İvme m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "Ağırlık",
      equation_text: "W = mg",
      summary: "Ağırlığı hesaplar (W = mg)",
      description: "Bir nesne üzerindeki yerçekimi kuvvetini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         W: "Ağırlık (Kuvvet N)",
         m: "Kütle (Kütle kg)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "Maksimum Statik Sürtünme",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "Maksimum statik sürtünmeyi hesaplar (F_s = μ_s * N)",
      description: "Mümkün olan maksimum statik sürtünme kuvvetini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f_s_max: "Maksimum statik sürtünme kuvveti (Kuvvet N)",
         μ_s: "Statik sürtünme katsayısı (Boyutsuz)",
         F_N: "Normal kuvvet (Kuvvet N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "Kinetik Sürtünme",
      equation_text: "f_k = μ_k * F_N",
      summary: "Kinetik sürtünmeyi hesaplar (F_k = μ_k * N)",
      description: "Hareket eden bir nesne üzerinde etki eden kinetik sürtünme kuvvetini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f_k: "Kinetik sürtünme kuvveti (Kuvvet N)",
         μ_k: "Kinetik sürtünme katsayısı (Boyutsuz)",
         F_N: "Normal kuvvet (Kuvvet N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "Momentum (Çizgisel Momentum)",
      equation_text: "p = mv",
      summary: "Momentumu hesaplar (p = mv)",
      description: "Bir nesnenin çizgisel momentumunu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         p: "Momentum (Momentum kg·m/s)",
         m: "Kütle (Kütle kg)",
         v: "Hız (Hız m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "İtme",
      equation_text: "J = F_avg * Δt",
      summary: "İtmeyi hesaplar (J = F * Δt)",
      description: "Kuvvet ve zaman aralığından itmeyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         J: "İtme (İtme N·s)",
         F_avg: "Ortalama kuvvet (Kuvvet N)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "İtme-Momentum Teoremi",
      equation_text: "J = Δp",
      summary: "İtme-momentum teoremini doğrular (F * Δt = m * Δv)",
      description: "Verilen değerler için itmenin momentum değişimine eşit olup olmadığını kontrol eder. Boolean döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         J: "İtme (İtme N·s)",
         Δp: "Momentum değişimi (Momentum kg·m/s)",
         F: "Kuvvet (Kuvvet N)",
         Δt: "Zaman aralığı (Zaman s)",
         m: "Kütle (Kütle kg)",
         Δv: "Hız değişimi (Hız m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "Radyoaktif Aktivite",
      equation_text: "A = λN",
      summary: "Radyoaktif bozunmada ortalama aktiviteyi hesaplar (A_avg = ΔN/Δt)",
      description:
         "Bir radyoaktif numunenin belirli bir zaman aralığındaki ortalama aktivitesini (bozunma hızı) hesaplar. Not - Fonksiyon, ΔN çekirdek sayısı için `nValue` ve Δt zaman için `tValue` kullanır. Bu, Δt üzerinden basitleştirilmiş bir ortalamadır, anlık aktivite dN/dt = -λN'dir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         A_avg: "Ortalama radyoaktif aktivite (Aktivite Bq)",
         ΔN: "Bozunma sayısı (Boyutsuz Sayı)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "Yarı Ömür",
      equation_text: "T_½ = ln(2) / λ",
      summary: "Bozunma sonrası kalan miktarı hesaplar (N = N0 * (1/2)^(t/T_half))",
      description:
         "Bir maddenin belirli bir süre sonra kalan miktarını yarı ömrüne dayalı olarak hesaplar. Not - Zaman için `tValue` ve yarı ömür için `Thalf` kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         N: "Kalan miktar/çekirdek (Sayı)",
         N0: "Başlangıç miktarı/çekirdek (Sayı)",
         t: "Geçen zaman (Zaman s)",
         T_half: "Yarı ömür (Zaman s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "Absorbe Edilen Radyasyon Dozu",
      equation_text: "D = dE / dm",
      summary: "Absorbe edilen radyasyon dozunu hesaplar (D = E/m)",
      description:
         "Bir kütle tarafından emilen enerjiye dayalı olarak absorbe edilen radyasyon dozunu hesaplar. Not - Enerji için `EValue` ve kütle için `mValue` kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         D: "Absorbe edilen doz (Absorbe Edilen Doz Gy)",
         E: "Absorbe edilen enerji (Enerji J)",
         m: "Kütle (Kütle kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "Eşdeğer Radyasyon Dozu",
      equation_text: "H = D * W_R",
      summary: "Eşdeğer radyasyon dozunu hesaplar (H = wR * D)",
      description:
         "Farklı radyasyon türlerinin biyolojik etkinliğini dikkate alarak eşdeğer dozu hesaplar. Not - Absorbe edilen doz için `DValue` kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         H: "Eşdeğer doz (Eşdeğer Doz Sv)",
         D: "Absorbe edilen doz (Absorbe Edilen Doz Gy)",
         W_R: "Radyasyon ağırlık faktörü (Boyutsuz)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "Etkin Radyasyon Dozu",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "Etkin radyasyon dozunu hesaplar (E = wT * H)",
      description:
         "Farklı doku/organların radyasyona karşı duyarlılığını dikkate alarak etkin dozu hesaplar. Not - Eşdeğer doz için `HValue` kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Etkin doz (Etkin Doz Sv)",
         H_T: "Doku/organ T için eşdeğer doz (Eşdeğer Doz Sv)",
         W_T: "Doku/organ T için doku ağırlık faktörü (Boyutsuz)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "Çerenkov Açısı",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "Çerenkov açısını hesaplar (θ_C = arccos(c/nv_p))",
      description:
         "Bir ortamda ışık hızından daha hızlı hareket eden yüklü bir parçacık tarafından oluşturulan Çerenkov konisinin açısını hesaplar. Açıyı radyan cinsinden döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         θ_C: "Çerenkov açısı (Açı rad)",
         c: "Vakumda ışık hızı (Hız m/s)",
         n: "Ortamın kırılma indisi (Boyutsuz)",
         v: "Parçacık hızı (Hız m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "Girişim Saçakları (örneğin, konum, aralık)",
      equation_text: "Δy = λL / d (çift yarık aralığı)",
      summary: "Girişim saçaklarının konumunu hesaplar (y_n = (nλL)/d)",
      description: "Young'ın çift yarık girişim deseninde n. parlak saçakın konumunu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         y_n: "n. parlak saçakın konumu (Uzunluk m)",
         n: "Saçak sırası (Boyutsuz Tamsayı)",
         λ: "Dalga boyu (Uzunluk m)",
         L: "Ekrana olan mesafe (Uzunluk m)",
         d: "Yarık ayrımı (Uzunluk m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "Kırılma İndisi",
      equation_text: "n = c / v",
      summary: "Kırılma indisini hesaplar (n = c/v)",
      description:
         "Bir ortamın kırılma indisini, vakumdaki ve ortamdaki ışık hızına dayalı olarak hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         n: "Kırılma indisi (Boyutsuz)",
         c: "Vakumda ışık hızı (Hız m/s)",
         v: "Ortamda ışık hızı (Hız m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "Snell Yasası",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "Snell Yasasını doğrular (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "Verilen kırılma indisleri ve açılara sahip iki ortam arasında ışığın geçerken Snell Yasasının geçerli olup olmadığını kontrol eder. Boolean döndürür. Açılar radyan cinsinden olmalıdır. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         n1: "Ortam 1'in kırılma indisi (Boyutsuz)",
         θ1: "Ortam 1'deki açı (Açı rad)",
         n2: "Ortam 2'nin kırılma indisi (Boyutsuz)",
         θ2: "Ortam 2'deki açı (Açı rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "Kritik Açı",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "Kritik açıyı hesaplar (θ_c = arcsin(n2/n1))",
      description:
         "Işık n1 indisli bir ortamdan n2 indisli bir ortama geçerken (n1 > n2) tam iç yansıma için kritik açıyı hesaplar. Açıyı radyan cinsinden döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         θ_c: "Kritik açı (Açı rad)",
         n1: "Ortam 1'in kırılma indisi (Boyutsuz)",
         n2: "Ortam 2'nin kırılma indisi (Boyutsuz)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "Görüntü Konumu (Optik)",
      equation_text: "1/f = 1/d_o + 1/d_i (İnce Mercek/Ayna)",
      summary: "İnce mercek/ayna denklemini doğrular (1/f = 1/do + 1/di)",
      description:
         "Odak uzaklığı, nesne mesafesi ve görüntü mesafesi arasındaki ilişkinin doğru olup olmadığını kontrol eder. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f: "Odak uzaklığı (Uzunluk m)",
         d_o: "Nesne mesafesi (Uzunluk m)",
         d_i: "Görüntü mesafesi (Uzunluk m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "Görüntü Boyutu (Büyütme - Optik)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "Büyütme denklemini doğrular (h'/h = di/do) (Fonksiyon h'/h = di/do kullanır)",
      description:
         "Nesne/görüntü yükseklikleri ve mesafeleri arasındaki ilişkinin doğru olup olmadığını kontrol eder. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır. Fonksiyon, işaretli büyütme denklemi yerine `h'/h = di/do` büyüklük ilişkisini kullanır. Fonksiyon uygulamasına dayalı olarak belgelemektedir. Gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         M: "Büyütme (Boyutsuz)",
         h_i: "Görüntü yüksekliği (Uzunluk m)",
         h_o: "Nesne yüksekliği (Uzunluk m)",
         d_i: "Görüntü mesafesi (Uzunluk m)",
         d_o: "Nesne mesafesi (Uzunluk m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "Küresel Ayna Denklemi",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "Küresel bir aynanın odak uzaklığını hesaplar (f = r/2)",
      description: "Küresel bir aynanın odak uzaklığını eğrilik yarıçapına dayalı olarak hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f: "Odak uzaklığı (Uzunluk m)",
         r: "Eğrilik yarıçapı (Uzunluk m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "Yay Potansiyel Enerjisi",
      equation_text: "U_s = ½kx²",
      summary: "Bir yaydaki potansiyel enerjiyi hesaplar (PE = 0.5 * k * Δx^2)",
      description: "İdeal bir yayda depolanan elastik potansiyel enerjiyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         U_s: "Yay potansiyel enerjisi (Enerji J)",
         k: "Yay sabiti (Yay Sabiti N/m)",
         x: "Denge noktasından yer değiştirme (Uzunluk m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "Basit Harmonik Osilatör (BHO) Periyodu",
      equation_text: "T = 2π√(m/k)",
      summary: "Bir kütle-yay BHO'nun periyodunu hesaplar (T = 2π√(m/k))",
      description:
         "Bir yay üzerindeki bir kütleden oluşan basit harmonik osilatör için salınım periyodunu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         T: "Periyot (Zaman s)",
         π: "Pi (Boyutsuz sabit)",
         m: "Kütle (Kütle kg)",
         k: "Yay sabiti (Yay Sabiti N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "Basit Sarkaç Periyodu",
      equation_text: "T = 2π√(L/g)",
      summary: "Basit sarkaç periyodunu hesaplar (T = 2π√(l/g))",
      description: "Küçük açılarda basit bir sarkaç için salınım periyodunu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         T: "Periyot (Zaman s)",
         π: "Pi (Boyutsuz sabit)",
         L: "Sarkaç uzunluğu (Uzunluk m)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "Frekans",
      equation_text: "f = 1 / T",
      summary: "Frekansı hesaplar (f = 1/T)",
      description: "Salınım periyodundan frekansı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f: "Frekans (Frekans Hz)",
         T: "Periyot (Zaman s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "Açısal Frekans",
      equation_text: "ω = 2πf",
      summary: "Açısal frekansı hesaplar (ω = 2πf)",
      description: "Frekansdan açısal frekansı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ω: "Açısal frekans (Açısal Hız rad/s)",
         π: "Pi (Boyutsuz sabit)",
         f: "Frekans (Frekans Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "Lorentz Faktörü",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "Lorentz faktörünü hesaplar (γ)",
      description: "γ = 1/√(1 - (v²/c²)) formülünü kullanarak Lorentz faktörünü hesaplar. v < c olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         γ: "Lorentz faktörü (Boyutsuz)",
         v: "Hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "Zaman Genişlemesi",
      equation_text: "Δt' = γ * Δt₀",
      summary: "Zaman genişlemesini hesaplar (t' = γ * t₀)",
      description:
         "S atalet referans çerçevesindeki bir gözlemci için geçen zamanı (t') hesaplar, S' hareketli çerçevesinde ölçülen uygun zaman (t₀) ve S ile S' arasındaki bağıl hız (v) verildiğinde. t' = t₀ / √(1 - (v²/c²)) denklemini kullanır. t₀ ≥ 0 ve |v| ≤ c olmalıdır. t' birimleri t₀ ile aynı olacak, v ve c birimleri tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Δt: "Genişlemiş zaman (Zaman s)",
         Δt0: "Uygun zaman (Zaman s)",
         v: "Bağıl hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "Uzunluk Büzülmesi",
      equation_text: "L' = L₀ / γ",
      summary: "Uzunluk büzülmesini hesaplar (L' = L₀ / γ)",
      description:
         "Bir nesnenin S' hareketli çerçevesinden gözlemlenen uzunluğunu (L') hesaplar, onun S duran çerçevesinde ölçülen uygun uzunluğu (L₀) ve S ile S' arasındaki bağıl hız (v) verildiğinde. L' = L₀ * √(1 - (v²/c²)) denklemini kullanır. L₀ ≥ 0 ve |v| ≤ c olmalıdır. L' birimleri L₀ ile aynı olacak, v ve c birimleri tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         L: "Büzülmüş uzunluk (Uzunluk m)",
         L0: "Uygun uzunluk (Uzunluk m)",
         v: "Bağıl hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "Relativistik Hız Toplamı",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "Relativistik hız toplamını hesaplar",
      description:
         "Bir nesnenin S' çerçevesine göre hızını (u') hesaplar, onun S çerçevesine göre hızı (u) ve S çerçevesinin S' çerçevesine göre hızı (v) verildiğinde. u' = (u + v) / (1 + uv/c²) denklemini kullanır. Hareketin aynı çizgi üzerinde olduğunu varsayar. c ≠ 0 olmalıdır. u, v ve c birimleri tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         u: "Nesnenin S çerçevesindeki hızı (Hız m/s)",
         v: "S'e göre S çerçevesinin hızı (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
         "u'": "S' çerçevesine göre nesnenin hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "Relativistik Toplam Enerji",
      equation_text: "E = γmc²",
      summary: "Relativistik toplam enerjiyi hesaplar (E)",
      description:
         "Durgun kütleli (m) ve v hızıyla hareket eden bir parçacığın toplam relativistik enerjisini hesaplar. E = γmc² = mc² / √(1 - (v²/c²)) denklemini kullanır. Esasen durgun kütleli parçacıklar (m > 0) için kullanılır. m ≥ 0 ve |v| ≤ c olmalıdır. m, v ve c birimleri uygun birimlerde enerji elde etmek için tutarlı olmalıdır (örn. m kg cinsinden, v/c m/s cinsinden verildiğinde E Joule cinsinden olur).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Toplam relativistik enerji (Enerji J)",
         m: "Durgun kütle (Kütle kg)",
         v: "Hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "Relativistik Momentum",
      equation_text: "p = γmv",
      summary: "Relativistik momentumu hesaplar (p = γmv)",
      description:
         "Durgun kütleli (m) ve v hızıyla hareket eden bir parçacığın relativistik momentumunu hesaplar. p = γmv = mv / √(1 - (v²/c²)) denklemini kullanır. Esasen durgun kütleli parçacıklar (m > 0) için kullanılır. m ≥ 0 ve |v| ≤ c olmalıdır. m, v ve c birimleri uygun birimlerde momentum elde etmek için tutarlı olmalıdır (örn. m kg cinsinden, v m/s cinsinden, c m/s cinsinden verildiğinde p kg·m/s cinsinden olur).",
      language_code: "tr",
      subject: "Physics",
      variables: {
         p: "Relativistik momentum (Momentum kg·m/s)",
         m: "Durgun kütle (Kütle kg)",
         v: "Hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "Enerji-Momentum İlişkisi",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "Momentum ve durgun kütleden toplam enerjiyi hesaplar (E)",
      description:
         "Bir parçacığın toplam relativistik enerjisini, relativistik momentumundan (p) ve durgun kütlesinden (m) hesaplar. Enerji-momentum ilişkisini kullanır: E² = (pc)² + (mc²)². Bu denklem hem kütleli (m > 0) hem de kütlesiz (m = 0) parçacıklar için geçerlidir. p ≥ 0, m ≥ 0 ve c > 0 olmalıdır. p, m ve c birimleri tutarlı olmalıdır.\n",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Toplam relativistik enerji (Enerji J)",
         p: "Relativistik momentum (Momentum kg·m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
         m: "Durgun kütle (Kütle kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "Kütle-Enerji Eşdeğerliği (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "Kütle-enerji eşdeğerliğini hesaplar (E₀ = mc²)",
      description:
         "Verilen durgun kütlenin (m) eşdeğer durgun enerjisini (E₀), Einstein'ın ünlü E₀ = mc² denklemini kullanarak hesaplar. m ≥ 0 ve c > 0 olmalıdır. m ve c birimleri tutarlı olmalıdır (örn. m kg cinsinden, c m/s cinsinden verildiğinde E₀ Joule cinsinden olur). Bu uç nokta, 'c' açıkça belirtilmedikçe c için standart bir değer (yaklaşık 299792458 m/s) kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E0: "Durgun enerji (Enerji J)",
         m: "Durgun kütle (Kütle kg)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "Relativistik Kinetik Enerji",
      equation_text: "KE = (γ - 1)mc²",
      summary: "Relativistik kinetik enerjiyi hesaplar (KE)",
      description:
         "Durgun kütleli (m) ve v hızıyla hareket eden bir parçacığın relativistik kinetik enerjisini hesaplar. KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc² denklemini kullanır. Esasen durgun kütleli parçacıklar (m > 0) için kullanılır. m ≥ 0 ve |v| < c olmalıdır. m, v ve c birimleri uygun birimlerde enerji elde etmek için tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE: "Relativistik kinetik enerji (Enerji J)",
         m: "Durgun kütle (Kütle kg)",
         v: "Hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "Relativistik Doppler Etkisi (Dalga Boyu)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "Dalga boyu için relativistik boyuna Doppler etkisini hesaplar",
      description:
         "Bir kaynaktan, gözlemciden doğrudan uzaklaşan veya yaklaşan bağıl hızla (v_rel) hareket eden, uygun dalga boyu (λ₀) ile yayılan ışığın gözlemlenen dalga boyunu (λ') hesaplar. λ' = λ₀√((1 + β)/(1 - β)) denklemini kullanır, burada β = v_rel/c'dir. v_rel > 0 gerileme (kırmızıya kayma) için, v_rel < 0 yaklaşım (maviye kayma) içindir. λ₀ > 0 ve |v_rel| < c olmalıdır. λ' birimleri λ₀ ile aynı olacaktır, v_rel ve c birimleri tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         "λ'": "Gözlemlenen dalga boyu (Uzunluk m)",
         λ0: "Uygun dalga boyu (Uzunluk m)",
         v: "Bağıl hız (Hız m/s)",
         c: "Vakumda ışık hızı (Hız m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "Foton Enerjisi (Frekansdan)",
      equation_text: "E = hf",
      summary: "Frekansdan foton enerjisini hesaplar (E = hf)",
      description:
         "Bir fotonun enerjisini (E) frekansına (f) dayalı olarak hesaplar. Planck ilişkisi E = hf'yi kullanır. f ≥ 0 ve h > 0 olmalıdır. h ve f birimleri uygun birimlerde enerji elde etmek için tutarlı olmalıdır (örn. h J·s cinsinden, f Hz (s⁻¹) cinsinden verildiğinde E Joule cinsinden olur). Bu uç nokta, 'h' açıkça belirtilmedikçe h için standart bir değer (yaklaşık 6.626e-34 J·s) kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Foton enerjisi (Enerji J)",
         h: "Planck sabiti (Sabit J·s)",
         f: "Frekans (Frekans Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "Foton Momenti (Dalga Boyundan)",
      equation_text: "p = h / λ",
      summary: "Dalga boyundan foton momentini hesaplar (p = h/λ)",
      description:
         "Bir fotonun momentumunu (p) dalga boyuna (λ) dayalı olarak hesaplar. p = h/λ ilişkisini kullanır. λ > 0 ve h > 0 olmalıdır. h ve λ birimleri uygun birimlerde momentum elde etmek için tutarlı olmalıdır (örn. h J·s cinsinden, λ metre cinsinden verildiğinde p kg·m/s cinsinden olur). Bu uç nokta, 'h' açıkça belirtilmedikçe h için standart bir değer (yaklaşık 6.626e-34 J·s) kullanır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         p: "Foton momenti (Momentum kg·m/s)",
         h: "Planck sabiti (Sabit J·s)",
         λ: "Dalga boyu (Uzunluk m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "Fotoelektrik Etki (Maksimum KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "Fotoelektrik etkide maksimum kinetik enerjiyi hesaplar (KE_max)",
      description:
         "Fotoelektrik etkide yayılan elektronların maksimum kinetik enerjisini (KE_max) hesaplar. KE_max = E_photon - φ denklemini kullanır, burada E_photon gelen foton enerjisi ve φ malzemenin iş fonksiyonudur. Eğer E_photon ≤ φ ise, elektronlar yayılmaz ve KE_max 0 olur. E_photon ≥ 0 ve φ ≥ 0 olmalıdır. E_photon ve φ birimleri KE_max'ı aynı birimlerde elde etmek için tutarlı olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE_max: "Maksimum elektron kinetik enerjisi (Enerji J)",
         E_photon: "Foton enerjisi (Enerji J)",
         φ: "İş fonksiyonu (Enerji J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "Rydberg Denklemi (Atomik Geçiş)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "Hidrojen benzeri atom geçişleri için enerji veya dalga sayısı hesaplar",
      description:
         "Hidrojen benzeri bir atomdaki (Z) iki enerji seviyesi arasındaki bir elektron geçişi için enerji farkını (ΔE) veya dalga sayısını (1/λ) hesaplar. Sonuç = Sabit * Z² * (1/n_initial² - 1/n_final²) denklemini kullanır. Eğer 'Sabit' Rydberg enerji birimi ise (örn. eV cinsinden), sonuç enerji farkı E_final - E_initial'dır (absorpsiyon için pozitif, emisyon için negatif). Eğer 'Sabit' dalga sayısı için Rydberg sabiti ise (örn. m⁻¹ cinsinden), sonuç dalga sayısı 1/λ'dır (emisyon için pozitif, absorpsiyon için negatif). nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (tam sayılar) ve Sabit > 0 olmalıdır.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔE: "Enerji farkı (Enerji J)",
         R_y: "Rydberg sabiti (Sabit J veya ters uzunluk m⁻¹)",
         Z: "Atom numarası (Boyutsuz Tam Sayı)",
         n1: "Başlangıç ana kuantum sayısı (Boyutsuz Tam Sayı)",
         n2: "Son ana kuantum sayısı (Boyutsuz Tam Sayı)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "Açısal Hız",
      equation_text: "ω = Δθ / Δt",
      summary: "Açısal hızı hesaplar (ω = Δθ / Δt)",
      description: "Açı ve zaman değişimine dayalı olarak açısal hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ω: "Açısal hız (Açısal Hız rad/s)",
         Δθ: "Açısal yer değiştirme (Açı rad)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "Açısal İvme",
      equation_text: "α = Δω / Δt",
      summary: "Açısal ivmeyi hesaplar (α = Δω / Δt)",
      description: "Açısal hız değişimine ve zamana dayalı olarak açısal ivmeyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         α: "Açısal ivme (Açısal İvme rad/s²)",
         Δω: "Açısal hız değişimi (Açısal Hız rad/s)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "Dönme Kinematiği (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "Son açısal hızı hesaplar (ω = ω0 + αt)",
      description: "Dönme kinematiği birinci denklemini kullanarak son açısal hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ω: "Son açısal hız (Açısal Hız rad/s)",
         ω0: "İlk açısal hız (Açısal Hız rad/s)",
         α: "Açısal ivme (Açısal İvme rad/s²)",
         t: "Zaman (Zaman s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "Dönme Kinematiği (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "Açısal konumu hesaplar (θ = θ0 + ω0t + 0.5αt^2)",
      description: "Dönme kinematiği ikinci denklemini kullanarak açısal konumu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         θ: "Son açısal konum (Açı rad)",
         θ0: "İlk açısal konum (Açı rad)",
         ω0: "İlk açısal hız (Açısal Hız rad/s)",
         t: "Zaman (Zaman s)",
         α: "Açısal ivme (Açısal İvme rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "Dönme Kinematiği (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "Açısal hızın karesini hesaplar (ω^2 = ω0^2 + 2α(θ - θ0))",
      description: "Dönme kinematiği üçüncü denklemini kullanarak açısal hızın karesini hesaplar. Not - ω değil, ω^2 döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ω: "Son açısal hız (Açısal Hız rad/s)",
         ω0: "İlk açısal hız (Açısal Hız rad/s)",
         α: "Açısal ivme (Açısal İvme rad/s²)",
         Δθ: "Açısal yer değiştirme (Açı rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "Ortalama Açısal Hız",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "Ortalama açısal hızı hesaplar (ω_avg = 0.5 * (ω + ω0))",
      description: "Sabit açısal ivme varsayarak ortalama açısal hızı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ω_avg: "Ortalama açısal hız (Açısal Hız rad/s)",
         ω: "Son açısal hız (Açısal Hız rad/s)",
         ω0: "İlk açısal hız (Açısal Hız rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "Tork",
      equation_text: "τ = rFsin(θ)",
      summary: "Torku hesaplar (τ = rF sin(θ))",
      description: "Yarıçap, kuvvet ve aralarındaki açıya dayalı olarak torku hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         τ: "Tork (Tork N·m)",
         r: "Kuvvet kolu (Comprimento m)",
         F: "Kuvvet (Kuvvet N)",
         θ: "Kuvvet ve kuvvet kolu arasındaki açı (Açı rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "Newton'un İkinci Yasası (Dönme)",
      equation_text: "τ_net = Iα",
      summary: "Dönme 2. Yasasını kullanarak torku hesaplar (τ = Iα)",
      description: "Eylemsizlik momenti ve açısal ivmeye dayalı olarak torku hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         τ_net: "Net tork (Tork N·m)",
         I: "Eylemsizlik momenti (Eylemsizlik Momenti kg·m²)",
         α: "Açısal ivme (Açısal İvme rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "Eylemsizlik Momenti",
      equation_text: "I = mr² (nokta kütle)",
      summary: "Nokta kütle için eylemsizlik momentini hesaplar (I = mr^2)",
      description: "Bir eksene göre tek bir nokta kütle için eylemsizlik momentini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         I: "Eylemsizlik momenti (Eylemsizlik Momenti kg·m²)",
         m: "Kütle (Kütle kg)",
         r: "Eksen uzaklığı (Uzunluk m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "Dönme İşi",
      equation_text: "W = τΔθ (sabit tork)",
      summary: "Dönme işini hesaplar (W = τΔθ)",
      description: "Sabit bir torkun açısal bir yer değiştirme boyunca yaptığı işi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         W: "Dönme işi (Enerji J)",
         τ: "Tork (Tork N·m)",
         Δθ: "Açısal yer değiştirme (Açı rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "Dönme Gücü",
      equation_text: "P = τω",
      summary: "Dönme gücünü hesaplar (P = τω cos(θ))",
      description:
         "Tork, açısal hız ve aralarındaki açıya dayalı olarak anlık dönme gücünü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Dönme gücü (Güç W)",
         τ: "Tork (Tork N·m)",
         ω: "Açısal hız (Açısal Hız rad/s)",
         θ: "Tork ve açısal hız arasındaki açı (Açı rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "Dönme Kinetik Enerjisi",
      equation_text: "KE_rot = ½Iω²",
      summary: "Dönme kinetik enerjisini hesaplar (KE = 0.5Iω^2)",
      description: "Dönen bir nesnenin kinetik enerjisini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE_rot: "Dönme kinetik enerjisi (Enerji J)",
         I: "Eylemsizlik momenti (Eylemsizlik Momenti kg·m²)",
         ω: "Açısal hız (Açısal Hız rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "Açısal Momentum",
      equation_text: "L = Iω",
      summary: "Açısal momentumu hesaplar (L = mrv sin(θ))",
      description: "Bir noktaya göre hareket eden bir nokta kütle için açısal momentumu hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         L: "Açısal momentum (Açısal Momentum kg·m²/s)",
         m: "Kütle (Kütle kg)",
         r: "Eksen/noktadan mesafe (Uzunluk m)",
         v: "Hız (Hız m/s)",
         θ: "Yarıçap vektörü ile hız arasındaki açı (Açı rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "Açısal İtme",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "Açısal itmeyi hesaplar (J = τΔt)",
      description: "Tork ve zaman aralığından açısal itmeyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         J_angular: "Açısal itme (Açısal İtme N·m·s)",
         τ_avg: "Ortalama tork (Tork N·m)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "Elastisite Modülü (Young Modülü)",
      equation_text: "E = σ / ε",
      summary: "Elastisite Modülünü (Young Modülü) hesaplar (E = (F * L0) / (A * ΔL))",
      description: "Çekme veya basma gerilmesi altındaki bir malzemenin Elastisite Modülünü (Young Modülü) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         E: "Elastisite Modülü (Basınç Pa)",
         F: "Kuvvet (Kuvvet N)",
         L0: "Orijinal uzunluk (Uzunluk m)",
         A: "Kesit alanı (Alan m²)",
         ΔL: "Uzunluk değişimi (Uzunluk m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "Kesme Modülü",
      equation_text: "G = τ / γ",
      summary: "Kesme modülünü hesaplar (G = (F * y) / (A * Δx))",
      description: "Kesme gerilmesi altındaki bir malzemenin kesme modülünü (rijitlik modülü) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         G: "Kesme modülü (Basınç Pa)",
         F: "Kuvvet (Kuvvet N)",
         y: "Kuvvete dik mesafe (Uzunluk m)",
         A: "Alan (Alan m²)",
         Δx: "Yerdeğiştirme (Uzunluk m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "Hacimsel Modül",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "Hacimsel modülü hesaplar (K = (F * V0) / (A * ΔV))",
      description: "Düzgün basınç (hidrostatik gerilme) altındaki bir malzemenin hacimsel modülünü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         K: "Hacimsel modül (Basınç Pa)",
         ΔP: "Basınç değişimi (Basınç Pa)",
         ΔV: "Hacim değişimi (Hacim m³)",
         V0: "Orijinal hacim (Hacim m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "Hooke Yasası",
      equation_text: "F = kx",
      summary: "Bir yayın kuvvetini hesaplar (F = -k * Δx)",
      description:
         "Hooke Yasasına göre ideal bir yayın uyguladığı geri çağırıcı kuvveti hesaplar. Not - yer değiştirmeye karşı gelen kuvveti gösteren negatif bir değer döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         F: "Kuvvet (Kuvvet N)",
         k: "Yay sabiti (Yay Sabiti N/m)",
         x: "Denge noktasından yer değiştirme (Uzunluk m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "Katı Termal Genleşme (Uzunluk)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "Katı doğrusal termal genleşmeyi hesaplar (ΔL = αL0ΔT)",
      description: "Bir katı malzemenin sıcaklık değişiminden dolayı uzunluk değişimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔL: "Uzunluk değişimi (Uzunluk m)",
         α: "Doğrusal genleşme katsayısı (Sıcaklık başına Katsayı K⁻¹)",
         L0: "Orijinal uzunluk (Uzunluk m)",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "Katı Termal Genleşme (Alan)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "Katı alan termal genleşmeyi hesaplar (ΔA = 2αA0ΔT)",
      description:
         "Doğrusal genleşme katsayısı kullanılarak bir katı malzemenin sıcaklık değişiminden dolayı alan değişimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔA: "Alan değişimi (Alan m²)",
         α: "Doğrusal genleşme katsayısı (Sıcaklık başına Katsayı K⁻¹)",
         A0: "Orijinal alan (Alan m²)",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "Katı Termal Genleşme (Hacim)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "Katı hacim termal genleşmeyi hesaplar (ΔV = 3αV0ΔT)",
      description:
         "Doğrusal genleşme katsayısı kullanılarak bir katı malzemenin sıcaklık değişiminden dolayı hacim değişimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔV: "Hacim değişimi (Hacim m³)",
         α: "Doğrusal genleşme katsayısı (Sıcaklık başına Katsayı K⁻¹)",
         V0: "Orijinal hacim (Hacim m³)",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "Sıvı Termal Genleşme",
      equation_text: "ΔV = βV₀ΔT",
      summary: "Sıvı termal genleşmeyi hesaplar (ΔV = βV0ΔT)",
      description: "Bir sıvının sıcaklık değişiminden dolayı hacim değişimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔV: "Hacim değişimi (Hacim m³)",
         β: "Hacimsel genleşme katsayısı (Sıcaklık başına Katsayı K⁻¹)",
         V0: "Orijinal hacim (Hacim m³)",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "Duyulur Isı",
      equation_text: "Q = mcΔT",
      summary: "Duyulur ısıyı hesaplar (Q = mcΔT)",
      description: "Bir maddenin sıcaklık değişimine neden olan aktarılan ısıyı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Q: "Duyulur ısı (Enerji J)",
         m: "Kütle (Kütle kg)",
         c: "Özgül ısı kapasitesi (Özgül Isı Kapasitesi J/(kg·K))",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "Gizli Isı",
      equation_text: "Q = mL",
      summary: "Gizli ısıyı hesaplar (Q = mL)",
      description: "Bir maddenin faz değişimi sırasında aktarılan ısıyı hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Q: "Gizli ısı (Enerji J)",
         m: "Kütle (Kütle kg)",
         L: "Gizli ısı (Özgül Enerji J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "İdeal Gaz Yasası",
      equation_text: "PV = nRT",
      summary: "İdeal Gaz Yasasını doğrular (PV = nRT)",
      description:
         "Verilen parametreler için İdeal Gaz Yasası denkleminin doğru olup olmadığını kontrol eder. Boolean döndürür. Not - Kayan nokta hassasiyetine duyarlı olabilen katı eşitlik (===) kullanır; gerçek dünya kontrolleri için tolerans düşünülmelidir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Basınç (Basınç Pa)",
         V: "Hacim (Hacim m³)",
         n: "Mol sayısı (Madde Miktarı mol)",
         R: "İdeal gaz sabiti (Sabit J/(mol·K))",
         T: "Sıcaklık (Sıcaklık K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "Moleküler Kinetik Enerji",
      equation_text: "KE_avg = (3/2)kT",
      summary: "Ortalama moleküler kinetik enerjiyi hesaplar (KE = (3/2)kT)",
      description: "İdeal bir gazın molekül başına ortalama öteleme kinetik enerjisini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE_avg: "Ortalama moleküler kinetik enerji (Enerji J)",
         k: "Boltzmann sabiti (Sabit J/K)",
         T: "Sıcaklık (Sıcaklık K)",
         m: "Tek bir molekülün kütlesi (Kütle kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "Moleküler Hız (En Olası)",
      equation_text: "v_p = √(2kT/m)",
      summary: "En olası moleküler hızı hesaplar (v_p = √(2kT/m))",
      description:
         "Maxwell-Boltzmann dağılımına göre ideal bir gazdaki moleküllerin en olası hızını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_p: "En olası moleküler hız (Hız m/s)",
         k: "Boltzmann sabiti (Sabit J/K)",
         T: "Sıcaklık (Sıcaklık K)",
         m: "Tek bir molekülün kütlesi (Kütle kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "Moleküler Hız (Ortalama)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "Ortalama moleküler hızı hesaplar (v_avg = √(8kT/(πm)))",
      description:
         "Maxwell-Boltzmann dağılımına göre ideal bir gazdaki moleküllerin ortalama hızını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_avg: "Ortalama moleküler hız (Hız m/s)",
         k: "Boltzmann sabiti (Sabit J/K)",
         T: "Sıcaklık (Sıcaklık K)",
         π: "Pi (Boyutsuz sabit)",
         m: "Tek bir molekülün kütlesi (Kütle kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "Moleküler Hız (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "Karekök ortalama kare moleküler hızını hesaplar (v_rms = √(3kT/m))",
      description:
         "Maxwell-Boltzmann dağılımına göre ideal bir gazdaki moleküllerin karekök ortalama kare hızını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v_rms: "Karekök ortalama kare moleküler hız (Hız m/s)",
         k: "Boltzmann sabiti (Sabit J/K)",
         T: "Sıcaklık (Sıcaklık K)",
         m: "Tek bir molekülün kütlesi (Kütle kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "İç Enerji Değişimi",
      equation_text: "ΔU = Q - W",
      summary: "İdeal tek atomlu gaz için iç enerji değişimini hesaplar (ΔU = (3/2)nRΔT)",
      description:
         "Sıcaklık değişimine uğrayan tek atomlu ideal bir gazın iç enerji değişimini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         ΔU: "İç enerji değişimi (Enerji J)",
         n: "Mol sayısı (Madde Miktarı mol)",
         R: "İdeal gaz sabiti (Sabit J/(mol·K))",
         ΔT: "Sıcaklık değişimi (Sıcaklık Farkı K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "Termodinamik İş",
      equation_text: "W = PΔV (sabit basınç)",
      summary: "Sabit basınçta sistem tarafından yapılan termodinamik işi hesaplar (W = -PΔV)",
      description:
         "Sabit basınçta bir termodinamik işlem sırasında sistem tarafından yapılan veya sisteme yapılan işi hesaplar. Not - Denklem, sistem tarafından yapılan işi hesaplar, genişleme için pozitif, sıkıştırma için negatif. Fonksiyon -P*deltaV döndürür, bu W = PΔV denklemine göre sistem tarafından yapılan iş ile tutarlıdır, ancak konvensiyona bağlı olarak sisteme yapılan işi ima edebilecek bir eksi işareti eklenmiştir. Fonksiyonun çıktısı belgelenmektedir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         W: "Termodinamik iş (Enerji J)",
         P: "Basınç (Basınç Pa)",
         ΔV: "Hacim değişimi (Hacim m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "Gerçek Verimlilik",
      equation_text: "η = W_out / Q_in",
      summary: "Gerçek bir motorun verimliliğini hesaplar (η_real = 1 - (Q_C / Q_H))",
      description: "Emilen ve reddedilen ısıya dayalı olarak bir ısı motorunun termik verimliliğini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         η: "Verimlilik (Boyutsuz)",
         Q_H: "Sıcak rezervuardan emilen ısı (Enerji J)",
         Q_C: "Soğuk rezervuara reddedilen ısı (Enerji J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "İdeal Verimlilik",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "İdeal verimliliği (Carnot) hesaplar (η_ideal = 1 - (T_C / T_H))",
      description:
         "İki sıcaklık arasında çalışan bir ısı motorunun maksimum teorik verimliliğini (Carnot verimliliği) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         η_ideal: "İdeal verimlilik (Boyutsuz)",
         T_hot: "Sıcak rezervuar sıcaklığı (Sıcaklık K)",
         T_cold: "Soğuk rezervuar sıcaklığı (Sıcaklık K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "Gerçek Performans Katsayısı (COP)",
      equation_text: "COP_ref = Q_c / W (Buzdolabı)",
      summary: "Gerçek bir buzdolabının performans katsayısını hesaplar (COP_real = QC / (QH - QC))",
      description: "Gerçek bir buzdolabı veya ısı pompasının performans katsayısını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         COP_real: "Performans katsayısı (Boyutsuz)",
         Q_C: "Soğuk rezervuardan ısı (Enerji J)",
         Q_H: "Sıcak rezervuara ısı (Enerji J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "İdeal Performans Katsayısı (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "İdeal bir buzdolabının performans katsayısını hesaplar (COP_ideal = TC / (TH - TC))",
      description:
         "İki sıcaklık arasında çalışan bir buzdolabı veya ısı pompasının maksimum teorik performans katsayısını hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         COP_ideal: "İdeal performans katsayısı (Boyutsuz)",
         T_h: "Sıcak rezervuar sıcaklığı (Sıcaklık K)",
         T_c: "Soğuk rezervuar sıcaklığı (Sıcaklık K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "Periyodik Dalga Hızı",
      equation_text: "v = fλ",
      summary: "Dalga hızını hesaplar (v = fλ)",
      description: "Periyodik bir dalganın hızını, frekansına ve dalga boyuna dayalı olarak hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         v: "Dalga hızı (Hız m/s)",
         f: "Frekans (Frekans Hz)",
         λ: "Dalga boyu (Uzunluk m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "Dalga Şiddeti",
      equation_text: "I = P / A",
      summary: "Şiddeti hesaplar (I = P/A)",
      description: "Bir dalganın şiddetini (birim alan başına düşen güç) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         I: "Şiddet (Şiddet W/m²)",
         P: "Güç (Güç W)",
         A: "Alan (Alan m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "Şiddet Seviyesi (Desibel)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "Desibel cinsinden şiddet seviyesini hesaplar (L = 10 log10(I/I0))",
      description: "Bir referans şiddete göre şiddet seviyesini (ses şiddet seviyesi) hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         β: "Şiddet seviyesi (Şiddet Seviyesi dB)",
         I: "Şiddet (Şiddet W/m²)",
         I0: "Referans şiddet (Şiddet W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "Basınç Seviyesi (Ses Basıncı Seviyesi)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "Desibel cinsinden ses basınç seviyesini hesaplar (L = 20 log10(ΔP/ΔP0))",
      description: "Bir referans basınç değişimine göre ses basınç seviyesini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         L_p: "Ses basıncı seviyesi (Basınç Seviyesi dB)",
         P_rms: "RMS basınç dalgalanması (Basınç Pa)",
         P_ref: "Referans basınç (Basınç Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "Doppler Etkisi (Ses/Non-Relativistik)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "Doppler etkisi hız faktörünü hesaplar ((c + v_o) / (c - v_s))",
      description:
         "Doppler etkisi denkleminin hız faktörü kısmını (f' = f * factor) hesaplar. Gözlemcinin kaynağa doğru, kaynağın gözlemciye doğru hareketi için hızlar pozitiftir.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         f_obs: "Gözlemlenen frekans (Frekans Hz)",
         f_source: "Kaynak frekansı (Frekans Hz)",
         v_wave: "Dalga hızı (Hız m/s)",
         v_observer: "Ortama göre gözlemci hızı (Hız m/s)",
         v_source: "Ortama göre kaynak hızı (Hız m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "Mach Açısı",
      equation_text: "sin(μ) = 1 / M",
      summary: "Mach açısını hesaplar (θ_M = arcsin(c/v))",
      description:
         "Ses hızından daha hızlı hareket eden bir nesne tarafından oluşturulan Mach konisinin açısını hesaplar. Açıyı radyan cinsinden döndürür.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         μ: "Mach açısı (Açı rad)",
         M: "Mach sayısı (Boyutsuz)",
         c: "Ses hızı (Hız m/s)",
         v: "Nesne hızı (Hız m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "İş",
      equation_text: "W = Fdcos(θ)",
      summary: "Yapılan işi hesaplar (W = F * Δs * cos(θ))",
      description: "Kuvvet, yer değiştirme ve aralarındaki açıya dayalı olarak yapılan işi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         W: "Yapılan iş (Enerji J)",
         F: "Kuvvet büyüklüğü (Kuvvet N)",
         d: "Yerdeğiştirme büyüklüğü (Comprimento m)",
         θ: "Kuvvet ve yer değiştirme arasındaki açı (Açı rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "Kinetik Enerji",
      equation_text: "KE = ½mv²",
      summary: "Kinetik enerjiyi hesaplar (KE = 0.5 * m * v^2)",
      description: "Kütle ve hıza dayalı olarak kinetik enerjiyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE: "Kinetik enerji (Enerji J)",
         m: "Kütle (Kütle kg)",
         v: "Hız (Hız m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "Kinetik Enerji (Momentumdan)",
      equation_text: "KE = p² / (2m)",
      summary: "Momentumdan kinetik enerjiyi hesaplar (KE = p^2 / (2m))",
      description: "Momentum ve kütleye dayalı olarak kinetik enerjiyi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         KE: "Kinetik enerji (Enerji J)",
         p: "Momentum (Momentum kg·m/s)",
         m: "Kütle (Kütle kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "Kütleçekim Potansiyel Enerjisi",
      equation_text: "U_g = mgh (yüzeye yakın)",
      summary: "Kütleçekim potansiyel enerjisini hesaplar (PE = mgh)",
      description: "Kütleçekim potansiyel enerjisindeki değişimi hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         U_g: "Kütleçekim potansiyel enerjisi (Enerji J)",
         m: "Kütle (Kütle kg)",
         g: "Yerçekimi ivmesi (İvme m/s²)",
         h: "Yükseklik (Uzunluk m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "Verimlilik",
      equation_text: "Verimlilik = Çıkış / Giriş",
      summary: "Verimliliği hesaplar (η = W_out / W_in)",
      description: "Bir işlemin veya makinenin verimliliğini hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         Efficiency: "Verimlilik (Boyutsuz)",
         Output: "Kullanışlı çıkış enerji veya gücü (Enerji J veya Güç W)",
         Input: "Toplam giriş enerji veya gücü (Enerji J veya Güç W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "Güç",
      equation_text: "P = W / t",
      summary: "Gücü hesaplar (P = ΔW / Δt)",
      description: "İş değişimine ve zamana dayalı olarak ortalama gücü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Güç (Güç W)",
         ΔW: "İş değişimi (Enerji J)",
         Δt: "Zaman aralığı (Zaman s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "Güç (P = Fv)",
      equation_text: "P = Fv",
      summary: "Kuvvet ve hızdan gücü hesaplar (P = Fv cos(θ))",
      description: "Kuvvet, hız ve aralarındaki açıya dayalı olarak anlık gücü hesaplar.",
      language_code: "tr",
      subject: "Physics",
      variables: {
         P: "Güç (Güç W)",
         F: "Kuvvet büyüklüğü (Kuvvet N)",
         v: "Hız büyüklüğü (Hız m/s)",
         θ: "Kuvvet ve hız arasındaki açı (Açı rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = tr;