const ur = [
   {
      equation_id: "centripetal-acceleration",
      name: "مرکزی تسارع",
      equation_text: "a_c = v² / r",
      summary: "مرکزی تسارع (a_c = v^2 / r) حساب کرتا ہے",
      description:
         "لکیری رفتار اور رداس کا استعمال کرتے ہوئے دائرہ نما راستے کے مرکز کی طرف ہدایت کردہ تسارع حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         a_c: "مرکزی تسارع (تسارع m/s²)",
         v: "لکیری رفتار (رفتار m/s)",
         r: "دائرہ نما راستے کا رداس (لمبائی m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "مرکزی تسارع (زاویہ)",
      equation_text: "a_c = ω²r",
      summary: "زاویہ رفتار کا استعمال کرتے ہوئے مرکزی تسارع (a_c = -ω^2 * r) حساب کرتا ہے",
      description:
         "زاویہ رفتار اور رداس کا استعمال کرتے ہوئے مرکزی تسارع ویکٹر کا جزو حساب کرتا ہے۔ منفی علامت مرکز کی طرف ہدایت کو ظاہر کرتی ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         a_c: "مرکزی تسارع (تسارع m/s²)",
         ω: "زاویہ رفتار (زاویہ رفتار rad/s)",
         r: "دائرہ نما راستے کا رداس (لمبائی m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "قانون کولمب (قوت)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "قانون کولمبب کا استعمال کرتے ہوئے برقی قوت حساب کرتا ہے (F = k * q1*q2 / r^2)",
      description:
         "دو نقطہ چارجز کے درمیان برقی قوت حساب کرتا ہے۔ دستخط شدہ قوت (تنفّر کے لیے مثبت، کشش کے لیے منفی) لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F: "برقی قوت (قوت N)",
         k: "کولمب کا مستقل (مستقل N·m²/C²)",
         q1: "چارج 1 (چارج C)",
         q2: "چارج 2 (چارج C)",
         r: "چارجز کے درمیان فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "برقی میدان",
      equation_text: "E = kq / r² (نقطہ چارج)",
      summary: "قوت سے برقی میدان حساب کرتا ہے (E = F_E/q)",
      description: "ٹیسٹ چارج پر لگائی گئی قوت کی بنیاد پر برقی میدان کی شدت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "برقی میدان کی مقدار (برقی میدان N/C)",
         k: "کولمب کا مستقل (مستقل N·m²/C²)",
         q: "ماخذ چارج (چارج C)",
         r: "ماخذ چارج سے فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "برقی پوٹینشل",
      equation_text: "V = kq / r (نقطہ چارج)",
      summary: "پوٹینشل توانائی کی تبدیلی سے برقی پوٹینشل حساب کرتا ہے (V = ΔU_E/q)",
      description:
         "برقی پوٹینشل (وولٹیج) حساب کرتا ہے جو فی یونٹ چارج برقی پوٹینشل توانائی کی تبدیلی پر مبنی ہے۔ نوٹ - فنکشن کا نام `calculateElectricPotential` درست ہے، لیکن پیرامیٹر `deltaUE` تبدیلی کو ظاہر کرتا ہے، جبکہ مساوات عام طور پر V=U_E/q یا ΔV=ΔU_E/q ہے۔ ΔV = ΔU_E/q مساوات کی بنیاد پر دستاویزات اور ΔV واپس کر رہا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         V: "برقی پوٹینشل (وولٹیج V)",
         k: "کولمب کا مستقل (مستقل N·m²/C²)",
         q: "ماخذ چارج (چارج C)",
         r: "ماخذ چارج سے فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "برقی میدان اور پوٹینشل کا رشتہ",
      equation_text: "E_x = -dV/dx",
      summary: "پوٹینشل فرق سے برقی میدان حساب کرتا ہے (E = ΔV/d)",
      description:
         'ایک فاصلے پر پوٹینشل فرق کی بنیاد پر یکساں برقی میدان کی مقدار حساب کرتا ہے۔ نوٹ - فنکشن کا نام "فیلڈ اور پوٹینشل" گمراہ کن ہے؛ یہ برقی فیلڈ E کا حساب لگاتا ہے۔',
      language_code: "ur",
      subject: "Physics",
      variables: {
         E_x: "برقی میدان کا جزو (برقی میدان V/m)",
         V: "برقی پوٹینشل (وولٹیج V)",
         x: "پوزیشن (لمبائی m)",
         ΔV: "پوٹینشل فرق (وولٹیج V)",
         d: "فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "گنجائش",
      equation_text: "C = Q / V",
      summary: "گنجائش حساب کرتا ہے (C = Q/V)",
      description: "ذخیرہ شدہ چارج اور کپیسیٹر کے وولٹیج کی بنیاد پر گنجائش حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C: "گنجائش (گنجائش F)",
         Q: "چارج (چارج C)",
         V: "وولٹیج (وولٹیج V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "پلیٹ کپیسیٹر گنجائش",
      equation_text: "C = ε₀A / d",
      summary: "متوازی پلیٹ کپیسیٹر گنجائش حساب کرتا ہے (C = (kε₀A)/d)",
      description:
         "ڈائی الیکٹرک کے ساتھ متوازی پلیٹ کپیسیٹر کی گنجائش حساب کرتا ہے۔ نوٹ - فنکشن k * ε₀ کو واحد ان پٹ (`kEpsilon`) کے طور پر استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C: "گنجائش (گنجائش F)",
         ε0: "خالی جگہ کی اجازت (مستقل F/m)",
         k: "ڈائی الیکٹرک کانسٹنٹ (بے ابعادی)",
         A: "پلیٹوں کا رقبہ (رقبہ m²)",
         d: "پلیٹوں کے درمیان فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "سلنڈرک کپیسیٹر گنجائش",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "سلنڈرک کپیسیٹر گنجائش حساب کرتا ہے (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "ڈائی الیکٹرک کے ساتھ سلنڈرک کپیسیٹر کی گنجائش حساب کرتا ہے۔ نوٹ - فنکشن k * ε₀ کو واحد ان پٹ (`kEpsilon`) کے طور پر استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C: "گنجائش (گنجائش F)",
         π: "پائی (بے ابعادی مستقل)",
         ε0: "خالی جگہ کی اجازت (مستقل F/m)",
         k: "ڈائی الیکٹرک کانسٹنٹ (بے ابعادی)",
         L: "سلنڈروں کی لمبائی (لمبائی m)",
         b: "بیرونی رداس (لمبائی m)",
         a: "اندرونی رداس (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "گولائی کپیسیٹر گنجائش",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "گولائی کپیسیٹر گنجائش حساب کرتا ہے (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "ڈائی الیکٹرک کے ساتھ گولائی کپیسیٹر کی گنجائش حساب کرتا ہے۔ نوٹ - فنکشن k * ε₀ کو واحد ان پٹ (`kEpsilon`) کے طور پر استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C: "گنجائش (گنجائش F)",
         π: "پائی (بے ابعادی مستقل)",
         ε0: "خالی جگہ کی اجازت (مستقل F/m)",
         k: "ڈائی الیکٹرک کانسٹنٹ (بے ابعادی)",
         a: "اندرونی رداس (لمبائی m)",
         b: "بیرونی رداس (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "کپیسیٹیو پوٹینشل انرجی",
      equation_text: "U_C = ½CV²",
      summary: "کپیسیٹر پوٹینشل انرجی مساواتوں کی توثیق کرتا ہے (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "دیئے گئے Q، V، اور C کے لیے کپیسیٹر میں ذخیرہ شدہ پوٹینشل انرجی کے تین عام مساواتوں کے برابر ہونے کی جانچ کرتا ہے۔ بولین ویلیو لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         U_C: "کپیسیٹیو پوٹینشل انرجی (انرجی J)",
         Q: "چارج (چارج C)",
         V: "وولٹیج (وولٹیج V)",
         C: "گنجائش (گنجائش F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "برقی رو",
      equation_text: "I = ΔQ / Δt",
      summary: "برقی رو حساب کرتا ہے (I = ΔQ/Δt)",
      description: "وقت کی اکائی میں ایک نقطے سے گزرنے والے چارج کی مقدار کی بنیاد پر برقی رو حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         I: "برقی رو (رو A)",
         ΔQ: "چارج میں تبدیلی (چارج C)",
         Δt: "وقت میں تبدیلی (وقت s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "چارج کثافت",
      equation_text: "ρ = Q / V (حجم)",
      summary: "چارج کثافت حساب کرتا ہے (ρ = Q/V)",
      description: "اوسط چارج کثافت (فی یونٹ حجم چارج) حساب کرتا ہے۔",
language_code: "ur",
      subject: "Physics",
      variables: {
         ρ: "حجم چارج کثافت (چارج کثافت C/m³)",
         Q: "کل چارج (چارج C)",
         V: "حجم (حجم m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "رو کثافت",
      equation_text: "J = I / A",
      summary: "رو کثافت حساب کرتا ہے (J = I/A)",
      description: "برقی رو کثافت (فی یونٹ کراس سیکشنل ایریا رو) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         J: "رو کثافت (رو کثافت A/m²)",
         I: "برقی رو (رو A)",
         A: "رقبہ (رقبہ m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "اوم کا قانون",
      equation_text: "V = IR",
      summary: "اوم کے قانون کا استعمال کرتے ہوئے مزاحمت حساب کرتا ہے (R = V/I)",
      description:
         "وولٹیج اور رو کی بنیاد پر مزاحمت حساب کرتا ہے۔ نوٹ - فنکشن V اور I سے R مزاحمت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         V: "وولٹیج (وولٹیج V)",
         I: "رو (رو A)",
         R: "مزاحمت (مزاحمت Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "مزاحمتی اور موصلیت",
      equation_text: "ρ = RA / L",
      summary: "مزاحمتی سے موصلیت حساب کرتا ہے (σ = 1/ρ)",
      description: "مزاحمتی (ρ) سے موصلیت (σ) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         σ: "موصلیت (موصلیت S/m)",
         ρ: "مزاحمتی (مزاحمتی Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "برقی مزاحمت",
      equation_text: "R = ρL / A",
      summary: "برقی مزاحمت حساب کرتا ہے (R = ρ(l/A))",
      description:
         "ایک موصل کی مزاحمت حساب کرتا ہے جو اس کی مزاحمتی، لمبائی اور کراس سیکشنل ایریا پر مبنی ہے۔ نوٹ - مزاحمتی کے لیے `rhoValue` استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         R: "مزاحمت (مزاحمت Ω)",
         ρ: "مزاحمتی (مزاحمتی Ω·m)",
         L: "لمبائی (لمبائی m)",
         A: "کراس سیکشنل ایریا (رقبہ m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "برقی پاور",
      equation_text: "P = IV",
      summary: "برقی پاور مساواتوں کی توثیق کرتا ہے (P = VI = I^2R = V^2/R)",
      description:
         "دیئے گئے V، I، اور R کے لیے برقی پاور کے تین عام مساواتوں کے برابر ہونے کی جانچ کرتا ہے۔ بولین ویلیو لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "برقی پاور (پاور W)",
         V: "وولٹیج (وولٹیج V)",
         I: "رو (رو A)",
         R: "مزاحمت (مزاحمت Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "سیریز میں مزاحمت کنندہ",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "سیریز میں مزاحمت کنندگان کے لیے کل مزاحمت حساب کرتا ہے (R_total = R1 + R2 + ...)",
      description: "سیریز میں جڑے کئی مزاحمت کنندگان کے لیے کل برابر مزاحمت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         R_total: "کل مزاحمت (مزاحمت Ω)",
         R: "انفرادی مزاحمت (مزاحمت Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "متوازی میں مزاحمت کنندہ",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "متوازی میں مزاحمت کنندگان کے لیے کل مزاحمت حساب کرتا ہے (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "متوازی میں جڑے کئی مزاحمت کنندگان کے لیے کل برابر مزاحمت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         R_total: "کل مزاحمت (مزاحمت Ω)",
         R: "انفرادی مزاحمت (مزاحمت Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "سیریز میں کپیسیٹر",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "سیریز میں کپیسیٹر کے لیے کل گنجائش حساب کرتا ہے (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "سیریز میں جڑے کئی کپیسیٹر کے لیے کل برابر گنجائش حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C_total: "کل گنجائش (گنجائش F)",
         C: "انفرادی گنجائش (گنجائش F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "متوازی میں کپیسیٹر",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "متوازی میں کپیسیٹر کے لیے کل گنجائش حساب کرتا ہے (C_total = C1 + C2 + ...)",
      description: "متوازی میں جڑے کئی کپیسیٹر کے لیے کل برابر گنجائش حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         C_total: "کل گنجائش (گنجائش F)",
         C: "انفرادی گنجائش (گنجائش F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "چارج پر مقناطیسی قوت",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "چارج شدہ ذرات پر مقناطیسی قوت حساب کرتا ہے (F = qvB sin(θ))",
      description:
         "متحرک چارج شدہ ذرے پر لگنے والی مقناطیسی قوت کا مقدار حساب کرتا ہے۔ زاویہ ریڈیان میں ہونا چاہیے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F_B: "مقناطیسی قوت کی مقدار (قوت N)",
         q: "چارج کی مقدار (چارج C)",
         v: "رفتار کی مقدار (رفتار m/s)",
         B: "مقناطیسی میدان کی مقدار (مقناطیسی میدان T)",
         θ: "رفتار اور مقناطیسی میدان کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "کرنٹ پر مقناطیسی قوت",
      equation_text: "F_B = ILBsin(θ)",
      summary: "کرنٹ لے جانے والے موصل پر مقناطیسی قوت حساب کرتا ہے (F = I l B sin(θ))",
      description:
         "مقناطیسی میدان میں کرنٹ لے جانے والے سیدھے موصل پر لگنے والی مقناطیسی قوت کا مقدار حساب کرتا ہے۔ زاویہ ریڈیان میں ہونا چاہیے۔",
language_code: "ur",
      subject: "Physics",
      variables: {
         F_B: "مقناطیسی قوت کی مقدار (قوت N)",
         I: "رو (رو A)",
         L: "موصل کی لمبائی (لمبائی m)",
         B: "مقناطیسی میدان کی مقدار (مقناطیسی میدان T)",
         θ: "رو اور مقناطیسی میدان کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "بیو-ساوار کا قانون",
      equation_text: "B = μ₀I / (2πr) (لامحدود سیدھا تار)",
      summary: "کرنٹ عنصر سے مقناطیسی میدان حساب کرتا ہے (dB = (μ₀I ds) / (4πr^2))",
      description:
         "رداس ویکٹر کے عمودی ایک تفریق کرنٹ عنصر سے مقناطیسی میدان میں شراکت کی مقدار حساب کرتا ہے۔ نوٹ - فنکشن `(μ₀ * I * ds) / (4 * π * r^2)` کو نافذ کرتا ہے، تفریق فارم میں اکثر موجود sin(θ) اصطلاح کو نظر انداز کرتے ہوئے، مؤثر طریقے سے θ=90 ڈگری فرض کرتے ہوئے یا اس مخصوص جہاز میں رداس ویکٹر کے عمودی جزو کو ہی حساب کرتے ہوئے۔ نافذ کردہ مساوات کی دستاویزات۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         dB: "مقناطیسی میدان شراکت کی مقدار (مقناطیسی میدان T)",
         μ0: "خالی جگہ کی پارگمیتا (مستقل T·m/A)",
         I: "رو (رو A)",
         ds: "کرنٹ عنصر کی تفریق لمبائی (لمبائی m)",
         r: "کرنٹ عنصر سے فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "سولینائیڈ کا مقناطیسی میدان",
      equation_text: "B = μ₀nI (اندر، مثالی)",
      summary: "لمبی سولینائیڈ کے اندر مقناطیسی میدان حساب کرتا ہے (B = μ₀nI)",
      description: "لمبی مثالی سولینائیڈ کے اندر مقناطیسی میدان کی مقدار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         B: "سولینائیڈ کے اندر مقناطیسی میدان کی شدت (مقناطیسی میدان T)",
         μ0: "خالی جگہ کی پارگمیتا (مستقل T·m/A)",
         n: "فی یونٹ لمبائی موڑ کی تعداد (فی لمبائی تعداد m⁻¹)",
         I: "رو (رو A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "سیدھے تار کا مقناطیسی میدان",
      equation_text: "B = μ₀I / (2πr) (لامحدود تار)",
      summary: "ایک لامحدود سیدھے تار سے مقناطیسی میدان حساب کرتا ہے (B = (μ₀I)/(2πr))",
      description:
         "کرنٹ لے جانے والے لمبے، سیدھے موصل سے فاصلے پر مقناطیسی میدان کی مقدار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         B: "سیدھے تار سے مقناطیسی میدان کی شدت (مقناطیسی میدان T)",
         μ0: "خالی جگہ کی پارگمیتا (مستقل T·m/A)",
         I: "رو (رو A)",
         π: "پائی (بے ابعادی مستقل)",
         r: "تار سے فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "متوازی تاروں کے درمیان قوت",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "متوازی تاروں کے درمیان فی یونٹ لمبائی قوت حساب کرتا ہے (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "کرنٹ لے جانے والے دو لمبے، متوازی موصلوں کے درمیان فی یونٹ لمبائی قوت کی مقدار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         "F/L": "فی یونٹ لمبائی قوت (فی لمبائی قوت N/m)",
         μ0: "خالی جگہ کی پارگمیتا (مستقل T·m/A)",
         I1: "تار 1 میں رو (رو A)",
         I2: "تار 2 میں رو (رو A)",
         π: "پائی (بے ابعادی مستقل)",
         d: "تاروں کے درمیان فاصلہ (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "برقی فلکس",
      equation_text: "Φ_E = EAcos(θ) (E یکساں)",
      summary: "برقی فلکس حساب کرتا ہے (Φ_E = E * A * cos(θ))",
      description:
         "یکساں برقی میدان میں ایک فلیٹ سطح سے گزرنے والا برقی فلکس حساب کرتا ہے۔ زاویہ برقی میدان ویکٹر اور رقبہ ویکٹر کے درمیان ہونا چاہیے، ریڈیان میں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Φ_E: "برقی فلکس (برقی فلکس N·m²/C)",
         E: "برقی میدان کی مقدار (برقی میدان N/C)",
         A: "رقبہ (رقبہ m²)",
         θ: "E اور رقبہ ویکٹر کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "مقناطیسی فلکس",
      equation_text: "Φ_B = BAcos(θ) (B یکساں)",
      summary: "مقناطیسی فلکس حساب کرتا ہے (Φ_B = B * A * cos(θ))",
      description:
         "یکساں مقناطیسی میدان میں ایک فلیٹ سطح سے گزرنے والا مقناطیسی فلکس حساب کرتا ہے۔ زاویہ مقناطیسی میدان ویکٹر اور رقبہ ویکٹر کے درمیان ہونا چاہیے، ریڈیان میں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Φ_B: "مقناطیسی فلکس (مقناطیسی فلکس Wb)",
         B: "مقناطیسی میدان کی مقدار (مقناطیسی میدان T)",
         A: "رقبہ (رقبہ m²)",
         θ: "B اور رقبہ ویکٹر کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "موشنل ای ایم ایف",
      equation_text: "ε = vBL (سیدھا موصل)",
      summary: "موشنل ای ایم ایف حساب کرتا ہے (emf = Blv)",
      description:
         "مقناطیسی میدان کے عمودی حرکت کرنے والے موصل میں پیدا ہونے والی ای ایم ایف کا مقدار حساب کرتا ہے۔ نوٹ - فنکشن Blv کی مقدار حساب کرتا ہے، سمت کے لیے بعض اوقات استعمال ہونے والے منفی نشان (لینز کا قانون) کو چھوڑ کر۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ε: "موشنل ای ایم ایف مقدار (وولٹیج V)",
         v: "موصل کی رفتار (رفتار m/s)",
         B: "مقناطیسی میدان کی مقدار (مقناطیسی میدان T)",
         L: "موصل کی لمبائی (لمبائی m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "پیدا شدہ ای ایم ایف (فیراڈے کا قانون)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "تبدیل ہونے والے فلکس سے پیدا شدہ ای ایم ایف حساب کرتا ہے (emf = -ΔΦ_B / Δt)",
      description: "فیراڈے کے انڈکشن قانون کے مطابق بدلتے ہوئے مقناطیسی فلکس کے ذریعے پیدا ہونے والی ای ایم ایف حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ε: "پیدا شدہ ای ایم ایف (وولٹیج V)",
         ΔΦ_B: "مقناطیسی فلکس میں تبدیلی (مقناطیسی فلکس Wb)",
         Δt: "وقت میں تبدیلی (وقت s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "انڈکٹنس سے پیدا شدہ ای ایم ایف",
      equation_text: "ε_L = -L dI / dt",
      summary: "انڈکٹر میں کرنٹ کی تبدیلی سے پیدا شدہ ای ایم ایف حساب کرتا ہے (emf = -L * ΔI / Δt)",
      description:
         "کرنٹ کی تبدیلی کی وجہ سے انڈکٹر میں خود پیدا ہونے والی ای ایم ایف حساب کرتا ہے۔ نوٹ - فنکشن کا نام `calculateInductance` ہے لیکن یہ مساوات کا استعمال کرتے ہوئے ای ایم ایف لوٹاتا ہے۔ جو یہ لوٹاتا ہے اسے دستاویز کر رہا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ε_L: "انڈکٹر میں پیدا شدہ ای ایم ایف (وولٹیج V)",
         L: "انڈکٹنس (انڈکٹنس H)",
         ΔI: "رو میں تبدیلی (رو A)",
         Δt: "وقت میں تبدیلی (وقت s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "کپیسیٹیو ری ایکٹنس",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "کپیسیٹیو ری ایکٹنس حساب کرتا ہے (X_C = 1/(2πfC))",
      description: "ایک کپیسیٹر کی متبادل کرنٹ کے خلاف مخالفت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         X_C: "کپیسیٹیو ری ایکٹنس (ری ایکٹنس Ω)",
         π: "پائی (بے ابعادی مستقل)",
         f: "فریکوئنسی (فریکوئنسی Hz)",
         C: "گنجائش (گنجائش F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "انڈکٹیو ری ایکٹنس",
      equation_text: "X_L = 2πfL",
      summary: "انڈکٹیو ری ایکٹنس حساب کرتا ہے (X_L = 2πfL))",
      description: "ایک انڈکٹر کی متبادل کرنٹ کے خلاف مخالفت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         X_L: "انڈکٹیو ری ایکٹنس (ری ایکٹنس Ω)",
         π: "پائی (بے ابعادی مستقل)",
         f: "فریکوئنسی (فریکوئنسی Hz)",
         L: "انڈکٹنس (انڈکٹنس H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "ایمپیڈنس",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "ایمپیڈنس حساب کرتا ہے (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "ایک AC سرکٹ میں کرنٹ کے بہاؤ کے خلاف کل مخالفت حساب کرتا ہے جس میں مزاحمت، انڈکٹیو ری ایکٹنس، اور کپیسیٹیو ری ایکٹنس شامل ہیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Z: "ایمپیڈنس (ایمپیڈنس Ω)",
         R: "مزاحمت (مزاحمت Ω)",
         X_L: "انڈکٹیو ری ایکٹنس (ری ایکٹنس Ω)",
         X_C: "کپیسیٹیو ری ایکٹنس (ری ایکٹنس Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "کثافت",
      equation_text: "ρ = m / V",
      summary: "کثافت حساب کرتا ہے (ρ = m/V)",
      description: "ماس اور حجم کی بنیاد پر کثافت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ρ: "کثافت (کثافت kg/m³)",
         m: "ماس (ماس kg)",
         V: "حجم (حجم m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "دباؤ",
      equation_text: "P = F / A",
      summary: "دباؤ حساب کرتا ہے (P = F/A)",
      description: "رقبے پر لگائی گئی قوت کی بنیاد پر دباؤ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "دباؤ (دباؤ Pa)",
         F: "قوت (قوت N)",
         A: "رقبہ (رقبہ m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "مائع میں دباؤ",
      equation_text: "P = P₀ + ρgh",
      summary: "مائع میں دباؤ حساب کرتا ہے (P = P0 + ρgh)",
      description: "مائع میں ایک مخصوص گہرائی پر مطلق دباؤ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "مطلق دباؤ (دباؤ Pa)",
         P0: "فضا یا سطح کا دباؤ (دباؤ Pa)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
         h: "گہرائی (لمبائی m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "اچھال",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "اچھال قوت حساب کرتا ہے (F_b = ρgV_displaced)",
      description:
         "مائع کی طرف سے ڈوبے ہوئے یا جزوی طور پر ڈوبے ہوئے جسم پر لگائی جانے والی اچھال قوت (آرکیڈیس اصول) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F_B: "اچھال قوت (قوت N)",
         ρ_fluid: "مائع کی کثافت (کثافت kg/m³)",
         V_submerged: "ڈوبا ہوا حجم (حجم m³)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "ماس فلو ریٹ",
      equation_text: "ṁ = ρAv",
      summary: "ماس فلو ریٹ حساب کرتا ہے (ṁ = Δm/Δt)",
      description: "وقت کی اکائی میں ایک نقطے سے گزرنے والی ماس کی شرح حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ṁ: "ماس فلو ریٹ (ماس فلو ریٹ kg/s)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
         A: "رقبہ (رقبہ m²)",
         v: "مائع کی رفتار (رفتار m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "حجم فلو ریٹ",
      equation_text: "Q = Av",
      summary: "حجم فلو ریٹ حساب کرتا ہے (Q = ΔV/Δt)",
      description: "وقت کی اکائی میں ایک نقطے سے گزرنے والے حجم کی شرح حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Q: "حجم فلو ریٹ (حجم فلو ریٹ m³/s)",
         A: "رقبہ (رقبہ m²)",
         v: "مائع کی رفتار (رفتار m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "برنولی کی مساوات",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "برنولی کی مساوات کو چیک کرتا ہے (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "دیئے گئے دو نقطوں پر مائع کی خصوصیات اور حالات کے لیے برنولی کی مساوات کے درست ہونے کی توثیق کرتا ہے۔ بولین ویلیو لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "دباؤ (دباؤ Pa)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
         v: "مائع کی رفتار (رفتار m/s)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
         y: "اونچائی (لمبائی m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "متحرک وسکوسٹی",
      equation_text: "τ = μ * (dv/dy)",
      summary: "متحرک وسکوسٹی حساب کرتا ہے (η = F * Δy / (A * Δvx))",
      description:
         "قوت، رفتار گریڈینٹ، اور رقبہ کی بنیاد پر متحرک وسکوسٹی حساب کرتا ہے۔ یہ مساوات شیر سٹریس/سٹرین ریٹ سے ماخوذ ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         μ: "متحرک وسکوسٹی (متحرک وسکوسٹی Pa·s)",
         F: "قوت (قوت N)",
         Δy: "بہاؤ کے عمودی فاصلہ (لمبائی m)",
         A: "رقبہ (رقبہ m²)",
         Δvx: "رفتار میں تبدیلی (رفتار m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "کائینیٹک وسکوسٹی",
      equation_text: "ν = μ / ρ",
      summary: "کائینیٹک وسکوسٹی حساب کرتا ہے (ν = η / ρ)",
      description: "متحرک وسکوسٹی اور کثافت سے کائینیٹک وسکوسٹی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ν: "کائینیٹک وسکوسٹی (کائینیٹک وسکوسٹی m²/s)",
         μ: "متحرک وسکوسٹی (متحرک وسکوسٹی Pa·s)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "ڈریگ فورس",
      equation_text: "F_D = ½ρv²CdA",
      summary: "ڈریگ فورس حساب کرتا ہے (F_d = 0.5 * ρ * C_A * v^2)",
      description: "مائع میں حرکت کرنے والے جسم پر ڈریگ فورس حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F_D: "ڈریگ فورس (قوت N)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
         v: "رفتار (رفتار m/s)",
         Cd: "ڈریگ کوفیشینٹ (بے ابعادی)",
         A: "حوالہ رقبہ (رقبہ m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "ماخ نمبر",
      equation_text: "M = v / c_sound",
      summary: "ماخ نمبر حساب کرتا ہے (M = v/c)",
      description: "ماخ نمبر، جو کسی جسم کی رفتار کا درمیانے میں آواز کی رفتار سے نسبت ہے، حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         M: "ماخ نمبر (بے ابعادی)",
         v: "جسم کی رفتار (رفتار m/s)",
         c_sound: "درمیانے میں آواز کی رفتار (رفتار m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "رينولدز عدد",
      equation_text: "Re = ρvd / μ",
      summary: "رينولدز عدد حساب کرتا ہے (Re = (ρ * v * D) / η)",
      description:
         "رينولدز عدد، ایک بے ابعادی مقدار ہے جو مختلف مائع فلو حالات میں فلو پیٹرنز کی پیش گوئی کے لیے استعمال ہوتی ہے، حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Re: "رينولدز عدد (بے ابعادی)",
         ρ: "مائع کی کثافت (کثافت kg/m³)",
         v: "رفتار (رفتار m/s)",
         d: "خصوصی لمبائی (لمبائی m)",
         μ: "متحرک وسکوسٹی (متحرک وسکوسٹی Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "فرود عدد",
      equation_text: "Fr = v / √(gL)",
      summary: "فرود عدد حساب کرتا ہے (Fr = v / √(g * l))",
      description:
         "فرود عدد، ایک بے ابعادی مقدار ہے جو مائع حرکت پر کشش ثقل کے اثر کو ظاہر کرنے کے لیے استعمال ہوتی ہے، حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Fr: "فرود عدد (بے ابعادی)",
         v: "رفتار (رفتار m/s)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
         L: "خصوصی لمبائی (لمبائی m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "سطحی تناؤ",
      equation_text: "γ = F / L",
      summary: "سطحی تناؤ حساب کرتا ہے (γ = F / l)",
      description: "قوت اور لمبائی کی بنیاد پر مائع کا سطحی تناؤ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         γ: "سطحی تناؤ (سطحی تناؤ N/m)",
         F: "قوت (قوت N)",
         L: "لمبائی (لمبائی m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "عالمگیر کشش ثقل (قوت)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "کشش ثقل حساب کرتا ہے (F = -Gm1m2/r^2)",
      description:
         "دو نقطہ کتلوں کے درمیان کشش ثقل حساب کرتا ہے۔ نوٹ - کشش کو ظاہر کرنے والی ایک منفی ویلیو لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F: "کشش ثقل (قوت N)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         m1: "ماس 1 (ماس kg)",
         m2: "ماس 2 (ماس kg)",
         r: "ماسوں کے درمیان فاصلہ (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "کشش ثقل کا میدان",
      equation_text: "g = GM / r² (مقدار)",
      summary: "کشش ثقل کا میدان حساب کرتا ہے (g = -Gm/r^2)",
      description:
         "ایک نقطہ ماس سے فاصلے پر کشش ثقل کے میدان کی شدت حساب کرتا ہے۔ نوٹ - ماس کی طرف ہدایت کو ظاہر کرنے والی ایک منفی ویلیو لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         g: "کشش ثقل کے میدان کی شدت کی مقدار (کشش ثقل کا میدان N/kg)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         M: "ماخذ ماس (ماس kg)",
         r: "ماخذ ماس سے فاصلہ (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "کشش ثقل کی پوٹینشل انرجی",
      equation_text: "U_g = -G m₁m₂ / r (عام)",
      summary: "دو ماسوں کے درمیان کشش ثقل کی پوٹینشل انرجی حساب کرتا ہے (PE = -Gm1m2/r)",
      description: "دو نقطہ ماسوں کے نظام کی کشش ثقل کی پوٹینشل انرجی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         U_g: "کشش ثقل کی پوٹینشل انرجی (انرجی J)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         m1: "ماس 1 (ماس kg)",
         m2: "ماس 2 (ماس kg)",
         r: "ماسوں کے درمیان فاصلہ (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "کشش ثقل کا پوٹینشل",
      equation_text: "V_g = -GM / r",
      summary: "کشش ثقل کا پوٹینشل حساب کرتا ہے (V_g = -Gm/r)",
      description: "ایک نقطہ ماس سے فاصلے پر کشش ثقل کا پوٹینشل حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         V_g: "کشش ثقل کا پوٹینشل (کشش ثقل کا پوٹینشل J/kg)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         M: "ماخذ ماس (ماس kg)",
         r: "ماخذ ماس سے فاصلہ (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "مداری رفتار",
      equation_text: "v_orbit = √(GM / r) (دائری)",
      summary: "مداری رفتار حساب کرتا ہے (v = sqrt(Gm/r))",
      description: "ایک بڑے ماس کے گرد دائرہ نما مدار میں کسی شے کی رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_orbit: "مداری رفتار (رفتار m/s)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         M: "مرکزی جسم کی ماس (ماس kg)",
         r: "مداری رداس (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "فرار کی رفتار",
      equation_text: "v_escape = √(2GM / r)",
      summary: "فرار کی رفتار حساب کرتا ہے (v = sqrt(2Gm/r))",
      description:
         "دیئے گئے فاصلے سے کسی ماس کی کشش ثقل سے فرار ہونے کے لیے درکار کم از کم رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_escape: "فرار کی رفتار (رفتار m/s)",
         G: "کشش ثقل کا مستقل (مستقل N·m²/kg²)",
         M: "مرکزی جسم کی ماس (ماس kg)",
         r: "مرکز سے فاصلہ (لمبائی m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "حرارتی ترسیل",
      equation_text: "Q/t = kAΔT/d",
      summary: "حرارتی ترسیل کی شرح حساب کرتا ہے (Q/t = (kAΔT) / L)",
      description:
         "مادے کے ذریعے ترسیل کے ذریعہ حرارت کی منتقلی کی شرح حساب کرتا ہے۔ نوٹ - فنکشن Q کا حساب لگاتا ہے، یہ فرض کرتے ہوئے کہ شرح کے لیے مساوات کے عام استعمال سے ایک وقت کا وقفہ مضمر ہے۔ دستاویز میں Q کا ذکر ہے، لیکن مساوات عام طور پر Q/t کے لیے ہے۔ اس فرق کو واضح کیا جا رہا ہے۔ فنکشن شرح مساوات کے دائیں جانب کا نتیجہ لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         "Q/t": "حرارت کی منتقلی کی شرح (پاور W)",
         k: "حرارتی موصلیت (حرارتی موصلیت W/(m·K))",
         A: "رقبہ (رقبہ m²)",
         ΔT: "درجہ حرارت کا فرق (درجہ حرارت کا فرق K)",
         d: "موٹائی (لمبائی m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "اسٹیفن-بولٹزمین قانون",
      equation_text: "P = εσAT⁴",
      summary: "حرارتی تابکاری کی طاقت حساب کرتا ہے (P = εσA(T^4 - T0^4))",
      description: "ایک شے کی اس کے ماحول کو مدنظر رکھتے ہوئے خارج ہونے والی توانائی کی خالص شرح حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "خالص تابکاری کی طاقت (پاور W)",
         ε: "انبعاثیت (بے ابعادی)",
         σ: "اسٹیفن-بولٹزمین کا مستقل (مستقل W/(m²·K⁴))",
         A: "سطح کا رقبہ (رقبہ m²)",
         T: "شے کا درجہ حرارت (درجہ حرارت K)",
         T0: "گرد و نواح کا درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "وین کا ڈسپلیسمنٹ قانون (زیادہ سے زیادہ طول موج)",
      equation_text: "λ_max = b/T",
      summary: "وین کا قانون استعمال کرتے ہوئے چوٹی کی طول موج حساب کرتا ہے (λ_max = b/T)",
      description: "وہ طول موج حساب کرتا ہے جہاں ایک بلیک باڈی کا اخراج سپیکٹرم سب سے زیادہ ہوتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         λ_max: "چوٹی اخراج کی طول موج (لمبائی m)",
         b: "وین کا ڈسپلیسمنٹ مستقل (مستقل m·K)",
         T: "درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "وین کا ڈسپلیسمنٹ قانون (زیادہ سے زیادہ فریکوئنسی)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "وین کا قانون استعمال کرتے ہوئے چوٹی کی فریکوئنسی حساب کرتا ہے (f_max = b' * T)",
      description:
         "وہ فریکوئنسی حساب کرتا ہے جہاں ایک بلیک باڈی کا اخراج سپیکٹرم سب سے زیادہ ہوتا ہے۔ نوٹ - یہ ورژن ترمیم شدہ وین مستقل b' استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f_max: "چوٹی اخراج کی فریکوئنسی (فریکوئنسی Hz)",
         "b'": "ترمیم شدہ وین مستقل (مستقل Hz/K)",
         T: "درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "مساوات کی معلومات (خاص)",
      equation_text: "قابل اطلاق نہیں (معلومات حاصل کرتا ہے، حساب نہیں لگاتا)",
      summary: "ID اور زبان کے ذریعے مساوات کی معلومات حاصل کریں",
      description:
         "اس کی منفرد شناخت کنندہ (ID) اور مطلوبہ زبان کی بنیاد پر ایک مخصوص مساوات کی تفصیلات حاصل کرتا ہے۔ نوٹ - زبان کو 'language_code' پاتھ پیرامیٹر سے نکالا جاتا ہے۔ کوڈ کے ٹکڑے میں دکھایا گیا اندرونی منطق 'lang' کیوری پیرامیٹر کو بھی دیکھتا ہے، لیکن یہ سواگر ڈیفینیشن بنیادی پاتھ پیرامیٹرز کو دستاویز کرتی ہے۔",
      language_code: "ur",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "API میں تمام مساوات کے اینڈ پوائنٹس حاصل کریں۔",
      description: "API میں تمام اینڈ پوائنٹس کے بارے میں خلاصہ معلومات حاصل کرتا ہے۔",
      language_code: "ur",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "رفتار",
      equation_text: "v = Δx / Δt",
      summary: "رفتار حساب کرتا ہے",
      description: "پوزیشن کی تبدیلی اور وقت کی بنیاد پر رفتار حساب کرتا ہے (v = Δs / Δt)۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v: "رفتار (رفتار m/s)",
         Δx: "پوزیشن کی تبدیلی (لمبائی m)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "تسارع",
      equation_text: "a = Δv / Δt",
      summary: "تسارع حساب کرتا ہے",
      description: "رفتار اور وقت میں تبدیلی کی بنیاد پر تسارع حساب کرتا ہے (a = Δv / Δt)۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         a: "تسارع (تسارع m/s²)",
         Δv: "رفتار میں تبدیلی (رفتار m/s)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "حرکت کی مساوات (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "حتمی رفتار حساب کرتا ہے (v = v0 + at)",
      description: "پہلی حرکیاتی مساوات کا استعمال کرتے ہوئے حتمی رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v: "حتمی رفتار (رفتار m/s)",
         v0: "ابتدائی رفتار (رفتار m/s)",
         a: "تسارع (تسارع m/s²)",
         t: "وقت (وقت s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "حرکت کی مساوات (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "حتمی پوزیشن حساب کرتا ہے (s = s0 + v0t + 0.5at^2)",
      description: "دوسری حرکیاتی مساوات کا استعمال کرتے ہوئے حتمی پوزیشن حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         s: "حتمی پوزیشن (لمبائی m)",
         s0: "ابتدائی پوزیشن (لمبائی m)",
         v0: "ابتدائی رفتار (رفتار m/s)",
         t: "وقت (وقت s)",
         a: "تسارع (تسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "حرکت کی مساوات (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "حتمی رفتار کا مربع حساب کرتا ہے (v^2 = v0^2 + 2a(s - s0))",
      description: "تیسری حرکیاتی مساوات کا استعمال کرتے ہوئے حتمی رفتار کا مربع حساب کرتا ہے۔ نوٹ - v نہیں بلکہ v^2 لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v: "حتمی رفتار (رفتار m/s)",
         v0: "ابتدائی رفتار (رفتار m/s)",
         a: "تسارع (تسارع m/s²)",
         Δs: "پوزیشن کی تبدیلی (لمبائی m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "اوسط رفتار",
      equation_text: "v_avg = Δx / Δt",
      summary: "اوسط رفتار حساب کرتا ہے (v_avg = 0.5 * (v + v0))",
      description: "مستقل تسارع کو فرض کرتے ہوئے اوسط رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_avg: "اوسط رفتار (رفتار m/s)",
         v: "حتمی رفتار (رفتار m/s)",
         v0: "ابتدائی رفتار (رفتار m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "قوت (نیوٹن کا دوسرا قانون)",
      equation_text: "F_net = ma",
      summary: "قوت حساب کرتا ہے (F = ma)",
      description: "نیوٹن کے دوسرے قانون کا استعمال کرتے ہوئے قوت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F_net: "خالص قوت (قوت N)",
         m: "ماس (ماس kg)",
         a: "تسارع (تسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "وزن",
      equation_text: "W = mg",
      summary: "وزن حساب کرتا ہے (W = mg)",
      description: "کسی چیز پر کشش ثقل کی قوت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         W: "وزن (قوت N)",
         m: "ماس (ماس kg)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "زیادہ سے زیادہ جامد رگڑ",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "زیادہ سے زیادہ جامد رگڑ حساب کرتا ہے (F_s = μ_s * N)",
      description: "ممکنہ زیادہ سے زیادہ جامد رگڑ قوت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f_s_max: "زیادہ سے زیادہ جامد رگڑ قوت (قوت N)",
         μ_s: "جامد رگڑ کا گتانک (بے ابعادی)",
         F_N: "نارمل قوت (قوت N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "حرکی رگڑ",
      equation_text: "f_k = μ_k * F_N",
      summary: "حرکی رگڑ حساب کرتا ہے (F_k = μ_k * N)",
      description: "متحرک جسم پر عمل کرنے والی حرکی رگڑ قوت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f_k: "حرکی رگڑ قوت (قوت N)",
         μ_k: "حرکی رگڑ کا گتانک (بے ابعادی)",
         F_N: "نارمل قوت (قوت N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "مومنٹم",
      equation_text: "p = mv",
      summary: "مومنٹم حساب کرتا ہے (p = mv)",
      description: "کسی چیز کا خطی مومنٹم حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         p: "مومنٹم (مومنٹم kg·m/s)",
         m: "ماس (ماس kg)",
         v: "رفتار (رفتار m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "امپلس",
      equation_text: "J = F_avg * Δt",
      summary: "امپلس حساب کرتا ہے (J = F * Δt)",
      description: "قوت اور وقت کے وقفے سے امپلس حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         J: "امپلس (امپلس N·s)",
         F_avg: "اوسط قوت (قوت N)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "امپلس-مومنٹم تھیوری",
      equation_text: "J = Δp",
      summary: "امپلس-مومنٹم تھیوری کی توثیق کرتا ہے (F * Δt = m * Δv)",
      description: "دیئے گئے اقدار کے لیے امپلس کا مومنٹم میں تبدیلی کے برابر ہونے کی جانچ کرتا ہے۔ بولین لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         J: "امپلس (امپلس N·s)",
         Δp: "مومنٹم میں تبدیلی (مومنٹم kg·m/s)",
         F: "قوت (قوت N)",
         Δt: "وقت کا وقفہ (وقت s)",
         m: "ماس (ماس kg)",
         Δv: "رفتار میں تبدیلی (رفتار m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "تابکار سرگرمی",
      equation_text: "A = λN",
      summary: "تابکار زوال میں اوسط سرگرمی حساب کرتا ہے (A_avg = ΔN/Δt)",
      description:
         "وقت کے وقفے کے دوران ریڈیو ایکٹیو نمونے کی اوسط سرگرمی (زوال کی شرح) حساب کرتا ہے۔ نوٹ - فنکشن ΔN نیوکلئی کی تعداد کے لیے `nValue` استعمال کرتا ہے اور وقت Δt کے لیے `tValue` استعمال کرتا ہے۔ یہ Δt سے زیادہ ایک سادہ اوسط ہے، فوری سرگرمی dN/dt = -λN ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         A_avg: "اوسط تابکار سرگرمی (سرگرمی Bq)",
         ΔN: "زوالات کی تعداد (بے ابعادی تعداد)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "نصف عمر",
      equation_text: "T_½ = ln(2) / λ",
      summary: "زوال کے بعد باقی مقدار حساب کرتا ہے (N = N0 * (1/2)^(t/T_half))",
      description:
         "اس کی نصف عمر کی بنیاد پر، ایک مدت کے بعد کسی مادے کی باقی ماندہ مقدار حساب کرتا ہے۔ نوٹ - وقت کے لیے `tValue` اور نصف عمر کے لیے `Thalf` استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         N: "باقی مقدار/نیوکلئی (تعداد)",
         N0: "ابتدائی مقدار/نیوکلئی (تعداد)",
         t: "گزر چکا وقت (وقت s)",
         T_half: "نصف عمر (وقت s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "جذب شدہ تابکاری خوراک",
      equation_text: "D = dE / dm",
      summary: "جذب شدہ تابکاری خوراک حساب کرتا ہے (D = E/m)",
      description:
         "کسی ماس کے ذریعے جذب شدہ توانائی کی بنیاد پر تابکاری کی جذب شدہ خوراک حساب کرتا ہے۔ نوٹ - توانائی کے لیے `EValue` اور ماس کے لیے `mValue` استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         D: "جذب شدہ خوراک (جذب شدہ خوراک Gy)",
         E: "جذب شدہ توانائی (انرجی J)",
         m: "ماس (ماس kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "مساوی تابکاری خوراک",
      equation_text: "H = D * W_R",
      summary: "مساوی تابکاری خوراک حساب کرتا ہے (H = wR * D)",
      description:
         "مختلف قسم کی تابکاری کی حیاتیاتی تاثیر کو مدنظر رکھتے ہوئے مساوی خوراک حساب کرتا ہے۔ نوٹ - جذب شدہ خوراک کے لیے `DValue` استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         H: "مساوی خوراک (مساوی خوراک Sv)",
         D: "جذب شدہ خوراک (جذب شدہ خوراک Gy)",
         W_R: "تابکاری ویٹنگ فیکٹر (بے ابعادی)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "مؤثر تابکاری خوراک",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "مؤثر تابکاری خوراک حساب کرتا ہے (E = wT * H)",
      description:
         "مؤثر خوراک حساب کرتا ہے، مختلف ٹشوز/اعضاء کی تابکاری کے لیے حساسیت کو مدنظر رکھتے ہوئے۔ نوٹ - مساوی خوراک کے لیے `HValue` استعمال کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "مؤثر خوراک (مؤثر خوراک Sv)",
         H_T: "ٹشو/عضو T کے لیے مساوی خوراک (مساوی خوراک Sv)",
         W_T: "ٹشو/عضو T کے لیے ٹشو ویٹنگ فیکٹر (بے ابعادی)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "چیرنکوف زاویہ",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "چیرنکوف زاویہ حساب کرتا ہے (θ_C = arccos(c/nv_p))",
      description:
         "میڈیم میں روشنی کی رفتار سے تیز حرکت کرنے والے چارج شدہ ذرہ کے ذریعہ بننے والے چیرنکوف مخروط کا زاویہ حساب کرتا ہے۔ زاویہ ریڈیان میں لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         θ_C: "چیرنکوف زاویہ (زاویہ rad)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
         n: "میڈیم کا اضطراب انڈیکس (بے ابعادی)",
         v: "ذره کی رفتار (رفتار m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "مداخلت کے فرینجز (جیسے پوزیشن، فاصلہ)",
      equation_text: "Δy = λL / d (دوہری سلٹ فاصلہ)",
      summary: "مداخلت کے فرینجز کی پوزیشن حساب کرتا ہے (y_n = (nλL)/d)",
      description: "ینگ کے دوہری سلٹ مداخلت پیٹرن میں nویں روشن فرنج کی پوزیشن حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         y_n: "nویں روشن فرنج کی پوزیشن (لمبائی m)",
         n: "فرنج آرڈر (بے ابعادی عدد)",
         λ: "طول موج (لمبائی m)",
         L: "اسکرین سے فاصلہ (لمبائی m)",
         d: "سلٹ علیحدگی (لمبائی m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "اضطراب انڈیکس",
      equation_text: "n = c / v",
      summary: "اضطراب انڈیکس حساب کرتا ہے (n = c/v)",
      description:
         "خلا اور میڈیم میں روشنی کی رفتار کی بنیاد پر ایک میڈیم کا اضطراب انڈیکس حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         n: "اضطراب انڈیکس (بے ابعادی)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
         v: "میڈیم میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "سنل کا قانون",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "سنل کے قانون کی توثیق کرتا ہے (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "دیئے گئے اضطراب انڈیکس اور زاویوں والے دو میڈیم کے درمیان روشنی گزرنے کے لیے سنل کا قانون لاگو ہوتا ہے یا نہیں، جانچ پڑتال کرتا ہے۔ بولین لوٹاتا ہے۔ زاویوں کو ریڈیان میں ہونا چاہیے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         n1: "میڈیم 1 کا اضطراب انڈیکس (بے ابعادی)",
         θ1: "میڈیم 1 میں زاویہ (زاویہ rad)",
         n2: "میڈیم 2 کا اضطراب انڈیکس (بے ابعادی)",
         θ2: "میڈیم 2 میں زاویہ (زاویہ rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "نازک زاویہ",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "نازک زاویہ حساب کرتا ہے (θ_c = arcsin(n2/n1))",
      description:
         "جب روشنی اضطراب انڈیکس n1 سے n2 (n1 > n2) والے میڈیم میں جاتی ہے تو کل داخلی انعکاس کے لیے نازک زاویہ حساب کرتا ہے۔ زاویہ ریڈیان میں لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         θ_c: "نازک زاویہ (زاویہ rad)",
         n1: "میڈیم 1 کا اضطراب انڈیکس (بے ابعادی)",
         n2: "میڈیم 2 کا اضطراب انڈیکس (بے ابعادی)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "شبیہ کی پوزیشن (بصریات)",
      equation_text: "1/f = 1/d_o + 1/d_i (پتلی لینس/آئینہ)",
      summary: "پتلی لینس/آئینہ مساوات کی توثیق کرتا ہے (1/f = 1/do + 1/di)",
      description:
         "فوکل لمبائی، آبجیکٹ ڈسٹنس، اور امیج ڈسٹنس کے درمیان تعلق درست ہے یا نہیں، جانچ پڑتال کرتا ہے۔ بولین لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f: "فوکل لمبائی (لمبائی m)",
         d_o: "آبجیکٹ ڈسٹنس (لمبائی m)",
         d_i: "شبیہ ڈسٹنس (لمبائی m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "شبیہ کا سائز (بڑا کرنا - بصریات)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "بڑا کرنے کی مساوات کی توثیق کرتا ہے (h'/h = di/do) (فنکشن h'/h = di/do استعمال کرتا ہے)",
      description:
         "آبجیکٹ/امیج کی بلندیوں اور فاصلوں کے درمیان تعلق درست ہے یا نہیں، جانچ پڑتال کرتا ہے۔ بولین لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ فنکشن سائن شدہ بڑا کرنے کی مساوات کے بجائے مقدار کا رشتہ `h'/h = di/do` استعمال کرتا ہے۔ فنکشن عملدرآمد کی بنیاد پر دستاویزات۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         M: "بڑا کرنا (بے ابعادی)",
         h_i: "شبیہ کی اونچائی (لمبائی m)",
         h_o: "آبجیکٹ کی اونچائی (لمبائی m)",
         d_i: "شبیہ ڈسٹنس (لمبائی m)",
         d_o: "آبجیکٹ ڈسٹنس (لمبائی m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "گولائی آئینہ مساوات",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "گولائی آئینے کی فوکل لمبائی حساب کرتا ہے (f = r/2)",
      description: "اس کی وکر رداس کی بنیاد پر ایک گولائی آئینے کی فوکل لمبائی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f: "فوکل لمبائی (لمبائی m)",
         r: "وکر رداس (لمبائی m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "سپرنگ کی پوٹینشل انرجی",
      equation_text: "U_s = ½kx²",
      summary: "سپرنگ میں پوٹینشل انرجی حساب کرتا ہے (PE = 0.5 * k * Δx^2)",
      description: "ایک مثالی سپرنگ میں ذخیرہ شدہ لچکدار پوٹینشل انرجی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         U_s: "سپرنگ کی پوٹینشل انرجی (انرجی J)",
         k: "سپرنگ مستقل (سپرنگ مستقل N/m)",
         x: "اتزان سے بے گھری (لمبائی m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "سادہ ہارمونک اوسیلیٹر (SHO) پیریڈ",
      equation_text: "T = 2π√(m/k)",
      summary: "سپرنگ-ماس SHO کا پیریڈ حساب کرتا ہے (T = 2π√(m/k))",
      description:
         "سپرنگ پر ماس پر مشتمل ایک سادہ ہارمونک اوسیلیٹر کے لیے آسکیلیشن کا پیریڈ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         T: "پیریڈ (وقت s)",
         π: "پائی (بے ابعادی مستقل)",
         m: "ماس (ماس kg)",
         k: "سپرنگ مستقل (سپرنگ مستقل N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "سادہ پینڈولم پیریڈ",
      equation_text: "T = 2π√(L/g)",
      summary: "سادہ پینڈولم کا پیریڈ حساب کرتا ہے (T = 2π√(l/g))",
      description: "چھوٹے زاویوں پر ایک سادہ پینڈولم کے لیے آسکیلیشن کا پیریڈ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         T: "پیریڈ (وقت s)",
         π: "پائی (بے ابعادی مستقل)",
         L: "پینڈولم کی لمبائی (لمبائی m)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "فریکوئنسی",
      equation_text: "f = 1 / T",
      summary: "فریکوئنسی حساب کرتا ہے (f = 1/T)",
      description: "آسکیلیشن کے پیریڈ سے فریکوئنسی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f: "فریکوئنسی (فریکوئنسی Hz)",
         T: "پیریڈ (وقت s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "زاویہ فریکوئنسی",
      equation_text: "ω = 2πf",
      summary: "زاویہ فریکوئنسی حساب کرتا ہے (ω = 2πf)",
      description: "فریکوئنسی سے زاویہ فریکوئنسی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ω: "زاویہ فریکوئنسی (زاویہ رفتار rad/s)",
         π: "پائی (بے ابعادی مستقل)",
         f: "فریکوئنسی (فریکوئنسی Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "لورینٹز فیکٹر",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "لورینٹز فیکٹر (γ) حساب کرتا ہے",
      description: "γ = 1/√(1 - (v²/c²)) استعمال کرتے ہوئے لورینٹز فیکٹر حساب کرتا ہے۔ v < c ضروری ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         γ: "لورینٹز فیکٹر (بے ابعادی)",
         v: "رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "وقت کا پھیلاؤ",
      equation_text: "Δt' = γ * Δt₀",
      summary: "وقت کا پھیلاؤ حساب کرتا ہے (t' = γ * t₀)",
      description:
         "انارشیل فریم S میں مشاہدہ کار کے لیے گزرے ہوئے وقت (t') کو حساب کرتا ہے، جو متحرک فریم S' میں ماپا گیا مناسب وقت (t₀) اور S اور S' کے درمیان نسبتی رفتار (v) کی بنیاد پر ہے۔ t' = t₀ / √(1 - (v²/c²)) استعمال کرتا ہے۔ t₀ ≥ 0 اور |v| ≤ c ضروری ہے۔ t' کی یونٹ t₀ کی طرح ہوگی، v اور c کی یونٹیں متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Δt: "پھیلا ہوا وقت (وقت s)",
         Δt0: "مناسب وقت (وقت s)",
         v: "نسبتی رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "لمبائی کا سکڑاؤ",
      equation_text: "L' = L₀ / γ",
      summary: "لمبائی کا سکڑاؤ حساب کرتا ہے (L' = L₀ / γ)",
      description:
         "متحرک فریم S' سے دیکھے گئے جسم کی لمبائی (L') کو حساب کرتا ہے، جو اس کے آرام فریم S میں ماپا گیا مناسب لمبائی (L₀) اور S اور S' کے درمیان نسبتی رفتار (v) کی بنیاد پر ہے۔ L' = L₀ * √(1 - (v²/c²)) استعمال کرتا ہے۔ L₀ ≥ 0 اور |v| ≤ c ضروری ہے۔ L' کی یونٹ L₀ کی طرح ہوگی، v اور c کی یونٹیں متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         L: "سکڑی ہوئی لمبائی (لمبائی m)",
         L0: "مناسب لمبائی (لمبائی m)",
         v: "نسبتی رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "نسبتی رفتار کا اضافہ",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "نسبتی رفتار کا اضافہ حساب کرتا ہے",
      description:
         "شے کی رفتار (u') کو ایک فریم S' کے لحاظ سے حساب کرتا ہے، جو اس کی رفتار (u) کو ایک فریم S کے لحاظ سے اور فریم S کی رفتار (v) کو فریم S' کے لحاظ سے جانتا ہے۔ u' = (u + v) / (1 + uv/c²) مساوات کا استعمال کرتا ہے۔ ایک ہی لائن پر حرکت فرض کرتا ہے۔ c ≠ 0 ضروری ہے۔ u، v، اور c کی یونٹیں متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         u: "فریم S میں شے کی رفتار (رفتار m/s)",
         v: "S' کے لحاظ سے فریم S کی رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
         "u'": "S' کے لحاظ سے شے کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "نسبتی کل توانائی",
      equation_text: "E = γmc²",
      summary: "نسبتی کل توانائی (E) حساب کرتا ہے",
      description:
         "ایک پارٹیکل کی کل نسبتی توانائی حساب کرتا ہے جس کی ریسٹ ماس (m) ہے اور جو رفتار (v) سے حرکت کر رہا ہے۔ E = γmc² = mc² / √(1 - (v²/c²)) مساوات کا استعمال کرتا ہے۔ بنیادی طور پر ریسٹ ماس (m > 0) والے پارٹیکلز کے لیے ہے۔ m ≥ 0 اور |v| ≤ c ضروری ہے۔ m، v، اور c کی یونٹیں مناسب یونٹوں میں توانائی حاصل کرنے کے لیے متناسق ہونی چاہئیں (جیسے m کلو گرام میں، v/c میٹر فی سیکنڈ میں E جولز میں دیتا ہے)۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "کل نسبتی توانائی (انرجی J)",
         m: "ریسٹ ماس (ماس kg)",
         v: "رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "نسبتی مومنٹم",
      equation_text: "p = γmv",
      summary: "نسبتی مومنٹم حساب کرتا ہے (p = γmv)",
      description:
         "ایک پارٹیکل کا نسبتی مومنٹم حساب کرتا ہے جس کی ریسٹ ماس (m) ہے اور جو رفتار (v) سے حرکت کر رہا ہے۔ p = γmv = mv / √(1 - (v²/c²)) مساوات کا استعمال کرتا ہے۔ بنیادی طور پر ریسٹ ماس (m > 0) والے پارٹیکلز کے لیے ہے۔ m ≥ 0 اور |v| ≤ c ضروری ہے۔ m، v، اور c کی یونٹیں مناسب یونٹوں میں مومنٹم حاصل کرنے کے لیے متناسق ہونی چاہئیں (جیسے m کلو گرام میں، v میٹر فی سیکنڈ میں، c میٹر فی سیکنڈ میں p کلو گرام·میٹر/سیکنڈ میں دیتا ہے)۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         p: "نسبتی مومنٹم (مومنٹم kg·m/s)",
         m: "ریسٹ ماس (ماس kg)",
         v: "رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "توانائی-مومنٹم تعلق",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "مومنٹم اور ریسٹ ماس سے کل توانائی حساب کرتا ہے (E)",
      description:
         "ایک پارٹیکل کی کل نسبتی توانائی حساب کرتا ہے اس کے نسبتی مومنٹم (p) اور ریسٹ ماس (m) سے۔ توانائی-مومنٹم تعلق: E² = (pc)² + (mc²)² استعمال کرتا ہے۔ یہ مساوات ماسیو (m > 0) اور ماس لیس (m = 0) پارٹیکلز دونوں کے لیے درست ہے۔ p ≥ 0، m ≥ 0، اور c > 0 ضروری ہیں۔ p، m، اور c کی یونٹیں متناسق ہونی چاہئیں۔\n",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "کل نسبتی توانائی (انرجی J)",
         p: "نسبتی مومنٹم (مومنٹم kg·m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
         m: "ریسٹ ماس (ماس kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "ماس-انرجی مساوات (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "ماس-انرجی مساوات حساب کرتا ہے (E₀ = mc²)",
      description:
         "آئن سٹائن کی مشہور مساوات E₀ = mc² کا استعمال کرتے ہوئے دیئے گئے ریسٹ ماس (m) کے برابر ریسٹ انرجی (E₀) حساب کرتا ہے۔ m ≥ 0 اور c > 0 ضروری ہیں۔ m اور c کی یونٹیں متناسق ہونی چاہئیں (جیسے m کلو گرام میں، c میٹر فی سیکنڈ میں E₀ جولز میں دیتا ہے)۔ یہ اینڈ پوائنٹ c کے لیے ایک معیاری قدر (تقریباً 299792458 m/s) استعمال کرتا ہے جب تک کہ 'c' واضح طور پر فراہم نہ کیا جائے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E0: "ریسٹ انرجی (انرجی J)",
         m: "ریسٹ ماس (ماس kg)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "نسبتی حرکی توانائی",
      equation_text: "KE = (γ - 1)mc²",
      summary: "نسبتی حرکی توانائی (KE) حساب کرتا ہے",
      description:
         "ایک پارٹیکل کی نسبتی حرکی توانائی حساب کرتا ہے جس کی ریسٹ ماس (m) ہے اور جو رفتار (v) سے حرکت کر رہا ہے۔ KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc² مساوات کا استعمال کرتا ہے۔ بنیادی طور پر ریسٹ ماس (m > 0) والے پارٹیکلز کے لیے ہے۔ m ≥ 0 اور |v| < c ضروری ہیں۔ m، v، اور c کی یونٹیں مناسب یونٹوں میں توانائی حاصل کرنے کے لیے متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE: "نسبتی حرکی توانائی (انرجی J)",
         m: "ریسٹ ماس (ماس kg)",
         v: "رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "نسبتی ڈوپلر اثر (طول موج)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "طول موج کے لیے نسبتی طولی ڈوپلر اثر حساب کرتا ہے",
      description:
         "ایک ماخذ سے خارج ہونے والی روشنی کی مشاہدہ شدہ طول موج (λ') حساب کرتا ہے جس کی اپنی طول موج (λ₀) ہے اور جو ناظرین سے براہ راست دور یا ان کی طرف نسبتی رفتار (v_rel) سے حرکت کر رہا ہے۔ λ' = λ₀√((1 + β)/(1 - β)) مساوات کا استعمال کرتا ہے، جہاں β = v_rel/c ہے۔ v_rel > 0 انحراف (ریڈ شفٹ) کے لیے، v_rel < 0 قریب آنے (بلیو شفٹ) کے لیے ہے۔ λ₀ > 0 اور |v_rel| < c ضروری ہیں۔ λ' کی یونٹ λ₀ کی طرح ہوگی، v_rel اور c کی یونٹیں متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         "λ'": "مشاہدہ شدہ طول موج (لمبائی m)",
         λ0: "مناسب طول موج (لمبائی m)",
         v: "نسبتی رفتار (رفتار m/s)",
         c: "خلا میں روشنی کی رفتار (رفتار m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "فوٹون انرجی (فریکوئنسی سے)",
      equation_text: "E = hf",
      summary: "فریکوئنسی سے فوٹون انرجی حساب کرتا ہے (E = hf)",
      description:
         "ایک فوٹون کی انرجی (E) حساب کرتا ہے جو اس کی فریکوئنسی (f) پر مبنی ہے۔ E = hf پلانک کا تعلق استعمال کرتا ہے۔ f ≥ 0 اور h > 0 ضروری ہے۔ h اور f کی یونٹیں مناسب یونٹوں میں توانائی حاصل کرنے کے لیے متناسق ہونی چاہئیں (جیسے h J·s میں، f Hz (s⁻¹) میں E جولز میں دیتا ہے)۔ یہ اینڈ پوائنٹ h کے لیے ایک معیاری قدر (تقریباً 6.626e-34 J·s) استعمال کرتا ہے جب تک کہ 'h' واضح طور پر فراہم نہ کیا جائے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "فوٹون انرجی (انرجی J)",
         h: "پلانک مستقل (مستقل J·s)",
         f: "فریکوئنسی (فریکوئنسی Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "فوٹون مومنٹم (طول موج سے)",
      equation_text: "p = h / λ",
      summary: "طول موج سے فوٹون مومنٹم حساب کرتا ہے (p = h/λ)",
      description:
         "ایک فوٹون کا مومنٹم (p) حساب کرتا ہے جو اس کی طول موج (λ) پر مبنی ہے۔ p = h/λ تعلق استعمال کرتا ہے۔ λ > 0 اور h > 0 ضروری ہے۔ h اور λ کی یونٹیں مناسب یونٹوں میں مومنٹم حاصل کرنے کے لیے متناسق ہونی چاہئیں (جیسے h J·s میں، λ میٹر میں p کلو گرام·میٹر/سیکنڈ میں دیتا ہے)۔ یہ اینڈ پوائنٹ h کے لیے ایک معیاری قدر (تقریباً 6.626e-34 J·s) استعمال کرتا ہے جب تک کہ 'h' واضح طور پر فراہم نہ کیا جائے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         p: "فوٹون مومنٹم (مومنٹم kg·m/s)",
         h: "پلانک مستقل (مستقل J·s)",
         λ: "طول موج (لمبائی m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "فوٹو الیکٹرک اثر (زیادہ سے زیادہ KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "فوٹو الیکٹرک اثر میں زیادہ سے زیادہ حرکی توانائی حساب کرتا ہے (KE_max)",
      description:
         "فوٹو الیکٹرک اثر میں خارج ہونے والے الیکٹرانوں کی زیادہ سے زیادہ حرکی توانائی (KE_max) حساب کرتا ہے۔ KE_max = E_photon - φ مساوات کا استعمال کرتا ہے، جہاں E_photon آنے والے فوٹون کی توانائی ہے اور φ مادے کا ورک فنکشن ہے۔ اگر E_photon ≤ φ، تو کوئی الیکٹران خارج نہیں ہوتا، اور KE_max 0 ہے۔ E_photon ≥ 0 اور φ ≥ 0 ضروری ہے۔ E_photon اور φ کی یونٹیں KE_max کو ایک ہی یونٹ میں حاصل کرنے کے لیے متناسق ہونی چاہئیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE_max: "زیادہ سے زیادہ الیکٹران حرکی توانائی (انرجی J)",
         E_photon: "فوٹون انرجی (انرجی J)",
         φ: "ورک فنکشن (انرجی J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "ریڈبرگ مساوات (ایٹمی منتقلی)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "ہائیڈروجن جیسی ایٹمی منتقلی کے لیے توانائی یا ویونمبر حساب کرتا ہے",
      description:
         "ہائیڈروجن جیسی ایٹم (Z) میں دو توانائی کی سطحوں کے درمیان الیکٹران منتقلی کے لیے توانائی کا فرق (ΔE) یا ویونمبر (1/λ) حساب کرتا ہے۔ نتیجہ = مستقل * Z² * (1/n_initial² - 1/n_final²) مساوات کا استعمال کرتا ہے۔ اگر 'مستقل' ریڈبرگ انرجی یونٹ ہے (جیسے، eV میں)، تو نتیجہ توانائی کا فرق E_final - E_initial ہے (جذب کے لیے مثبت، اخراج کے لیے منفی)۔ اگر 'مستقل' ویونمبر کے لیے ریڈبرگ مستقل ہے (جیسے، m⁻¹ میں)، تو نتیجہ ویونمبر 1/λ ہے (اخراج کے لیے مثبت، جذب کے لیے منفی)۔ nInitial > 0، nFinal > 0، nInitial ≠ nFinal، Z > 0 (صحیح اعداد)، اور مستقل > 0 ضروری ہیں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔE: "توانائی کا فرق (انرجی J)",
         R_y: "ریڈبرگ مستقل (مستقل J یا الٹا لمبائی m⁻¹)",
         Z: "ایٹمی عدد (بے ابعادی عدد)",
         n1: "ابتدائی پرنسپل کوانٹم نمبر (بے ابعادی عدد)",
         n2: "حتمی پرنسپل کوانٹم نمبر (بے ابعادی عدد)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "زاویائی رفتار",
      equation_text: "ω = Δθ / Δt",
      summary: "زاویائی رفتار حساب کرتا ہے (ω = Δθ / Δt)",
      description: "زاویہ اور وقت میں تبدیلی کی بنیاد پر زاویائی رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ω: "زاویائی رفتار (زاویائی رفتار rad/s)",
         Δθ: "زاویائی بے گھری (زاویہ rad)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "زاویائی تسارع",
      equation_text: "α = Δω / Δt",
      summary: "زاویائی تسارع حساب کرتا ہے (α = Δω / Δt)",
      description: "زاویائی رفتار اور وقت میں تبدیلی کی بنیاد پر زاویائی تسارع حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         α: "زاویائی تسارع (زاویائی تسارع rad/s²)",
         Δω: "زاویائی رفتار میں تبدیلی (زاویائی رفتار rad/s)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "گردشی کائنمیٹکس (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "حتمی زاویائی رفتار حساب کرتا ہے (ω = ω0 + αt)",
      description: "پہلی گردشی کائنمیٹک مساوات کا استعمال کرتے ہوئے حتمی زاویائی رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ω: "حتمی زاویائی رفتار (زاویائی رفتار rad/s)",
         ω0: "ابتدائی زاویائی رفتار (زاویائی رفتار rad/s)",
         α: "زاویائی تسارع (زاویائی تسارع rad/s²)",
         t: "وقت (وقت s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "گردشی کائنمیٹکس (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "زاویائی پوزیشن حساب کرتا ہے (θ = θ0 + ω0t + 0.5αt^2)",
      description: "دوسری گردشی کائنمیٹک مساوات کا استعمال کرتے ہوئے حتمی زاویائی پوزیشن حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         θ: "حتمی زاویائی پوزیشن (زاویہ rad)",
         θ0: "ابتدائی زاویائی پوزیشن (زاویہ rad)",
         ω0: "ابتدائی زاویائی رفتار (زاویائی رفتار rad/s)",
         t: "وقت (وقت s)",
         α: "زاویائی تسارع (زاویائی تسارع rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "گردشی کائنمیٹکس (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "زاویائی رفتار کا مربع حساب کرتا ہے (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "گردشی کائنمیٹک مساوات کا استعمال کرتے ہوئے حتمی زاویائی رفتار کا مربع حساب کرتا ہے۔ نوٹ - ω نہیں بلکہ ω^2 لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ω: "حتمی زاویائی رفتار (زاویائی رفتار rad/s)",
         ω0: "ابتدائی زاویائی رفتار (زاویائی رفتار rad/s)",
         α: "زاویائی تسارع (زاویائی تسارع rad/s²)",
         Δθ: "زاویائی بے گھری (زاویہ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "اوسط زاویائی رفتار",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "اوسط زاویائی رفتار حساب کرتا ہے (ω_avg = 0.5 * (ω + ω0))",
      description: "مستقل زاویائی تسارع کو فرض کرتے ہوئے اوسط زاویائی رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ω_avg: "اوسط زاویائی رفتار (زاویائی رفتار rad/s)",
         ω: "حتمی زاویائی رفتار (زاویائی رفتار rad/s)",
         ω0: "ابتدائی زاویائی رفتار (زاویائی رفتار rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "ٹارک",
      equation_text: "τ = rFsin(θ)",
      summary: "ٹارک حساب کرتا ہے (τ = rF sin(θ))",
      description: "رداس، قوت اور ان کے درمیان زاویہ کی بنیاد پر ٹارک حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         τ: "ٹارک (ٹارک N·m)",
         r: "لیور آرم (لمبائی m)",
         F: "قوت (قوت N)",
         θ: "قوت اور لیور آرم کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "نیوٹن کا دوسرا قانون (گردش)",
      equation_text: "τ_net = Iα",
      summary: "گردشی دوسرے قانون کا استعمال کرتے ہوئے ٹارک حساب کرتا ہے (τ = Iα)",
      description: "عزم انحرافی اور زاویائی تسارع کی بنیاد پر ٹارک حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         τ_net: "خالص ٹارک (ٹارک N·m)",
         I: "عزم انحرافی (عزم انحرافی kg·m²)",
         α: "زاویائی تسارع (زاویائی تسارع rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "عزم انحرافی",
      equation_text: "I = mr² (نقطہ ماس)",
      summary: "نقطہ ماس کے لیے عزم انحرافی حساب کرتا ہے (I = mr^2)",
      description: "ایک محور کے نسبت واحد نقطہ ماس کے لیے عزم انحرافی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         I: "عزم انحرافی (عزم انحرافی kg·m²)",
         m: "ماس (ماس kg)",
         r: "محور سے فاصلہ (لمبائی m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "گردشی کام",
      equation_text: "W = τΔθ (مستقل ٹارک)",
      summary: "گردشی کام حساب کرتا ہے (W = τΔθ)",
      description: "مستقل ٹارک کے ذریعہ زاویائی بے گھری پر کیے گئے کام حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         W: "گردشی کام (انرجی J)",
         τ: "ٹارک (ٹارک N·m)",
         Δθ: "زاویائی بے گھری (زاویہ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "گردشی پاور",
      equation_text: "P = τω",
      summary: "گردشی پاور حساب کرتا ہے (P = τω cos(θ))",
      description:
         "ٹارک، زاویائی رفتار، اور ان کے درمیان زاویہ کی بنیاد پر فوری گردشی پاور حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "گردشی پاور (پاور W)",
         τ: "ٹارک (ٹارک N·m)",
         ω: "زاویائی رفتار (زاویائی رفتار rad/s)",
         θ: "ٹارک اور زاویائی رفتار کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "گردشی حرکی توانائی",
      equation_text: "KE_rot = ½Iω²",
      summary: "گردشی حرکی توانائی حساب کرتا ہے (KE = 0.5Iω^2)",
      description: "گھومنے والی چیز کی حرکی توانائی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE_rot: "گردشی حرکی توانائی (انرجی J)",
         I: "عزم انحرافی (عزم انحرافی kg·m²)",
         ω: "زاویائی رفتار (زاویائی رفتار rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "زاویائی مومنٹم",
      equation_text: "L = Iω",
      summary: "زاویائی مومنٹم حساب کرتا ہے (L = mrv sin(θ))",
      description: "کسی نقطہ کے نسبت حرکت کرنے والے نقطہ ماس کے لیے زاویائی مومنٹم حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         L: "زاویائی مومنٹم (زاویائی مومنٹم kg·m²/s)",
         m: "ماس (ماس kg)",
         r: "محور/نقطہ سے فاصلہ (لمبائی m)",
         v: "رفتار (رفتار m/s)",
         θ: "رداس ویکٹر اور رفتار کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "زاویائی امپلس",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "زاویائی امپلس حساب کرتا ہے (J = τΔt)",
      description: "ٹارک اور وقت کے وقفے سے زاویائی امپلس حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         J_angular: "زاویائی امپلس (زاویائی امپلس N·m·s)",
         τ_avg: "اوسط ٹارک (ٹارک N·m)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "ینگ کا ماڈیول",
      equation_text: "E = σ / ε",
      summary: "ینگ کا ماڈیول حساب کرتا ہے (E = (F * L0) / (A * ΔL))",
      description: "تناؤ یا کمپریشن تناؤ کے تحت ایک مواد کے ینگ کا ماڈیول (لچکدار ماڈیول) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         E: "ینگ کا ماڈیول (دباؤ Pa)",
         F: "قوت (قوت N)",
         L0: "ابتدائی لمبائی (لمبائی m)",
         A: "کراس سیکشنل ایریا (رقبہ m²)",
         ΔL: "لمبائی میں تبدیلی (لمبائی m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "شیئر ماڈیول",
      equation_text: "G = τ / γ",
      summary: "شیئر ماڈیول حساب کرتا ہے (G = (F * y) / (A * Δx))",
      description: "شیئر سٹریس کے تحت ایک مواد کا شیئر ماڈیول (صلابت ماڈیول) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         G: "شیئر ماڈیول (دباؤ Pa)",
         F: "قوت (قوت N)",
         y: "قوت کے عمودی فاصلہ (لمبائی m)",
         A: "رقبہ (رقبہ m²)",
         Δx: "پوزیشن کی تبدیلی (لمبائی m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "بلک ماڈیول",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "بلک ماڈیول حساب کرتا ہے (K = (F * V0) / (A * ΔV))",
      description: "یکساں دباؤ (ہائڈروسٹیٹک سٹریس) کے تحت ایک مواد کا بلک ماڈیول حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         K: "بلک ماڈیول (دباؤ Pa)",
         ΔP: "دباؤ میں تبدیلی (دباؤ Pa)",
         ΔV: "حجم میں تبدیلی (حجم m³)",
         V0: "ابتدائی حجم (حجم m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "ہک کا قانون",
      equation_text: "F = kx",
      summary: "سپرنگ کی قوت حساب کرتا ہے (F = -k * Δx)",
      description:
         "ہک کے قانون کے مطابق ایک مثالی سپرنگ کے ذریعے لگائی جانے والی بحال قوت حساب کرتا ہے۔ نوٹ - بے گھری کی مخالفت کرنے والی قوت کو ظاہر کرنے والی منفی ویلیو لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         F: "قوت (قوت N)",
         k: "سپرنگ مستقل (سپرنگ مستقل N/m)",
         x: "اتزان سے بے گھری (لمبائی m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "جامد حرارتی توسیع (لمبائی)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "جامد خطی حرارتی توسیع حساب کرتا ہے (ΔL = αL0ΔT)",
      description: "درجہ حرارت میں تبدیلی کی وجہ سے ٹھوس مواد کی لمبائی میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔL: "لمبائی میں تبدیلی (لمبائی m)",
         α: "خطی توسیع کا گتانک (فی درجہ حرارت گتانک K⁻¹)",
         L0: "ابتدائی لمبائی (لمبائی m)",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "جامد حرارتی توسیع (رقبہ)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "جامد رقبہ حرارتی توسیع حساب کرتا ہے (ΔA = 2αA0ΔT)",
      description:
         "خطی توسیع گتانک کا استعمال کرتے ہوئے درجہ حرارت میں تبدیلی کی وجہ سے ٹھوس مواد کے رقبہ میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔA: "رقبہ میں تبدیلی (رقبہ m²)",
         α: "خطی توسیع کا گتانک (فی درجہ حرارت گتانک K⁻¹)",
         A0: "ابتدائی رقبہ (رقبہ m²)",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "جامد حرارتی توسیع (حجم)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "جامد حجم حرارتی توسیع حساب کرتا ہے (ΔV = 3αV0ΔT)",
      description:
         "خطی توسیع گتانک کا استعمال کرتے ہوئے درجہ حرارت میں تبدیلی کی وجہ سے ٹھوس مواد کے حجم میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔV: "حجم میں تبدیلی (حجم m³)",
         α: "خطی توسیع کا گتانک (فی درجہ حرارت گتانک K⁻¹)",
         V0: "ابتدائی حجم (حجم m³)",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "مائع حرارتی توسیع",
      equation_text: "ΔV = βV₀ΔT",
      summary: "مائع حرارتی توسیع حساب کرتا ہے (ΔV = βV0ΔT)",
      description: "درجہ حرارت میں تبدیلی کی وجہ سے مائع کے حجم میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔV: "حجم میں تبدیلی (حجم m³)",
         β: "حجم توسیع کا گتانک (فی درجہ حرارت گتانک K⁻¹)",
         V0: "ابتدائی حجم (حجم m³)",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "محسوس حرارت",
      equation_text: "Q = mcΔT",
      summary: "محسوس حرارت حساب کرتا ہے (Q = mcΔT)",
      description: "مادے کے درجہ حرارت میں تبدیلی پیدا کرنے والی منتقل شدہ حرارت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Q: "محسوس حرارت (انرجی J)",
         m: "ماس (ماس kg)",
         c: "خاص حرارت کی صلاحیت (خاص حرارت کی صلاحیت J/(kg·K))",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "خفیہ حرارت",
      equation_text: "Q = mL",
      summary: "خفیہ حرارت حساب کرتا ہے (Q = mL)",
      description: "مادے کی حالت کی تبدیلی کے دوران منتقل ہونے والی حرارت حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Q: "خفیہ حرارت (انرجی J)",
         m: "ماس (ماس kg)",
         L: "خفیہ حرارت (خاص انرجی J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "مثالی گیس کا قانون",
      equation_text: "PV = nRT",
      summary: "مثالی گیس کے قانون کی توثیق کرتا ہے (PV = nRT)",
      description:
         "دیئے گئے پیرامیٹرز کے لیے مثالی گیس کے قانون کی مساوات درست ہے یا نہیں، جانچ پڑتال کرتا ہے۔ بولین ویلیو لوٹاتا ہے۔ نوٹ - سختی سے مساوات (===) استعمال کرتا ہے جو فلوٹنگ پوائنٹ کی درستگی کے لیے حساس ہوسکتی ہے۔ حقیقی دنیا کی جانچ کے لیے رواداری پر غور کریں۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "دباؤ (دباؤ Pa)",
         V: "حجم (حجم m³)",
         n: "مولز کی تعداد (مادے کی مقدار mol)",
         R: "مثالی گیس مستقل (مستقل J/(mol·K))",
         T: "درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "مالیکیولر حرکی توانائی",
      equation_text: "KE_avg = (3/2)kT",
      summary: "اوسط مالیکیولر حرکی توانائی حساب کرتا ہے (KE = (3/2)kT)",
      description: "مثالی گیس کے فی مالیکیول اوسط انتقالی حرکی توانائی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE_avg: "اوسط مالیکیولر حرکی توانائی (انرجی J)",
         k: "بولٹزمین مستقل (مستقل J/K)",
         T: "درجہ حرارت (درجہ حرارت K)",
         m: "ایک مالیکیول کا ماس (ماس kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "مالیکیولر رفتار (سب سے ممکنہ)",
      equation_text: "v_p = √(2kT/m)",
      summary: "سب سے ممکنہ مالیکیولر رفتار حساب کرتا ہے (v_p = √(2kT/m))",
      description:
         "میکسویل-بولٹزمین تقسیم کے مطابق مثالی گیس میں مالیکیولوں کی سب سے ممکنہ رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_p: "سب سے ممکنہ مالیکیولر رفتار (رفتار m/s)",
         k: "بولٹزمین مستقل (مستقل J/K)",
         T: "درجہ حرارت (درجہ حرارت K)",
         m: "ایک مالیکیول کا ماس (ماس kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "مالیکیولر رفتار (اوسط)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "اوسط مالیکیولر رفتار حساب کرتا ہے (v_avg = √(8kT/(πm)))",
      description:
         "میکسویل-بولٹزمین تقسیم کے مطابق مثالی گیس میں مالیکیولوں کی اوسط رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_avg: "اوسط مالیکیولر رفتار (رفتار m/s)",
         k: "بولٹزمین مستقل (مستقل J/K)",
         T: "درجہ حرارت (درجہ حرارت K)",
         π: "پائی (بے ابعادی مستقل)",
         m: "ایک مالیکیول کا ماس (ماس kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "مالیکیولر رفتار (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "مالیکیولر رفتار جذر اوسط مربع حساب کرتا ہے (v_rms = √(3kT/m))",
      description:
         "میکسویل-بولٹزمین تقسیم کے مطابق مثالی گیس میں مالیکیولوں کی جذر اوسط مربع رفتار حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v_rms: "مالیکیولر رفتار جذر اوسط مربع (رفتار m/s)",
         k: "بولٹزمین مستقل (مستقل J/K)",
         T: "درجہ حرارت (درجہ حرارت K)",
         m: "ایک مالیکیول کا ماس (ماس kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "اندرونی توانائی میں تبدیلی",
      equation_text: "ΔU = Q - W",
      summary: "مثالی مونو اٹمک گیس کے لیے اندرونی توانائی میں تبدیلی حساب کرتا ہے (ΔU = (3/2)nRΔT)",
      description:
         "درجہ حرارت میں تبدیلی سے گزرنے والے مونو اٹمک مثالی گیس کے لیے اندرونی توانائی میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         ΔU: "اندرونی توانائی میں تبدیلی (انرجی J)",
         n: "مولز کی تعداد (مادے کی مقدار mol)",
         R: "مثالی گیس مستقل (مستقل J/(mol·K))",
         ΔT: "درجہ حرارت میں تبدیلی (درجہ حرارت کا فرق K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "تھرموڈائنامک کام",
      equation_text: "W = PΔV (مستقل دباؤ)",
      summary: "مستقل دباؤ پر نظام کے ذریعے کیا گیا تھرموڈائنامک کام حساب کرتا ہے (W = -PΔV)",
      description:
         "مستقل دباؤ پر تھرموڈائنامک عمل کے دوران نظام کے ذریعے کیا گیا یا اس پر کیا گیا کام حساب کرتا ہے۔ نوٹ - مساوات نظام کے ذریعہ کیا گیا کام حساب کرتی ہے، پھیلاؤ کے لیے مثبت، دباؤ کے لیے منفی۔ فنکشن -P*deltaV لوٹاتا ہے، جو W = PΔV مساوات کے مطابق نظام کے ذریعہ کیے گئے کام کے مطابق ہے، جس میں ایک اضافی منفی علامت شامل ہے جو کنونشن کے لحاظ سے نظام پر کیے گئے کام کو ظاہر کر سکتی ہے۔ فنکشن کے آؤٹ پٹ کو دستاویز کر رہا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         W: "تھرموڈائنامک کام (انرجی J)",
         P: "دباؤ (دباؤ Pa)",
         ΔV: "حجم میں تبدیلی (حجم m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "اصل کارکردگی",
      equation_text: "η = W_out / Q_in",
      summary: "اصلی انجن کی کارکردگی حساب کرتا ہے (η_real = 1 - (Q_C / Q_H))",
      description: "جذب شدہ اور مسترد شدہ حرارت کی بنیاد پر حرارتی انجن کی حرارتی کارکردگی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         η: "کارکردگی (بے ابعادی)",
         Q_H: "گرم ریزروائر سے جذب شدہ حرارت (انرجی J)",
         Q_C: "سرد ریزروائر کو مسترد شدہ حرارت (انرجی J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "مثالی کارکردگی",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "مثالی کارکردگی (کارنو) حساب کرتا ہے (η_ideal = 1 - (T_C / T_H))",
      description:
         "دو درجہ حرارت کے درمیان کام کرنے والے حرارتی انجن کی زیادہ سے زیادہ نظریاتی کارکردگی (کارنو کارکردگی) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         η_ideal: "مثالی کارکردگی (بے ابعادی)",
         T_hot: "گرم ریزروائر کا درجہ حرارت (درجہ حرارت K)",
         T_cold: "سرد ریزروائر کا درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "اصلی پرفارمنس کوفیشینٹ (COP)",
      equation_text: "COP_ref = Q_c / W (ری فریجریٹر)",
      summary: "اصلی ری فریجریٹر کے لیے پرفارمنس کوفیشینٹ حساب کرتا ہے (COP_real = QC / (QH - QC))",
      description: "ایک اصلی ری فریجریٹر یا ہیٹ پمپ کے لیے پرفارمنس کوفیشینٹ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         COP_real: "پرفارمنس کوفیشینٹ (بے ابعادی)",
         Q_C: "سرد ریزروائر سے حرارت (انرجی J)",
         Q_H: "گرم ریزروائر کو حرارت (انرجی J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "مثالی پرفارمنس کوفیشینٹ (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "مثالی ری فریجریٹر کے لیے پرفارمنس کوفیشینٹ حساب کرتا ہے (COP_ideal = TC / (TH - TC))",
      description:
         "دو درجہ حرارت کے درمیان کام کرنے والے ری فریجریٹر یا ہیٹ پمپ کے لیے زیادہ سے زیادہ نظریاتی پرفارمنس کوفیشینٹ حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         COP_ideal: "مثالی پرفارمنس کوفیشینٹ (بے ابعادی)",
         T_h: "گرم ریزروائر کا درجہ حرارت (درجہ حرارت K)",
         T_c: "سرد ریزروائر کا درجہ حرارت (درجہ حرارت K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "موقتی لہر کی رفتار",
      equation_text: "v = fλ",
      summary: "لہر کی رفتار حساب کرتا ہے (v = fλ)",
      description: "موقتی لہر کی رفتار حساب کرتا ہے جو اس کی فریکوئنسی اور طول موج پر مبنی ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         v: "لہر کی رفتار (رفتار m/s)",
         f: "فریکوئنسی (فریکوئنسی Hz)",
         λ: "طول موج (لمبائی m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "لہر کی شدت",
      equation_text: "I = P / A",
      summary: "شدت حساب کرتا ہے (I = P/A)",
      description: "لہر کی شدت (فی یونٹ رقبہ پاور) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         I: "شدت (شدت W/m²)",
         P: "پاور (پاور W)",
         A: "رقبہ (رقبہ m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "شدت کی سطح (ڈیسیبل)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "ڈیسیبل میں شدت کی سطح حساب کرتا ہے (L = 10 log10(I/I0))",
      description: "حوالہ شدہ شدت کی نسبت شدت کی سطح (آواز کی شدت کی سطح) حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         β: "شدت کی سطح (شدت کی سطح dB)",
         I: "شدت (شدت W/m²)",
         I0: "حوالہ شدہ شدت (شدت W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "دباؤ کی سطح (آواز دباؤ کی سطح)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "ڈیسیبل میں آواز دباؤ کی سطح حساب کرتا ہے (L = 20 log10(ΔP/ΔP0))",
      description: "حوالہ شدہ دباؤ تبدیلی کے نسبت آواز دباؤ کی سطح حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         L_p: "آواز دباؤ کی سطح (دباؤ کی سطح dB)",
         P_rms: "RMS دباؤ فلکچویشن (دباؤ Pa)",
         P_ref: "حوالہ شدہ دباؤ (دباؤ Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "ڈوپلر اثر (آواز/غیر نسبتی)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "ڈوپلر اثر رفتار فیکٹر حساب کرتا ہے ((c + v_o) / (c - v_s))",
      description:
         "ڈوپلر اثر مساوات کے رفتار فیکٹر کا حصہ (f' = f * factor) حساب کرتا ہے۔ مشاہدہ کار کی ذریعہ کی طرف حرکت کے لیے، ذریعہ کی مشاہدہ کار کی طرف حرکت کے لیے مثبت رفتار۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         f_obs: "مشاہدہ شدہ فریکوئنسی (فریکوئنسی Hz)",
         f_source: "ماخذ فریکوئنسی (فریکوئنسی Hz)",
         v_wave: "لہر کی رفتار (رفتار m/s)",
         v_observer: "میڈیم کے نسبت مشاہدہ کار کی رفتار (رفتار m/s)",
         v_source: "میڈیم کے نسبت ماخذ کی رفتار (رفتار m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "ماخ زاویہ",
      equation_text: "sin(μ) = 1 / M",
      summary: "ماخ زاویہ حساب کرتا ہے (θ_M = arcsin(c/v))",
      description:
         "آواز کی رفتار سے تیز حرکت کرنے والی شے کے ذریعہ بننے والے ماخ مخروط کا زاویہ حساب کرتا ہے۔ زاویہ ریڈیان میں لوٹاتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         μ: "ماخ زاویہ (زاویہ rad)",
         M: "ماخ نمبر (بے ابعادی)",
         c: "آواز کی رفتار (رفتار m/s)",
         v: "شے کی رفتار (رفتار m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "کام",
      equation_text: "W = Fdcos(θ)",
      summary: "کیا گیا کام حساب کرتا ہے (W = F * Δs * cos(θ))",
      description: "قوت، بے گھری اور ان کے درمیان زاویہ کی بنیاد پر کیا گیا کام حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         W: "کیا گیا کام (انرجی J)",
         F: "قوت کی مقدار (قوت N)",
         d: "بے گھری کی مقدار (لمبائی m)",
         θ: "قوت اور بے گھری کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "حرکی توانائی",
      equation_text: "KE = ½mv²",
      summary: "حرکی توانائی حساب کرتا ہے (KE = 0.5 * m * v^2)",
      description: "ماس اور رفتار کی بنیاد پر حرکی توانائی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE: "حرکی توانائی (انرجی J)",
         m: "ماس (ماس kg)",
         v: "رفتار (رفتار m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "حرکی توانائی (مومنٹم سے)",
      equation_text: "KE = p² / (2m)",
      summary: "مومنٹم سے حرکی توانائی حساب کرتا ہے (KE = p^2 / (2m))",
      description: "مومنٹم اور ماس کی بنیاد پر حرکی توانائی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         KE: "حرکی توانائی (انرجی J)",
         p: "مومنٹم (مومنٹم kg·m/s)",
         m: "ماس (ماس kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "کشش ثقل کی پوٹینشل انرجی",
      equation_text: "U_g = mgh (سطح کے قریب)",
      summary: "کشش ثقل کی پوٹینشل انرجی حساب کرتا ہے (PE = mgh)",
      description: "کشش ثقل کی پوٹینشل انرجی میں تبدیلی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         U_g: "کشش ثقل کی پوٹینشل انرجی (انرجی J)",
         m: "ماس (ماس kg)",
         g: "کشش ثقل کا تسارع (تسارع m/s²)",
         h: "اونچائی (لمبائی m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "کارکردگی",
      equation_text: "کارکردگی = آؤٹ پٹ / ان پٹ",
      summary: "کارکردگی حساب کرتا ہے (η = W_out / W_in)",
      description: "کسی عمل یا مشین کی کارکردگی حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         Efficiency: "کارکردگی (بے ابعادی)",
         Output: "مفید آؤٹ پٹ توانائی یا پاور (انرجی J یا پاور W)",
         Input: "کل ان پٹ توانائی یا پاور (انرجی J یا پاور W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "پاور",
      equation_text: "P = W / t",
      summary: "پاور حساب کرتا ہے (P = ΔW / Δt)",
      description: "کام اور وقت میں تبدیلی کی بنیاد پر اوسط پاور حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "پاور (پاور W)",
         ΔW: "کام میں تبدیلی (انرجی J)",
         Δt: "وقت کا وقفہ (وقت s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "پاور (P = Fv)",
      equation_text: "P = Fv",
      summary: "قوت اور رفتار سے پاور حساب کرتا ہے (P = Fv cos(θ))",
      description: "قوت، رفتار اور ان کے درمیان زاویہ کی بنیاد پر فوری پاور حساب کرتا ہے۔",
      language_code: "ur",
      subject: "Physics",
      variables: {
         P: "پاور (پاور W)",
         F: "قوت کی مقدار (قوت N)",
         v: "رفتار کی مقدار (رفتار m/s)",
         θ: "قوت اور رفتار کے درمیان زاویہ (زاویہ rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = ur;