const zh = [
   {
      equation_id: "centripetal-acceleration",
      name: "向心加速度",
      equation_text: "a_c = v² / r",
      summary: "计算向心加速度 (a_c = v^2 / r)",
      description:
         "利用线速度和半径计算指向圆周路径中心的加速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         a_c: "向心加速度 (加速度 m/s²)",
         v: "线速度 (速度 m/s)",
         r: "圆周路径的半径 (长度 m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "向心加速度 (角速度)",
      equation_text: "a_c = ω²r",
      summary: "利用角速度计算向心加速度 (a_c = -ω^2 * r)",
      description:
         "利用角速度和半径计算向心加速度矢量分量。负号表示指向中心的方向。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         a_c: "向心加速度 (加速度 m/s²)",
         ω: "角速度 (角速度 rad/s)",
         r: "圆周路径的半径 (长度 m)",
      },
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "库仑定律 (力)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "利用库仑定律计算电力 (F = k * q1*q2 / r^2)",
      description:
         "计算两个点电荷之间的电力。返回带符号的力（斥力为正，引力为负）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F: "电力 (力 N)",
         k: "库仑常数 (常数 N·m²/C²)",
         q1: "电荷 1 (电荷 C)",
         q2: "电荷 2 (电荷 C)",
         r: "电荷间的距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "电场",
      equation_text: "E = kq / r² (点电荷)",
      summary: "从力计算电场 (E = F_E/q)",
      description: "根据施加在测试电荷上的力来计算电场强度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "电场大小 (电场 N/C)",
         k: "库仑常数 (常数 N·m²/C²)",
         q: "源电荷 (电荷 C)",
         r: "源电荷的距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "电位",
      equation_text: "V = kq / r (点电荷)",
      summary: "从势能变化计算电位 (V = ΔU_E/q)",
      description:
         "根据单位电荷的电势能变化计算电位（电压）。注意 - 函数名 `calculateElectricPotential` 是正确的，但参数 `deltaUE` 意味着变化，而等式通常是 V=U_E/q 或 ΔV=ΔU_E/q。根据等式 ΔV = ΔU_E/q 进行文档说明并返回 ΔV。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         V: "电位 (电压 V)",
         k: "库仑常数 (常数 N·m²/C²)",
         q: "源电荷 (电荷 C)",
         r: "源电荷的距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "电场和电位关系",
      equation_text: "E_x = -dV/dx",
      summary: "从电位差计算电场 (E = ΔV/d)",
      description:
         '根据距离上的电位差计算均匀电场的强度。注意 - 函数名“Field and Potential”（场和电位）有误导性；它计算电场 E。',
      language_code: "zh",
      subject: "Physics",
      variables: {
         E_x: "电场分量 (电场 V/m)",
         V: "电位 (电压 V)",
         x: "位置 (长度 m)",
         ΔV: "电位差 (电压 V)",
         d: "距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "电容",
      equation_text: "C = Q / V",
      summary: "计算电容 (C = Q/V)",
      description: "根据储存的电荷和电容器两端的电压计算电容。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C: "电容 (电容 F)",
         Q: "电荷 (电荷 C)",
         V: "电压 (电压 V)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "平行板电容器电容",
      equation_text: "C = ε₀A / d",
      summary: "计算平行板电容器电容 (C = (kε₀A)/d)",
      description:
         "计算带有介电质的平行板电容器的电容。注意 - 函数使用 k * ε₀ 作为单一输入 (`kEpsilon`)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C: "电容 (电容 F)",
         ε0: "自由空间的介电常数 (常数 F/m)",
         k: "介电常数 (无量纲)",
         A: "极板面积 (面积 m²)",
         d: "极板间距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "圆柱形电容器电容",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "计算圆柱形电容器电容 (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "计算带有介电质的圆柱形电容器的电容。注意 - 函数使用 k * ε₀ 作为单一输入 (`kEpsilon`)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C: "电容 (电容 F)",
         π: "圆周率 (无量纲常数)",
         ε0: "自由空间的介电常数 (常数 F/m)",
         k: "介电常数 (无量纲)",
         L: "圆柱体长度 (长度 m)",
         b: "外半径 (长度 m)",
         a: "内半径 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "球形电容器电容",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "计算球形电容器电容 (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "计算带有介电质的球形电容器的电容。注意 - 函数使用 k * ε₀ 作为单一输入 (`kEpsilon`)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C: "电容 (电容 F)",
         π: "圆周率 (无量纲常数)",
         ε0: "自由空间的介电常数 (常数 F/m)",
         k: "介电常数 (无量纲)",
         a: "内半径 (长度 m)",
         b: "外半径 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "电容器势能",
      equation_text: "U_C = ½CV²",
      summary: "验证电容器势能等式 (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "检查对于给定的Q、V和C，电容器中存储的势能的三个常见等式是否等效。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         U_C: "电容器势能 (能量 J)",
         Q: "电荷 (电荷 C)",
         V: "电压 (电压 V)",
         C: "电容 (电容 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "电流",
      equation_text: "I = ΔQ / Δt",
      summary: "计算电流 (I = ΔQ/Δt)",
      description: "根据单位时间内通过某点的电荷量计算电流。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         I: "电流 (电流 A)",
         ΔQ: "电荷的变化 (电荷 C)",
         Δt: "时间的变化 (时间 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "电荷密度",
      equation_text: "ρ = Q / V (体积)",
      summary: "计算电荷密度 (ρ = Q/V)",
      description: "计算平均电荷密度（单位体积的电荷）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ρ: "体积电荷密度 (电荷密度 C/m³)",
         Q: "总电荷 (电荷 C)",
         V: "体积 (体积 m³)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "电流密度",
      equation_text: "J = I / A",
      summary: "计算电流密度 (J = I/A)",
      description: "计算电流密度（单位横截面积的电流）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         J: "电流密度 (电流密度 A/m²)",
         I: "电流 (电流 A)",
         A: "面积 (面积 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "欧姆定律",
      equation_text: "V = IR",
      summary: "利用欧姆定律计算电阻 (R = V/I)",
      description:
         "根据电压和电流计算电阻。注意 - 函数根据 V 和 I 计算电阻 R。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         V: "电压 (电压 V)",
         I: "电流 (电流 A)",
         R: "电阻 (电阻 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "电阻率和电导率",
      equation_text: "ρ = RA / L",
      summary: "从电阻率计算电导率 (σ = 1/ρ)",
      description: "从电阻率 (ρ) 计算电导率 (σ)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         σ: "电导率 (电导率 S/m)",
         ρ: "电阻率 (电阻率 Ω·m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "电阻",
      equation_text: "R = ρL / A",
      summary: "计算电阻 (R = ρ(l/A))",
      description:
         "根据导体的电阻率、长度和横截面积计算其电阻。注意 - 使用 `rhoValue` 表示电阻率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         R: "电阻 (电阻 Ω)",
         ρ: "电阻率 (电阻率 Ω·m)",
         L: "长度 (长度 m)",
         A: "横截面积 (面积 m²)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "电功率",
      equation_text: "P = IV",
      summary: "验证电功率等式 (P = VI = I^2R = V^2/R)",
      description:
         "检查对于给定的V、I和R，电功率的三个常见等式是否等效。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "电功率 (功率 W)",
         V: "电压 (电压 V)",
         I: "电流 (电流 A)",
         R: "电阻 (电阻 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "串联电阻",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "计算串联电阻的总电阻 (R_total = R1 + R2 + ...)",
      description: "计算多个串联电阻的总等效电阻。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         R_total: "总电阻 (电阻 Ω)",
         R: "单个电阻 (电阻 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "并联电阻",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "计算并联电阻的总电阻 (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "计算多个并联电阻的总等效电阻。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         R_total: "总电阻 (电阻 Ω)",
         R: "单个电阻 (电阻 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "串联电容器",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "计算串联电容器的总电容 (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "计算多个串联电容器的总等效电容。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C_total: "总电容 (电容 F)",
         C: "单个电容 (电容 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "并联电容器",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "计算并联电容器的总电容 (C_total = C1 + C2 + ...)",
      description: "计算多个并联电容器的总等效电容。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         C_total: "总电容 (电容 F)",
         C: "单个电容 (电容 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "电荷上的磁力",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "计算带电粒子上的磁力 (F = qvB sin(θ))",
      description:
         "计算运动的带电粒子所受磁力的强度。角度应为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F_B: "磁力大小 (力 N)",
         q: "电荷大小 (电荷 C)",
         v: "速度大小 (速度 m/s)",
         B: "磁场大小 (磁场 T)",
         θ: "速度与磁场之间的角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "电流上的磁力",
      equation_text: "F_B = ILBsin(θ)",
      summary: "计算载流导体上的磁力 (F = I l B sin(θ))",
      description:
         "计算在磁场中载流的直线导体所受磁力的强度。角度应为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F_B: "磁力大小 (力 N)",
         I: "电流 (电流 A)",
         L: "导体长度 (长度 m)",
         B: "磁场大小 (磁场 T)",
         θ: "电流与磁场之间的角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "毕奥-萨伐尔定律",
      equation_text: "B = μ₀I / (2πr) (无限长直线电流)",
      summary: "计算电流元产生的磁场 (dB = (μ₀I ds) / (4πr^2))",
      description:
         "计算垂直于径向向量的微小电流元对磁场的贡献大小。注意 - 函数实现了 `(μ₀ * I * ds) / (4 * π * r^2)`，省略了微分形式中常有的 sin(θ) 项，实际上假定 θ=90 度或只计算特定平面中垂直于径向向量的成分。文档基于函数实现进行说明。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         dB: "磁场贡献大小 (磁场 T)",
         μ0: "自由空间磁导率 (常数 T·m/A)",
         I: "电流 (电流 A)",
         ds: "电流元的微小长度 (长度 m)",
         r: "电流元的距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "螺线管的磁场",
      equation_text: "B = μ₀nI (内部, 理想)",
      summary: "计算长螺线管内部的磁场 (B = μ₀nI)",
      description: "计算长理想螺线管内部磁场的强度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         B: "螺线管内部磁场强度 (磁场 T)",
         μ0: "自由空间磁导率 (常数 T·m/A)",
         n: "单位长度匝数 (每长度 m⁻¹)",
         I: "电流 (电流 A)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "直线电流的磁场",
      equation_text: "B = μ₀I / (2πr) (无限长导线)",
      summary: "计算无限长直线电流产生的磁场 (B = (μ₀I)/(2πr))",
      description:
         "计算长直导体中电流产生的磁场强度，距导体一定距离处。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         B: "直线电流产生的磁场强度 (磁场 T)",
         μ0: "自由空间磁导率 (常数 T·m/A)",
         I: "电流 (电流 A)",
         π: "圆周率 (无量纲常数)",
         r: "距导线的距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "平行导线间的力",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "计算平行导线间的单位长度力 (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "计算两个长直平行导体中电流产生的单位长度的力的强度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         "F/L": "单位长度力 (每长度力 N/m)",
         μ0: "自由空间磁导率 (常数 T·m/A)",
         I1: "导线 1 中的电流 (电流 A)",
         I2: "导线 2 中的电流 (电流 A)",
         π: "圆周率 (无量纲常数)",
         d: "导线间距离 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "电通量",
      equation_text: "Φ_E = EAcos(θ) (E 均匀)",
      summary: "计算电通量 (Φ_E = E * A * cos(θ))",
      description:
         "计算均匀电场中通过平面的电通量。角度应为电场矢量和面积矢量之间的角度，单位为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Φ_E: "电通量 (电通量 N·m²/C)",
         E: "电场大小 (电场 N/C)",
         A: "面积 (面积 m²)",
         θ: "E 和面积矢量之间的角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "磁通量",
      equation_text: "Φ_B = BAcos(θ) (B 均匀)",
      summary: "计算磁通量 (Φ_B = B * A * cos(θ))",
      description:
         "计算均匀磁场中通过平面的磁通量。角度应为磁场矢量和面积矢量之间的角度，单位为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Φ_B: "磁通量 (磁通量 Wb)",
         B: "磁场大小 (磁场 T)",
         A: "面积 (面积 m²)",
         θ: "B 和面积矢量之间的角度 (角度 rad)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "动生电动势",
      equation_text: "ε = vBL (直线导体)",
      summary: "计算动生电动势 (emf = Blv)",
      description:
         "计算垂直于磁场运动的导体中感应电动势的大小。注意 - 函数计算的是 Blv 的大小，省略了有时用于表示方向的负号（楞次定律）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ε: "动生电动势大小 (电压 V)",
         v: "导体速度 (速度 m/s)",
         B: "磁场大小 (磁场 T)",
         L: "导体长度 (长度 m)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "感应电动势 (法拉第定律)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "从变化的磁通量计算感应电动势 (emf = -ΔΦ_B / Δt)",
      description: "根据法拉第电磁感应定律，计算变化磁通量引起的感应电动势。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ε: "感应电动势 (电压 V)",
         ΔΦ_B: "磁通量的变化 (磁通量 Wb)",
         Δt: "时间的变化 (时间 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "电感产生的感应电动势",
      equation_text: "ε_L = -L dI / dt",
      summary: "计算电感器中电流变化产生的感应电动势 (emf = -L * ΔI / Δt)",
      description:
         "计算电感器中由于电流变化而产生的自感电动势。注意 - 函数名称是 `calculateInductance` 但使用此等式返回电动势。文档记录了它返回的内容。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ε_L: "电感器中的感应电动势 (电压 V)",
         L: "电感 (电感 H)",
         ΔI: "电流的变化 (电流 A)",
         Δt: "时间的变化 (时间 s)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "容抗",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "计算容抗 (X_C = 1/(2πfC))",
      description: "计算电容器对交流电的阻抗。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         X_C: "容抗 (电抗 Ω)",
         π: "圆周率 (无量纲常数)",
         f: "频率 (频率 Hz)",
         C: "电容 (电容 F)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "感抗",
      equation_text: "X_L = 2πfL",
      summary: "计算感抗 (X_L = 2πfL))",
      description: "计算电感器对交流电的阻抗。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         X_L: "感抗 (电抗 Ω)",
         π: "圆周率 (无量纲常数)",
         f: "频率 (频率 Hz)",
         L: "电感 (电感 H)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "阻抗",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "计算阻抗 (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "计算包含电阻、感抗和容抗的交流电路中总的电流阻抗。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Z: "阻抗 (阻抗 Ω)",
         R: "电阻 (电阻 Ω)",
         X_L: "感抗 (电抗 Ω)",
         X_C: "容抗 (电抗 Ω)",
      },
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "密度",
      equation_text: "ρ = m / V",
      summary: "计算密度 (ρ = m/V)",
      description: "根据质量和体积计算密度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ρ: "密度 (密度 kg/m³)",
         m: "质量 (质量 kg)",
         V: "体积 (体积 m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "压力",
      equation_text: "P = F / A",
      summary: "计算压力 (P = F/A)",
      description: "根据作用在面积上的力计算压力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "压力 (压力 Pa)",
         F: "力 (力 N)",
         A: "面积 (面积 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "流体中的压力",
      equation_text: "P = P₀ + ρgh",
      summary: "计算流体中的压力 (P = P0 + ρgh)",
      description: "计算流体中特定深度的绝对压力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "绝对压力 (压力 Pa)",
         P0: "大气压或表面压力 (压力 Pa)",
         ρ: "流体密度 (密度 kg/m³)",
         g: "重力加速度 (加速度 m/s²)",
         h: "深度 (长度 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "浮力",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "计算浮力 (F_b = ρgV_displaced)",
      description:
         "计算流体对浸没或部分浸没物体的浮力（阿基米德原理）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F_B: "浮力 (力 N)",
         ρ_fluid: "流体密度 (密度 kg/m³)",
         V_submerged: "浸没体积 (体积 m³)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "质量流量",
      equation_text: "ṁ = ρAv",
      summary: "计算质量流量 (ṁ = Δm/Δt)",
      description: "计算单位时间通过某点的质量速率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ṁ: "质量流量 (质量流量 kg/s)",
         ρ: "流体密度 (密度 kg/m³)",
         A: "面积 (面积 m²)",
         v: "流体速度 (速度 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "体积流量",
      equation_text: "Q = Av",
      summary: "计算体积流量 (Q = ΔV/Δt)",
      description: "计算单位时间通过某点的体积速率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Q: "体积流量 (体积流量 m³/s)",
         A: "面积 (面积 m²)",
         v: "流体速度 (速度 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "伯努利方程",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "检查伯努利方程 (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "验证对于两个点上的给定流体性质和条件，伯努利方程是否成立。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "压力 (压力 Pa)",
         ρ: "流体密度 (密度 kg/m³)",
         v: "流体速度 (速度 m/s)",
         g: "重力加速度 (加速度 m/s²)",
         y: "高度 (长度 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "动力粘度",
      equation_text: "τ = μ * (dv/dy)",
      summary: "计算动力粘度 (η = F * Δy / (A * Δvx))",
      description:
         "根据力、速度梯度和面积计算动力粘度。该等式来源于剪切应力/应变率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         μ: "动力粘度 (动力粘度 Pa·s)",
         F: "力 (力 N)",
         Δy: "垂直于流动的距离 (长度 m)",
         A: "面积 (面积 m²)",
         Δvx: "速度的变化 (速度 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "运动粘度",
      equation_text: "ν = μ / ρ",
      summary: "计算运动粘度 (ν = η / ρ)",
      description: "从动力粘度和密度计算运动粘度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ν: "运动粘度 (运动粘度 m²/s)",
         μ: "动力粘度 (动力粘度 Pa·s)",
         ρ: "流体密度 (密度 kg/m³)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "阻力",
      equation_text: "F_D = ½ρv²CdA",
      summary: "计算阻力 (F_d = 0.5 * ρ * C_A * v^2)",
      description: "计算物体在流体中运动时受到的阻力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F_D: "阻力 (力 N)",
         ρ: "流体密度 (密度 kg/m³)",
         v: "速度 (速度 m/s)",
         Cd: "阻力系数 (无量纲)",
         A: "参考面积 (面积 m²)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "马赫数",
      equation_text: "M = v / c_sound",
      summary: "计算马赫数 (M = v/c)",
      description: "计算马赫数，即物体速度与媒质中声速之比。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         M: "马赫数 (无量纲)",
         v: "物体速度 (速度 m/s)",
         c_sound: "媒质中声速 (速度 m/s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "雷诺数",
      equation_text: "Re = ρvd / μ",
      summary: "计算雷诺数 (Re = (ρ * v * D) / η)",
      description:
         "计算雷诺数，一个无量纲量，用于预测不同流体流动情况下的流动模式。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Re: "雷诺数 (无量纲)",
         ρ: "流体密度 (密度 kg/m³)",
         v: "速度 (速度 m/s)",
         d: "特征长度 (长度 m)",
         μ: "动力粘度 (动力粘度 Pa·s)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "弗劳德数",
      equation_text: "Fr = v / √(gL)",
      summary: "计算弗劳德数 (Fr = v / √(g * l))",
      description:
         "计算弗劳德数，一个无量纲量，用于指示重力对流体运动的影响。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Fr: "弗劳德数 (无量纲)",
         v: "速度 (速度 m/s)",
         g: "重力加速度 (加速度 m/s²)",
         L: "特征长度 (长度 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "表面张力",
      equation_text: "γ = F / L",
      summary: "计算表面张力 (γ = F / l)",
      description: "根据力和长度计算液体的表面张力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         γ: "表面张力 (表面张力 N/m)",
         F: "力 (力 N)",
         L: "长度 (长度 m)",
      },
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "万有引力 (力)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "计算万有引力 (F = -Gm1m2/r^2)",
      description:
         "计算两个点质量之间的引力。注意 - 返回负值表示引力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F: "万有引力 (力 N)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         m1: "质量 1 (质量 kg)",
         m2: "质量 2 (质量 kg)",
         r: "质量间的距离 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "引力场",
      equation_text: "g = GM / r² (大小)",
      summary: "计算引力场 (g = -Gm/r^2)",
      description:
         "计算距离点质量一定距离处的引力场强度。注意 - 返回负值表示指向质量的方向。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         g: "引力场强度大小 (引力场 N/kg)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         M: "源质量 (质量 kg)",
         r: "源质量的距离 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "引力势能",
      equation_text: "U_g = -G m₁m₂ / r (一般)",
      summary: "计算两个质量之间的引力势能 (PE = -Gm1m2/r)",
      description: "计算两个点质量系统的引力势能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         U_g: "引力势能 (能量 J)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         m1: "质量 1 (质量 kg)",
         m2: "质量 2 (质量 kg)",
         r: "质量间的距离 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "引力势",
      equation_text: "V_g = -GM / r",
      summary: "计算引力势 (V_g = -Gm/r)",
      description: "计算距离点质量一定距离处的引力势。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         V_g: "引力势 (引力势 J/kg)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         M: "源质量 (质量 kg)",
         r: "源质量的距离 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "轨道速度",
      equation_text: "v_orbit = √(GM / r) (圆轨道)",
      summary: "计算轨道速度 (v = sqrt(Gm/r))",
      description: "计算物体在较大质量周围圆形轨道中的速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_orbit: "轨道速度 (速度 m/s)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         M: "中心体质量 (质量 kg)",
         r: "轨道半径 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "逃逸速度",
      equation_text: "v_escape = √(2GM / r)",
      summary: "计算逃逸速度 (v = sqrt(2Gm/r))",
      description:
         "计算从给定距离逃离质量的引力所需的最小速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_escape: "逃逸速度 (速度 m/s)",
         G: "万有引力常数 (常数 N·m²/kg²)",
         M: "中心体质量 (质量 kg)",
         r: "距中心距离 (长度 m)",
      },
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "热传导",
      equation_text: "Q/t = kAΔT/d",
      summary: "计算热传导率 (Q/t = (kAΔT) / L)",
      description:
         "计算通过材料传导传热的速率。注意 - 函数计算 Q，假设时间间隔是由等式通常用于速率而暗示的。文档说明 Q，但等式通常用于 Q/t。正在澄清这种区别。函数返回速率等式右侧的结果。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         "Q/t": "热传导率 (功率 W)",
         k: "热导率 (热导率 W/(m·K))",
         A: "面积 (面积 m²)",
         ΔT: "温度差 (温度差 K)",
         d: "厚度 (长度 m)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "斯特藩-玻尔兹曼定律",
      equation_text: "P = εσAT⁴",
      summary: "计算热辐射功率 (P = εσA(T^4 - T0^4))",
      description: "计算物体考虑其周围环境的净辐射能量率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "净辐射功率 (功率 W)",
         ε: "发射率 (无量纲)",
         σ: "斯特藩-玻尔兹曼常数 (常数 W/(m²·K⁴))",
         A: "表面积 (面积 m²)",
         T: "物体温度 (温度 K)",
         T0: "环境温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "维恩位移定律 (最大波长)",
      equation_text: "λ_max = b/T",
      summary: "利用维恩定律计算峰值波长 (λ_max = b/T)",
      description: "计算黑体发射光谱达到最大值的波长。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         λ_max: "峰值发射波长 (长度 m)",
         b: "维恩位移常数 (常数 m·K)",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "维恩位移定律 (最大频率)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "利用维恩定律计算峰值频率 (f_max = b' * T)",
      description:
         "计算黑体发射光谱达到最大值的频率。注意 - 此版本使用修正的维恩常数 b'。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f_max: "峰值发射频率 (频率 Hz)",
         "b'": "修正维恩常数 (常数 Hz/K)",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "公式信息 (特定)",
      equation_text: "不适用 (检索信息，不计算)",
      summary: "按ID和语言获取公式信息",
      description:
         "根据其唯一ID和所需的语言检索特定公式的详细信息。注意 - 语言从“language_code”路径参数中提取。代码片段中显示的内部逻辑也查找“lang”查询参数，但此Swagger定义文档说明了主要的路径参数。",
      language_code: "zh",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "获取API中的所有公式端点。",
      description: "检索API中所有端点的摘要信息。",
      language_code: "zh",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "速度",
      equation_text: "v = Δx / Δt",
      summary: "计算速度",
      description: "根据位移和时间计算速度 (v = Δs / Δt)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v: "速度 (速度 m/s)",
         Δx: "位移 (长度 m)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "加速度",
      equation_text: "a = Δv / Δt",
      summary: "计算加速度",
      description: "根据速度变化和时间计算加速度 (a = Δv / Δt)。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         a: "加速度 (加速度 m/s²)",
         Δv: "速度的变化 (速度 m/s)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "运动学方程 (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "计算末速度 (v = v0 + at)",
      description: "使用第一个运动学方程计算末速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v: "末速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
         a: "加速度 (加速度 m/s²)",
         t: "时间 (时间 s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "运动学方程 (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "计算末位置 (s = s0 + v0t + 0.5at^2)",
      description: "使用第二个运动学方程计算末位置。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         s: "末位置 (长度 m)",
         s0: "初位置 (长度 m)",
         v0: "初速度 (速度 m/s)",
         t: "时间 (时间 s)",
         a: "加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "运动学方程 (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "计算末速度平方 (v^2 = v0^2 + 2a(s - s0))",
      description: "使用第三个运动学方程计算末速度平方。注意 - 返回 v^2，而不是 v。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v: "末速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
         a: "加速度 (加速度 m/s²)",
         Δs: "位移 (长度 m)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "平均速度",
      equation_text: "v_avg = Δx / Δt",
      summary: "计算平均速度 (v_avg = 0.5 * (v + v0))",
      description: "假定恒定加速度计算平均速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_avg: "平均速度 (速度 m/s)",
         v: "末速度 (速度 m/s)",
         v0: "初速度 (速度 m/s)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "力 (牛顿第二定律)",
      equation_text: "F_net = ma",
      summary: "计算力 (F = ma)",
      description: "使用牛顿第二定律计算力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F_net: "合力 (力 N)",
         m: "质量 (质量 kg)",
         a: "加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "重量",
      equation_text: "W = mg",
      summary: "计算重量 (W = mg)",
      description: "计算物体受到的重力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         W: "重量 (力 N)",
         m: "质量 (质量 kg)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "最大静摩擦力",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "计算最大静摩擦力 (F_s = μ_s * N)",
      description: "计算可能的最大静摩擦力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f_s_max: "最大静摩擦力 (力 N)",
         μ_s: "静摩擦系数 (无量纲)",
         F_N: "支持力 (力 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "动摩擦力",
      equation_text: "f_k = μ_k * F_N",
      summary: "计算动摩擦力 (F_k = μ_k * N)",
      description: "计算作用在运动物体上的动摩擦力。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f_k: "动摩擦力 (力 N)",
         μ_k: "动摩擦系数 (无量纲)",
         F_N: "支持力 (力 N)",
      },
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "动量",
      equation_text: "p = mv",
      summary: "计算动量 (p = mv)",
      description: "计算物体的线形动量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         p: "动量 (动量 kg·m/s)",
         m: "质量 (质量 kg)",
         v: "速度 (速度 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "冲量",
      equation_text: "J = F_avg * Δt",
      summary: "计算冲量 (J = F * Δt)",
      description: "根据力和时间间隔计算冲量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         J: "冲量 (冲量 N·s)",
         F_avg: "平均力 (力 N)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "冲量-动量定理",
      equation_text: "J = Δp",
      summary: "验证冲量-动量定理 (F * Δt = m * Δv)",
      description: "检查冲量是否等于给定值下的动量变化。返回布尔值。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         J: "冲量 (冲量 N·s)",
         Δp: "动量的变化 (动量 kg·m/s)",
         F: "力 (力 N)",
         Δt: "时间间隔 (时间 s)",
         m: "质量 (质量 kg)",
         Δv: "速度的变化 (速度 m/s)",
      },
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "放射性活度",
      equation_text: "A = λN",
      summary: "计算放射性衰变的平均活度 (A_avg = ΔN/Δt)",
      description:
         "计算放射性样品在一段时间内的平均活度（衰变率）。注意 - 函数使用 `nValue` 表示核数 ΔN，使用 `tValue` 表示时间 Δt。这是 Δt 的简化平均值，瞬时活度为 dN/dt = -λN。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         A_avg: "平均放射性活度 (活度 Bq)",
         ΔN: "衰变数 (无量纲数)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "半衰期",
      equation_text: "T_½ = ln(2) / λ",
      summary: "计算衰变后的剩余量 (N = N0 * (1/2)^(t/T_half))",
      description:
         "根据物质的半衰期，计算经过一段时间后物质的剩余量。注意 - 时间使用 `tValue`，半衰期使用 `Thalf`。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         N: "剩余量/核 (数)",
         N0: "初始量/核 (数)",
         t: "经过的时间 (时间 s)",
         T_half: "半衰期 (时间 s)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "吸收剂量",
      equation_text: "D = dE / dm",
      summary: "计算吸收剂量 (D = E/m)",
      description:
         "根据质量吸收的能量计算放射线的吸收剂量。注意 - 能量使用 `EValue`，质量使用 `mValue`。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         D: "吸收剂量 (吸收剂量 Gy)",
         E: "吸收的能量 (能量 J)",
         m: "质量 (质量 kg)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "等效剂量",
      equation_text: "H = D * W_R",
      summary: "计算等效剂量 (H = wR * D)",
      description:
         "计算等效剂量，考虑不同类型放射线的生物学效应。注意 - 吸收剂量使用 `DValue`。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         H: "等效剂量 (等效剂量 Sv)",
         D: "吸收剂量 (吸收剂量 Gy)",
         W_R: "放射线加权因子 (无量纲)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "有效剂量",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "计算有效剂量 (E = wT * H)",
      description:
         "计算有效剂量，考虑不同组织/器官对放射线的敏感性。注意 - 等效剂量使用 `HValue`。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "有效剂量 (有效剂量 Sv)",
         H_T: "组织/器官 T 的等效剂量 (等效剂量 Sv)",
         W_T: "组织/器官 T 的组织加权因子 (无量纲)",
      },
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "切伦科夫角",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "计算切伦科夫角 (θ_C = arccos(c/nv_p))",
      description:
         "计算带电粒子在介质中速度超过光速时形成的切伦科夫锥的角度。返回角度为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         θ_C: "切伦科夫角 (角度 rad)",
         c: "真空中的光速 (速度 m/s)",
         n: "介质的折射率 (无量纲)",
         v: "粒子速度 (速度 m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "干涉条纹 (例如：位置、间距)",
      equation_text: "Δy = λL / d (双缝间距)",
      summary: "计算干涉条纹的位置 (y_n = (nλL)/d)",
      description: "计算杨氏双缝干涉图案中第 n 个亮条纹的位置。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         y_n: "第 n 个亮条纹的位置 (长度 m)",
         n: "条纹级数 (无量纲整数)",
         λ: "波长 (长度 m)",
         L: "到屏幕的距离 (长度 m)",
         d: "狭缝间距 (长度 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "折射率",
      equation_text: "n = c / v",
      summary: "计算折射率 (n = c/v)",
      description:
         "根据真空中的光速和介质中的光速计算介质的折射率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         n: "折射率 (无量纲)",
         c: "真空中的光速 (速度 m/s)",
         v: "介质中的光速 (速度 m/s)",
      },
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "斯涅耳定律",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "验证斯涅耳定律 (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "检查光线在具有给定折射率和角度的两个介质之间通过时，斯涅耳定律是否成立。返回布尔值。角度应为弧度。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         n1: "介质 1 的折射率 (无量纲)",
         θ1: "介质 1 中的角度 (角度 rad)",
         n2: "介质 2 的折射率 (无量纲)",
         θ2: "介质 2 中的角度 (角度 rad)",
      },
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "临界角",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "计算临界角 (θ_c = arcsin(n2/n1))",
      description:
         "计算当光线从折射率为 n1 的介质进入折射率为 n2 的介质时（n1 > n2），发生全内反射的临界角。返回角度为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         θ_c: "临界角 (角度 rad)",
         n1: "介质 1 的折射率 (无量纲)",
         n2: "介质 2 的折射率 (无量纲)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "像的位置 (光学)",
      equation_text: "1/f = 1/d_o + 1/d_i (薄透镜/镜)",
      summary: "验证薄透镜/镜方程 (1/f = 1/do + 1/di)",
      description:
         "检查焦距、物距和像距之间的关系是否成立。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f: "焦距 (长度 m)",
         d_o: "物距 (长度 m)",
         d_i: "像距 (长度 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "像的大小 (放大率 - 光学)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "验证放大率方程 (h'/h = di/do) (函数使用 h'/h = di/do)",
      description:
         "检查物体/像高度和距离之间的关系是否成立。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感。函数使用幅度关系 `h'/h = di/do` 而不是带符号的放大率方程。文档基于函数实现进行说明。考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         M: "放大率 (无量纲)",
         h_i: "像的高度 (长度 m)",
         h_o: "物体的高度 (长度 m)",
         d_i: "像距 (长度 m)",
         d_o: "物距 (长度 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "球面镜方程",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "计算球面镜的焦距 (f = r/2)",
      description: "根据球面镜的曲率半径计算其焦距。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f: "焦距 (长度 m)",
         r: "曲率半径 (长度 m)",
      },
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "弹性势能",
      equation_text: "U_s = ½kx²",
      summary: "计算弹簧的势能 (PE = 0.5 * k * Δx^2)",
      description: "计算理想弹簧中储存的弹性势能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         U_s: "弹性势能 (能量 J)",
         k: "弹簧常数 (弹簧常数 N/m)",
         x: "距平衡位置的位移 (长度 m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "简谐振子 (SHO) 周期",
      equation_text: "T = 2π√(m/k)",
      summary: "计算弹簧-质量系统简谐振子的周期 (T = 2π√(m/k))",
      description:
         "计算由弹簧上的质量组成的简谐振子的振荡周期。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         T: "周期 (时间 s)",
         π: "圆周率 (无量纲常数)",
         m: "质量 (质量 kg)",
         k: "弹簧常数 (弹簧常数 N/m)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "单摆周期",
      equation_text: "T = 2π√(L/g)",
      summary: "计算单摆周期 (T = 2π√(l/g))",
      description: "计算小角度下单摆的振荡周期。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         T: "周期 (时间 s)",
         π: "圆周率 (无量纲常数)",
         L: "摆长 (长度 m)",
         g: "重力加速度 (加速度 m/s²)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "频率",
      equation_text: "f = 1 / T",
      summary: "计算频率 (f = 1/T)",
      description: "从振荡周期计算频率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f: "频率 (频率 Hz)",
         T: "周期 (时间 s)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "角频率",
      equation_text: "ω = 2πf",
      summary: "计算角频率 (ω = 2πf)",
      description: "从频率计算角频率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ω: "角频率 (角速度 rad/s)",
         π: "圆周率 (无量纲常数)",
         f: "频率 (频率 Hz)",
      },
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "洛伦兹因子",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "计算洛伦兹因子 (γ)",
      description: "使用 γ = 1/√(1 - (v²/c²)) 计算洛伦兹因子。需要 v < c。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         γ: "洛伦兹因子 (无量纲)",
         v: "速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "时间膨胀",
      equation_text: "Δt' = γ * Δt₀",
      summary: "计算时间膨胀 (t' = γ * t₀)",
      description:
         "计算惯性参考系 S 中观察者所经历的时间 (t')，已知运动参考系 S' 中测量的固有时间 (t₀) 和 S 与 S' 之间的相对速度 (v)。使用 t' = t₀ / √(1 - (v²/c²))。要求 t₀ ≥ 0 且 |v| ≤ c。t' 的单位将与 t₀ 相同，v 和 c 的单位必须一致。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Δt: "膨胀的时间 (时间 s)",
         Δt0: "固有时间 (时间 s)",
         v: "相对速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "长度收缩",
      equation_text: "L' = L₀ / γ",
      summary: "计算长度收缩 (L' = L₀ / γ)",
      description:
         "计算从运动参考系 S' 观察到的物体长度 (L')，已知其在静止参考系 S 中测量的固有长度 (L₀) 和 S 与 S' 之间的相对速度 (v)。使用 L' = L₀ * √(1 - (v²/c²))。要求 L₀ ≥ 0 且 |v| ≤ c。L' 的单位将与 L₀ 相同，v 和 c 的单位必须一致。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         L: "收缩后的长度 (长度 m)",
         L0: "固有长度 (长度 m)",
         v: "相对速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "相对论速度叠加",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "计算相对论速度叠加",
      description:
         "计算物体相对于参考系 S' 的速度 (u')，已知其相对于参考系 S 的速度 (u) 和参考系 S 相对于参考系 S' 的速度 (v)。使用等式 u' = (u + v) / (1 + uv/c²)。假定沿同一条直线运动。要求 c ≠ 0。u、v 和 c 的单位必须一致。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         u: "物体在参考系 S 中的速度 (速度 m/s)",
         v: "参考系 S 相对于 S' 的速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
         "u'": "物体相对于参考系 S' 的速度 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "相对论总能量",
      equation_text: "E = γmc²",
      summary: "计算相对论总能量 (E)",
      description:
         "计算具有静止质量 (m) 并以速度 (v) 运动的粒子的总相对论能量。使用等式 E = γmc² = mc² / √(1 - (v²/c²))。主要用于具有静止质量 (m > 0) 的粒子。要求 m ≥ 0 且 |v| ≤ c。m、v 和 c 的单位必须一致才能获得适当单位的能量（例如，m 以 kg 为单位，v/c 以 m/s 为单位时，E 以焦耳为单位）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "总相对论能量 (能量 J)",
         m: "静止质量 (质量 kg)",
         v: "速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "相对论动量",
      equation_text: "p = γmv",
      summary: "计算相对论动量 (p = γmv)",
      description:
         "计算具有静止质量 (m) 并以速度 (v) 运动的粒子的相对论动量。使用等式 p = γmv = mv / √(1 - (v²/c²))。主要用于具有静止质量 (m > 0) 的粒子。要求 m ≥ 0 且 |v| ≤ c。m、v 和 c 的单位必须一致才能获得适当单位的动量（例如，m 以 kg 为单位，v 以 m/s 为单位，c 以 m/s 为单位时，p 以 kg·m/s 为单位）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         p: "相对论动量 (动量 kg·m/s)",
         m: "静止质量 (质量 kg)",
         v: "速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "能量-动量关系",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "计算从动量和静止质量的总能量 (E)",
      description:
         "根据粒子的相对论动量 (p) 和静止质量 (m) 计算其总相对论能量。使用能量-动量关系：E² = (pc)² + (mc²)²。此等式适用于有质量 (m > 0) 和无质量 (m = 0) 的粒子。要求 p ≥ 0, m ≥ 0, c > 0。p, m, c 的单位必须一致。\n",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "总相对论能量 (能量 J)",
         p: "相对论动量 (动量 kg·m/s)",
         c: "真空中的光速 (速度 m/s)",
         m: "静止质量 (质量 kg)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "质量-能量等价性 (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "计算质量-能量等价性 (E₀ = mc²)",
      description:
         "利用爱因斯坦的著名等式 E₀ = mc² 计算给定静止质量 (m) 的等效静止能量 (E₀)。要求 m ≥ 0 且 c > 0。m 和 c 的单位必须一致（例如，m 以 kg 为单位，c 以 m/s 为单位时，E₀ 以焦耳为单位）。此端点使用 c 的标准值（约 299792458 m/s），除非明确提供了 'c'。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E0: "静止能量 (能量 J)",
         m: "静止质量 (质量 kg)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "相对论动能",
      equation_text: "KE = (γ - 1)mc²",
      summary: "计算相对论动能 (KE)",
      description:
         "计算具有静止质量 (m) 并以速度 (v) 运动的粒子的相对论动能。使用等式 KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc²。主要用于具有静止质量 (m > 0) 的粒子。要求 m ≥ 0 且 |v| < c。m、v 和 c 的单位必须一致才能获得适当单位的能量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE: "相对论动能 (能量 J)",
         m: "静止质量 (质量 kg)",
         v: "速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "相对论多普勒效应 (波长)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "计算波长的相对论纵向多普勒效应",
      description:
         "计算从以相对速度 (v_rel) 直接远离或接近观察者的光源发出的具有固有波长 (λ₀) 的光的观测波长 (λ')。使用等式 λ' = λ₀√((1 + β)/(1 - β))，其中 β = v_rel/c。v_rel > 0 表示远离（红移），v_rel < 0 表示接近（蓝移）。要求 λ₀ > 0 且 |v_rel| < c。λ' 的单位将与 λ₀ 相同，v_rel 和 c 的单位必须一致。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         "λ'": "观测波长 (长度 m)",
         λ0: "固有波长 (长度 m)",
         v: "相对速度 (速度 m/s)",
         c: "真空中的光速 (速度 m/s)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "光子能量 (从频率)",
      equation_text: "E = hf",
      summary: "从频率计算光子能量 (E = hf)",
      description:
         "根据光子的频率 (f) 计算其能量 (E)。使用普朗克关系 E = hf。要求 f ≥ 0 且 h > 0。h 和 f 的单位必须一致才能获得适当单位的能量（例如，h 以 J·s 为单位，f 以 Hz (s⁻¹) 为单位时，E 以焦耳为单位）。此端点使用 h 的标准值（约 6.626e-34 J·s），除非明确提供了 'h'。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "光子能量 (能量 J)",
         h: "普朗克常数 (常数 J·s)",
         f: "频率 (频率 Hz)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "光子动量 (从波长)",
      equation_text: "p = h / λ",
      summary: "从波长计算光子动量 (p = h/λ)",
      description:
         "根据光子的波长 (λ) 计算其动量 (p)。使用关系式 p = h/λ。要求 λ > 0 且 h > 0。h 和 λ 的单位必须一致才能获得适当单位的动量（例如，h 以 J·s 为单位，λ 以米为单位时，p 以 kg·m/s 为单位）。此端点使用 h 的标准值（约 6.626e-34 J·s），除非明确提供了 'h'。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         p: "光子动量 (动量 kg·m/s)",
         h: "普朗克常数 (常数 J·s)",
         λ: "波长 (长度 m)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "光电效应 (最大动能)",
      equation_text: "KE_max = E_photon - φ",
      summary: "计算光电效应中的最大动能 (KE_max)",
      description:
         "计算光电效应中发射电子的最大动能 (KE_max)。使用等式 KE_max = E_photon - φ，其中 E_photon 是入射光子能量，φ 是材料的逸出功。如果 E_photon ≤ φ，则不发射电子，KE_max 为 0。要求 E_photon ≥ 0 且 φ ≥ 0。E_photon 和 φ 的单位必须一致才能获得相同单位的 KE_max。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE_max: "最大电子动能 (能量 J)",
         E_photon: "光子能量 (能量 J)",
         φ: "逸出功 (能量 J)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "里德伯格公式 (原子跃迁)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "计算类氢原子跃迁的能量或波数",
      description:
         "计算类氢原子 (Z) 中电子在两个能级之间跃迁的能量差 (ΔE) 或波数 (1/λ)。使用等式 结果 = 常数 * Z² * (1/n_initial² - 1/n_final²)。如果 '常数' 是里德伯格能量单位（例如，以 eV 为单位），则结果是能量差 E_final - E_initial（吸收为正，发射为负）。如果 '常数' 是波数的里德伯格常数（例如，以 m⁻¹ 为单位），则结果是波数 1/λ（发射为正，吸收为负）。要求 nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (整数), 常数 > 0。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔE: "能量差 (能量 J)",
         R_y: "里德伯格常数 (常数 J 或反长度 m⁻¹)",
         Z: "原子序数 (无量纲整数)",
         n1: "初始主量子数 (无量纲整数)",
         n2: "最终主量子数 (无量纲整数)",
      },
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "角速度",
      equation_text: "ω = Δθ / Δt",
      summary: "计算角速度 (ω = Δθ / Δt)",
      description: "根据角度的变化和时间计算角速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ω: "角速度 (角速度 rad/s)",
         Δθ: "角位移 (角度 rad)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "角加速度",
      equation_text: "α = Δω / Δt",
      summary: "计算角加速度 (α = Δω / Δt)",
      description: "根据角速度的变化和时间计算角加速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         α: "角加速度 (角加速度 rad/s²)",
         Δω: "角速度的变化 (角速度 rad/s)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "转动运动学 (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "计算末角速度 (ω = ω0 + αt)",
      description: "使用第一个转动运动学方程计算末角速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ω: "末角速度 (角速度 rad/s)",
         ω0: "初角速度 (角速度 rad/s)",
         α: "角加速度 (角加速度 rad/s²)",
         t: "时间 (时间 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "转动运动学 (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "计算角位置 (θ = θ0 + ω0t + 0.5αt^2)",
      description: "使用第二个转动运动学方程计算末角位置。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         θ: "末角位置 (角度 rad)",
         θ0: "初角位置 (角度 rad)",
         ω0: "初角速度 (角速度 rad/s)",
         t: "时间 (时间 s)",
         α: "角加速度 (角加速度 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "转动运动学 (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "计算角速度平方 (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "使用转动运动学的第三个方程计算末角速度的平方。注意 - 返回 ω^2，而不是 ω。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ω: "末角速度 (角速度 rad/s)",
         ω0: "初角速度 (角速度 rad/s)",
         α: "角加速度 (角加速度 rad/s²)",
         Δθ: "角位移 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "平均角速度",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "计算平均角速度 (ω_avg = 0.5 * (ω + ω0))",
      description: "假定角加速度恒定计算平均角速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ω_avg: "平均角速度 (角速度 rad/s)",
         ω: "末角速度 (角速度 rad/s)",
         ω0: "初角速度 (角速度 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "转矩 (力矩)",
      equation_text: "τ = rFsin(θ)",
      summary: "计算转矩 (τ = rF sin(θ))",
      description: "根据半径、力和它们之间的角度计算转矩。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         τ: "转矩 (转矩 N·m)",
         r: "力臂 (长度 m)",
         F: "力 (力 N)",
         θ: "力与力臂之间的角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "牛顿第二定律 (转动)",
      equation_text: "τ_net = Iα",
      summary: "利用转动第二定律计算转矩 (τ = Iα)",
      description: "根据转动惯量和角加速度计算转矩。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         τ_net: "净转矩 (转矩 N·m)",
         I: "转动惯量 (转动惯量 kg·m²)",
         α: "角加速度 (角加速度 rad/s²)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "转动惯量",
      equation_text: "I = mr² (点质量)",
      summary: "计算点质量的转动惯量 (I = mr^2)",
      description: "计算相对于轴的单个点质量的转动惯量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         I: "转动惯量 (转动惯量 kg·m²)",
         m: "质量 (质量 kg)",
         r: "距轴距离 (长度 m)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "转动功",
      equation_text: "W = τΔθ (恒定转矩)",
      summary: "计算转动功 (W = τΔθ)",
      description: "计算恒定转矩在角位移上所做的功。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         W: "转动功 (能量 J)",
         τ: "转矩 (转矩 N·m)",
         Δθ: "角位移 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "转动功率",
      equation_text: "P = τω",
      summary: "计算转动功率 (P = τω cos(θ))",
      description:
         "根据转矩、角速度以及它们之间的角度计算瞬时转动功率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "转动功率 (功率 W)",
         τ: "转矩 (转矩 N·m)",
         ω: "角速度 (角速度 rad/s)",
         θ: "转矩与角速度之间的角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "转动动能",
      equation_text: "KE_rot = ½Iω²",
      summary: "计算转动动能 (KE = 0.5Iω^2)",
      description: "计算旋转物体的动能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE_rot: "转动动能 (能量 J)",
         I: "转动惯量 (转动惯量 kg·m²)",
         ω: "角速度 (角速度 rad/s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "角动量",
      equation_text: "L = Iω",
      summary: "计算角动量 (L = mrv sin(θ))",
      description: "计算点质量相对于某个点的角动量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         L: "角动量 (角动量 kg·m²/s)",
         m: "质量 (质量 kg)",
         r: "距轴/点距离 (长度 m)",
         v: "速度 (速度 m/s)",
         θ: "径向矢量与速度之间的角度 (角度 rad)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "角冲量",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "计算角冲量 (J = τΔt)",
      description: "根据转矩和时间间隔计算角冲量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         J_angular: "角冲量 (角冲量 N·m·s)",
         τ_avg: "平均转矩 (转矩 N·m)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "杨氏模量",
      equation_text: "E = σ / ε",
      summary: "计算杨氏模量 (E = (F * L0) / (A * ΔL))",
      description: "计算材料在拉伸或压缩应力下的杨氏模量（弹性模量）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         E: "杨氏模量 (压力 Pa)",
         F: "力 (力 N)",
         L0: "原始长度 (长度 m)",
         A: "横截面积 (面积 m²)",
         ΔL: "长度变化 (长度 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "剪切模量",
      equation_text: "G = τ / γ",
      summary: "计算剪切模量 (G = (F * y) / (A * Δx))",
      description: "计算材料在剪切应力下的剪切模量（刚度模量）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         G: "剪切模量 (压力 Pa)",
         F: "力 (力 N)",
         y: "垂直于力的距离 (长度 m)",
         A: "面积 (面积 m²)",
         Δx: "位移 (长度 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "体积模量",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "计算体积模量 (K = (F * V0) / (A * ΔV))",
      description: "计算材料在均匀压力（静水压力）下的体积模量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         K: "体积模量 (压力 Pa)",
         ΔP: "压力变化 (压力 Pa)",
         ΔV: "体积变化 (体积 m³)",
         V0: "原始体积 (体积 m³)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "胡克定律",
      equation_text: "F = kx",
      summary: "计算弹簧的力 (F = -k * Δx)",
      description:
         "根据胡克定律计算理想弹簧所施加的回复力。注意 - 返回负值表示力与位移方向相反。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         F: "力 (力 N)",
         k: "弹簧常数 (弹簧常数 N/m)",
         x: "距平衡位置的位移 (长度 m)",
      },
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "固体热膨胀 (长度)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "计算固体线热膨胀 (ΔL = αL0ΔT)",
      description: "计算固体材料由于温度变化引起的长度变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔL: "长度变化 (长度 m)",
         α: "线膨胀系数 (每温度系数 K⁻¹)",
         L0: "原始长度 (长度 m)",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "固体热膨胀 (面积)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "计算固体面积热膨胀 (ΔA = 2αA0ΔT)",
      description:
         "使用线膨胀系数计算固体材料由于温度变化引起的面积变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔA: "面积变化 (面积 m²)",
         α: "线膨胀系数 (每温度系数 K⁻¹)",
         A0: "原始面积 (面积 m²)",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "固体热膨胀 (体积)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "计算固体体积热膨胀 (ΔV = 3αV0ΔT)",
      description:
         "使用线膨胀系数计算固体材料由于温度变化引起的体积变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔV: "体积变化 (体积 m³)",
         α: "线膨胀系数 (每温度系数 K⁻¹)",
         V0: "原始体积 (体积 m³)",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "液体热膨胀",
      equation_text: "ΔV = βV₀ΔT",
      summary: "计算液体热膨胀 (ΔV = βV0ΔT)",
      description: "计算液体由于温度变化引起的体积变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔV: "体积变化 (体积 m³)",
         β: "体积膨胀系数 (每温度系数 K⁻¹)",
         V0: "原始体积 (体积 m³)",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "显热",
      equation_text: "Q = mcΔT",
      summary: "计算显热 (Q = mcΔT)",
      description: "计算导致物质温度变化的传热量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Q: "显热 (能量 J)",
         m: "质量 (质量 kg)",
         c: "比热容 (比热容 J/(kg·K))",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "潜热",
      equation_text: "Q = mL",
      summary: "计算潜热 (Q = mL)",
      description: "计算物质相变过程中传递的热量。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Q: "潜热 (能量 J)",
         m: "质量 (质量 kg)",
         L: "比潜热 (比能量 J/kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "理想气体定律",
      equation_text: "PV = nRT",
      summary: "验证理想气体定律 (PV = nRT)",
      description:
         "检查对于给定参数，理想气体定律方程是否成立。返回布尔值。注意 - 使用严格等价（===），可能对浮点精度敏感；考虑实际检查中的容差。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "压力 (压力 Pa)",
         V: "体积 (体积 m³)",
         n: "摩尔数 (物质的量 mol)",
         R: "理想气体常数 (常数 J/(mol·K))",
         T: "温度 (温度 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "分子动能",
      equation_text: "KE_avg = (3/2)kT",
      summary: "计算平均分子动能 (KE = (3/2)kT)",
      description: "计算理想气体每个分子的平均平动动能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE_avg: "平均分子动能 (能量 J)",
         k: "玻尔兹曼常数 (常数 J/K)",
         T: "温度 (温度 K)",
         m: "单个分子的质量 (质量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "分子速率 (最概然)",
      equation_text: "v_p = √(2kT/m)",
      summary: "计算最概然分子速率 (v_p = √(2kT/m))",
      description:
         "根据麦克斯韦-玻尔兹曼分布计算理想气体中分子的最概然速率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_p: "最概然分子速率 (速度 m/s)",
         k: "玻尔兹曼常数 (常数 J/K)",
         T: "温度 (温度 K)",
         m: "单个分子的质量 (质量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "分子速率 (平均)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "计算平均分子速率 (v_avg = √(8kT/(πm)))",
      description:
         "根据麦克斯韦-玻尔兹曼分布计算理想气体中分子的平均速率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_avg: "平均分子速率 (速度 m/s)",
         k: "玻尔兹曼常数 (常数 J/K)",
         T: "温度 (温度 K)",
         π: "圆周率 (无量纲常数)",
         m: "单个分子的质量 (质量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "分子速率 (均方根)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "计算均方根分子速率 (v_rms = √(3kT/m))",
      description:
         "根据麦克斯韦-玻尔兹曼分布计算理想气体中分子的均方根速率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v_rms: "均方根分子速率 (速度 m/s)",
         k: "玻尔兹曼常数 (常数 J/K)",
         T: "温度 (温度 K)",
         m: "单个分子的质量 (质量 kg)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "内能变化",
      equation_text: "ΔU = Q - W",
      summary: "计算理想单原子气体的内能变化 (ΔU = (3/2)nRΔT)",
      description:
         "计算单原子理想气体经历温度变化时的内能变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         ΔU: "内能变化 (能量 J)",
         n: "摩尔数 (物质的量 mol)",
         R: "理想气体常数 (常数 J/(mol·K))",
         ΔT: "温度变化 (温度差 K)",
      },
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "热力学功",
      equation_text: "W = PΔV (恒定压力)",
      summary: "计算系统在恒定压力下所做的热力学功 (W = -PΔV)",
      description:
         "计算系统在恒定压力下的热力学过程中所做的或受到的功。注意 - 方程计算系统所做的功，膨胀为正，压缩为负。函数返回 -P*deltaV，与方程 W = PΔV 计算的系统所做的功一致，额外增加的负号可能表示系统受到的功，取决于约定。文档说明了函数的输出。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         W: "热力学功 (能量 J)",
         P: "压力 (压力 Pa)",
         ΔV: "体积变化 (体积 m³)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "实际效率",
      equation_text: "η = W_out / Q_in",
      summary: "计算实际热机的效率 (η_real = 1 - (Q_C / Q_H))",
      description: "根据吸收和放出的热量计算热机的热效率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         η: "效率 (无量纲)",
         Q_H: "从热源吸收的热量 (能量 J)",
         Q_C: "释放到冷源的热量 (能量 J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "理想效率",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "计算理想效率 (卡诺循环) (η_ideal = 1 - (T_C / T_H))",
      description:
         "计算在两个温度之间工作的热机的最大理论效率（卡诺效率）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         η_ideal: "理想效率 (无量纲)",
         T_hot: "热源温度 (温度 K)",
         T_cold: "冷源温度 (温度 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "实际性能系数 (COP)",
      equation_text: "COP_ref = Q_c / W (冰箱)",
      summary: "计算实际冰箱的性能系数 (COP_real = QC / (QH - QC))",
      description: "计算实际冰箱或热泵的性能系数。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         COP_real: "性能系数 (无量纲)",
         Q_C: "从冷源获得的热量 (能量 J)",
         Q_H: "传递到热源的热量 (能量 J)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "理想性能系数 (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "计算理想冰箱的性能系数 (COP_ideal = TC / (TH - TC))",
      description:
         "计算在两个温度之间工作的冰箱或热泵的最大理论性能系数。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         COP_ideal: "理想性能系数 (无量纲)",
         T_h: "热源温度 (温度 K)",
         T_c: "冷源温度 (温度 K)",
      },
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "周期波速度",
      equation_text: "v = fλ",
      summary: "计算波速 (v = fλ)",
      description: "根据周期波的频率和波长计算其速度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         v: "波速 (速度 m/s)",
         f: "频率 (频率 Hz)",
         λ: "波长 (长度 m)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "波的强度",
      equation_text: "I = P / A",
      summary: "计算强度 (I = P/A)",
      description: "计算波的强度（单位面积的功率）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         I: "强度 (强度 W/m²)",
         P: "功率 (功率 W)",
         A: "面积 (面积 m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "强度级 (分贝)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "以分贝为单位计算强度级 (L = 10 log10(I/I0))",
      description: "计算相对于参考强度的强度级（声强级）。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         β: "强度级 (强度级 dB)",
         I: "强度 (强度 W/m²)",
         I0: "参考强度 (强度 W/m²)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "压力级 (声压级)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "计算声压级以分贝为单位 (L = 20 log10(ΔP/ΔP0))",
      description: "计算相对于参考压力变化的声压级。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         L_p: "声压级 (压力级 dB)",
         P_rms: "均方根压力波动 (压力 Pa)",
         P_ref: "参考压力 (压力 Pa)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "多普勒效应 (声音/非相对论)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "计算多普勒效应速度因子 ((c + v_o) / (c - v_s))",
      description:
         "计算多普勒效应方程的速度因子部分 (f' = f * factor)。观测者向源移动，源向观测者移动时，速度为正。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         f_obs: "观测频率 (频率 Hz)",
         f_source: "源频率 (频率 Hz)",
         v_wave: "波速 (速度 m/s)",
         v_observer: "观测者相对于介质的速度 (速度 m/s)",
         v_source: "源相对于介质的速度 (速度 m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "马赫角",
      equation_text: "sin(μ) = 1 / M",
      summary: "计算马赫角 (θ_M = arcsin(c/v))",
      description:
         "计算物体以超声速运动时形成的马赫锥的角度。返回角度为弧度。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         μ: "马赫角 (角度 rad)",
         M: "马赫数 (无量纲)",
         c: "声速 (速度 m/s)",
         v: "物体速度 (速度 m/s)",
      },
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "功",
      equation_text: "W = Fdcos(θ)",
      summary: "计算所做的功 (W = F * Δs * cos(θ))",
      description: "根据力、位移和它们之间的角度计算所做的功。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         W: "所做的功 (能量 J)",
         F: "力的大小 (力 N)",
         d: "位移的大小 (长度 m)",
         θ: "力与位移之间的角度 (角度 rad)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "动能",
      equation_text: "KE = ½mv²",
      summary: "计算动能 (KE = 0.5 * m * v^2)",
      description: "根据质量和速度计算动能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE: "动能 (能量 J)",
         m: "质量 (质量 kg)",
         v: "速度 (速度 m/s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "动能 (从动量)",
      equation_text: "KE = p² / (2m)",
      summary: "从动量计算动能 (KE = p^2 / (2m))",
      description: "根据动量和质量计算动能。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         KE: "动能 (能量 J)",
         p: "动量 (动量 kg·m/s)",
         m: "质量 (质量 kg)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "引力势能",
      equation_text: "U_g = mgh (近地表)",
      summary: "计算引力势能 (PE = mgh)",
      description: "计算引力势能的变化。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         U_g: "引力势能 (能量 J)",
         m: "质量 (质量 kg)",
         g: "重力加速度 (加速度 m/s²)",
         h: "高度 (长度 m)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "效率",
      equation_text: "效率 = Output / Input",
      summary: "计算效率 (η = W_out / W_in)",
      description: "计算过程或机器的效率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         Efficiency: "效率 (无量纲)",
         Output: "有用输出能量或功率 (能量 J 或 功率 W)",
         Input: "总输入能量或功率 (能量 J 或 功率 W)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "功率",
      equation_text: "P = W / t",
      summary: "计算功率 (P = ΔW / Δt)",
      description: "根据功的变化和时间计算平均功率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "功率 (功率 W)",
         ΔW: "功的变化 (能量 J)",
         Δt: "时间间隔 (时间 s)",
      },
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "功率 (P = Fv)",
      equation_text: "P = Fv",
      summary: "根据力和速度计算功率 (P = Fv cos(θ))",
      description: "根据力、速度和它们之间的角度计算瞬时功率。",
      language_code: "zh",
      subject: "Physics",
      variables: {
         P: "功率 (功率 W)",
         F: "力的大小 (力 N)",
         v: "速度的大小 (速度 m/s)",
         θ: "力与速度之间的角度 (角度 rad)",
      },
      topic: "Work And Energy",
   },
];
module.exports = zh;