const es = [
   {
      equation_id: "centripetal-acceleration",
      name: "Centripetal Acceleration",
      equation_text: "a_c = v² / r",
      summary: "Calcula la aceleración centrípeta (a_c = v^2 / r)",
      description:
         "Calcula la aceleración dirigida hacia el centro de una trayectoria circular utilizando la velocidad lineal y el radio.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Circular Motion",
   },
   {
      equation_id: "centripetal-acceleration-angular",
      name: "Centripetal Acceleration (Angular)",
      equation_text: "a_c = ω²r",
      summary: "Calcula la aceleración centrípeta (a_c = -ω^2 * r) usando velocidad angular",
      description:
         "Calcula el componente vectorial de la aceleración centrípeta utilizando la velocidad angular y el radio. El signo negativo indica la dirección hacia el centro.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Circular Motion",
   },
   {
      equation_id: "coulombs-law",
      name: "Coulomb's Law (Force)",
      equation_text: "F = k |q₁q₂| / r²",
      summary: "Calcula la fuerza eléctrica usando la Ley de Coulomb (F = k * q1*q2 / r^2)",
      description:
         "Calcula la fuerza eléctrica entre dos cargas puntuales. Devuelve fuerza con signo (positivo para repulsión, negativo para atracción).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-field",
      name: "Electric Field",
      equation_text: "E = kq / r² (point charge)",
      summary: "Calcula el campo eléctrico a partir de la fuerza (E = F_E/q)",
      description: "Calcula la intensidad del campo eléctrico basado en la fuerza ejercida sobre una carga de prueba.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-potential",
      name: "Electric Potential",
      equation_text: "V = kq / r (point charge)",
      summary: "Calcula el potencial eléctrico a partir del cambio de energía potencial (V = ΔU_E/q)",
      description:
         "Calcula el potencial eléctrico (voltaje) basado en el cambio de energía potencial eléctrica por unidad de carga. Nota: El nombre de la función `calculateElectricPotential` es correcto, pero el parámetro `deltaUE` implica cambio, mientras que la fórmula es típicamente V=U_E/q o ΔV=ΔU_E/q. Documentado basado en la fórmula ΔV = ΔU_E/q y devolviendo ΔV.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "field-and-potential",
      name: "Electric Field and Potential Relationship",
      equation_text: "E_x = -dV/dx",
      summary: "Calcula el campo eléctrico a partir de la diferencia de potencial (E = ΔV/d)",
      description:
         'Calcula la magnitud de un campo eléctrico uniforme basado en la diferencia de potencial a través de una distancia. Nota: El nombre de la función "Field and Potential" es engañoso; calcula el Campo Eléctrico E.',
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitance",
      name: "Capacitance",
      equation_text: "C = Q / V",
      summary: "Calcula la capacitancia (C = Q/V)",
      description: "Calcula la capacitancia basada en la carga almacenada y el voltaje a través de un capacitor.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "plate-capacitor",
      name: "Plate Capacitor Capacitance",
      equation_text: "C = ε₀A / d",
      summary: "Calcula la capacitancia de un capacitor de placas paralelas (C = (kε₀A)/d)",
      description:
         "Calcula la capacitancia de un capacitor de placas paralelas con un dieléctrico. Nota: La función usa k * ε₀ como una sola entrada (`kEpsilon`).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "cylindrical-capacitor",
      name: "Cylindrical Capacitor Capacitance",
      equation_text: "C = 2πε₀L / ln(b/a)",
      summary: "Calcula la capacitancia de un capacitor cilíndrico (C = (2πkε₀l) / ln(r2/r1))",
      description:
         "Calcula la capacitancia de un capacitor cilíndrico con un dieléctrico. Nota: La función usa k * ε₀ como una sola entrada (`kEpsilon`).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "spherical-capacitor",
      name: "Spherical Capacitor Capacitance",
      equation_text: "C = 4πε₀ * (ab / (b-a))",
      summary: "Calcula la capacitancia de un capacitor esférico (C = 4πkε₀ / (1/r1 - 1/r2))",
      description:
         "Calcula la capacitancia de un capacitor esférico con un dieléctrico. Nota: La función usa k * ε₀ como una sola entrada (`kEpsilon`).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-pe",
      name: "Capacitive Potential Energy",
      equation_text: "U_C = ½CV²",
      summary: "Valida ecuaciones de energía potencial en capacitores (PE = 0.5QV = 0.5CV^2 = 0.5Q^2/C)",
      description:
         "Verifica si las tres fórmulas comunes para la energía potencial almacenada en un capacitor son equivalentes para los valores dados de Q, V y C. Devuelve booleano. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante; considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-current",
      name: "Electric Current",
      equation_text: "I = ΔQ / Δt",
      summary: "Calcula la corriente eléctrica (I = ΔQ/Δt)",
      description:
         "Calcula la corriente eléctrica basada en la cantidad de carga que pasa por un punto por unidad de tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "charge-density",
      name: "Charge Density",
      equation_text: "ρ = Q / V (Volume)",
      summary: "Calcula la densidad de carga (ρ = Q/V)",
      description: "Calcula la densidad de carga promedio (carga por unidad de volumen).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "current-density",
      name: "Current Density",
      equation_text: "J = I / A",
      summary: "Calcula la densidad de corriente (J = I/A)",
      description: "Calcula la densidad de corriente eléctrica (corriente por unidad de área transversal).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "ohms-law",
      name: "Ohm's Law",
      equation_text: "V = IR",
      summary: "Calcula la resistencia usando la Ley de Ohm (R = V/I)",
      description:
         "Calcula la resistencia basada en el voltaje y la corriente. Nota: La función calcula la Resistencia R a partir de V e I.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistivity-conductivity",
      name: "Resistivity and Conductivity",
      equation_text: "ρ = RA / L",
      summary: "Calcula la conductividad a partir de la resistividad (σ = 1/ρ)",
      description: "Calcula la conductividad (σ) a partir de la resistividad (ρ).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-resistance",
      name: "Electric Resistance",
      equation_text: "R = ρL / A",
      summary: "Calcula la resistencia eléctrica (R = ρ(l/A))",
      description:
         "Calcula la resistencia de un conductor basada en su resistividad, longitud y área transversal. Nota: Usa `rhoValue` para resistividad.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-power",
      name: "Electric Power",
      equation_text: "P = IV",
      summary: "Valida ecuaciones de potencia eléctrica (P = VI = I^2R = V^2/R)",
      description:
         "Verifica si las tres fórmulas comunes para la potencia eléctrica son equivalentes para los valores dados de V, I y R. Devuelve booleano. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante; considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-series",
      name: "Resistors in Series",
      equation_text: "R_total = R₁ + R₂ + ...",
      summary: "Calcula la resistencia total para resistencias en serie (R_total = R1 + R2 + ...)",
      description: "Calcula la resistencia equivalente total para múltiples resistencias conectadas en serie.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "resistors-in-parallel",
      name: "Resistors in Parallel",
      equation_text: "1/R_total = 1/R₁ + 1/R₂ + ...",
      summary: "Calcula la resistencia total para resistencias en paralelo (1/R_total = 1/R1 + 1/R2 + ...)",
      description: "Calcula la resistencia equivalente total para múltiples resistencias conectadas en paralelo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-series",
      name: "Capacitors in Series",
      equation_text: "1/C_total = 1/C₁ + 1/C₂ + ...",
      summary: "Calcula la capacitancia total para capacitores en serie (1/C_total = 1/C1 + 1/C2 + ...)",
      description: "Calcula la capacitancia equivalente total para múltiples capacitores conectados en serie.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitors-in-parallel",
      name: "Capacitors in Parallel",
      equation_text: "C_total = C₁ + C₂ + ...",
      summary: "Calcula la capacitancia total para capacitores en paralelo (C_total = C1 + C2 + ...)",
      description: "Calcula la capacitancia equivalente total para múltiples capacitores conectados en paralelo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-charge",
      name: "Magnetic Force on a Charge",
      equation_text: "F_B = |q|vBsin(θ)",
      summary: "Calcula la fuerza magnética sobre una partícula cargada (F = qvB sin(θ))",
      description:
         "Calcula la magnitud de la fuerza magnética ejercida sobre una partícula cargada en movimiento. El ángulo debe estar en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-force-current",
      name: "Magnetic Force on a Current",
      equation_text: "F_B = ILBsin(θ)",
      summary: "Calcula la fuerza magnética sobre un conductor con corriente (F = I l B sin(θ))",
      description:
         "Calcula la magnitud de la fuerza magnética ejercida sobre un conductor recto que lleva corriente en un campo magnético. El ángulo debe estar en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "biot-savart-law",
      name: "Biot-Savart Law",
      equation_text: "B = μ₀I / (2πr) (infinite straight wire)",
      summary: "Calcula el campo magnético de un elemento de corriente (dB = (μ₀I ds) / (4πr^2))",
      description:
         "Calcula la magnitud de la contribución del campo magnético de un elemento diferencial de corriente perpendicular al vector radio. Nota: La función implementa `(μ₀ * I * ds) / (4 * π * r^2)`, omitiendo el término sin(θ) a menudo presente en la forma diferencial, asumiendo efectivamente θ=90 grados o calculando solo el componente perpendicular al vector radio en ese plano específico. Documentando la fórmula implementada.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "solenoid",
      name: "Magnetic Field of a Solenoid",
      equation_text: "B = μ₀nI (inside, ideal)",
      summary: "Calcula el campo magnético dentro de un solenoide largo (B = μ₀nI)",
      description: "Calcula la magnitud del campo magnético dentro de un solenoide ideal largo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "straight-wire",
      name: "Magnetic Field of a Straight Wire",
      equation_text: "B = μ₀I / (2πr) (infinite wire)",
      summary: "Calcula el campo magnético de un alambre recto infinito (B = (μ₀I)/(2πr))",
      description:
         "Calcula la magnitud del campo magnético a una distancia de un conductor largo y recto que lleva corriente.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "parallel-wires",
      name: "Force Between Parallel Wires",
      equation_text: "F/L = (μ₀I₁I₂) / (2πd)",
      summary: "Calcula la fuerza por unidad de longitud entre alambres paralelos (F/L = (μ₀I₁I₂)/(2πd))",
      description:
         "Calcula la magnitud de la fuerza por unidad de longitud entre dos conductores largos y paralelos que llevan corrientes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "electric-flux",
      name: "Electric Flux",
      equation_text: "Φ_E = EAcos(θ) (uniform E)",
      summary: "Calcula el flujo eléctrico (Φ_E = E * A * cos(θ))",
      description:
         "Calcula el flujo eléctrico a través de una superficie plana en un campo eléctrico uniforme. El ángulo debe estar entre el vector del campo eléctrico y el vector de área, en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "magnetic-flux",
      name: "Magnetic Flux",
      equation_text: "Φ_B = BAcos(θ) (uniform B)",
      summary: "Calcula el flujo magnético (Φ_B = B * A * cos(θ))",
      description:
         "Calcula el flujo magnético a través de una superficie plana en un campo magnético uniforme. El ángulo debe estar entre el vector del campo magnético y el vector de área, en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "motional-emf",
      name: "Motional EMF",
      equation_text: "ε = vBL (straight conductor)",
      summary: "Calcula la fem motriz (emf = Blv)",
      description:
         "Calcula la magnitud de la fem inducida en un conductor moviéndose perpendicularmente a un campo magnético. Nota: La función calcula la magnitud Blv, omitiendo el signo negativo a veces usado para dirección (Ley de Lenz).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "induced-emf",
      name: "Induced EMF (Faraday's Law)",
      equation_text: "ε = -dΦ_B / dt",
      summary: "Calcula la fem inducida por un flujo cambiante (emf = -ΔΦ_B / Δt)",
      description: "Calcula la fem inducida por un flujo magnético cambiante según la Ley de Inducción de Faraday.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductance-induced-emf",
      name: "Induced EMF from Inductance",
      equation_text: "ε_L = -L dI / dt",
      summary: "Calcula la fem inducida por corriente cambiante en un inductor (emf = -L * ΔI / Δt)",
      description:
         "Calcula la fem autoinducida en un inductor debido a una corriente cambiante. Nota: La función se llama `calculateInductance` pero devuelve fem usando esta fórmula. Documentando lo que devuelve.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "capacitive-reactance",
      name: "Capacitive Reactance",
      equation_text: "X_C = 1 / (2πfC)",
      summary: "Calcula la reactancia capacitiva (X_C = 1/(2πfC))",
      description: "Calcula la oposición de un capacitor a la corriente alterna.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "inductive-reactance",
      name: "Inductive Reactance",
      equation_text: "X_L = 2πfL",
      summary: "Calcula la reactancia inductiva (X_L = 2πfL)",
      description: "Calcula la oposición de un inductor a la corriente alterna.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "impedance",
      name: "Impedance",
      equation_text: "Z = √(R² + (X_L - X_C)²)",
      summary: "Calcula la impedancia (Z = √(R^2 + (X_L - X_C)^2))",
      description:
         "Calcula la oposición total al flujo de corriente en un circuito AC que contiene resistencia, reactancia inductiva y reactancia capacitiva.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Electromagnetism",
   },
   {
      equation_id: "density",
      name: "Density",
      equation_text: "ρ = m / V",
      summary: "Calcula la densidad (ρ = m/V)",
      description: "Calcula la densidad basada en masa y volumen.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure",
      name: "Pressure",
      equation_text: "P = F / A",
      summary: "Calcula la presión (P = F/A)",
      description: "Calcula la presión basada en la fuerza aplicada sobre un área.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "pressure-in-fluid",
      name: "Pressure in a Fluid",
      equation_text: "P = P₀ + ρgh",
      summary: "Calcula la presión en un fluido (P = P0 + ρgh)",
      description: "Calcula la presión absoluta a cierta profundidad en un fluido.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "buoyancy",
      name: "Buoyancy",
      equation_text: "F_B = ρ_fluid * V_submerged * g",
      summary: "Calcula la fuerza de flotación (F_b = ρgV_desplazado)",
      description:
         "Calcula la fuerza de flotación ejercida por un fluido sobre un objeto sumergido o parcialmente sumergido (principio de Arquímedes).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mass-flow-rate",
      name: "Mass Flow Rate",
      equation_text: "ṁ = ρAv",
      summary: "Calcula el caudal másico (ṁ = Δm/Δt)",
      description: "Calcula la tasa a la que la masa pasa por un punto por unidad de tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "volume-flow-rate",
      name: "Volume Flow Rate",
      equation_text: "Q = Av",
      summary: "Calcula el caudal volumétrico (Q = ΔV/Δt)",
      description: "Calcula la tasa a la que el volumen pasa por un punto por unidad de tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "bernoulli-equation",
      name: "Bernoulli's Equation",
      equation_text: "P + ½ρv² + ρgy = constant",
      summary: "Verifica la ecuación de Bernoulli (P1 + ρgy1 + 0.5ρv1^2 = P2 + ρgy2 + 0.5ρv2^2)",
      description:
         "Valida si la ecuación de Bernoulli es cierta para las propiedades y condiciones del fluido en dos puntos. Devuelve booleano. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante; considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "dynamic-viscosity",
      name: "Dynamic Viscosity",
      equation_text: "τ = μ * (dv/dy)",
      summary: "Calcula la viscosidad dinámica (η = F * Δy / (A * Δvx))",
      description:
         "Calcula la viscosidad dinámica basada en fuerza, gradiente de velocidad y área. Esta fórmula se deriva del esfuerzo cortante/tasa de deformación.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "kinematic-viscosity",
      name: "Kinematic Viscosity",
      equation_text: "ν = μ / ρ",
      summary: "Calcula la viscosidad cinemática (ν = η / ρ)",
      description: "Calcula la viscosidad cinemática a partir de la viscosidad dinámica y la densidad.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "drag",
      name: "Drag Force",
      equation_text: "F_D = ½ρv²CdA",
      summary: "Calcula la fuerza de arrastre (F_d = 0.5 * ρ * C_A * v^2)",
      description: "Calcula la fuerza de arrastre sobre un objeto moviéndose a través de un fluido.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "mach-number",
      name: "Mach Number",
      equation_text: "M = v / c_sound",
      summary: "Calcula el número de Mach (M = v/c)",
      description:
         "Calcula el número de Mach, la relación entre la velocidad de un objeto y la velocidad del sonido en el medio.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "reynolds-number",
      name: "Reynolds Number",
      equation_text: "Re = ρvd / μ",
      summary: "Calcula el número de Reynolds (Re = (ρ * v * D) / η)",
      description:
         "Calcula el número de Reynolds, una cantidad adimensional usada para predecir patrones de flujo en diferentes situaciones de flujo de fluidos.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "froude-number",
      name: "Froude Number",
      equation_text: "Fr = v / √(gL)",
      summary: "Calcula el número de Froude (Fr = v / √(g * l))",
      description:
         "Calcula el número de Froude, una cantidad adimensional usada para indicar la influencia de la gravedad en el movimiento de fluidos.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "surface-tension",
      name: "Surface Tension",
      equation_text: "γ = F / L",
      summary: "Calcula la tensión superficial (γ = F / l)",
      description: "Calcula la tensión superficial de un líquido basada en fuerza y longitud.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Fluids And Thermodynamics",
   },
   {
      equation_id: "universal-gravitation",
      name: "Universal Gravitation (Force)",
      equation_text: "F = G m₁m₂ / r²",
      summary: "Calcula la fuerza gravitacional (F = -Gm1m2/r^2)",
      description:
         "Calcula la fuerza gravitacional atractiva entre dos masas puntuales. Nota: devuelve un valor negativo indicando atracción.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-field",
      name: "Gravitational Field",
      equation_text: "g = GM / r² (magnitude)",
      summary: "Calcula el campo gravitacional (g = -Gm/r^2)",
      description:
         "Calcula la intensidad del campo gravitacional a una distancia de una masa puntual. Nota: devuelve un valor negativo indicando dirección hacia la masa.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-pe",
      name: "Gravitational Potential Energy",
      equation_text: "U_g = -G m₁m₂ / r (general)",
      summary: "Calcula la energía potencial gravitacional entre dos masas (PE = -Gm1m2/r)",
      description: "Calcula la energía potencial gravitacional de un sistema de dos masas puntuales.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "gravitational-potential",
      name: "Gravitational Potential",
      equation_text: "V_g = -GM / r",
      summary: "Calcula el potencial gravitacional (V_g = -Gm/r)",
      description: "Calcula el potencial gravitacional a una distancia de una masa puntual.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "orbital-speed",
      name: "Orbital Speed",
      equation_text: "v_orbit = √(GM / r) (circular)",
      summary: "Calcula la velocidad orbital (v = sqrt(Gm/r))",
      description: "Calcula la velocidad de un objeto en una órbita circular alrededor de una masa mayor.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "escape-speed",
      name: "Escape Speed",
      equation_text: "v_escape = √(2GM / r)",
      summary: "Calcula la velocidad de escape (v = sqrt(2Gm/r))",
      description:
         "Calcula la velocidad mínima necesaria para escapar del tirón gravitacional de una masa desde una distancia dada.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Gravitation",
   },
   {
      equation_id: "thermal-conduction",
      name: "Thermal Conduction",
      equation_text: "Q/t = kAΔT/d",
      summary: "Calcula la tasa de conducción térmica (Q/t = (kAΔT) / L)",
      description:
         "Calcula la tasa de transferencia de calor por conducción a través de un material. Nota: La función calcula Q, asumiendo un intervalo de tiempo implícito por el uso típico de la fórmula para tasa. La documentación indica Q, pero la fórmula es típicamente para Q/t. Aclarando esta diferencia. La función devuelve el resultado del lado derecho de la ecuación de tasa.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "stefan-boltzmann-law",
      name: "Stefan-Boltzmann Law",
      equation_text: "P = εσAT⁴",
      summary: "Calcula la potencia de radiación térmica (P = εσA(T^4 - T0^4))",
      description: "Calcula la tasa neta de energía radiada por un objeto, considerando su entorno.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-lambda-max",
      name: "Wien's Displacement Law (Max Wavelength)",
      equation_text: "λ_max = b/T",
      summary: "Calcula la longitud de onda pico usando la Ley de Wien (λ_max = b/T)",
      description: "Calcula la longitud de onda en la que el espectro de emisión de un cuerpo negro es máximo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "wien-law-f-max",
      name: "Wien's Displacement Law (Max Frequency)",
      equation_text: "f_max ≈ 2.82 * kT / h",
      summary: "Calcula la frecuencia pico usando la Ley de Wien (f_max = b' * T)",
      description:
         "Calcula la frecuencia en la que el espectro de emisión de un cuerpo negro es máximo. Nota: Esta versión usa una constante de Wien modificada b'.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "{language_code}",
      name: "Equation Info (Specific)",
      equation_text: "N/A (Retrieves info, not calculates)",
      summary: "Obtiene información de fórmula por ID e idioma",
      description:
         "Recupera detalles para una fórmula específica basada en su ID único y el idioma deseado. Nota - El idioma se extrae del parámetro de ruta 'language_code'. La lógica interna mostrada en el fragmento de código también mira un parámetro de consulta 'lang', pero esta definición Swagger documenta los parámetros de ruta principales.",
      language_code: "es",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "{language_code}",
      name: "",
      equation_text: "",
      summary: "Obtiene todos los endpoints de ecuaciones en la API.",
      description: "Recupera información resumida sobre todos los endpoints en la API.",
      language_code: "es",
      subject: "Api Information",
      variables: {},
      topic: "Api Information",
   },
   {
      equation_id: "velocity",
      name: "Velocity",
      equation_text: "v = Δx / Δt",
      summary: "Calcula la velocidad",
      description: "Calcula la velocidad basada en desplazamiento y tiempo (v = Δs / Δt).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "acceleration",
      name: "Acceleration",
      equation_text: "a = Δv / Δt",
      summary: "Calcula la aceleración",
      description: "Calcula la aceleración basada en el cambio de velocidad y tiempo (a = Δv / Δt).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v",
      name: "Kinematic Equation (v = v₀ + at)",
      equation_text: "v = v₀ + at",
      summary: "Calcula la velocidad final (v = v0 + at)",
      description: "Calcula la velocidad final usando la primera ecuación cinemática.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "motion-s",
      name: "Kinematic Equation (s = s₀ + v₀t + ½at²)",
      equation_text: "s = s₀ + v₀t + ½at²",
      summary: "Calcula la posición final (s = s0 + v0t + 0.5at^2)",
      description: "Calcula la posición final usando la segunda ecuación cinemática.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v2",
      name: "Kinematic Equation (v² = v₀² + 2aΔs)",
      equation_text: "v² = v₀² + 2aΔs",
      summary: "Calcula la velocidad final al cuadrado (v^2 = v0^2 + 2a(s - s0))",
      description:
         "Calcula la velocidad final al cuadrado usando la tercera ecuación cinemática. Nota: devuelve v^2, no v.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "motion-v-avg",
      name: "Average Velocity",
      equation_text: "v_avg = Δx / Δt",
      summary: "Calcula la velocidad promedio (v_avg = 0.5 * (v + v0))",
      description: "Calcula la velocidad promedio asumiendo aceleración constante.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "force",
      name: "Force (Newton's Second Law)",
      equation_text: "F_net = ma",
      summary: "Calcula la fuerza (F = ma)",
      description: "Calcula la fuerza usando la segunda ley de Newton.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "weight",
      name: "Weight",
      equation_text: "W = mg",
      summary: "Calcula el peso (W = mg)",
      description: "Calcula la fuerza de gravedad sobre un objeto.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-static-max",
      name: "Maximum Static Friction",
      equation_text: "f_s_max = μ_s * F_N",
      summary: "Calcula la fricción estática máxima (F_s = μ_s * N)",
      description: "Calcula la máxima fuerza de fricción estática posible.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "dry-friction-kinetic",
      name: "Kinetic Friction",
      equation_text: "f_k = μ_k * F_N",
      summary: "Calcula la fricción cinética (F_k = μ_k * N)",
      description: "Calcula la fuerza de fricción cinética que actúa sobre un objeto en movimiento.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Mechanics",
   },
   {
      equation_id: "momentum",
      name: "Momentum",
      equation_text: "p = mv",
      summary: "Calcula el momento lineal (p = mv)",
      description: "Calcula el momento lineal de un objeto.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Momentum",
   },
   {
      equation_id: "impulse",
      name: "Impulse",
      equation_text: "J = F_avg * Δt",
      summary: "Calcula el impulso (J = F * Δt)",
      description: "Calcula el impulso a partir de la fuerza y el intervalo de tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Momentum",
   },
   {
      equation_id: "impulse-momentum",
      name: "Impulse-Momentum Theorem",
      equation_text: "J = Δp",
      summary: "Valida el teorema impulso-momento (F * Δt = m * Δv)",
      description: "Verifica si el impulso es igual al cambio en el momento para valores dados. Devuelve booleano.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Momentum",
   },
   {
      equation_id: "activity",
      name: "Radioactive Activity",
      equation_text: "A = λN",
      summary: "Calcula la actividad promedio en desintegración radiactiva (A_avg = ΔN/Δt)",
      description:
         "Calcula la actividad promedio (tasa de desintegración) de una muestra radiactiva en un intervalo de tiempo. Nota: La función usa nValue para el número de núcleos ΔN y tValue para el tiempo Δt. Esta es un promedio simplificado sobre Δt, la actividad instantánea es dN/dt = -λN.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Nuclear Physics",
   },
   {
      equation_id: "half-life",
      name: "Half-Life",
      equation_text: "T_½ = ln(2) / λ",
      summary: "Calcula la cantidad restante después de la desintegración (N = N0 * (1/2)^(t/T_half))",
      description:
         "Calcula la cantidad restante de una sustancia después de un tiempo basado en su vida media. Nota: Usa tValue para tiempo y Thalf para vida media.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Nuclear Physics",
   },
   {
      equation_id: "absorbed-dose",
      name: "Absorbed Radiation Dose",
      equation_text: "D = dE / dm",
      summary: "Calcula la dosis de radiación absorbida (D = E/m)",
      description:
         "Calcula la dosis absorbida de radiación basada en la energía absorbida por una masa. Nota: Usa EValue para energía y mValue para masa.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Nuclear Physics",
   },
   {
      equation_id: "equivalent-dose",
      name: "Equivalent Radiation Dose",
      equation_text: "H = D * W_R",
      summary: "Calcula la dosis equivalente de radiación (H = wR * D)",
      description:
         "Calcula la dosis equivalente, considerando la efectividad biológica de diferentes tipos de radiación. Nota: Usa DValue para dosis absorbida.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Nuclear Physics",
   },
   {
      equation_id: "effective-dose",
      name: "Effective Radiation Dose",
      equation_text: "E = Σ (H_T * W_T)",
      summary: "Calcula la dosis efectiva de radiación (E = wT * H)",
      description:
         "Calcula la dosis efectiva, considerando la sensibilidad de diferentes tejidos/órganos a la radiación. Nota: Usa HValue para dosis equivalente.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Nuclear Physics",
   },
   {
      equation_id: "cerenkov-angle",
      name: "Cherenkov Angle",
      equation_text: "cos(θ_C) = c / (nv)",
      summary: "Calcula el ángulo de Cherenkov (θ_C = arccos(c/nv_p))",
      description:
         "Calcula el ángulo del cono de Cherenkov formado por una partícula cargada moviéndose más rápido que la velocidad de la luz en un medio. Devuelve el ángulo en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "interference-fringes",
      name: "Interference Fringes (e.g., position, spacing)",
      equation_text: "Δy = λL / d (double slit spacing)",
      summary: "Calcula la posición de las franjas de interferencia (y_n = (nλL)/d)",
      description:
         "Calcula la posición de la franja brillante n-ésima en un patrón de interferencia de doble rendija de Young.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "index-of-refraction",
      name: "Index of Refraction",
      equation_text: "n = c / v",
      summary: "Calcula el índice de refracción (n = c/v)",
      description:
         "Calcula el índice de refracción de un medio basado en la velocidad de la luz en el vacío y en el medio.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "snells-law",
      name: "Snell's Law",
      equation_text: "n₁sin(θ₁) = n₂sin(θ₂)",
      summary: "Valida la Ley de Snell (n1*sin(θ1) = n2*sin(θ2))",
      description:
         "Verifica si la Ley de Snell se cumple para la luz que pasa entre dos medios con índices de refracción y ángulos dados. Devuelve booleano. Los ángulos deben estar en radianes. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante; considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "critical-angle",
      name: "Critical Angle",
      equation_text: "sin(θ_c) = n₂ / n₁ (n₁ > n₂)",
      summary: "Calcula el ángulo crítico (θ_c = arcsin(n2/n1))",
      description:
         "Calcula el ángulo crítico para reflexión interna total cuando la luz va de un medio con índice n1 a n2 (n1 > n2). Devuelve el ángulo en radianes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "image-location",
      name: "Image Location (Optics)",
      equation_text: "1/f = 1/d_o + 1/d_i (Thin Lens/Mirror)",
      summary: "Valida la fórmula de lentes delgados/espejos (1/f = 1/do + 1/di)",
      description:
         "Verifica si la relación entre distancia focal, distancia al objeto y distancia a la imagen es cierta. Devuelve booleano. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante; considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "image-size",
      name: "Image Size (Magnification - Optics)",
      equation_text: "M = h_i / h_o = -d_i / d_o",
      summary: "Valida la fórmula de magnificación (h'/h = -di/do) (La función usa h'/h = di/do)",
      description:
         "Verifica si la relación entre alturas de objeto/imagen y distancias es cierta. Devuelve booleano. Nota: Usa igualdad estricta (===) que puede ser sensible a la precisión de punto flotante. La función usa la relación de magnitud h'/h = di/do en lugar de la fórmula de magnificación con signo. Documentado basado en la implementación de la función. Considerar tolerancia para verificaciones en el mundo real.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "spherical-mirror",
      name: "Spherical Mirror Equation",
      equation_text: "1/f = 1/d_o + 1/d_i",
      summary: "Calcula la distancia focal de un espejo esférico (f = r/2)",
      description: "Calcula la distancia focal de un espejo esférico basado en su radio de curvatura.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Optics",
   },
   {
      equation_id: "spring-pe",
      name: "Spring Potential Energy",
      equation_text: "U_s = ½kx²",
      summary: "Calcula la energía potencial en un resorte (PE = 0.5 * k * Δx^2)",
      description: "Calcula la energía potencial elástica almacenada en un resorte ideal.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "sho-period",
      name: "Simple Harmonic Oscillator (SHO) Period",
      equation_text: "T = 2π√(m/k)",
      summary: "Calcula el período de un oscilador armónico masa-resorte (T = 2π√(m/k))",
      description:
         "Calcula el período de oscilación para un oscilador armónico simple que consiste en una masa en un resorte.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "simple-pendulum-period",
      name: "Simple Pendulum Period",
      equation_text: "T = 2π√(L/g)",
      summary: "Calcula el período de un péndulo simple (T = 2π√(l/g))",
      description: "Calcula el período de oscilación para un péndulo simple en ángulos pequeños.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "frequency",
      name: "Frequency",
      equation_text: "f = 1 / T",
      summary: "Calcula la frecuencia (f = 1/T)",
      description: "Calcula la frecuencia a partir del período de oscilación.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "angular-frequency",
      name: "Angular Frequency",
      equation_text: "ω = 2πf",
      summary: "Calcula la frecuencia angular (ω = 2πf)",
      description: "Calcula la frecuencia angular a partir de la frecuencia.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Oscillations And Waves",
   },
   {
      equation_id: "lorentz-factor",
      name: "Lorentz Factor",
      equation_text: "γ = 1 / √(1 - v²/c²)",
      summary: "Calcula el factor de Lorentz (γ)",
      description: "Calcula el factor de Lorentz usando γ = 1/√(1 - (v²/c²)). Requiere v < c.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "time-dilation",
      name: "Time Dilation",
      equation_text: "Δt' = γ * Δt₀",
      summary: "Calcula la dilatación del tiempo (t' = γ * t₀)",
      description:
         "Calcula el tiempo transcurrido (t') para un observador en un marco inercial S, dado el tiempo propio (t₀) medido en un marco móvil S' y la velocidad relativa (v) entre S y S'. Usa t' = t₀ / √(1 - (v²/c²)). Requiere t₀ ≥ 0 y |v| ≤ c. Las unidades de t' serán las mismas que t₀, las unidades de v y c deben ser consistentes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "length-contraction",
      name: "Length Contraction",
      equation_text: "L' = L₀ / γ",
      summary: "Calcula la contracción de longitud (L' = L₀ / γ)",
      description:
         "Calcula la longitud (L') de un objeto observado desde un marco móvil S', dada su longitud propia (L₀) medida en su marco en reposo S y la velocidad relativa (v) entre S y S'. Usa L' = L₀ * √(1 - (v²/c²)). Requiere L₀ ≥ 0 y |v| ≤ c. Las unidades de L' serán las mismas que L₀, las unidades de v y c deben ser consistentes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-velocity",
      name: "Relativistic Velocity Addition",
      equation_text: "u' = (u + v) / (1 + uv/c²)",
      summary: "Calcula la suma relativista de velocidades",
      description:
         "Calcula la velocidad (u') de un objeto relativa a un marco S', dada su velocidad (u) relativa a un marco S, y la velocidad (v) del marco S relativa al marco S'. Usa la fórmula u' = (u + v) / (1 + uv/c²). Asume movimiento a lo largo de la misma línea. Requiere c ≠ 0. Las unidades de u, v y c deben ser consistentes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-energy",
      name: "Relativistic Total Energy",
      equation_text: "E = γmc²",
      summary: "Calcula la energía total relativista (E)",
      description:
         "Calcula la energía total relativista de una partícula con masa en reposo (m) moviéndose a velocidad (v). Usa la fórmula E = γmc² = mc² / √(1 - (v²/c²)). Principalmente para partículas con masa en reposo (m > 0). Requiere m ≥ 0 y |v| ≤ c. Las unidades de m, v y c deben ser consistentes para dar energía en unidades apropiadas (ej., m en kg, v/c en m/s da E en Joules).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-momentum",
      name: "Relativistic Momentum",
      equation_text: "p = γmv",
      summary: "Calcula el momento relativista (p = γmv)",
      description:
         "Calcula el momento relativista de una partícula con masa en reposo (m) moviéndose a velocidad (v). Usa la fórmula p = γmv = mv / √(1 - (v²/c²)). Principalmente para partículas con masa en reposo (m > 0). Requiere m ≥ 0 y |v| ≤ c. Las unidades de m, v y c deben ser consistentes para dar momento en unidades apropiadas (ej., m en kg, v en m/s, c en m/s da p en kg·m/s).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "energy-momentum-relation",
      name: "Energy-Momentum Relation",
      equation_text: "E² = (pc)² + (mc²)²",
      summary: "Calcula la energía total a partir del momento y masa en reposo (E)",
      description:
         "Calcula la energía total relativista de una partícula a partir de su momento relativista (p) y masa en reposo (m). Usa la relación energía-momento: E² = (pc)² + (mc²)². Esta fórmula es válida tanto para partículas masivas (m > 0) como sin masa (m = 0). Requiere p ≥ 0, m ≥ 0 y c > 0. Las unidades de p, m y c deben ser consistentes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "mass-energy-equivalence",
      name: "Mass-Energy Equivalence (E₀ = mc²)",
      equation_text: "E₀ = mc²",
      summary: "Calcula la equivalencia masa-energía (E₀ = mc²)",
      description:
         "Calcula la energía en reposo (E₀) equivalente a una masa en reposo dada (m) usando la famosa ecuación de Einstein E₀ = mc². Requiere m ≥ 0 y c > 0. Las unidades de m y c deben ser consistentes (ej., m en kg, c en m/s da E₀ en Joules). Este endpoint usa un valor estándar para c (aprox 299792458 m/s) a menos que se proporcione explícitamente 'c'.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-kinetic-energy",
      name: "Relativistic Kinetic Energy",
      equation_text: "KE = (γ - 1)mc²",
      summary: "Calcula la energía cinética relativista (KE)",
      description:
         "Calcula la energía cinética relativista de una partícula con masa en reposo (m) moviéndose a velocidad (v). Usa la fórmula KE = (γ - 1)mc² = (1/√(1 - (v²/c²)) - 1)mc². Principalmente para partículas con masa en reposo (m > 0). Requiere m ≥ 0 y |v| < c. Las unidades de m, v y c deben ser consistentes para dar energía en unidades apropiadas.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "relativistic-doppler-effect",
      name: "Relativistic Doppler Effect (Wavelength)",
      equation_text: "λ' = λ₀√((1 + β)/(1 - β)) (β = v/c)",
      summary: "Calcula el efecto Doppler relativista longitudinal para longitud de onda",
      description:
         "Calcula la longitud de onda observada (λ') de la luz emitida con longitud de onda propia (λ₀) desde una fuente moviéndose con velocidad relativa (v_rel) directamente alejándose o acercándose al observador. Usa la fórmula λ' = λ₀√((1 + β)/(1 - β)), donde β = v_rel/c. v_rel > 0 para recesión (corrimiento al rojo), v_rel < 0 para acercamiento (corrimiento al azul). Requiere λ₀ > 0 y |v_rel| < c. Las unidades de λ' serán las mismas que λ₀, las unidades de v_rel y c deben ser consistentes.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-energy-from-frequency",
      name: "Photon Energy (from Frequency)",
      equation_text: "E = hf",
      summary: "Calcula la energía del fotón a partir de la frecuencia (E = hf)",
      description:
         "Calcula la energía (E) de un fotón basada en su frecuencia (f). Usa la relación de Planck E = hf. Requiere f ≥ 0 y h > 0. Las unidades de h y f deben ser consistentes para dar energía en unidades apropiadas (ej., h en J·s, f en Hz (s⁻¹) da E en Joules). Este endpoint usa un valor estándar para h (aprox 6.626e-34 J·s) a menos que se proporcione explícitamente 'h'.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photon-momentum-from-wavelength",
      name: "Photon Momentum (from Wavelength)",
      equation_text: "p = h / λ",
      summary: "Calcula el momento del fotón a partir de la longitud de onda (p = h/λ)",
      description:
         "Calcula el momento (p) de un fotón basado en su longitud de onda (λ). Usa la relación p = h/λ. Requiere λ > 0 y h > 0. Las unidades de h y λ deben ser consistentes para dar momento en unidades apropiadas (ej., h en J·s, λ en metros da p en kg·m/s). Este endpoint usa un valor estándar para h (aprox 6.626e-34 J·s) a menos que se proporcione explícitamente 'h'.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "photoelectric-effect-ke",
      name: "Photoelectric Effect (Max KE)",
      equation_text: "KE_max = E_photon - φ",
      summary: "Calcula la energía cinética máxima en el efecto fotoeléctrico (KE_max)",
      description:
         "Calcula la energía cinética máxima (KE_max) de electrones emitidos en el efecto fotoeléctrico. Usa la fórmula KE_max = E_photon - φ, donde E_photon es la energía del fotón entrante y φ es la función trabajo del material. Si E_photon ≤ φ, no se emiten electrones y KE_max es 0. Requiere E_photon ≥ 0 y φ ≥ 0. Las unidades de E_photon y φ deben ser consistentes para dar KE_max en las mismas unidades.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "rydberg-transition",
      name: "Rydberg Equation (Atomic Transition)",
      equation_text: "ΔE = R_y * Z² * (1/n₁² - 1/n₂²)",
      summary: "Calcula energía o número de onda para transiciones en átomos tipo hidrógeno",
      description:
         "Calcula la diferencia de energía (ΔE) o número de onda (1/λ) para una transición electrónica entre dos niveles de energía en un átomo tipo hidrógeno (Z). Usa la fórmula Resultado = Constante * Z² * (1/n_inicial² - 1/n_final²). Si 'Constante' es la unidad de energía de Rydberg (ej., en eV), el resultado es la diferencia de energía E_final - E_inicial (positivo para absorción, negativo para emisión). Si 'Constante' es la constante de Rydberg para número de onda (ej., en m⁻¹), el resultado es el número de onda 1/λ (positivo para emisión, negativo para absorción). Requiere nInitial > 0, nFinal > 0, nInitial ≠ nFinal, Z > 0 (enteros), y Constante > 0.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Relativity And Quantum",
   },
   {
      equation_id: "angular-velocity",
      name: "Angular Velocity",
      equation_text: "ω = Δθ / Δt",
      summary: "Calcula la velocidad angular (ω = Δθ / Δt)",
      description: "Calcula la velocidad angular basada en el cambio de ángulo y tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-acceleration",
      name: "Angular Acceleration",
      equation_text: "α = Δω / Δt",
      summary: "Calcula la aceleración angular (α = Δω / Δt)",
      description: "Calcula la aceleración angular basada en el cambio de velocidad angular y tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega",
      name: "Rotational Kinematics (ω)",
      equation_text: "ω = ω₀ + αt",
      summary: "Calcula la velocidad angular final (ω = ω0 + αt)",
      description: "Calcula la velocidad angular final usando la ecuación cinemática rotacional.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-theta",
      name: "Rotational Kinematics (θ)",
      equation_text: "θ = θ₀ + ω₀t + ½αt²",
      summary: "Calcula la posición angular (θ = θ0 + ω0t + 0.5αt^2)",
      description: "Calcula la posición angular final usando la ecuación cinemática rotacional.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega2",
      name: "Rotational Kinematics (ω²)",
      equation_text: "ω² = ω₀² + 2αΔθ",
      summary: "Calcula la velocidad angular al cuadrado (ω^2 = ω0^2 + 2α(θ - θ0))",
      description:
         "Calcula la velocidad angular final al cuadrado usando la ecuación cinemática rotacional. Nota: devuelve ω^2, no ω.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotation-omega-avg",
      name: "Average Angular Velocity",
      equation_text: "ω_avg = Δθ / Δt",
      summary: "Calcula la velocidad angular promedio (ω_avg = 0.5 * (ω + ω0))",
      description: "Calcula la velocidad angular promedio asumiendo aceleración angular constante.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "torque",
      name: "Torque",
      equation_text: "τ = rFsin(θ)",
      summary: "Calcula el torque (τ = rF sin(θ))",
      description: "Calcula el torque basado en radio, fuerza y el ángulo entre ellos.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "2nd-law-rotation",
      name: "Newton's Second Law (Rotation)",
      equation_text: "τ_net = Iα",
      summary: "Calcula el torque usando la segunda Ley rotacional (τ = Iα)",
      description: "Calcula el torque basado en momento de inercia y aceleración angular.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "moment-of-inertia",
      name: "Moment of Inertia",
      equation_text: "I = mr² (point mass)",
      summary: "Calcula el momento de inercia para una masa puntual (I = mr^2)",
      description: "Calcula el momento de inercia para una sola masa puntual relativa a un eje.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-work",
      name: "Rotational Work",
      equation_text: "W = τΔθ (constant torque)",
      summary: "Calcula el trabajo rotacional (W = τΔθ)",
      description: "Calcula el trabajo realizado por un torque constante sobre un desplazamiento angular.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-power",
      name: "Rotational Power",
      equation_text: "P = τω",
      summary: "Calcula la potencia rotacional (P = τω cos(θ))",
      description:
         "Calcula la potencia rotacional instantánea basada en torque, velocidad angular y el ángulo entre ellos.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "rotational-ke",
      name: "Rotational Kinetic Energy",
      equation_text: "KE_rot = ½Iω²",
      summary: "Calcula la energía cinética rotacional (KE = 0.5Iω^2)",
      description: "Calcula la energía cinética de un objeto en rotación.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-momentum",
      name: "Angular Momentum",
      equation_text: "L = Iω",
      summary: "Calcula el momento angular (L = mrv sin(θ))",
      description: "Calcula el momento angular para una masa puntual moviéndose relativa a un punto.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "angular-impulse",
      name: "Angular Impulse",
      equation_text: "J_angular = τ_avg * Δt",
      summary: "Calcula el impulso angular (J = τΔt)",
      description: "Calcula el impulso angular a partir de torque e intervalo de tiempo.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Rotational Motion",
   },
   {
      equation_id: "youngs-modulus",
      name: "Young's Modulus",
      equation_text: "E = σ / ε",
      summary: "Calcula el módulo de Young (E = (F * L0) / (A * ΔL))",
      description: "Calcula el módulo de Young (módulo elástico) de un material bajo tensión o compresión.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Solid Mechanics",
   },
   {
      equation_id: "shear-modulus",
      name: "Shear Modulus",
      equation_text: "G = τ / γ",
      summary: "Calcula el módulo de corte (G = (F * y) / (A * Δx))",
      description: "Calcula el módulo de corte (módulo de rigidez) de un material bajo esfuerzo cortante.",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Solid Mechanics",
   },
   {
      equation_id: "bulk-modulus",
      name: "Bulk Modulus",
      equation_text: "K = -ΔP / (ΔV / V₀)",
      summary: "Calcula el módulo de compresibilidad (K = (F * V0) / (A * ΔV))",
      description: "Calcula el módulo de compresibilidad de un material bajo presión uniforme (esfuerzo hidrostático).",
      language_code: "es",
      subject: "Physics",
      variables: {},
      topic: "Solid Mechanics",
   },
   {
      equation_id: "hookes-law",
      name: "Hooke's Law",
      equation_text: "F = kx",
      summary: "Calcula la fuerza de un muelle (F = -k * Δx)",
      description:
         "Calcula la fuerza restauradora ejercida por un muelle ideal según la Ley de Hooke. Nota: devuelve un valor negativo que indica que la fuerza se opone al desplazamiento.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Solid Mechanics",
   },
   {
      equation_id: "solid-expansion-length",
      name: "Solid Thermal Expansion (Length)",
      equation_text: "ΔL = αL₀ΔT",
      summary: "Calcula la expansión térmica lineal de sólidos (ΔL = αL0ΔT)",
      description: "Calcula el cambio en la longitud de un material sólido debido a un cambio de temperatura.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-area",
      name: "Solid Thermal Expansion (Area)",
      equation_text: "ΔA = βA₀ΔT",
      summary: "Calcula la expansión térmica de área de sólidos (ΔA = 2αA0ΔT)",
      description:
         "Calcula el cambio en el área de un material sólido debido a un cambio de temperatura, usando el coeficiente de expansión lineal.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "solid-expansion-volume",
      name: "Solid Thermal Expansion (Volume)",
      equation_text: "ΔV = γV₀ΔT",
      summary: "Calcula la expansión térmica de volumen de sólidos (ΔV = 3αV0ΔT)",
      description:
         "Calcula el cambio en el volumen de un material sólido debido a un cambio de temperatura, usando el coeficiente de expansión lineal.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "liquid-expansion",
      name: "Liquid Thermal Expansion",
      equation_text: "ΔV = βV₀ΔT",
      summary: "Calcula la expansión térmica de líquidos (ΔV = βV0ΔT)",
      description: "Calcula el cambio en el volumen de un líquido debido a un cambio de temperatura.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "sensible-heat",
      name: "Sensible Heat",
      equation_text: "Q = mcΔT",
      summary: "Calcula el calor sensible (Q = mcΔT)",
      description: "Calcula el calor transferido que causa un cambio en la temperatura de una sustancia.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "latent-heat",
      name: "Latent Heat",
      equation_text: "Q = mL",
      summary: "Calcula el calor latente (Q = mL)",
      description: "Calcula el calor transferido durante un cambio de fase de una sustancia.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "ideal-gas-law",
      name: "Ideal Gas Law",
      equation_text: "PV = nRT",
      summary: "Valida la Ley de los Gases Ideales (PV = nRT)",
      description:
         "Verifica si la ecuación de la Ley de los Gases Ideales es verdadera para los parámetros dados. Devuelve un booleano. Nota: utiliza igualdad estricta (===), que puede ser sensible a la precisión de punto flotante; considere la tolerancia para verificaciones en el mundo real.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-ke",
      name: "Molecular Kinetic Energy",
      equation_text: "KE_avg = (3/2)kT",
      summary: "Calcula la energía cinética molecular promedio (KE = (3/2)kT)",
      description: "Calcula la energía cinética traslacional promedio por molécula de un gas ideal.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-vp",
      name: "Molecular Speed (Most Probable)",
      equation_text: "v_p = √(2kT/m)",
      summary: "Calcula la velocidad molecular más probable (v_p = √(2kT/m))",
      description:
         "Calcula la velocidad más probable de las moléculas en un gas ideal según la distribución de Maxwell-Boltzmann.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-avg",
      name: "Molecular Speed (Average)",
      equation_text: "v_avg = √(8kT/πm)",
      summary: "Calcula la velocidad molecular promedio (v_avg = √(8kT/(πm)))",
      description:
         "Calcula la velocidad promedio de las moléculas en un gas ideal según la distribución de Maxwell-Boltzmann.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "molecular-speed-rms",
      name: "Molecular Speed (RMS)",
      equation_text: "v_rms = √(3kT/m)",
      summary: "Calcula la velocidad cuadrática media molecular (v_rms = √(3kT/m))",
      description:
         "Calcula la velocidad cuadrática media de las moléculas en un gas ideal según la distribución de Maxwell-Boltzmann.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "internal-energy-change",
      name: "Internal Energy Change",
      equation_text: "ΔU = Q - W",
      summary: "Calcula el cambio de energía interna para un gas monoatómico ideal (ΔU = (3/2)nRΔT)",
      description:
         "Calcula el cambio en la energía interna para un gas ideal monoatómico que experimenta un cambio de temperatura.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermal Physics / Thermodynamics",
   },
   {
      equation_id: "thermodynamic-work",
      name: "Thermodynamic Work",
      equation_text: "W = PΔV (constant pressure)",
      summary: "Calcula el trabajo termodinámico realizado por el sistema a presión constante (W = -PΔV)",
      description:
         "Calcula el trabajo realizado por o sobre un sistema durante un proceso termodinámico a presión constante. Nota: La fórmula calcula el trabajo *realizado por* el sistema, positivo para la expansión, negativo para la compresión. La función devuelve -P*deltaV, consistente con el trabajo *realizado por* el sistema según la fórmula W = PΔV, con un signo negativo añadido que puede implicar trabajo *realizado sobre* el sistema dependiendo de la convención. Documentando la salida de la función.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-real",
      name: "Real Efficiency",
      equation_text: "η = W_out / Q_in",
      summary: "Calcula la eficiencia de un motor real (η_real = 1 - (QC / QH))",
      description: "Calcula la eficiencia térmica de un motor térmico basándose en el calor absorbido y rechazado.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermodynamics",
   },
   {
      equation_id: "efficiency-ideal",
      name: "Ideal Efficiency",
      equation_text: "η_ideal = 1 - T_cold / T_hot",
      summary: "Calcula la eficiencia ideal (Carnot) (η_ideal = 1 - (TC / TH))",
      description:
         "Calcula la eficiencia teórica máxima de un motor térmico que opera entre dos temperaturas (eficiencia de Carnot).",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-real",
      name: "Real Coefficient of Performance (COP)",
      equation_text: "COP_ref = Q_c / W (Refrigerator)",
      summary: "Calcula el coeficiente de rendimiento para un frigorífico real (COP_real = QC / (QH - QC))",
      description: "Calcula el coeficiente de rendimiento para un frigorífico o bomba de calor real.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermodynamics",
   },
   {
      equation_id: "cop-ideal",
      name: "Ideal Coefficient of Performance (COP)",
      equation_text: "COP_ideal_ref = T_c / (T_h - T_c)",
      summary: "Calcula el coeficiente de rendimiento para un frigorífico ideal (COP_ideal = TC / (TH - TC))",
      description:
         "Calcula el coeficiente de rendimiento teórico máximo para un frigorífico o bomba de calor que opera entre dos temperaturas.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Thermodynamics",
   },
   {
      equation_id: "periodic-wave-velocity",
      name: "Periodic Wave Velocity",
      equation_text: "v = fλ",
      summary: "Calcula la velocidad de onda (v = fλ)",
      description: "Calcula la velocidad de una onda periódica basándose en su frecuencia y longitud de onda.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity",
      name: "Wave Intensity",
      equation_text: "I = P / A",
      summary: "Calcula la intensidad (I = P/A)",
      description: "Calcula la intensidad de una onda (potencia por unidad de área).",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "intensity-level",
      name: "Intensity Level (Decibels)",
      equation_text: "β = 10 * log₁₀(I / I₀)",
      summary: "Calcula el nivel de intensidad en decibelios (L = 10 log10(I/I0))",
      description:
         "Calcula el nivel de intensidad (nivel de intensidad sonora) relativo a una intensidad de referencia.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "pressure-level",
      name: "Pressure Level (Sound Pressure Level)",
      equation_text: "L_p = 20 * log₁₀(P_rms / P_ref)",
      summary: "Calcula el nivel de presión sonora en decibelios (L = 20 log10(ΔP/ΔP0))",
      description: "Calcula el nivel de presión sonora relativo a un cambio de presión de referencia.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "doppler-effect",
      name: "Doppler Effect (Sound/Non-Relativistic)",
      equation_text: "f_obs / f_source = (v_wave + v_observer) / (v_wave - v_source)",
      summary: "Calcula el factor de velocidad del efecto Doppler ((c + vo) / (c - vs))",
      description:
         "Calcula la porción del factor de velocidad de la fórmula del efecto Doppler (f' = f * factor). Velocidades positivas para el observador moviéndose hacia la fuente, la fuente moviéndose hacia el observador.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "mach-angle",
      name: "Mach Angle",
      equation_text: "sin(μ) = 1 / M",
      summary: "Calcula el ángulo de Mach (θM = arcsin(c/v))",
      description:
         "Calcula el ángulo del cono de Mach formado por un objeto que se mueve más rápido que la velocidad del sonido. Devuelve el ángulo en radianes.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Waves And Optics",
   },
   {
      equation_id: "work",
      name: "Work",
      equation_text: "W = Fdcos(θ)",
      summary: "Calcula el trabajo realizado (W = F * Δs * cos(θ))",
      description: "Calcula el trabajo realizado basándose en la fuerza, el desplazamiento y el ángulo entre ellos.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy",
      name: "Kinetic Energy",
      equation_text: "KE = ½mv²",
      summary: "Calcula la energía cinética (KE = 0.5 * m * v^2)",
      description: "Calcula la energía cinética basándose en la masa y la velocidad.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "kinetic-energy-from-momentum",
      name: "Kinetic Energy (from Momentum)",
      equation_text: "KE = p² / (2m)",
      summary: "Calcula la energía cinética a partir del momento (KE = p^2 / (2m))",
      description: "Calcula la energía cinética basándose en el momento y la masa.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "gravitational-potential-energy",
      name: "Gravitational Potential Energy",
      equation_text: "U_g = mgh (near surface)",
      summary: "Calcula la energía potencial gravitatoria (PE = mgh)",
      description: "Calcula el cambio en la energía potencial gravitatoria.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "efficiency",
      name: "Efficiency",
      equation_text: "Efficiency = Output / Input",
      summary: "Calcula la eficiencia (η = W_out / W_in)",
      description: "Calcula la eficiencia de un proceso o máquina.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "power",
      name: "Power",
      equation_text: "P = W / t",
      summary: "Calcula la potencia (P = ΔW / Δt)",
      description: "Calcula la potencia promedio basándose en el cambio de trabajo y tiempo.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
   {
      equation_id: "power-velocity",
      name: "Power (P = Fv)",
      equation_text: "P = Fv",
      summary: "Calcula la potencia a partir de la fuerza y la velocidad (P = Fv cos(θ))",
      description: "Calcula la potencia instantánea basándose en la fuerza, la velocidad y el ángulo entre ellos.",
      language_code: "es", // Updated
      subject: "Physics",
      variables: {}, // Untranslated as it's empty
      topic: "Work And Energy",
   },
];

module.exports = es; // Export the array of physics equations in Spanish